### ISSUE TITLE
coap_add_attr() does not take ownership over passed data(name/val)

### ISSUE THREAD

**Issue by DoumanAsh** [obgm/libcoap#10]
https://github.com/obgm/libcoap/blob/develop/src/resource.c#L333-L334

I understand that as of current it is user's responsibility to ensure that passed pointers are valid.
But i think it would be more rational for ```coap_attr_t``` struct to take ownership over passed values.
After all this strcture belongs to resource now and user should not change values inside of it without using a proper API. Though there is none for such needs as of current...

I didn't look into other places, but i would generally think that taking ownership of all resources would be right for library and its structures. Otherwise the line between library and application becomes dim.

**UPD:**
The same for uri in  ```coap_resource_init```

**Comment by obgm** [comment]
`coap_add_attr()` and `coap_resource_init()` actually take ownership of the passed pointers. Whether or not the storage pointed to by these pointers is released on destruction of the respective attribute or resource object is controlled by the `flags` parameter:

-  `COAP_RESOURCE_FLAGS_RELEASE_URI` causes the resource URI that was passed to `coap_resource_init()` to be freed when the resource is deleted by `coap_delete_resource()`.
- `COAP_ATTR_FLAGS_RELEASE_NAME` and `COAP_ATTR_FLAGS_RELEASE_VALUE` similarly control the deletion of attribute name and attribute value in `coap_delete_attr()`.

Using these attributes, you can pass literal character strings such as those used in the example server application as well as dynamically generated strings easily. Note that libcoap specifically has been designed to provide a very tight coupling between low-level operations and the application that use this library to meet the requirement of highly-optimized embedded applications.

**Comment by DoumanAsh** [comment]
Oh... I see...
Sorry for raising this issue.
