### ISSUE TITLE
My problem is to know how i can run coap dtls with OPENSSL version 1.0.x

### ISSUE THREAD

**Issue by khalifamb** [obgm/libcoap#1002]
**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.

**Additional context**

**Comment by mrdeep1** [comment]
@khalifamb It would be appreciated if you either filled in the description with background information, or deleted the description text that is not relevant for whatever reason.

The libcoap's interface into the OpenSSL Library makes use of functions provided by OpenSSL that were added in version 1.1.0 such as the BIO_*() functions.  To do a back port to 1.0.X would require a lot of work and is likely to have insecurities by using such an old version of the OpenSSL library.

Have you looked at the provided [HOWTO.dual.openssl](https://raw.githubusercontent.com/obgm/libcoap/develop/HOWTO.dual.openssl) to support dual versions of OpenSSL running on an appliance?

**Comment by mrdeep1** [comment]
@khalifamb Do you need anymore help here, or can this be closed off?

**Comment by mrdeep1** [comment]
Closing as information provided.
