### ISSUE TITLE
Coap context creation

### ISSUE THREAD

**Issue by arunkvnss** [obgm/libcoap#101]
Is there any way to attach user specific data to the coap-context ?

**Comment by arunkvnss** [comment]
Is there any way to attach user specific data to the coap-resource ?

**Comment by obgm** [comment]
For `coap_context_t`, there is `coap_set_app_data()` to set application-specific data. It takes two
arguments: First, the coap context to attach data to, second a void pointer to the application-specific
data.

`coap_resource_t` does not have such thing. Do you think this may be useful?

**Comment by arunkvnss** [comment]
Sorry for the late replay. It is enough, And we are in the implementation and testing of coap in tcp right ?.

**Comment by arunkvnss** [comment]
coap_set_app_data () API is not present in libcoap 4.1.2 version ?

**Comment by arunkvnss** [comment]
And coap in tcp source available in github ?

**Comment by obgm** [comment]
`coap_set_app_data()` will be in release 4.2 once it is ready. This will also have TCP/TLS.

Both are already present in the development branch.

**Comment by mrdeep1** [comment]
@arunkvnss Can this now be closed as 4.2.0 has been released?

**Comment by obgm** [comment]
Closing off as this functionality is available for quite some time now.
