### ISSUE TITLE
Does coap server example and coap client example fit for the node at the FIT IoT lab platform?

### ISSUE THREAD

**Issue by salmeghlef** [obgm/libcoap#1014]
Hello guys,
When compiling the coap example client as .exe or .elf format, it does not work on the real IoT devices that are available at FIT-IoT platform. It says, the format is not known. Any ideas please,,

**Comment by obgm** [comment]
You need to cross-compile the code for the target platform to run on.

**Comment by salmeghlef** [comment]
Is it possible to compile .c file into .elf in linux? if someone has an idea, please help

**Comment by salmeghlef** [comment]
Hope there is a tool that can help to convert .c file into .elf format. Using the traditional way, it requires more knowledge about opam, menhir and coq packages!!

**Comment by mrdeep1** [comment]
As said previously, you need to use a cross-compiler to compile source code into binary object files (which is your elf format) that are suitable to run on the target platform.  Whatever cross-compiler tool set you need and how to use it for FIT IoT lab is not a part of this forum.

**Comment by salmeghlef** [comment]
As you may remember me Jon, I just want to remind you that I like "detailed" answers. For instance, when you mention cross-compiler, you may add a little vocabs (for example x compiler, y compiler). It won't cost nothing except some keyboards clicks. Thanks for your help and kindness always.

**Comment by mrdeep1** [comment]
I know nothing about the FIT IoT lab platform environment - somewhere in that environment documentation you will find what the specific cross-compiler you need for your development environment, or whether they provide a native compilation environment.

**Comment by salmeghlef** [comment]
FIT-IoT lab platform only ask to install .elf object file format on their nodes. So, what cross-compiler can help to compile coap-client.c into .elf format. (elf stands for Executable and Linker Format).

**Comment by salmeghlef** [comment]
It was very simple. The gcc compiler by default compiles the .c file to .o format which is equivalent to .elf format. Please close this issue and thank for your guidance.
