### ISSUE TITLE
When compiling the coap-client.c using "gcc coap-client.c -o client", it gives lot of errors!!

### ISSUE THREAD

**Issue by salmeghlef** [obgm/libcoap#1016]
parallels@parallels-Parallels-Virtual-Platform:~/libcoap1/examples$ **gcc coap-client.c**
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `coap_malloc':
coap-client.c:(.text+0x19): undefined reference to `coap_malloc_type'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `coap_free':
coap-client.c:(.text+0x38): undefined reference to `coap_free_type'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `track_new_token':
coap-client.c:(.text+0x20f): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x231): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x263): undefined reference to `coap_new_binary'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `track_flush_token':
coap-client.c:(.text+0x4c4): undefined reference to `coap_delete_binary'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `coap_new_request':
coap-client.c:(.text+0x59d): undefined reference to `coap_new_pdu'
/usr/bin/ld: coap-client.c:(.text+0x5dc): undefined reference to `coap_session_new_token'
/usr/bin/ld: coap-client.c:(.text+0x606): undefined reference to `coap_add_token'
/usr/bin/ld: coap-client.c:(.text+0x60f): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x62d): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x647): undefined reference to `coap_add_optlist_pdu'
/usr/bin/ld: coap-client.c:(.text+0x674): undefined reference to `coap_add_data_large_request'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `nack_handler':
coap-client.c:(.text+0x883): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x8a1): undefined reference to `coap_log_impl'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `message_handler':
coap-client.c:(.text+0x8f9): undefined reference to `coap_pdu_get_code'
/usr/bin/ld: coap-client.c:(.text+0x90b): undefined reference to `coap_pdu_get_type'
/usr/bin/ld: coap-client.c:(.text+0x91d): undefined reference to `coap_pdu_get_token'
/usr/bin/ld: coap-client.c:(.text+0x92a): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x95d): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x962): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x97b): undefined reference to `coap_show_pdu'
/usr/bin/ld: coap-client.c:(.text+0x9c0): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x9de): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0xa26): undefined reference to `coap_check_option'
/usr/bin/ld: coap-client.c:(.text+0xa30): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0xa56): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0xa9e): undefined reference to `coap_get_data_large'
/usr/bin/ld: coap-client.c:(.text+0xaff): undefined reference to `coap_check_option'
/usr/bin/ld: coap-client.c:(.text+0xb28): undefined reference to `coap_opt_block_num'
/usr/bin/ld: coap-client.c:(.text+0xb4e): undefined reference to `coap_check_option'
/usr/bin/ld: coap-client.c:(.text+0xb71): undefined reference to `coap_opt_length'
/usr/bin/ld: coap-client.c:(.text+0xb81): undefined reference to `coap_opt_length'
/usr/bin/ld: coap-client.c:(.text+0xb91): undefined reference to `coap_opt_value'
/usr/bin/ld: coap-client.c:(.text+0xba0): undefined reference to `coap_opt_length'
/usr/bin/ld: coap-client.c:(.text+0xc49): undefined reference to `coap_get_data_large'
/usr/bin/ld: coap-client.c:(.text+0xd15): undefined reference to `coap_check_option'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `usage':
coap-client.c:(.text+0xd73): undefined reference to `coap_package_build'
/usr/bin/ld: coap-client.c:(.text+0xdb1): undefined reference to `coap_string_tls_version'
/usr/bin/ld: coap-client.c:(.text+0xdf2): undefined reference to `coap_string_tls_support'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `cmdline_content_type':
coap-client.c:(.text+0xf9b): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0xfc0): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0xfd7): undefined reference to `coap_encode_var_safe'
/usr/bin/ld: coap-client.c:(.text+0xfeb): undefined reference to `coap_new_optlist'
/usr/bin/ld: coap-client.c:(.text+0x100c): undefined reference to `coap_insert_optlist'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `cmdline_hop_limit':
coap-client.c:(.text+0x1087): undefined reference to `coap_encode_var_safe'
/usr/bin/ld: coap-client.c:(.text+0x109d): undefined reference to `coap_new_optlist'
/usr/bin/ld: coap-client.c:(.text+0x10be): undefined reference to `coap_insert_optlist'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `cmdline_uri':
coap-client.c:(.text+0x1140): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x115e): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x1180): undefined reference to `coap_new_optlist'
/usr/bin/ld: coap-client.c:(.text+0x1192): undefined reference to `coap_insert_optlist'
/usr/bin/ld: coap-client.c:(.text+0x11c2): undefined reference to `coap_split_uri'
/usr/bin/ld: coap-client.c:(.text+0x11cb): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x11e9): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x120d): undefined reference to `coap_dtls_is_supported'
/usr/bin/ld: coap-client.c:(.text+0x1216): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x1233): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x1262): undefined reference to `coap_tls_is_supported'
/usr/bin/ld: coap-client.c:(.text+0x126b): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x1288): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x12a2): undefined reference to `coap_tcp_is_supported'
/usr/bin/ld: coap-client.c:(.text+0x12ab): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x12c8): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x12fd): undefined reference to `coap_uri_into_options'
/usr/bin/ld: coap-client.c:(.text+0x1306): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x1324): undefined reference to `coap_log_impl'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `cmdline_blocksize':
coap-client.c:(.text+0x13d6): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x13f4): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x140b): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x1429): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x1444): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x1468): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x1488): undefined reference to `coap_fls'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `set_blocksize':
coap-client.c:(.text+0x1594): undefined reference to `coap_encode_var_safe'
/usr/bin/ld: coap-client.c:(.text+0x15af): undefined reference to `coap_new_optlist'
/usr/bin/ld: coap-client.c:(.text+0x15c1): undefined reference to `coap_insert_optlist'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `cmdline_subscribe':
coap-client.c:(.text+0x160b): undefined reference to `coap_encode_var_safe'
/usr/bin/ld: coap-client.c:(.text+0x1621): undefined reference to `coap_new_optlist'
/usr/bin/ld: coap-client.c:(.text+0x1633): undefined reference to `coap_insert_optlist'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `cmdline_proxy':
coap-client.c:(.text+0x1689): undefined reference to `coap_split_uri'
/usr/bin/ld: coap-client.c:(.text+0x16aa): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x16c8): undefined reference to `coap_log_impl'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `convert_hex_string':
coap-client.c:(.text+0x1892): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x18b7): undefined reference to `coap_log_impl'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `cmdline_option':
coap-client.c:(.text+0x1976): undefined reference to `coap_new_optlist'
/usr/bin/ld: coap-client.c:(.text+0x1988): undefined reference to `coap_insert_optlist'
/usr/bin/ld: coap-client.c:(.text+0x19ad): undefined reference to `coap_new_optlist'
/usr/bin/ld: coap-client.c:(.text+0x19bf): undefined reference to `coap_insert_optlist'
/usr/bin/ld: coap-client.c:(.text+0x1a9a): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x1abf): undefined reference to `coap_log_impl'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `cmdline_read_key':
coap-client.c:(.text+0x20df): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x20fd): undefined reference to `coap_log_impl'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `cmdline_read_hint_check':
coap-client.c:(.text+0x2141): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x2166): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x22b6): undefined reference to `coap_new_bin_const'
/usr/bin/ld: coap-client.c:(.text+0x2303): undefined reference to `coap_new_bin_const'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `verify_cn_callback':
coap-client.c:(.text+0x2553): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x258e): undefined reference to `coap_log_impl'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `verify_ih_callback':
coap-client.c:(.text+0x2615): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x263d): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x277b): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x27ad): undefined reference to `coap_log_impl'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `setup_pki':
coap-client.c:(.text+0x286a): undefined reference to `coap_context_set_pki_root_cas'
/usr/bin/ld: coap-client.c:(.text+0x288a): undefined reference to `coap_context_set_pki_root_cas'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `open_session':
coap-client.c:(.text+0x2e0d): undefined reference to `coap_new_client_session_pki'
/usr/bin/ld: coap-client.c:(.text+0x2e61): undefined reference to `coap_new_client_session_psk2'
/usr/bin/ld: coap-client.c:(.text+0x2e95): undefined reference to `coap_new_client_session_pki'
/usr/bin/ld: coap-client.c:(.text+0x2eb4): undefined reference to `coap_new_client_session'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `get_session':
coap-client.c:(.text+0x2f27): undefined reference to `coap_is_mcast'
/usr/bin/ld: coap-client.c:(.text+0x300d): undefined reference to `coap_address_init'
/usr/bin/ld: coap-client.c:(.text+0x30c9): undefined reference to `coap_address_init'
/usr/bin/ld: /tmp/ccgqFRMM.o: in function `main':
coap-client.c:(.text+0x36f1): undefined reference to `coap_debug_set_packet_loss'
/usr/bin/ld: coap-client.c:(.text+0x3724): undefined reference to `coap_tcp_is_supported'
/usr/bin/ld: coap-client.c:(.text+0x394e): undefined reference to `coap_startup'
/usr/bin/ld: coap-client.c:(.text+0x395b): undefined reference to `coap_set_log_level'
/usr/bin/ld: coap-client.c:(.text+0x3968): undefined reference to `coap_dtls_set_log_level'
/usr/bin/ld: coap-client.c:(.text+0x39e6): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x3a08): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x3b0f): undefined reference to `coap_new_context'
/usr/bin/ld: coap-client.c:(.text+0x3b25): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x3b46): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x3b62): undefined reference to `coap_context_set_keepalive'
/usr/bin/ld: coap-client.c:(.text+0x3b7c): undefined reference to `coap_context_set_block_mode'
/usr/bin/ld: coap-client.c:(.text+0x3b9d): undefined reference to `coap_context_set_csm_max_message_size'
/usr/bin/ld: coap-client.c:(.text+0x3bb6): undefined reference to `coap_register_response_handler'
/usr/bin/ld: coap-client.c:(.text+0x3bcf): undefined reference to `coap_register_event_handler'
/usr/bin/ld: coap-client.c:(.text+0x3be8): undefined reference to `coap_register_nack_handler'
/usr/bin/ld: coap-client.c:(.text+0x3d1a): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x3d3c): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x3d61): undefined reference to `coap_session_init_token'
/usr/bin/ld: coap-client.c:(.text+0x3e56): undefined reference to `coap_new_optlist'
/usr/bin/ld: coap-client.c:(.text+0x3e68): undefined reference to `coap_insert_optlist'
/usr/bin/ld: coap-client.c:(.text+0x3f4c): undefined reference to `coap_session_get_default_leisure'
/usr/bin/ld: coap-client.c:(.text+0x3f6f): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x3f95): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x3f9a): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x3fb8): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x3fbd): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x3fd6): undefined reference to `coap_show_pdu'
/usr/bin/ld: coap-client.c:(.text+0x3fef): undefined reference to `coap_send'
/usr/bin/ld: coap-client.c:(.text+0x3ff9): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x4017): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x40a1): undefined reference to `coap_io_process'
/usr/bin/ld: coap-client.c:(.text+0x40d3): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x40f5): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x4143): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x4161): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x41be): undefined reference to `coap_cancel_observe'
/usr/bin/ld: coap-client.c:(.text+0x41d2): undefined reference to `coap_io_process'
/usr/bin/ld: coap-client.c:(.text+0x4233): undefined reference to `coap_io_process'
/usr/bin/ld: coap-client.c:(.text+0x4355): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x4373): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x4378): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x4391): undefined reference to `coap_show_pdu'
/usr/bin/ld: coap-client.c:(.text+0x43b4): undefined reference to `coap_send'
/usr/bin/ld: coap-client.c:(.text+0x43be): undefined reference to `coap_get_log_level'
/usr/bin/ld: coap-client.c:(.text+0x43dc): undefined reference to `coap_log_impl'
/usr/bin/ld: coap-client.c:(.text+0x4457): undefined reference to `coap_io_pending'
/usr/bin/ld: coap-client.c:(.text+0x4520): undefined reference to `coap_delete_bin_const'
/usr/bin/ld: coap-client.c:(.text+0x454a): undefined reference to `coap_delete_bin_const'
/usr/bin/ld: coap-client.c:(.text+0x45ae): undefined reference to `coap_delete_binary'
/usr/bin/ld: coap-client.c:(.text+0x45e4): undefined reference to `coap_delete_optlist'
/usr/bin/ld: coap-client.c:(.text+0x45f3): undefined reference to `coap_session_release'
/usr/bin/ld: coap-client.c:(.text+0x4602): undefined reference to `coap_free_context'
/usr/bin/ld: coap-client.c:(.text+0x4607): undefined reference to `coap_cleanup'
collect2: error: ld returned 1 exit status

**Comment by salmeghlef** [comment]
Any idea from the developers of this project. Compiling using gcc doen't work, Do I have to another compiler instead?

**Comment by obgm** [comment]
The compiler output tells you that there are a couple of dependencies missing. The most simple approach to fix this is to invoke 'make' as the Makefile has been created to add the correct compiler flags.

**Comment by salmeghlef** [comment]
Cool. Is it possible to say "cmake coap-client.c TARGET=ELF" ? How to compile it to ELF (Executable and Linked Format) format.

**Comment by obgm** [comment]
When `configure`, you can specify the target platform as usual. With cmake, cross compilation is done with a small config file that contains the toolchain description. A web search for "cmake cross compilation" should yield a couple of howtos for this.

**Comment by salmeghlef** [comment]
The target platform is:

 make TARGET=**iotlab-m3**

How to find the small config file that contains the toolchain description of the target **"iotlab-m3"**

**Comment by obgm** [comment]
This is something you would need to ask your favorite web search engine by yourself. There is also the documentation of the iotlab-m3 hardware.

I am not sure what you are trying to achieve, though. You should be aware of the fact that the coap-client example most likely will not run out of the box on the iotlab-m3 because it has been designed as a Linux command-line client; moreover, it requires an underlying  operating system. Iotlab seems to use Contiki-NG by default which has a slightly different build process.

However, this is the libcoap issue tracker. Your questions are more about a general cross-compilation for the iotlab platform. Your answers are in the documentation.

**Comment by salmeghlef** [comment]
Thanks a lot. Now, please suggest me some PUBLIC coap-servers that are available online rather than californium on the address 20.47.97.44

**Comment by obgm** [comment]
There is, e.g., libcoap.net.

**Comment by obgm** [comment]
Is this issue resolved and can be closed off?
