### ISSUE TITLE
Extract the 86 features of CoAP protocol from a pcap file

### ISSUE THREAD

**Issue by salmeghlef** [obgm/libcoap#1025]
Team, coap protocol features are 86 features based on wireshark docs https://www.wireshark.org/docs/dfref/c/coap.html. When capturing through wireshark, only limited features are shown, is there a tool or say a python code to extract all these features from a pcap based coap packet? 

Thank you

**Comment by salmeghlef** [comment]
unbelievable!!! no one tries this before. Unless Jon or the project creator can help, how about other interested developers!!!

**Comment by mrdeep1** [comment]
Closing this as not a libcoap issue per se.
