### ISSUE TITLE
coap-client requests fail with content type null

### ISSUE THREAD

**Issue by StFS** [obgm/libcoap#1044]
## Environment

- libcoap version (run ``git describe --tags`` to find it): v4.3.0
- Build System:             Make
- Operating System:         macOS
- Operating System Version: [ ]
- Hosted Environment:       None

## Problem Description

When I compile my own version of coap-client and try to use it I always get an error complaining about "content type [null] does not match payload".

I run the exact same command line on the same version of coap-client on an Ubuntu (from the apt package) and that works fine.

Here is the command I run:

`coap-client-gnutls -u sensor1@DEFAULT_TENANT -k my-secret -m POST coaps://my-hono.mycompany.com/t -t  application/json -e '{"temp": 5}'`

And as I said, the binary on the Ubuntu machine works fine but the binary that I built on my mac fails with:

`4.00 content type [null] does not match payload`

I've also tried specifying `-t 50` instead of `-t application/json` but it has no effect.

Can anybody tell me something I could try to fix this issue? It's annoying to have to start up a virtual computer just to run the coap-client tool. Also, if there is any information that I need to provide additionally, please let me know.

For the record, I'm compiling libcoap in a rather standard way with:

```
./configure --disable-doxygen --disable-manpages
make
make install
```

And that seems to go fine. Here is the configuration summary:

```
libcoap configuration summary:
      libcoap package version  : "4.3.0"
      libcoap library version  : "3.0.0"
      libcoap API version      : "3"
      libcoap DTLS lib extn    : "-gnutls"
      host system              : "x86_64-apple-darwin22.3.0"
      build with TCP support   : "yes"
      build DTLS support       : "yes"
          -->  GnuTLS around   : "yes" (found GnuTLS 3.8.0)
               GNUTLS_CFLAGS   : "-I/usr/local/Cellar/gnutls/3.8.0/include -I/usr/local/Cellar/nettle/3.8.1/include -I/usr/local/Cellar/libtasn1/4.19.0/include -I/usr/local/Cellar/libidn2/2.3.4_1/include -I/usr/local/Cellar/p11-kit/0.24.1_1/include/p11-kit-1"
               GNUTLS_LIBS     : "-L/usr/local/Cellar/gnutls/3.8.0/lib -lgnutls"
      add default names        : "yes"
      enable small stack size  : "no"
      enable separate responses: "yes"
      build doxygen pages      : "no"
      build man pages          : "no"
      build unit test binary   : "no"
      build examples           : "yes"
      install examples source  : "yes"
      build with gcov support  : "no"
      build shared library     : "yes"
      build static library     : "yes"
```

**Comment by mrdeep1** [comment]
I’m not online at present to do any testing, but it looks like the server is complaining

What is the server?

does it understand content type 50?

have you tried a different content type?

what does the -v7 verbose  for the client logging say?

**Comment by mrdeep1** [comment]
I unfortunately do not have a MAC to test this on.

4.3.0 code is now fairly old (Jun 21 2021), 4.3.1 has been released and the develop branch has further changes.  It is worth trying later versions of code.

That said, with a GnuTLS version for 4.3.0 shows for the client (using -v7 verbose option) on my system
````
v:1 t:CON c:POST i:ddf3 {} [ Uri-Path:t, Content-Format:application/json ] :: '{"temp": 5}'
....
v:1 t:ACK c:2.04 i:ddf3 {} [ ]
````
and doing
````
$ coap-client-gnutls -? 2>&1 | head -8
coap-client-gnutls: invalid option -- '?'
coap-client v4.3.0 -- a small CoAP implementation
Copyright (C) 2010-2021 Olaf Bergmann <bergmann@tzi.org> and others

libcoap 4.3.0
TLS Library: GnuTLS - runtime 3.6.15, libcoap built for 3.6.15
(DTLS and TLS support; PSK, PKI, PKCS11 and RPK support)
```
`4.00 content type [null] does not match payload`
does not exist in the libcoap code which implies a server issue with 'application/json'.

**Comment by StFS** [comment]
Thanks for your reply @mrdeep1.

I'm using the Eclipse Hono project as a server.

As mentioned in the inital description, the Ubuntu binary packages for coap-client actually work fine against the Hono server. And this is the reason I picked that particular version of the project and compiled it, to be using the exact same version as the Ubuntu binary packages provide. That said, I did also try both the 4.3.1 tagged version as well as the latest version from git but all of them displayed the same behavior.

I'm afraid I don't quite understand what your last code block is demonstrating. Is it the root of my problems and if so, is there something I can do to fix it?

**Comment by mrdeep1** [comment]
Sorry - I badly formatted the response, which I have now corrected which should make more sense now.

It would be good if you can provide the coap-client output using the `-v7` option for both the Ubuntu and your built version for comparison - in particular I am looking for the request PDU which will look something like
````
v:1 t:CON c:POST i:ddf3 {} [ Uri-Path:t, Content-Format:application/json ] :: '{"temp": 5}'
````

**Comment by StFS** [comment]
Oh dear... I just figured out what was going on.

For some reason, the CLI binary on MacOS is more sensitive to the order of parameters than the binary on Linux.

So the problem was that I was running the CLI on my Mac providing the `-t` and `-e` parameters AFTER the URI and that seems to cause problems (but only on the Mac binary). When I moved these parameters in front of the URI everything seems to work fine.

For fun and giggles, here's the output of the four different combinations (parameters specified before and after the URI on Linux and Mac):

```
## Linux 

### -t & -e after URI  -  WORKS
stefan@stfs-kubuntu20:~$ coap-client-gnutls -u somesensor@MY_TENANT -k somesecret -v 6 -m POST coaps://my.coap.server.com/t -t application/json -e '{"temp": 5}'
v:1 t:CON c:POST i:8289 {} [ Uri-Host:my.coap.server.com, Uri-Path:t, Content-Format:application/json ] :: '{"temp": 5}'
Mar 06 11:12:08.408 INFO Identity Hint '' provided
v:1 t:ACK c:2.04 i:8289 {} [ ]

### -t & -e before URI  -  WORKS
stefan@stfs-kubuntu20:~$ coap-client-gnutls -u somesensor@MY_TENANT -k somesecret -v 6 -t application/json -e '{"temp": 5}' -m POST coaps://my.coap.server.com/t
v:1 t:CON c:POST i:f9fe {} [ Uri-Host:my.coap.server.com, Uri-Path:t, Content-Format:application/json ] :: '{"temp": 5}'
Mar 06 11:12:47.327 INFO Identity Hint '' provided
v:1 t:ACK c:2.04 i:f9fe {} [ ]


## MacOS

### -t & -e after URI  -  !!!FAILS!!!
❯ coap-client-gnutls -u somesensor@MY_TENANT -k somesecret -v 6 -m POST coaps://my.coap.server.com/t -t application/json -e '{"temp": 5}'
v:1 t:CON c:POST i:2c35 {} [ Uri-Host:my.coap.server.com, Uri-Path:t ]
Mar 06 11:16:58.164 INFO Identity Hint '' provided
v:1 t:ACK c:4.00 i:2c35 {} [ Content-Format:text/plain ] :: 'content type [null] does not match payload'
4.00 content type [null] does not match payload

### -t & -e before URI  -  WORKS
❯ coap-client-gnutls -u somesensor@MY_TENANT -k somesecret -v 6 -t application/json -e '{"temp": 5}' -m POST coaps://my.coap.server.com/t
v:1 t:CON c:POST i:cd24 {} [ Uri-Host:my.coap.server.com, Uri-Path:t, Content-Format:application/json ] :: '{"temp": 5}'
Mar 06 11:17:44.112 INFO Identity Hint '' provided
v:1 t:ACK c:2.04 i:cd24 {} [ ]
```

**Comment by mrdeep1** [comment]
Thanks for the feedback - another one to chalk up to experience!  I think I have stumbled into this with Windows ports as well.
