### ISSUE TITLE
How to send messages

### ISSUE THREAD

**Issue by pedropjr** [obgm/libcoap#105]
Hi, Im using libcoap with a network simulator called Mininet-Wifi and Im trying to send messages to one client to another, but I think Im doing a really silly mistake, but I cant identify what it is. The coap server's IP is 192.168.0.3, the first client who is sending the message is 192.168.0.1. I start the coap-server with "./coap-server -p 5683 -A 192.168.0.3 -v 9", but I dont really know how to create e resource or how to send a message to retrieve it later via GET method with the second client, I tried the example that comes in the source code, but its not working.

**Comment by obgm** [comment]
Can you be more specific what is not working with your second client? How do you call it, what is it supposed to do, what is the debug output on client and server, how does the wireshark trace look like?

**Comment by pedropjr** [comment]
Im having problem with the first client, Im trying to execute this command with my first client "./coap-client -m put -e "on" -t plain -p 5683 coap://192.168.0.3/status -v 9" but it generates "4.04 Not Found" error. I think it should be a really basic solution, but I cant make it work.

**Comment by obgm** [comment]
You will need a resource handler for "status" on your server:  

```c
resource = coap_resource_init((unsigned char *)"status", strlen("status"), 0);
if (resource != nullptr) {
  coap_register_handler(resource, COAP_REQUEST_PUT, your_status_handler);
}
```

**Comment by pedropjr** [comment]
Oh ok, I'll try. Thank you!

**Comment by nabilmakarem** [comment]
Hello,

I have the same problem. I need to create a resource on my coap server. For instance, I need my client to call the resource on the server using coap://server/temperature. I need to know how to create temperature and how to send data to it.

Moreover, in which file to create the following code:

resource = coap_resource_init((unsigned char *)"status", strlen("status"), 0);
if (resource != nullptr) {
  coap_register_handler(resource, COAP_REQUEST_PUT, your_status_handler);
}

regards,
Nabil M.

**Comment by pedropjr** [comment]
The server file needs a resource handler to deal with the incoming client requests. I was able to make it work by using a new coap-server.c file. I can email you with the new server file.

**Comment by obgm** [comment]
Closing as examples are provided in subdirectory `examples`, and there is also [libcoap-mininmal](/obgm/libcoap-minimal).
