### ISSUE TITLE
--disable-examples still builds examples and --disable-documentation still tries to build docs

### ISSUE THREAD

**Issue by karlp** [obgm/libcoap#11]
Worse, this gets you out of the configure tests for the asciidoc host tool, but then fails at "make install" as it tries to install non-existant documentation.

these two options should do what they say properly!

This is causing undesirable downstream patching, see: https://github.com/openwrt/packages/pull/1826

**Comment by obgm** [comment]
Thanks, fixed in commit 2da31de.

**Comment by karlp** [comment]
thanks for wonderfully prompt fixes :)
