### ISSUE TITLE
Question about multicast test.

### ISSUE THREAD

**Issue by ballzb** [obgm/libcoap#1105]
## Environment

- libcoap version (run ``git describe --tags`` to find it):

    // v4.3.1-153-ge05af0d
- Build System:             [CMake]
- Operating System:         [OpenWrt]
- Operating System Version: [ 22.03.0]
- Hosted Environment:       [None, but I'm not sure.] 

## Problem Description

I have tried multicast communication according to #820.
```shell
server: coap-server -g 224.0.1.187 -v7
client(on the same host): coap-client -N -m put -T cafe -e "coap test" coap://224.0.1.187:5683/time
```

But I don't get any log from the server side, is it reasonable?

### Code to reproduce this issue

```Makefile
CONFIGURE_ARGS += \
	--enable-examples \
	--disable-documentation \
	--disable-doxygen \
	--disable-dtls \
	--disable-gcov \
	--disable-tests

```

**Comment by mrdeep1** [comment]
> But I don't get any log from the server side, is it reasonable?

I don,t know how OpenWrt handles the output from the fprintf() command used by libcoap for the logging default. This may be the output issue, or else the coap-server is hanging on (waiting for) something during the startup process.

What are the first 6 lines from the output of
````
coap-server -?
````
Have you tried adding the `-v7` option to the coap-client invocation line - are you getting log output?

Are you getting a response back from the server?

**Comment by ballzb** [comment]
Thanks for your reply, please see the following log.


> What are the first 6 lines from the output of
> 
> ```
> coap-server -?
> ```

```
root@OpenWrt:/# coap-server -g 224.0.1.187 -v7
May 08 18:54:08.297 DEBG created TCP  endpoint [::]:5683
May 08 18:54:08.297 DEBG created UDP  endpoint [::]:5683
May 08 18:54:08.298 DEBG added mcast group 224.0.1.187:5683
```




> Have you tried adding the `-v7` option to the coap-client invocation line - are you getting log output?
> 
> Are you getting a response back from the server?

```
root@OpenWrt:~# coap-client  -N -m put -T cafe -e "coap test" -v7 coap://224.0.1.187:5683/time 
May 08 18:58:26.042 DEBG ***0.0.0.0:55960 <-> 224.0.1.187:5683 UDP : session 0xb6f24020: created outgoing session
May 08 18:58:26.042 DEBG ***0.0.0.0:55960 <-> 224.0.1.187:5683 UDP : session connected
May 08 18:58:26.042 DEBG timeout is set to 6 seconds
May 08 18:58:26.042 DEBG sending CoAP request:
May 08 18:58:26.042 DEBG ** 0.0.0.0:55960 <-> 224.0.1.187:5683 UDP : lg_crcv 0xb6e4fe80 initialized - stateless token xxxx000063616667
May 08 18:58:26.043 DEBG *  0.0.0.0:55960 <-> 224.0.1.187:5683 UDP : netif: sent   30 bytes
v:1 t:NON c:PUT i:2d56 {63616666} [ Uri-Path:time, Request-Tag:0x9e96d0e9 ] :: 'coap test'
May 08 18:58:32.049 INFO timeout
May 08 18:58:32.049 DEBG ** 0.0.0.0:55960 <-> 224.0.1.187:5683 UDP : lg_crcv 0xb6e4fe80 released
May 08 18:58:32.049 DEBG ***0.0.0.0:55960 <-> 224.0.1.187:5683 UDP : session 0xb6f24020: closed
```

**Comment by mrdeep1** [comment]
The logs are reporting information as expected.  It looks like there are multiple interfaces - the server is binding to one and the client is sending it out over another interface (using the default route).
````
netstat -ang
````
will tell you which interface the server is listening for the multicast request.  Try using `-G Iface` for the server to bind the server to listen on `Iface` as reported by `netstat -ang`.

**Comment by ballzb** [comment]
> will tell you which interface the server is listening for the multicast request. Try using `-G Iface` for the server to bind the server to listen on `Iface` as reported by `netstat -ang`.

I have tried your advice, but got the same result.

```
root@OpenWrt:/# coap-server -g 224.0.1.187 -G wan -v7 
May 08 19:13:07.851 DEBG created TCP  endpoint [::]:5683
May 08 19:13:07.851 DEBG created UDP  endpoint [::]:5683
May 08 19:13:07.851 DEBG added mcast group 224.0.1.187:5683 i/f wan
```
```
root@OpenWrt:~# netstat -an |grep 5683
tcp        0      0 :::5683                 :::*                    LISTEN      
udp        0      0 :::5683                 :::*                                
root@OpenWrt:~# 
root@OpenWrt:~# 
root@OpenWrt:~# coap-client  -N -m put -T cafe -e "coap test" -v7 coap://224.0.1.187:5683/time 
May 08 19:13:18.954 DEBG ***0.0.0.0:48528 <-> 224.0.1.187:5683 UDP : session 0xb6f12020: created outgoing session
May 08 19:13:18.955 DEBG ***0.0.0.0:48528 <-> 224.0.1.187:5683 UDP : session connected
May 08 19:13:18.955 DEBG timeout is set to 6 seconds
May 08 19:13:18.955 DEBG sending CoAP request:
May 08 19:13:18.955 DEBG ** 0.0.0.0:48528 <-> 224.0.1.187:5683 UDP : lg_crcv 0xb6e3de80 initialized - stateless token xxxx000063616667
May 08 19:13:18.956 DEBG *  0.0.0.0:48528 <-> 224.0.1.187:5683 UDP : netif: sent   30 bytes
v:1 t:NON c:PUT i:69b6 {63616666} [ Uri-Path:time, Request-Tag:0x4c90da98 ] :: 'coap test'
May 08 19:13:24.962 INFO timeout
May 08 19:13:24.962 DEBG ** 0.0.0.0:48528 <-> 224.0.1.187:5683 UDP : lg_crcv 0xb6e3de80 released
May 08 19:13:24.962 DEBG ***0.0.0.0:48528 <-> 224.0.1.187:5683 UDP : session 0xb6f12020: closed
```
```
root@OpenWrt:~# route 
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.0.3.1        0.0.0.0         UG    0      0        0 wan
10.0.3.0        *               255.255.255.0   U     0      0        0 wan
192.168.1.0     *               255.255.255.0   U     0      0        0 br-lan
```

**Comment by mrdeep1** [comment]
You need to add in the lower G option for `netstat -ang` which needs to be run when the server is running to determine which interface the server is binding the multicast address to.  You also need to check that there is not a firewall rule (I.e. iptables) that is dropping the traffic.

**Comment by mrdeep1** [comment]
@ballzb Are you now able to get this working?

**Comment by ballzb** [comment]
> 

sorry for delay answer, netstat in OpenWrt doesn't support opion g, so I need some time to debug it.

Please let me know if  I should close the issue firtst.

**Comment by ballzb** [comment]
> @ballzb Are you now able to get this working?

sorry for delay answer, netstat in OpenWrt doesn't support opion g, so I need some time to debug it.

Please let me know if I should close the issue firtst.

**Comment by mrdeep1** [comment]
The information you need is in `/proc/net/igmp`.  What I see on another system is
````
$  netstat -ang | grep 224
lo              1      224.0.0.1
eth0            1      224.0.1.187
eth0            1      224.0.0.1
eth1            1      224.0.0.1
$ sudo cat /proc/net/igmp
Idx     Device    : Count Querier       Group    Users Timer    Reporter
1       lo        :     1      V3
                                010000E0     1 0:00000000               0
2       eth0      :     2      V3
                                BB0100E0     1 0:00000000               0
                                010000E0     1 0:00000000               0
3       eth1      :     1      V3
                                010000E0     1 0:00000000               0
````
where the `BB0100E0 `is `224.0.1.187` in byte reverse order.

I suspect that you have iptables / firewall filtering out the multicast traffic.

Have you looked at https://oldwiki.archive.openwrt.org/doc/howto/udp_multicast ?

**Comment by ballzb** [comment]
> The information you need is in `/proc/net/igmp`. What I see on another system is

> Have you looked at https://oldwiki.archive.openwrt.org/doc/howto/udp_multicast ?

Thank you for your advices, I will try it later.

**Comment by ballzb** [comment]
I have tested multicast receive of coap_server, and get correct output. It seems work well.

Thanks.
