### ISSUE TITLE
Listing current observers on a resource

### ISSUE THREAD

**Issue by mikefoxTB** [obgm/libcoap#1109]
Is it possible to get a list of observers for a given server resource? I'd like to know if the observer has acked confirmable notifications, current waiting time for ack etc., with enough information to prune the observer from the server based on lack of confirmations.

**Comment by mrdeep1** [comment]
The resource and subscription are opaque structures to an application, and so an additional libcoap function would need to be created to get the sort of information you are looking for.

However, if the unsolicited responses from the server are confirmable, and there is no ACK response from the client for the (default) 4 retransmissions with exponentially increasing re-transmit times (default overall for all 4 retransmissions is 90 seconds), the CoAP response times out and the observe subscription is automatically deleted/pruned.  Is this just what you need?

If you want to count active observe subscriptions, then you may be able to use [coap_persist_track_funcs(3)](https://libcoap.net/doc/reference/develop/man_coap_persist_track_funcs.html)

**Comment by mrdeep1** [comment]
@mikefoxTB Do you need any more help here?

**Comment by mrdeep1** [comment]
Closing as this thread has gone quiet.
