### ISSUE TITLE
Is it possible to receive CON message in one process and reply ACK in another one?

### ISSUE THREAD

**Issue by ballzb** [obgm/libcoap#1115]
## Environment

- libcoap version (run ``git describe --tags`` to find it):

    // v4.3.1-153-ge05af0d

## Problem Description

Is it possible to receive CON message in one process and reply ACK in another one? If so, how can I implement that?

**Comment by ballzb** [comment]
I set the block mode as following:

```
coap_context_set_block_mode(ctx, COAP_BLOCK_SINGLE_BODY);
```

**Comment by mrdeep1** [comment]
I'm not entirely sure what you are trying to do here.

For a 'connection' between two CoAP endpoints, libcoap has what is known as a 'session'.  Over this 'session' is sent the CoAP request and gets back the CoAP response.  This 'session' also handles any underlying CoAP protocol requirements - e.g. for confirmation traffic it will generate the ACK for confirmable response, or generate the ACK for the confirmable request either with the response (piggybacked) or separately as required (i.e. delayed async response).

> coap_context_set_block_mode(ctx, COAP_BLOCK_SINGLE_BODY);

As COAP_BLOCK_LIBCOAP is not set in the parameter, this is treated as` coap_context_set_block_mode(ctx, 0);` ([coap_context_set_block_mode(3)](https://libcoap.net/doc/reference/develop/man_coap_context_set_block_mode.html) as per Option 1.

You do not say which type of handler you are updating the response pdu.

libcoap is not currently multi-thread safe.

**Comment by ballzb** [comment]
Thanks a lot, I found it's difficult for me to do that. So I have changed my implementation.
