### ISSUE TITLE
Receive multicast coap request sent by myself

### ISSUE THREAD

**Issue by ballzb** [obgm/libcoap#1130]
## Environment

- libcoap version (run ``git describe --tags`` to find it):

    v4.3.1-153-ge05af0d
- Build System:             [CMake]
- Operating System:         [OpenWrt]
- Operating System Version: [ 22.03]

## Problem Description

1. run server which listens on port 5683  and join group "224.0.1.187"
2. send request in group "224.0.1.187"  with port 5683
3. server will receive the request sent by myself.

Is the behaviour reasonable? And how can I avoid it?

**Comment by mrdeep1** [comment]
Assuming the server and client are two separate applications, then I would be expecting the server to be receiving/responding to the multicast request, no matter what the client’s IP address is.

However, a multicast server can elect not to respond, so there is nothing to stop you putting in code in the server request hander that checks if the request is mcast and from the local ip and so not setting the response code in the response pdu, so no response is sent back.

**Comment by ballzb** [comment]
> Assuming the server and client are two separate applications, then I would be expecting the server to be receiving/responding to the multicast request, no matter what the client’s IP address is.
> 
> However, a multicast server can elect not to respond, so there is nothing to stop you putting in code in the server request hander that checks if the request is mcast and from the local ip and so not setting the response code in the response pdu, so no response is sent back.

Thanks very much, I will ignore requests from local ip.

**Comment by mrdeep1** [comment]
Please feel free to close this issue then.

**Comment by ballzb** [comment]
> Please feel free to close this issue then.

I have fixed the problem as your advice, Thanks a lot.
