### ISSUE TITLE
Question:can coap_add_data_large_response() send over 1000 bytes' json value?

### ISSUE THREAD

**Issue by Michael-Jhw** [obgm/libcoap#1145]
I used the coap_add_data_large_response() with block2 to send json::value data.But once the data exceeds more than 1000 bytes, my server will restart.If the data don't exceeds more than 1000 bytes.Server will succeed to block the datas for client.
My coap server codes below here:
		string strResponse = fastWriter.write(jsonResponse);
		coap_pdu_set_code(response, COAP_RESPONSE_CODE_CONTENT);
		coap_add_data_large_response(resource, session, request, response, query, COAP_MEDIATYPE_APPLICATION_JSON, 1, 0,
			strResponse.length(), reinterpret_cast<const uint8_t*>(strResponse.c_str()), NULL, NULL);

**Comment by mrdeep1** [comment]
As per [coap_add_data_large_response(3)](https://libcoap.net/doc/reference/4.3.1/man_coap_add_data_large_response.html#coap_add_data_large_response), any dynamically generated data must exist over sending the multiple blocks and only be released when the final block has been successfully transmitted.  This can be done automatically by libcoap by using the last 2 parameters of the function.

`strResponse` only exists while the current response handler is active, not when the next block is being processed.

**Comment by Michael-Jhw** [comment]
Thanks a lot.It works.@mrdeep1
