### ISSUE TITLE
improve portability of coap-rd.c and coap-server.c

### ISSUE THREAD

**Issue by dmosberger** [obgm/libcoap#115]
Attached is a tiny patch to improve the portability of the examples.  The existing code assumes that FD_SETSIZE is greater than the largest valid file descriptor number.  On some embedded systems, that's not the case.

For example, with systems using the LWIP stack, the socket descriptor numbers may start at an offset (e.g., 4096) and fd_set may only be large enough to cover the socket descriptors (not regular file descriptors).  Thus, FD_SETSIZE could be much smaller than the largest valid socket descriptor number.  I ran into this problem on an esp32 system where, recently, the esp-idf SDK was changed to start socket numbers at 4096 (rather than 0).  fd_set by default is only large enough for 4 sockets.

[portability-improvement.patch.txt](https://github.com/obgm/libcoap/files/1425761/portability-improvement.patch.txt)

**Comment by obgm** [comment]
Thank you very much. In the develop branch, this has already been fixed during refactoring. You are using the master branch, i.e. the latest stable release?

**Comment by dmosberger** [comment]
Ah, yes, that looks much nicer!

**Comment by mrdeep1** [comment]
@dmosberger Can this be closed off now?

**Comment by dmosberger** [comment]
Yup, thanks!
