### ISSUE TITLE
coap_mcast_interface()

### ISSUE THREAD

**Issue by dmosberger** [obgm/libcoap#117]
Could someone explain to me how coap_mcast_interface() is intended to work?  As far as I can see, this "function" has always been defined as a macro that returns 0.  It is used only once in net.c:
```
	if ((respond == RESPONSE_SEND)
	  || /* RESPOND_DEFAULT */
	  (response->type != COAP_MESSAGE_NON ||
	  (response->code >= 64
	    && !coap_mcast_interface(&node->local_if)))) {

	  if (coap_send(session, response) == COAP_INVALID_TID)
```
I think the intent here is that if the HTTP response code is at least 200, then a non-confirmable response to a multicast request is not dropped (not sent).  Of course, since coap_mcast_interface() always returns 0, multicast responses are always sent, which may not be necessary or desirable.

Am I understanding this code correctly?  If so, why does it make the multicast-determination based on the interface?  Wouldn't it be better to make the decision based on whether the request packet was sent to a multicast address?

Thanks!

**Comment by obgm** [comment]
The multicast handling has been reworked lately. Closing off as obsolete.
