### ISSUE TITLE
DTLS: authentication based on the raw public key & certificate-based authentication 

### ISSUE THREAD

**Issue by sbalakrishnan-wisilica** [obgm/libcoap#118]
Hi,

Can some one please let know if currently DTLS with authentication based on the raw public key & certificate-based authentication is supported by libcoap. If yes, some brief pointers about how to go about building it (i.e which lib to use openssl, gnuTLS to use) and using it would be helpful.We were able to get DTLS with PSK working with tinyDTLS.

Thanks in advance,
sBalakrishnan

**Comment by obgm** [comment]
This is work in progress, please see the [mailing list](https://sourceforge.net/p/libcoap/mailman/libcoap-developers/thread/09ae01d32bdf%2482716fd0%2487544f70%24%40jpshallow.com/#msg36035684) for the current discussion on the API.

**Comment by sbalakrishnan-wisilica** [comment]
Thank You for the information.
