### ISSUE TITLE
coap_nack_handler_t function was executed incorrectly

### ISSUE THREAD

**Issue by MrHulu** [obgm/libcoap#1183]
Dear Contributors

## Environment

- libcoap version :  [v4.3.1-174-gf3861a6]
- Build System:             [CMake]
- Operating System:         [Windows]
- Hosted Environment:       [None]

## Problem Description

In the client, the coap_register_nack_handler callback function gets triggered incorrectly.

First of all, the retransmission count defaults to 4, and I didn't change that value. If the server is not connected, when I send a CON request to the server, then the number of times the callback function registered in the COAP_REGISTER_NAK_HANDLER function is triggered should be 4 (retransmission count) + 1 (normal send) + 1 (justified by the last of the COAP_NAK_TOO_MANY_RETRIES)

However, before sending the CON request, if I send N (non-confirmable) requests, the number of times the callback function is triggered will be N times on top of the normal number.

Looking forward to your reply.

**Comment by mrdeep1** [comment]
For the CON requests, I would expect the user defined NACK handler to be called with

- 5 * COAP_NACK_ICMP_ISSUE   (which assumes the remote end has responded with an ICMP diagnostic error message)
- 1 * COAP_NACK_TOO_MANY_RETRIES

With NON requests, the NACK handler is not currently being called as far as I can tell, so not sure what you are seeing in the NACK handler for your `N` (non-confirmable) requests.

**Comment by MrHulu** [comment]
I know that NON doesn't call the nack callback, but after I sent a NON request and a CON request, I received 6 * COAP_NACK_ICMP_ISSUE and 1 * COAP_NACK_TOO_MANY_RETRIES

**Comment by MrHulu** [comment]
```diff
diff --git a/client.cc b/client.cc
index 58a06e5..d2c9e3f 100644
--- a/client.cc
+++ b/client.cc
@@ -22,10 +22,10 @@ main(void) {
   coap_startup();
 
   /* Set logging level */
-  coap_set_log_level(COAP_LOG_WARN);
+  coap_set_log_level(LOG_INFO);
 
   /* resolve destination address where server should be sent */
-  if (resolve_address("coap.me", "5683", &dst) < 0) {
+  if (resolve_address("localhost", "5688", &dst) < 0) {
     coap_log_crit("failed to resolve address\n");
     goto finish;
   }
@@ -53,12 +53,24 @@ main(void) {
                                         coap_show_pdu(COAP_LOG_WARN, received);
                                         return COAP_RESPONSE_OK;
                                       });
+  coap_register_nack_handler(ctx, [](auto,
+                                    const coap_pdu_t *sent,
+                                    const coap_nack_reason_t reason,
+                                    const coap_mid_t mid){
+                                      coap_log(COAP_LOG_WARN, "nack: reason[%d] mid[%x]", reason, mid);
+                                      coap_show_pdu(COAP_LOG_WARN, sent);
+                                      return;
+                                    }); 
   /* construct CoAP message */
   pdu = coap_pdu_init(COAP_MESSAGE_CON,
                       COAP_REQUEST_CODE_GET,
                       coap_new_message_id(session),
                       coap_session_max_pdu_size(session));
-  if (!pdu) {
+
+  /* NON  */
+  auto non_pdu = coap_new_pdu(COAP_MESSAGE_NON, COAP_REQUEST_CODE_GET, session);
+
+  if (!pdu || !non_pdu) {
     coap_log_emerg("cannot create PDU\n" );
     goto finish;
   }
@@ -67,15 +79,23 @@ main(void) {
   coap_add_option(pdu, COAP_OPTION_URI_PATH, 5,
                   reinterpret_cast<const uint8_t *>("hello"));
 
+  coap_show_pdu(COAP_LOG_WARN, non_pdu);
   coap_show_pdu(COAP_LOG_WARN, pdu);
-  /* and send the PDU */
+
+  /* First send the NON PDU */
+   if (coap_send(session, non_pdu) == COAP_INVALID_MID) {
+    coap_log_err("cannot send CoAP non_pdu\n");
+    goto finish;
+  }
+
+  /* Then send the CON PDU */
   if (coap_send(session, pdu) == COAP_INVALID_MID) {
     coap_log_err("cannot send CoAP pdu\n");
     goto finish;
   }
 
   while (have_response == 0)
-    coap_io_process(ctx, COAP_IO_WAIT);
+    coap_io_process(ctx, 1000);
 
   result = EXIT_SUCCESS;
  finish:
```

## Log Debug
```
v:1 t:NON c:GET i:6763 {} [ ]
v:1 t:CON c:GET i:6762 {} [ Uri-Path:hello ]
Jul 21 17:48:07.237 WARN ** [::1]:59041 <-> [::1]:5688 UDP : coap_socket_recv: ICMP: 远程主机强迫关闭了一个现有的连接。


Jul 21 17:48:07.257 WARN nack: reason[4] mid[6762]v:1 t:CON c:GET i:6762 {} [ Uri-Path:hello, Request-Tag:0xd9cedcb5 ]
Jul 21 17:48:07.257 WARN ** [::1]:59041 <-> [::1]:5688 UDP : coap_socket_recv: ICMP: 远程主机强迫关闭了一个现有的连接。


Jul 21 17:48:07.257 WARN nack: reason[4] mid[6762]v:1 t:CON c:GET i:6762 {} [ Uri-Path:hello, Request-Tag:0xd9cedcb5 ]
Jul 21 17:48:10.177 WARN ** [::1]:59041 <-> [::1]:5688 UDP : coap_socket_recv: ICMP: 远程主机强迫关闭了一个现有的连接。


Jul 21 17:48:10.177 WARN nack: reason[4] mid[6762]v:1 t:CON c:GET i:6762 {} [ Uri-Path:hello, Request-Tag:0xd9cedcb5 ]
Jul 21 17:48:16.059 WARN ** [::1]:59041 <-> [::1]:5688 UDP : coap_socket_recv: ICMP: 远程主机强迫关闭了一个现有的连接。


Jul 21 17:48:16.059 WARN nack: reason[4] mid[6762]v:1 t:CON c:GET i:6762 {} [ Uri-Path:hello, Request-Tag:0xd9cedcb5 ]
Jul 21 17:48:27.823 WARN ** [::1]:59041 <-> [::1]:5688 UDP : coap_socket_recv: ICMP: 远程主机强迫关闭了一个现有的连接。


Jul 21 17:48:27.823 WARN nack: reason[4] mid[6762]v:1 t:CON c:GET i:6762 {} [ Uri-Path:hello, Request-Tag:0xd9cedcb5 ]
Jul 21 17:48:51.334 WARN ** [::1]:59041 <-> [::1]:5688 UDP : coap_socket_recv: ICMP: 远程主机强迫关闭了一个现有的连接。


Jul 21 17:48:51.334 WARN nack: reason[4] mid[6762]v:1 t:CON c:GET i:6762 {} [ Uri-Path:hello, Request-Tag:0xd9cedcb5 ]
Jul 21 17:49:38.347 WARN ** [::1]:59041 <-> [::1]:5688 UDP : mid=0x6762: give up after 4 attempts
```

**Comment by mrdeep1** [comment]
As can be seen from all the `WARN nack:` lines, the reported PDU is of type CON with the mid being 6762.

The logic sees a ICMP diagnostic packet and knows that it is associated with the current 5-tuple of (source)IP,port,prot,(destination)IP,port and so it is associated with the current CoAP session the client is using.  It has no idea as to which request is for (the NON or CON in your case) so looks up to see if there are any outstanding CON requests (not yet replied to) and chooses the first one of them to tell the application via the NACK handler.

What is happening here from a timing perspective is

- NON sent
- CON sent
- ICMP diagnostic response for the NON
- ICMP diagnostic response for the CON

When the ICMP diagnostic response for the NON arrives, it looks up whether there as any outstanding CON requests (answer Yes) and reports the CON request as potentially failing.  I cannot think of a simple way of getting around that,

**Comment by MrHulu** [comment]
If it's a NON request that is unresponsive, the nack callback function should not be able to be triggered, even though there is now also a CON request that is unresponsive, which would result in something like the title describes.

Is it possible to determine more precisely when a NON request is unresponsive before calling the nack callback function?

**Comment by MrHulu** [comment]
> When the ICMP diagnostic response for the NON arrives, it looks up whether there as any outstanding CON requests (answer Yes) and reports the CON request as potentially failing. I cannot think of a simple way of getting around that,

When the ICMP diagnostic response for the NON arrives, it should not query the CON for the request. I feel that not doing anything is also better than an incorrect callback notification... Otherwise it will cause misunderstanding

**Comment by MrHulu** [comment]
> When the ICMP diagnostic response for the NON arrives, it looks up whether there as any outstanding CON requests (answer Yes) and reports the CON request as potentially failing. I cannot think of a simple way of getting around that,

When the ICMP diagnostic response for the NON arrives, it should not query the CON for the request. I feel that not doing anything is also better than an incorrect callback notification... Otherwise it will cause misunderstanding

**Comment by mrdeep1** [comment]
An ICMP diagnostic error message is only guaranteed to the IP header and the first 8 bytes of the payload, which in this case is the UDP header (which is 8 bytes).  RFC1122 3.2.2 says
````
         Every ICMP error message includes the Internet header and at
         least the first 8 data octets of the datagram that triggered
         the error; more than 8 octets MAY be sent; this header and data
         MUST be unchanged from the received datagram.
````
so there is no guarantee that any of the CoAP payload is in the diagnostic response for analysis.

All one can assume is that if there is a ICMP diagnostic issue that there are network issues, but impossible to be specific about which packet it is the response to (other than it goes to the correct CoAP session).

It is also possible that no ICMP diagnostic response is received by the client (firewall, or target host is not online).

**Comment by MrHulu** [comment]
Well, it does seem that there is no good solution to this problem...

Finally I would like to ask if there is a function to stop io processing? I've noticed that sometimes I've freed all the resources (session, context, endpoint) but the nack or ack callback function is still triggered... It's easy to introduce program exceptions.

**Comment by mrdeep1** [comment]
> Well, it does seem that there is no good solution to this problem...

Agreed.  However, I do think that the NACK handler should be called for NON requests that trigger an ICMP diagnostic error and I will fix that.  The logic responding to the ICMP diagnostic error will not necessarily choose the correct `sent` PDU for reasons given above and may even set `sent` to NULL.

> Is  there is a function to stop io processing?

For a client, all you need to do is (from within `main()`)
````
  /* Clean up library usage */
  coap_session_release(session);
  coap_free_context(ctx);
  coap_cleanup();
````
when the code is exiting.  I/O processing only continues to happen when you keep on calling `coap_io_process()`.  To exit in the middle of a call-back handler (which is invoked by `coap_io_process()`) is unsafe.

**Comment by MrHulu** [comment]
> The logic responding to the ICMP diagnostic error will not necessarily choose the correct sent PDU for reasons given above and may even set sent to NULL.

Besides ICMP errors triggering the NACK handler, are there any other `reason` that cause incorrect `sent` PDU?

>when the code is exiting. I/O processing only continues to happen when you keep on calling coap_io_process(). To exit in the middle of a call-back handler (which is invoked by coap_io_process()) is unsafe.
`coap_io_process()` I put in a thread and call it in a loop, I will end the thread before I call these codes below:
```cpp
  /* Clean up library usage */
  coap_session_release(session).
  coap_free_context(ctx);
  coap_cleanup();
```
But I've noticed that the NACK handler continues to trigger once in a while...Perhaps there are other actions I should add?

**Comment by mrdeep1** [comment]
> Besides ICMP errors triggering the NACK handler, are there any other reason that cause incorrect sent PDU?

If a CoAP response is received, then there will be a correct match up for the PDU that is used in `sent` when the NACK handler is called for any other reason.

> coap_io_process() I put in a thread and call it in a loop,

This is unsafe, libcoap is not currently multi-thread safe, so interaction between 2 threads calling `coap_*()` functions will cause issues.

**Comment by MrHulu** [comment]
>This is unsafe, libcoap is not currently multi-thread safe, so interaction between 2 threads calling coap_*() functions will cause issues.

But coap_io_process is blocking and I can only put in threads or my UI will not work. Any solution for this?

**Comment by mrdeep1** [comment]
Just put the client.cc logic in its own thread so that all the coap_*() calls are just done on one thread.

**Comment by MrHulu** [comment]
> Just put the client.cc logic in its own thread so that all the coap_*() calls are just done on one thread.

Okay, thanks.
___
In the documentation I found the function `coap_io_pending`.
```doc
int coap_io_pending ( coap_context_t * context )	
Check to see if there is any i/o pending for the context.

This includes Observe active (client) and partial large block transfers.

coap_io_process() is called internally to try to send outstanding data as well as process any packets just received.

Parameters
context The CoAP context.
Returns
1 I/O still pending, 0 no I/O pending.
```
What I'm curious about is the internal call to `coap_io_process`. 
Can this function be used instead of `coap_io_process`? I didn't find an example. What is the preferred usage of this function? My thoughts are
```cpp
while(coap_io_pending(context));
```

**Comment by MrHulu** [comment]
Understand that it can only detect if the packet it sent was sent?
What problem did you design this function to solve? Or to facilitate some judgment?

**Comment by mrdeep1** [comment]
Someone wanted to check there were no outstanding transmissions before closing an app down.

**Comment by MrHulu** [comment]
Thank you for your answer.

Can I know what update your release version?

**Comment by mrdeep1** [comment]
Do you mean - when is 4.3.2 going to be released?  Not expected to be that long off, but need to check that -rc1 is stable first after fixing any minor issues found.

**Comment by MrHulu** [comment]
Thanks, looking forward to 4.3.2. Until then, I'll keep testing the dev branch.
