### ISSUE TITLE
openssl dtls  does not work

### ISSUE THREAD

**Issue by reckrock** [obgm/libcoap#119]
it works with non-dtls mode, but it seems run into endless loop with dtls mode. 

Here's the log on server:
./coap-server -v 15
Nov 14 09:36:51 DEBG created UDP endpoint [::]:5683
Nov 14 09:36:51 CRIT DTLS is supported 1
Nov 14 09:36:51 DEBG created DTLS  endpoint [::]:5684
Nov 14 09:36:51 DEBG created TCP endpoint [::]:5683
Nov 14 09:36:51 DEBG created TLS endpoint [::]:5684
Nov 14 09:36:57 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 305 bytes
Nov 14 09:36:57 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 60 bytes
Nov 14 09:36:57 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 337 bytes
Nov 14 09:36:57 DEBG SSL_accept:before SSL initialization
Nov 14 09:36:57 DEBG *** [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: new incoming session
Nov 14 09:36:59 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 337 bytes
Nov 14 09:36:59 DEBG SSL_accept:before SSL initialization
Nov 14 09:36:59 DEBG SSL_accept:SSLv3/TLS read client hello
Nov 14 09:36:59 DEBG SSL_accept:SSLv3/TLS write server hello
Nov 14 09:36:59 DEBG SSL_accept:SSLv3/TLS write key exchange
Nov 14 09:36:59 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 170 bytes
Nov 14 09:36:59 DEBG SSL_accept:SSLv3/TLS write server done
Nov 14 09:36:59 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 131 bytes
Nov 14 09:36:59 DEBG SSL_accept:SSLv3/TLS write server done
Nov 14 09:36:59 DEBG got psk_identity: 'coap'
Nov 14 09:36:59 DEBG SSL_accept:SSLv3/TLS read client key exchange
Nov 14 09:37:01 DEBG ** [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: DTLS retransmit timeout
Nov 14 09:37:01 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 78 bytes
Nov 14 09:37:01 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 67 bytes
Nov 14 09:37:01 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 25 bytes
Nov 14 09:37:01 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 64 bytes
Nov 14 09:37:01 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 14 bytes
Nov 14 09:37:01 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 53 bytes
Nov 14 09:37:04 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 64 bytes
Nov 14 09:37:04 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 78 bytes
Nov 14 09:37:04 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 67 bytes
Nov 14 09:37:04 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 25 bytes
Nov 14 09:37:04 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 14 bytes
Nov 14 09:37:04 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 53 bytes
Nov 14 09:37:09 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 64 bytes
Nov 14 09:37:09 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 78 bytes
Nov 14 09:37:09 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 67 bytes
Nov 14 09:37:09 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 25 bytes
Nov 14 09:37:09 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 14 bytes
Nov 14 09:37:09 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: received 53 bytes
Nov 14 09:37:18 DEBG ** [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: DTLS retransmit timeout
Nov 14 09:37:18 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 78 bytes
Nov 14 09:37:18 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 67 bytes
Nov 14 09:37:18 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 25 bytes
Nov 14 09:37:35 DEBG ** [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: DTLS retransmit timeout
Nov 14 09:37:35 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 78 bytes
Nov 14 09:37:35 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 67 bytes
Nov 14 09:37:35 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 25 bytes
Nov 14 09:38:08 DEBG ** [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: DTLS retransmit timeout
Nov 14 09:38:08 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 78 bytes
Nov 14 09:38:08 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 67 bytes
Nov 14 09:38:08 DEBG *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: sent 25 bytes
^CNov 14 09:38:37 DEBG *** [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:50288 (if1) DTLS: session closed

Here's the log on client:
coap-client -m get coaps://127.0.0.1/ -key secretPSK -u coap
^C

Thanks.

**Comment by obgm** [comment]
Thanks, I can reproduce this behavior and will have a look at it.

**Comment by reckrock** [comment]
@obgm I tested again, and found that the command of coap-client is wrong.  it should be "coap-client coaps://127.0.0.1/ -u coap -k secretPSK".  So this is not a issue now. 

Thank you!
