### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by nikosft** [obgm/libcoap#12]
Is it that hard to provide at least one example on how to compile a "hello world" program that uses libcoap?

**Comment by nikosft** [comment]
I created a minimum hello world CoAP server. You can find the source code and instructions for compiling it in Linux here http://respected-professor.blogspot.gr/2015/11/a-hello-world-coap-server-using-libcoap.html

**Comment by obgm** [comment]
Nikos Fotiou <notifications@github.com> writes:

> http://respected-professor.blogspot.gr/2015/11/a-hello-world-coap-server-using-libcoap.html

Great, thank you very much!

Grüße
Olaf

**Comment by tijuca** [comment]
Interesting!
What license is your source?

**Comment by nikosft** [comment]
it is just an example. Use it in any way you like it.

**Comment by tijuca** [comment]
Please set up some **any** copyright information, no information about the license is the worst thing you can do. I (or any project) wont use source code where I'm not know which license the code is come from.

**Comment by nikosft** [comment]
A simple CoAP client is now also provided

**Comment by obgm** [comment]
Closing as examples are available, see also the subdirectory `examples` as well as [libcoap-minimal](/obgm/libcoap-minimal).
