### ISSUE TITLE
How bulid it on arm-9?

### ISSUE THREAD

**Issue by xuanqingyi** [obgm/libcoap#122]
Ｔｈａｎｋ　ｙｏｕ　ｆｏｒ　ｙｏｕ　ｗａｔｃｈｉｎｇ
How to cross compile?
Need I revise the Makefile?
$./configure --host=arm-fsl-linux-gnuabi --disable-documentation
next ＄make or make CC=arm-fsl-linux-gnuabi　？

**Comment by tijuca** [comment]
Please see https://github.com/obgm/libcoap/issues/31

Scroll done to the end of the thread.
