### ISSUE TITLE
Libcoap coap_io_process segmentation fault

### ISSUE THREAD

**Issue by Harikeshk7** [obgm/libcoap#1227]
## Environment

- Build System:             Make
- Operating System:         [Windows|Linux]
- Operating System Version: [ ]
- Hosted Environment:       [None]

## Problem Description

I have a client side Libcoap script running on my Windows 10 machine, and I have a server side Libcoap script running on a Linux system (specifically a Raspberry Pi 4). They were adapted from the client and server examples from the repository. I ran both the server and client side scripts on the same windows machine and it worked correctly. Once I moved the server code to the linux machine, the code produces a segmentation fault after the execution of coap_io_process(). I assumed the difference was due to the addition of EPOLL support in the linux machine, which triggers execution of new code blocks. Specifically I found that the source of the fault was in coap_address.c in the function `int coap_is_bcast(const coap_address_t *a)`, at the if condition `if (ife->ifa_addr->sa_family == AF_INET && ife->ifa_flags & IFF_BROADCAST) ` at line 219 on the latest development branch. 

### Expected Behavior

The client initiates a CoAP get request to a resource created on the server script, and the server responds with a simple text message.

### Actual Behavior

The server receives the get request, and creates the CoAP response (I confirmed this with printing out the payload), after executing coap_send and eventually coap_io_process(), the segmentation fault occurs.

### Fix on my end
So I went to the specific if condition line and changed it to if (ife->ifa_addr && ife->ifa_addr->sa_family == AF_INET && ife->ifa_flags & IFF_BROADCAST).

to ensure the ife->ifa_addr is not NULL before trying to access the sa_family attribute,
And it works. 
I've attached my server script below, I've since then made a lot of changes to the implementation, but the fix is still necessary.

[coap-server_otbr.c.txt](https://github.com/obgm/libcoap/files/12560938/coap-server_otbr.c.txt)

I'm pretty sure I'm initializing the response properly with the address because when I run both script on the same machine there's no problem. So I'm lead to believe that it could be a bug?

**Comment by mrdeep1** [comment]
I can immediately see an issue with your server code design.  Using `coap_send()` is **not** required in a request handler (e.g. in your code `handle_get()`).  The response PDU is pre-built before calling the request handler (in `response` parameter) and the request handler just need to update that PDU.  On return from the request handler, the response PDU is either sent off based on the updated PDU code or dropped if it is left as 0.00.

See [coap_register_request_handler(3)](https://libcoap.net/doc/reference/develop/man_coap_register_request_handler.html) and the first EXAMPLE on that man page.

All you need to do is update the response PDU with your data based on query, and set the response code to COAP_RESPONSE_CODE_CONTENT (which is 2.05) before returning from the request handler function.

Separately, you have found a bug as you describe in `coap_is_bcast()` which I will get fixed.  Thanks for tracking this down.

**Comment by mrdeep1** [comment]
Fix for the NULL `ife->ifa_addr` is in PR #1228.

**Comment by Harikeshk7** [comment]
I see! Thank you so much for the information about the usage of the response parameter instead, that makes things a lot simpler. Also I'm glad that it is indeed a bug. Since it is already in the PR, should I close this issue, or should I leave it open?

**Comment by mrdeep1** [comment]
Please close this issue.
