### ISSUE TITLE
Deleting nested resources

### ISSUE THREAD

**Issue by arauko9** [obgm/libcoap#124]
Hello,

First of all, thank you for developing this library, it is really useful. 

What I'm trying to do is when I delete a resource I also want to delete its nested resources. To be able to delete those nested resources I'm trying to use the coap_delete_resource() function, but I need the key of the nested resource and I am not being able to get it. Is this the right approach or should I do something differently?

Thank you in advance,

arauko9

**Comment by obgm** [comment]
Thank you for the kind words. libcoap indeed is not yet very good with nested resources. Currently, every resource is independent of its ancestor (or successor, respectively). If you have a request object you should use the function `coap_hash_request_uri()` to calculate the resource's key (which then could be used as argument for `coap_get_resource_from_key()`.

But as I understand from your question, you want to delete a subtree of a resource. So far, this works only if you know the URIs for the nodes in the subtree (you could split the URI path and then call `coap_hash()` on each segment as done in `coap_get_resource_from_key()`). If you do not know the URIs of the nested resource, the only thing you can do is to use the macro `RESOURCES_ITER` to walk the entire resource collection and check against the `uri` component of each `coap_resource_t`. *Both methods are dirty hacks that might not work any more once nested resources will have been implemented in libcoap.*

**Comment by arauko9** [comment]
Thank you for your rapid response. Yes, you understand my question right. However, I'm struggling to achieve what I want. I'll try to explain more concretely my problem. 

As I previously said, I have nested resources. The nested resources hang from a resource called "Files". Then I have several files, and then each file has a resource named "Status". 
Files/
----File_01/
--------Status
----File_02/
--------Status
...

What I want is to delete the corresponding "Status" when deleting a File.

I achieved to receive the key of a resource with coap_hash() when it is in the first level of path, but I do not see how to go further.

**Comment by obgm** [comment]
One possibility to achieve this would be to add something like the following to your DELETE handler:

```c
coap_key_t key;
const char status_resource[] = "Status";
memcpy(key, resource->key, sizeof(key));
coap_hash((const unsigned char *)status_resource, sizeof(status_resource) - 1, key);

coap_delete_resource(ctx, key);
```

**Comment by arauko9** [comment]
Thank you, that worked!
I don't quite understand why it works, as there are several "Status" resources, but I will look into it. 
Thank you.

**Comment by obgm** [comment]
`resource->key` contains the hash value for `Files/File_NN`, i.e., the parent resource. The `memcpy` call initializes `key` with that hash value which is then updated by `coap_hash()`. This pretty much reflects what `coap_hash_request_uri()` does to retrieve the requested resource's key.
