### ISSUE TITLE
Sent PDU in response handler not correctly read

### ISSUE THREAD

**Issue by torres98** [obgm/libcoap#1243]
## Environment

- Build System:             Make 4.3 | CMake 3.27.4
- Operating System:         Ubuntu 22.04.03 LTS
- Hosted Environment:       None

## libcoap Configuration Summary

[configure_output.txt](https://github.com/obgm/libcoap/files/12749466/configure_output.txt)

## Problem Description

Inside a response handler, you have the possibility to access the PDU sent as a request by the client. When the request PDU is too long (i.e. when divided in blocks by libcoap), then trying to read its content inside the response handler results in a truncated or empty byte array.

### Expected Behavior

I would expect to be able to read the content of the sent PDU correctly.

### Steps to reproduce
On linux, these are the commands i use:

```
gcc client.c -l coap-3 -o client
./client
```
```
gcc server.c -l coap-3 -o server
./server
```
### Code to reproduce this issue

[client.txt](https://github.com/obgm/libcoap/files/12749523/client.txt)
[server.txt](https://github.com/obgm/libcoap/files/12749524/server.txt)

**Comment by mrdeep1** [comment]
Yes, the returned sent PDU (which may be NULL for a NON transfer, or this is an unsolicited Observe response, etc.) is not completely reflecting the original sent PDU as the underlying logic for handling large transmissions is updating what is actually being sent.  I will look to see if there is an easy way to track the original provided PDU for sending.

There are several coding / logic issues in your client.c file.
````
static coap_response_t reply_handler(coap_session_t* session, const coap_pdu_t* sent_pdu, const coap_pdu_t* incoming_pdu, coap_mid_t) {
````
is missing a variable name that follows `coap_mid_t`.

````
  //create a client endpoint for context
  coap_session_t* session = coap_new_client_session(ctx, NULL, &server_address, COAP_PROTO_UDP);
....
  // register handler
  coap_register_response_handler(ctx, reply_handler);
````
I would recommend defining the response handler before initiating a new client session - just in case there is an unsolicited response coming down the wire following a client restart.

````
  // Cleanup and free resources
  coap_free_context(ctx);
  coap_session_release(session);
````
[coap_free_context(3)](https://libcoap.net/doc/reference/develop/man_coap_free_context.html) clears down all sessions associated with `ctx`, so `coap_session_release()` is now working on a `session `that has been released and memory is invalid.

**Comment by torres98** [comment]
Thank you for the tips! So do you plan to change this behaviour in order to allow the full access to the sent PDU?

**Comment by torres98** [comment]
Well, in our code base it becomes necessary, but we have a workaround ready. So in case don't worry, but I would point this behaviour out somewhere (maybe in the docs)

**Comment by mrdeep1** [comment]
Yes, will update the documentation re behaviour.

**Comment by mrdeep1** [comment]
[coap_register_request_handler(3)](https://libcoap.net/doc/reference/develop/man_coap_register_request_handler.html) has been updated to reflect the fact that data is not always available in the `sent` parameter.
