### ISSUE TITLE
Add zephyr integration

### ISSUE THREAD

**Issue by mkschreder** [obgm/libcoap#1253]
**Is your feature request related to a problem? Please describe.**

It would be nice to import libcoap as a zephyr module and build it for all zephyr platforms that support networking. 
**Describe the solution you would like**
I would like to see zephyr folder with module jaml and also zephyr cmakelists.txt file

**Comment by mrdeep1** [comment]
@mkschreder Please see #1267 as a starting point for you to try out, and comments welcome.

I am not a Zephyr developer, so there may be some better ways of doing things, but was able to run a CoAP client with no issues.

**Comment by mkschreder** [comment]
Thank you. Will have to evaluate this but looks like a good starting point so far.

**Comment by mrdeep1** [comment]
Closing as zephyr support is now available with a client example.
