### ISSUE TITLE
Is coaps+tcp client supported by lwip+mbedtls?

### ISSUE THREAD

**Issue by JimmyBaize** [obgm/libcoap#1268]
**Is your feature request related to a problem? Please describe.**
I plan to use lwip+mbedtls to implement the coaps+tcp client, Is this supported?

**Comment by JimmyBaize** [comment]
Because I looked at the LWIP section of the installation guide
https://libcoap.net/install.html
I thought that if Using libcoap with LwIP, only support TinyDTLS.
Is it right?

**Comment by mrdeep1** [comment]
The initial libcoap support for using LwIP was UDP based as CoAP over TCP was not around (but now is as per RFC8323.  I would not expect adding in TCP support to be that difficult.

Adding in MbedTLS support would involve adding in the MbedTLS library source files for compilation - similar to how TinyDTLS support was added in.  LwIP does support `altcp` with MbedTLS, but that too requires the MbedTLS library source files to be compiled in.  However, `altcp` would not really help here as libcoap inserts the (D)TLS layer into the network stack depending on whether coap (or coap+tcp) is being used, or coaps (or coaps+tcp) is being used, so just using `tcp` in LwIp wold be better.

**Comment by JimmyBaize** [comment]
If I port lwip to the OS, libcoap only uses the POSIX socket API, is that okay?

**Comment by mrdeep1** [comment]
To set LWIP_SOCKET to 1 requires that NO_SYS is set to 0, which has other ramifications.

Two ways forward for LwIP TCP support as I initially see it
Support NO_SYS ==0
Update libcoap code to support non-posix TCP calls.
