### ISSUE TITLE
coaps+tcp client support Full-duplex?

### ISSUE THREAD

**Issue by JimmyBaize** [obgm/libcoap#1269]
**Is your feature request related to a problem? Please describe.**

one coaps+tcp client and  one session. 
Because coap is full duplex,Therefore, there are two message flow scenarios:

1. proactively send a request and receive response

1. receive request  and send response 

**Is this a feasible design?**

_thread-A_ run 
```
while(1){
   coap_io_process(ctx, 1000)
}
```
it will process io event. When there is no I/O event, the CPU time slice is released.

_thread-B_ run `coap_send` to sending heartbeat messages periodically  or send some request

When a request is sent(_thread-B) and a response is sent(_thread-A) simultaneously, **does the socket multi-thread problem occur?**

**Comment by mrdeep1** [comment]
At present, libcoap is not currently multi-thread safe.  There is a reasonable chance that `coap_context_t` or `coap_session_t` could get corrupted when `coap_send()` is done in a different thread to `coap_io_process()`.

Multi-threading libcoap is on the TODO List, but no completion time-scales.

In your scenario, there is no guarantee that Thread-B will get the response to the `coap_send()` in Thread-B, but will get it in Thread-A. 

It Thread-B was to 'post' a message to Thread-A, then Thread-A can safely send it using `coap_send()`.  Thread-A would need to support a response handler as well as support a request handler (with appropriate resource) for when the client is acting as a 'server'.

In terms of socket multi-thread issues - that will be down to the TCP stack you are using - most will be multi-thread safe.

**Comment by JimmyBaize** [comment]
Assuming :
Thread-B put message to mqueue(POSIX).
Thread-A get message from mqueue, and use `coap_send` send message.  

Question：
How does a Thread-A handle both block in `coap_io_process` and receive message from mqueue?

**Comment by mrdeep1** [comment]
Is this for LwIP?

If not, it depends on whether you have EPOLL support or not in the underlying OS.

If no EPOLL support, you can use [coap_io_process_with_fds()](https://libcoap.net/doc/reference/develop/man_coap_io_process_with_fds.html) and then send the message using `pipe()` where the receiving `fd` is added to the `readfds` parameter.

If there is EPOLL support, then you can get the EPOLL fd by using [context_get_coap_fd(3)](https://libcoap.net/doc/reference/develop/man_coap_context_get_coap_fd.html) and again use `pipe()` to do a `select()` against the 2 fds and process accordingly.

**Comment by JimmyBaize** [comment]
LwIP with OS, use POSIX socket , do not use EPOLL.
But as client,just have one connection, one `fd` ,is right?
So Thread-A  handle one `fd` write and read  and get message from mqueue.

**Comment by mrdeep1** [comment]
In principle, there is one `fd `in use.  However, to use LWIP_SOCKET, NO_SYS has to be defined as 1 which then introduces multiple threads into the LwIP stack which I have seen as being problematic when using libcoap.

You can use `mq_notify()` to be told when it is safe to call `mq_receive()`, and I would expect a `select()` waiting on the `fd `to return with EINTR when `mq_notify()` is triggered.

I am looking at how easy it is to make libcoap multithread safe.

**Comment by JimmyBaize** [comment]
Can coap_io_process be divided into coap_in_process and coap_send?
In this way, users can use coap_io_process if they are single-threaded. If there are multiple threads, coap_in_process processes the input (In addition, the received request does not respond directly in the thread, but is placed in a in-box.) The other thread is responsible for writing requests and responses(handle in-box).

**Comment by mrdeep1** [comment]
> Can coap_io_process be divided into coap_in_process and coap_send?

Not easily.

coap_send() takes a PDU and passes it down the stack to a point when it is either has to be delayed (i.e. congestion control is in place), or passes it to the network sending stack.

coap_io_process() checks for any incoming PDUs, and well as transmitting any delayed PDUs and re-transmits PDUs that have not received a response (re-transmit not true for reliable protocols - e.g. TCP).  Additional checks are done for things like unsolicited Observe response needs sending.

Initial work on multithread safe support is looking promising - I may have something in the next few days.
