### ISSUE TITLE
macro HAVE_IFADDRS_H not define in coap_config.h

### ISSUE THREAD

**Issue by deep-eyes** [obgm/libcoap#1297]
In my build system, I have the ifaddrs.h header file, but there is no definition like "#define HAVE_IFADDRS_H 1" in the generated coap_config.h 
Should I add the following statement in cmake_coap_config.h.in: "#cmakedefine HAVE_IFADDRS_H @HAVE_IFADDRS_H@"

**Comment by mrdeep1** [comment]
@deep-eyes Yes, this has been missed out from `cmake_coap_config.h.in`.  Thanks for spending the time finding and reporting it.

I will raise a PR fix for this as there are several other ones missing as well for the cmake environment.

**Comment by mrdeep1** [comment]
Please test #1298 and confirm the issue has been fixed

**Comment by deep-eyes** [comment]
Yes，it fixed，thank you

**Comment by mrdeep1** [comment]
Thanks for coming back - please close this issue as #1298 is now merged into the develop branch.
