### ISSUE TITLE
Support functions for reverse proxy functionality

### ISSUE THREAD

**Issue by anyc** [obgm/libcoap#1313]
I am currently thinking about how I can implement a reverse proxy with libcoap. Similar to what is described in #958, I have a CoAP server with a DTLS socket that can communicate with one or more internal CoAP servers over Unix sockets. These internal servers would run with the minimal required privileges for their specific task. For simple CoAP requests, I think I could (more or less) just copy the request URI and the payload to a new PDU and use the async functions to make a request to the internal server and return the response to the original caller later. However, for block transfers I would have to cache all the data in the entry server and add it as one large payload with coap_add_data() - which might be inefficient.

I saw there are proxy functions but as far as I understand them, they are used for "regular" proxy functionality but in my case the caller should not have to know who really serves the actual data.

Do you think it would be possible/reasonable to create a coap_pdu_copy function that one can use to make a copy of a request  and use the resulting PDU to send it over a different session? Or is there a better solution?

Alternatively (or in addition), I might be helpful if libcoap would offer an interface to send the payload block-wise. This might also be helpful in cases where the sending application itself does not have the payload completely in RAM.

Thank you!

**Comment by mrdeep1** [comment]
I think that you need to de-couple the PDU information between the `World<->Proxy-Server` and `Proxy-Server<->Internal-Server`.

For example. it is possible that the World session is TCP based, but the Internal session is datagram based which have different CoAP PDU types and then things would start to get messy when copying PDS across.  Then data payload lengths could also be different.

Yes, the `examples/coap-server` provides proxy functionality - currently invoked when the World session uses the Proxy-Uri or Proxy-Scheme CoAP options, but there is no reason as to why you can't update handler code to always invoke the ongoing proxy logic to the appropriate Internal server (in other words, do not use `coap_resource_proxy_uri_init2()`, but use `coap_resource_unknown_init2()`).  Then in the handler(s) defined for the `coap_resource_unknown_init2()` resource, just invoke the appropriate proxy style logic which keeps track of the 2 different CoAP sessions.
[These handlers will need to parse the URI to determine which internal server to communicate with, and can use that URI when building up the ongoing PDU].

If you set `COAP_BLOCK_SINGLE_BODY `(and `COAP_BLOCK_USE_LIBCOAP`) in `coap_context_set_block_mode()`, then this will handle the necessary large data block handling for you for both the World and Internal sessions.  Yes, it will be a RAM hit, but it will keep everything simple.  You only need to do this for the reverse proxy server, but would also be nice for the different Internal servers.

It is currently possible for the proxy application layer to send / receive the individual blocks (and was done this way before `coap_context_set_block_mode()` was introduced) and is the default mode in the general `examples/coap-server` for non-proxy sessions.

**Comment by mrdeep1** [comment]
@anyc Do you need any more help here, or can this be closed?

**Comment by anyc** [comment]
I was not able to work again on this yet. I think your explanation will help me with the next steps. Thank you!
