### ISSUE TITLE
Add coap_get_resource_from_uri_path() to man pages.

### ISSUE THREAD

**Issue by WndDezorian** [obgm/libcoap#1383]
This is a very minor nit, but coap_get_resource_from_uri_path() is not documented in the man pages, only in the doxygen modules.  I'm assuming it's still a public API and thus OK for me to write code around, but it may be worth adding this to the man pages so developers are aware of the feature without too much digging, and are confident it's public API and not internal.

**Comment by mrdeep1** [comment]
@WndDezorian Thanks for bring this to our attention.  There are some other undocumented public API functions that are in the doxygen modules, but not in the man pages.  Someone needs to spend time updating the man pages.

As a point of information, if a function does not appear in `libcoap-3.sym` and is not a #define wrapper, then it is not part of the public API.  Alternatively, if the function definition is in one of the `include/coap3/coap_*_internal.h` files, then it is not in the public API.

**Comment by mrdeep1** [comment]
`coap_get_resource_from_uri_path()` is now documented in the develop branch.
