### ISSUE TITLE
HTTP/S Support for Proxy URIs in CoAP to HTTP Proxy

### ISSUE THREAD

**Issue by fj-blanco** [obgm/libcoap#1388]
I've been working with a CoAP to HTTP proxy and encountered an issue starting from release v4.3.2. The proxy logs a "WARN Unsupported URI type 4", and this triggers a "5.05 Proxying Not Supported" error on the client side. This issue appears to be linked to changes made in commit dfaaa47405fccfd73010c2b6a1862e3ae1feef46, specifically within the `coap_split_uri_sub()` function. It seems the `COAP_URI_SCHEME_HTTP` case falls to the default case, returning an error. I found that inserting a break statement after `COAP_URI_SCHEME_HTTP` resolves the issue when working with OpenSSL. Is there a plan to support HTTP/HTTPS in future releases, or should I submit a PR to add this support?

**Comment by mrdeep1** [comment]
This is a bug, providing `coap_split_proxy_uri()` is called, not `coap_split_uri()`.  I will get it fixed shortly.

**Comment by mrdeep1** [comment]
@fj-blanco Please see #1390 for a fix.  Please confirm things work now for you as expected.

**Comment by fj-blanco** [comment]
> @fj-blanco Please see #1390 for a fix. Please confirm things work now for you as expected.

This solves the issue, thank you!

**Comment by mrdeep1** [comment]
Closing - thanks for testing.
