### ISSUE TITLE
Actively denying a new session

### ISSUE THREAD

**Issue by anyc** [obgm/libcoap#1396]
Hello,

I have a requirement that I need to deny access to my CoAP server after several failed logins. On regular server machines, I      usually use fail2ban to simply drop packets of certain IPs. In this case, I need my CoAP server to handle this itself. I tried to call coap_session_disconnected() while handling COAP_EVENT_SERVER_SESSION_NEW but it looks like this will not stop a session. According to the docs,  I could simply return NULL in my validate_id_call_back if the session uses DTLS. However, I think it would be good if I could deny a new session in a generic way while handling COAP_EVENT_SERVER_SESSION_NEW.

I looked at the code and I would like to know if you think it would be a good approach if we use the return value of coap_handle_event() to signal the coap_new_server_session() in coap_session.c that it should go to the error label instead of continuing with establishing the session? Or maybe call l_close() of the sock structure. I will try to figure out the details if you think this could work out in general.

Thank you!

**Comment by anyc** [comment]
From a security point of view I am unsure if it would be better to just ignore further packets in this case or if it is okay to let the client know that he will not get any answers. As far as I understand DTLS 1.2, the server would simply not respond and the client would retry to connect until it gives up. What do you think?

**Comment by mrdeep1** [comment]
`coap_new_server_session()` is for TCP based sessions. For DTLS, this would be using `coap_endpoint_get_session()`  See coap_session.c:1077 as a practical place the ignore a new incoming DTLS session.

My concern about checking the return value from `coap_handle_event()` is current apps may not be rigorous in what they return from the coap_event_handler_t handler.  The libcoap examples return 0, but the return value is not documented.

That said, if your server app logic was to maintain a list of failing IPs and their counts, there is no reason as to when the count hits a threshold an `iptables` cmd line is invoked to drop/reject traffic from the misbehaving IP.  I would also have a timeout bit of logic where the drop/reject IP iptables rule is removed (say after a few hours) as a new, genuine client may be given the IP address of the misbehaving client.

From a security perspective, it is all down to your policy.  Do you want to let the client know the server is still active (but does not like the client) or not.  With iptables, this can be a (silent) drop or reject (TCP RST or ICMP deny).  To aid client troubleshooting, it is better to reject (but interim firewalls may drop the ICMP response).

**Comment by mrdeep1** [comment]
@anyc Do you need any more help here, or can this now be closed?
