### ISSUE TITLE
Build with wolfSSL not loading certificates on server side

### ISSUE THREAD

**Issue by fj-blanco** [obgm/libcoap#1406]
I'm bringing this issue from here https://github.com/obgm/libcoap/issues/1285#issuecomment-2117780825.

> Not sure if I should create a dedicated issue for this.
> 
> The following scenario, with
> 
> ```bash
> coap-server -A ::1 -c server_cert.pem -j server_key.pem
> ```
> on server side, and
> 
> ```bash
> coap-client -m get coaps://[::1]/
> ```
> 
> is not working when the flag `HAVE_RPK` is not set.
> 
> The Client Hello is sent correctly, but this error is being thrown by wolfSSL debugging on server side
> 

> ```console
> Setting WOLFSSL_SSL to be server side
> wolfSSL Entering wolfSSL_DTLS_SetCookieSecret
> wolfSSL Leaving wolfSSL_DTLS_SetCookieSecret, return 0
> Server missing certificate
> wolfSSL error occurred, error = 317 line:9666 file:../src/ssl.c
> ```
> 
> It seems `setup_pki_ssl()` is never called so the certificates are never being set. I'm not sure if the `tls_server_name_call_back()` is expected to be called after receiving the first Client Hello, which should then trigger `setup_pki_ssl()`, but this is not happening. Any idea?

Answering @mrdeep1 reply https://github.com/obgm/libcoap/issues/1285#issuecomment-2118702758

> This works as expected for me with HAVE_RPK both set and not set using the latest master for wolfSSL and develop for libcoap. It may be an issue with your `server_cert.pem` or `server_cert.key` files.
> 
> I assume all works for you if HAVE_RPK is enabled?
> 
> It would be best to raise this as a separate issue detailing both the libcoap and wolfSSL ./configure output and invocation lines along with the cert details if it cannot immediately be resolved.

Yes, everything works for me with `HAVE_RPK`.

Regarding certificates, I have tried several and they work fine with OpenSSL. The problem is that they are not even loaded.

Regarding wolfSSL, I'm using the latest master. May I ask, are you building wofSSL with the `--enable-all`? I think this is defining `HAVE_RPK` by default and that could be why it's working for you.

This is my wolfSSL build

```bash
../configure CFLAGS="-DHAVE_SECRET_CALLBACK" \
    --enable-opensslall \
    --enable-opensslextra \
    --enable-static \
    --enable-psk \
    --enable-alpn \
    --enable-aesccm \
    --enable-aesgcm \
    --enable-dtls-mtu \
    --enable-context-extra-user-data=yes \
    --enable-dtls \
    --enable-debug \
    --enable-dtls13 \
    --enable-tls13 \
    --enable-experimental \
    --enable-dtls-frag-ch
```

**Comment by mrdeep1** [comment]
> May I ask, are you building wofSSL with the --enable-all?

Yes, but had also added in --disable-rpk and confirmed that HAVE_RPK was not set.

However, using your wolfSSL configure options, I am getting a failure.

I note that just adding in --enable-rpk to your ./configure list gives me a libcoap build failure as `wc_PubKeyPemToDer()` is not available.

Now that there is something reproducible, I can check further.

**Comment by mrdeep1** [comment]
Please checkout #1407 for a fix.

**Comment by fj-blanco** [comment]
> Please checkout #1407 for a fix.

It works. Thanks for your time. This has been really helpful.
