### ISSUE TITLE
[Question] Proxy-scheme and proxy-uri example with coap-client and coap-server applications

### ISSUE THREAD

**Issue by fpic78** [obgm/libcoap#1423]
I'm trying to understand how does it work proxy-scheme and proxy-uri using coap-client and coap-server application.  Is it possible?
Is there any example on how to configure them properly and verify that is working fine?
Can you provide command lines to be used for that purpose?
Thanks.

**Comment by mrdeep1** [comment]
> I'm trying to understand how does it work proxy-scheme and proxy-uri using coap-client and coap-server
> application. Is it possible?

Simple answer is Yes.

See [coap-client(5)](https://libcoap.net/doc/reference/develop/man_coap-client.html) and [coap-server(5)](https://libcoap.net/doc/reference/develop/man_coap-server.html) for a full explanation of the options available.  The `-P` option in both cases describes how to use the proxy logic for the specific application. For the coap-client, you will need to use the `-O` option to define a proxy-scheme.  So, for the client, you can use
````
$ examples/coap-client -v7 -O39,coap coap://localhost
   or
$ examples/coap-client -v7 -P coap://upstream-proxy/.well-known/core coap://localhost
````
substituting as appropriate.  For the server, you can do something like
````
$ examples/coap-server -v7 -P,127.0.0.2
````
which routes the proxy request on to the host defined by the client, unless the client specifies the host as 12.7.0.0.2, when the request is not sent on to the requested server, but treated as a local connection.

**Comment by fpic78** [comment]
I used following sequence
(server)           $examples/coap-server -v7
(proxy-server) $examples/coap-server -p 2020 -P,127.0.0.1:5683 -v9
(client)            $examples/coap-client -v7 -P coap://127.0.0.1:2020 coap://localhost:5683/.well-known/core

and I can see that request is forwarded to server from proxy and return back to client.

In any case libcoap server and client do support only CoAP protocol. 
Proxy server should be always able to understand CoAP protocol and eventually transform these request into HTTP format.
Is this right?

Thanks

**Comment by mrdeep1** [comment]
A proxy server can map between CoAP and HTTP as per RFC 7252.

This support has not been added into the examples coap-server, but can be added if someone wants to work on the code.

**Comment by fpic78** [comment]
Ok. Thanks for your support.
