### ISSUE TITLE
Issues building on Windows

### ISSUE THREAD

**Issue by williamd** [obgm/libcoap#144]
Hi all,

Quick background: I'm creating an app that communicates with IKEA Trådfri devices. To build binaries for Mac and Linux was a no-brainer - many thanks for all your hard work! I'm also trying to build the win32 VS2015 Solution from develop branch but ran into some issues. As I've been a Mac/Linux guy for the last 15+ years my Windows knowledge is severely lacking. 

- Running Win7 and Win10 VMs in VirtualBox on Mac 10.13.13
- Using VS2015 Community
- Tried with OpenSSL 0.9.8, 1.0.1e, 1.0.2c, 1.0.2n, 1.1.0c, 1.1.0g (I know 1.1 is required, but I had to try)

I read on the [mailinglist](https://sourceforge.net/p/libcoap/mailman/libcoap-developers/?page=2) that it should suffice to copy the DLL and include files into win32/lib and win32/include dirs. I do however wind up with build errors. libcoap itself builds without warnings (e.g. Release x86) but coap-client fails with ~80 Errors, all of them unresolved external symbols (LNK2001) and the referenced file is libcoap.lib (coap_openssl.obj).

I also tried to update the paths in project properties, but that didn't help either.

On Win10 I built OpenSSL with the help of [this gist](https://gist.github.com/terrillmoore/995421ea6171a9aa50552f6aa4be0998). I also tried using OpenSSL from [this place](https://slproweb.com/products/Win32OpenSSL.html) to no avail.

After a long, long night of fiddling, I actually managed to build a .exe on Win10. The binary is only ~89KB and fails to use commands I've tried (related to Trådfri that is).

I'd appreciate some pointers as I'm sure I'm missing something fundamental. 

Thanks,
William Dahlheim

**Comment by jcmichelou** [comment]
On windows you must bear in mind that the linker uses the import lib while the executable uses the dll (which have to be in either your path or next to the exe). Which files did you copy in win32/lib ? Did you try the DLL build confugurations ?

**Comment by gnbl** [comment]
I just managed to build it with VS2017 community and the libraries from a prebuilt OpenSSL 1.1.1.
There are probably ways to point to the libraries correctly but I could not get the Project settings right - the linker error went away when copying `libssl.lib` and `libcrypto.lib` into the build directory `libcoap-develop\win32\out\lib`.
To run it, `libssl-1_1.dll` and `libcrypto-1_1.dll` are needed in `libcoap-develop\win32\Release`.
If you run it but get no console output whatsoever, it might be that you have a console emulation that does not produce Windows errors - use CMD.exe directly.
One last hint: the quote behaviour on CMD is different than the many linux examples found online - ensure that arguments are contained in `"` (double quotes) and use `'` (single quotes) as inner string delimiter. 
To debug that, you could add the following to examples\client.c at the beginning of main():
```
  for (int n = 0; n < argc; n++) {
	  printf("%02d %s\n", n, argv[n]);
  }
```

With all that out of the way, I'm now getting `4.00` and `4.01` result codes or "WARN PSK identity not defined" and "EMRG cannot create client session" but these are a different matter...

**Comment by mrdeep1** [comment]
It is good that things are starting to work.  When using the coap-client, you need to use the -u option as in "-u myidentity" to provide the identity to the libcoap PSK subsystem. That should then fix the WARN and EMRG messages you were seeing.

**Comment by gnbl** [comment]
Sorry, the messages (I've just removed from my previous post) were due to incorrect identity. With proper escaping, I was able to obtain a key from the gateway and it's now working. Currently looking into setting colors for a "TRADFRI bulb E27 CWS opal 600lm".

**Comment by jcmichelou** [comment]
The path to your installation of OpenSSL is configurable in the “property sheet” tab of visual studio for the libcoap project. Select the properties for libcoap and edit the path in “user macros”.
