### ISSUE TITLE
coap_new_context fails with "coap_init: no DTLS context available" error

### ISSUE THREAD

**Issue by rakeshksahu** [obgm/libcoap#1475]
Hello there,
My project demands that coap server to be started/stopped several times.
However when I stop the server and start again, coap_new_context fails with below error:

`Jul 17 06:31:41.799 EMRG coap_init: no DTLS context available
Jul 17 06:31:41.799 EMRG cannot initialize context`

To investigate this further I tried to recreate the issue by adding coap_new_context(nullptr) call at coap-minimal example repo in server.cc (https://github.com/obgm/libcoap-minimal/blob/main/server.cc#L121) after the cleanup part.
And I was able to reproduce the same.

Please help me to get post this issue related to coap_context.
I have compiled libcoap with openssl and working with commit id 9f9129cca83fd57db618c767b8ddc1ba26660e33 of libcoap.

**Comment by mrdeep1** [comment]
Thanks for raising this and the addition of subsequent information as to what TLS library you are using, as well as the libcoap version.  It would help in the future if you fill out the Issue template with the appropriate information.

With OpenSSL, are you are calling `coap_free_context()`, `coap_cleanup(),` `coap_startup()` and then `coap_new_context()`.  Is that correct?

**Comment by mrdeep1** [comment]
@rakeshksahu This should be fixed for you in #1476.  Please confirm this.

**Comment by rakeshksahu** [comment]
Hello @mrdeep1, the order is correct. Also I see with #1476, it works fine. thanks!

**Comment by mrdeep1** [comment]
Thanks for the feedback on testing.  Closing this now.
