### ISSUE TITLE
No release Tag with recent API

### ISSUE THREAD

**Issue by baw-serafin** [obgm/libcoap#148]
Is there a reason that there is no recent release?

` git diff --stat v4.1.2 ` results in `102 files changed, 13137 insertions(+), 3966 deletions(-)`

If I compare the server example in developp and v4.1.2 the new API seems much more sane and user-friendly but my product manager refuses to use a develop version. Is there a timeline for a new release?

**Comment by obgm** [comment]
See issue #145 (this is discussed on the mailing list...)

Your product manager is correct in refusing the development version as it is in development. In particular, the API is not stable (although we are currently getting there), and the next TCP interop test is about to happen soon.

However, it looks as if there will be a new release soon with a big lot of improvements over 4.1.2, especially (D)TLS support.
