### ISSUE TITLE
How to build coap on uc/OS?

### ISSUE THREAD

**Issue by xuanqingyi** [obgm/libcoap#149]
Thank you for reading this issue. I try to build uCOS on STM32. And try to built coap on ucos, but  I want to know if  it can be successful. If it can what should I do? Thank you.

**Comment by obgm** [comment]
I do not know anything about μC/OS but I presume that porting libcoap will be very difficult. You will most likely have to replace the network I/O functionality, socket handling, timers, etc. Please refer to the Contiki- or LWIP-specific parts of the code to see what will be necessary.

In general, you might consider switching to an open-source operating system as the community support will be much better.

**Comment by xuanqingyi** [comment]
Thank you for your patience. I thought about what I thought before and found it ridiculous. Now I want to develop COAP on uCOS for the two time. So we need to speed up your understanding of your source code, can you provide your flow chart? Or is it a function dependency that lets me understand the data of your code faster?
