### ISSUE TITLE
coap add resource in example

### ISSUE THREAD

**Issue by anupam19** [obgm/libcoap#15]
Hi, is there any way to create resource or any example is given in sample client server application ?

**Comment by obgm** [comment]
Yes, resource creation is illustrated in the function init_resources() in examples/coap-server.c.

**Comment by krajco** [comment]
Hello, how it is possible make new resources on server, I mean create request to create new resources, always I get reposned Not Allowed method.

**Comment by obgm** [comment]
There is example code in `examples/coap-server.c` (Try out with `coap-server -d 10`). Basically, you need to register a handler for requests to unknown resources using [coap_resource_unknown_init()](https://libcoap.net/doc/reference/4.2.0/man_coap_resource.html).

**Comment by krajco** [comment]
Hello,

thank you, I will try it, stay awesome!

Cituji obgm <notifications@github.com>:
