### ISSUE TITLE
Fail to bind to coap_address_t address

### ISSUE THREAD

**Issue by ea2973929** [obgm/libcoap#150]
Found on Mac OS X (10.13.2)

Faulty line:
https://github.com/obgm/libcoap/blob/d02ab4d0ab2c5543cd8184082f3adac1df4a4415/src/coap_io.c#L232

The member `addr.sa` is of type `sockaddr` which is 16 bytes. However `listen_addr->size` is 28. Bind fails with "Invalid argument".

The `listen_addr` is initialised using `coap_address_init()` which will fill in `addr->size = sizeof(addr->addr);` which is a union with `sockaddr_in6` being the largest struct at 28 bytes.
 
~~Fix would be to `bind(sock->fd, &listen_addr->addr.sa, sizeof(sockaddr))`.~~

**Comment by mrdeep1** [comment]
A better fix would be to do different bind() and possibly getsockname() under the AF_INET and AF_INET6 case options.

**Comment by ea2973929** [comment]
Ah, I guess my proposed fix would only work in the case of an IPV4 address? Otherwise the struct should indeed be the size of a sockaddr_in6.

**Comment by mrdeep1** [comment]
Correct.

**Comment by mrdeep1** [comment]
@ea2973929 Did you manage to get this to work - and what was the final solution?

It just is that EINVAL ("Invalid Argument") for MAC OS X (additional info for AF_UNIX, not relevant here) only states (Linux does have additional descriptions, but this code works on Linux systems)
"[EINVAL]  socket is already bound to an address and the protocol does not support binding to a new address.  Alternatively, socket may have been shut down."

[I do not have a Mac OS X to work on to test any fixes]

My thoughts would be
````
diff --git a/src/coap_io.c b/src/coap_io.c
index 91fcbb6..f356708 100644
--- a/src/coap_io.c
+++ b/src/coap_io.c
@@ -223,6 +223,11 @@ coap_socket_bind_udp(coap_socket_t *sock,
       coap_log(LOG_ALERT,
                "coap_socket_bind_udp: setsockopt IP_PKTINFO: %s\n",
                 coap_socket_strerror());
+    if (bind(sock->fd, &listen_addr->addr.sa, sizeof(struct sockaddr_in)) == COAP_SOCKET_ERROR) {
+      coap_log(LOG_WARNING, "coap_socket_bind_udp: bind 4: %s\n",
+               coap_socket_strerror());
+      goto error;
+    }
     break;
   case AF_INET6:
     /* Configure the socket as dual-stacked */
@@ -235,16 +240,16 @@ coap_socket_bind_udp(coap_socket_t *sock,
                "coap_socket_bind_udp: setsockopt IPV6_PKTINFO: %s\n",
                 coap_socket_strerror());
     setsockopt(sock->fd, IPPROTO_IP, GEN_IP_PKTINFO, OPTVAL_T(&on), sizeof(on)); /* ignore error, because the likely cause is that IPv4 is disabled at the os level */
+    if (bind(sock->fd, &listen_addr->addr.sa, sizeof(struct sockaddr_in6)) == COAP_SOCKET_ERROR) {
+      coap_log(LOG_WARNING, "coap_socket_bind_udp: bind 6: %s\n",
+               coap_socket_strerror());
+      goto error;
+    }
     break;
   default:
     coap_log(LOG_ALERT, "coap_socket_bind_udp: unsupported sa_family\n");
-    break;
-  }
-
-  if (bind(sock->fd, &listen_addr->addr.sa, listen_addr->size) == COAP_SOCKET_ERROR) {
-    coap_log(LOG_WARNING, "coap_socket_bind_udp: bind: %s\n",
-             coap_socket_strerror());
     goto error;
+    break;
   }
 
   bound_addr->size = (socklen_t)sizeof(*bound_addr);
````

**Comment by matisszilard** [comment]
Hello,

A workaround can be to set the address size after `coap_address_init` like it was suggested above.

I assume that the tcp bind is affected as well.

Is it planned to include this patch int the lib?

**Comment by mrdeep1** [comment]
Apologies - I had done the original work but wanted confirmation that the issue was actually fixed before pushing any code as a PR.
Code changes (slightly different as in this ticket) has just been pushed as PR #396 .

**Comment by obgm** [comment]
The problem here is that apparently `listen_addr->size` is not set correctly when `listen_addr->addr.sa` was initialized. `coap_address_init()` obviously cannot guess the correct value and therefore initializes size to some reasonable value. The fix proposed in PR #396 will not work as soon as anything other than AF_INET or AF_INET6 was used.

**Comment by mrdeep1** [comment]
Fair comment.  Should we then just test for `AF_INET` and make that `sizeof(struct sockaddr_in)`, otherwise leave it as -`>size` in #396 to keep the MACs happy?

**Comment by obgm** [comment]
Sounds reasonable.

**Comment by mrdeep1** [comment]
@matisszilard @ea2973929 Now that #396 has been merged into develop, does this fix your issue with bind() on MAC OS?

**Comment by matisszilard** [comment]
@mrdeep1 Yes. The solution works for me.
