### ISSUE TITLE
How Do I Use the libcoap Component to Receive and Send Coap Packets in the Same Function?

### ISSUE THREAD

**Issue by shenhaicheng** [obgm/libcoap#1523]
**Is your feature request related to a problem? Please describe.**

Currently, an api needs to be provided. I need to send CoAP packets in the api and set the response to the output parameter.

**Describe the solution you would like**

A function that can process responses synchronously is required. Is this function supported in the current version? Thank you so much for supporting!

**Comment by mrdeep1** [comment]
I'm trying to understand what you are looking for here.  Are you looking for something like
````
/*
 * Send a request PDU and wait for the response PDU.
 * 
 * @param request_pdu The requesting PDU. This PDU cannot contain the Observe CoAP option. 
 * @param response_pdu If there is a response, the response PDU is put here.
 *                      This PDU must be freed off by the caller after processing.
 *
 * @return @c 1 if success, else @c 0 on failure (response_pdu set to NULL). request_pdu is always freed off.
 */
int coap_send_recv(coap_pdu_t* request_pdu, coap_pdu_t** response_pdu);
````

**Comment by shenhaicheng** [comment]
> I'm trying to understand what you are looking for here. Are you looking for something like
> 
> ```
> /*
>  * Send a request PDU and wait for the response PDU.
>  * 
>  * @param request_pdu The requesting PDU. This PDU cannot contain the Observe CoAP option. 
>  * @param response_pdu If there is a response, the response PDU is put here.
>  *                      This PDU must be freed off by the caller after processing.
>  *
>  * @return @c 1 if success, else @c 0 on failure (response_pdu set to NULL). request_pdu is always freed off.
>  */
> int coap_send_recv(coap_pdu_t* request_pdu, coap_pdu_t** response_pdu);
> ```

Yes, I'm really looking for this，but I can‘t find this interface. T.T

**Comment by mrdeep1** [comment]
> Yes, I'm really looking for thisbut I can‘t find this interface. T.T

This interface does not exist - someone needs to write it - I don't have spare time at present.

**Comment by mrdeep1** [comment]
@shenhaicheng Appreciate that time has passed, but please try out #1538 where there is now support for `coap_send_recv()`.

**Comment by mrdeep1** [comment]
Closing as `coap_send_recv()` is now in the develop branch.
