### ISSUE TITLE
add subrepo contents while creating release archive

### ISSUE THREAD

**Issue by rakeshksahu** [obgm/libcoap#1528]
**autoconf step fails if tinydtls contents are not present in libcoap subrepo.**

I am using bitbake recipe for libcoap, which I followed from build instructions provided in the repo.
However build does not pass because autoconf gets failed.

The same recipe works when I provide libcoap commit id with subrepo details of tinydtls.

**please add subrepo contents while archiving the release version.**

attaching the error logs.

**Below are bitbake recipe with release  zip file.**
[Uploading bitbake.log…]()

LIC_FILES_CHKSUM = "file://LICENSE;md5=9aa68c0f6785376aa8ec7f4f1aa6ae3c"
SRC_URI = "https://github.com/obgm/libcoap/archive/refs/tags/v4.3.5.zip"
SRC_URI[sha256sum] = "adf8ee10d6d3f21a1e80c8d34afac5edf789d0721c81bda09c2cd12e8996b912"

**Below are bitbake recipe with commit id.**
LIC_FILES_CHKSUM = "file://LICENSE;md5=9aa68c0f6785376aa8ec7f4f1aa6ae3c"

SRC_URI = "git://github.com/obgm/libcoap.git;branch=develop;protocol=https \
           git://github.com/eclipse/tinydtls.git;branch=develop;protocol=https;destsuffix=git/ext/tinydtls;name=tinydtls \
"

SRC_URI = "https://github.com/obgm/libcoap/archive/refs/tags/v4.3.5.zip"

SRC_URI[sha256sum] = "adf8ee10d6d3f21a1e80c8d34afac5edf789d0721c81bda09c2cd12e8996b912"

SRCREV_FORMAT_tinydtls = "git"
SRCREV_FORMAT = "${SRCREV_FORMAT_tinydtls}"

SRCREV = "7cf7465b784baded4de183290c547d582becfd28"
SRCREV_tinydtls = "4a6a78236043da7f8af9ad7be8488aeed6884eda"

**Comment by rakeshksahu** [comment]
[bitbake.log](https://github.com/user-attachments/files/17259172/bitbake.log)

**Comment by mrdeep1** [comment]
As TinyDTLS has a different Licence, I am not sure that we can ship this bundled into the libcoap .zip file.

At least, things work when using git.

Have you looked at doing a second recipe?

**Comment by rakeshksahu** [comment]
I am not sure if I understood your question.

**Comment by mrdeep1** [comment]
I am not that familiar with bitbake, but I was thinking of something like https://a4z.gitlab.io/docs/BitBake/guide.html#_use_myclass_with_the_second_recipe as a possibility.

**Comment by rakeshksahu** [comment]
sure, i will try this.
