### ISSUE TITLE
Building of PDUs requires a lot of libcoap knowledge / duplicating what is in example/client.c

### ISSUE THREAD

**Issue by mrdeep1** [obgm/libcoap#154]
For example, adding in Options to the PDU requires them to be added in in the correct order, so examples/client.c has provided a mechanism to do this using coap_list_t which is not a part of libcoap.
Then there are macros such as LL_FOREACH which really are macros for internal use.

I think a cleaner, easier to document, way forward here would be to

Make coap_list_t a part of the libcoap (examples/coap_list.[ch]) with external functions being
coap_insert_list() and coap_delete_list().

Create a new coap_new_option_list() and coap_add_options_list()

Resultant simplified example code is at the end of this information.

Example  code currently needed to be used to set up the PDU
===========================================

typedef struct coap_list_t {
  struct coap_list_t *next;
  char data[];
} coap_list_t;

static int coap_insert(coap_list_t **head, coap_list_t *node) {
  if (!node) {
    coap_log(LOG_WARNING, "node not specified\n");
  } else {
    /* must append at the list end to avoid re-ordering of
     * options during sort */
    LL_APPEND((*head), node);
  }
 
  return node != NULL;
}

static coap_list_t * new_option_node(uint16_t key, size_t length,
unsigned char *data) {
  coap_list_t *node;

  node = coap_malloc(sizeof(coap_list_t) + sizeof(coap_option) + length);

  if (node) {
    coap_option *option;
    option = (coap_option *)(node->data);
    COAP_OPTION_KEY(*option) = key;
    COAP_OPTION_LENGTH(*option) = length;
    memcpy(COAP_OPTION_DATA(*option), data, length);
  } else {
    coap_log(LOG_DEBUG, "new_option_node: malloc\n");
  }

  return node;
}

static int order_opts(void *a, void *b) {
  coap_option *o1, *o2;

  if (!a || !b)
    return a < b ? -1 : 1;

  o1 = (coap_option *)(((coap_list_t *)a)->data);
  o2 = (coap_option *)(((coap_list_t *)b)->data);

  return (COAP_OPTION_KEY(*o1) < COAP_OPTION_KEY(*o2))
    ? -1
    : (COAP_OPTION_KEY(*o1) != COAP_OPTION_KEY(*o2));
}

static coap_pdu_t *
coap_new_request(coap_context_t *ctx, coap_session_t *session, char m,
coap_list_t **options, unsigned char *data, size_t length, int observe) {
  static unsigned int token = 0;
  coap_pdu_t *pdu;
  coap_list_t *opt;
  (void)ctx;

  if (!(pdu = coap_new_pdu(session)))
    return NULL;

  pdu->type = msgtype;
  pdu->tid = coap_new_message_id(session);
  pdu->code = m;

  /* Create uniqueness for this request */
  token++;
  if (!coap_add_token(pdu, sizeof(token), (unsigned char*)&token)) {
    coap_log(LOG_DEBUG, "cannot add token to request\n");
  }

  if (m == COAP_REQUEST_GET && observe) {
    /* Indicate that we want to observe this resource */
    coap_insert(options, new_option_node(COAP_OPTION_OBSERVE, 0, NULL));
  }

  if (options) {
    /* sort options for delta encoding */
    LL_SORT((*options), order_opts);

    LL_FOREACH((*options), opt) {
      coap_option *o = (coap_option *)(opt->data);
      coap_add_option(pdu,
                      COAP_OPTION_KEY(*o),
                      COAP_OPTION_LENGTH(*o),
                      COAP_OPTION_DATA(*o));
    }
  }

  if (length) {
    coap_add_data(pdu, length, data);
  }

  return pdu;
}

Example code needed to be used to set up the PDU after changes
===========================================

static coap_pdu_t *
coap_new_request(coap_context_t *ctx, coap_session_t *session, char m,
coap_list_t **options, unsigned char *data, size_t length, int observe) {
  static unsigned int token = 0;
  coap_pdu_t *pdu;
  coap_list_t *opt;
  (void)ctx;

  if (!(pdu = coap_new_pdu(session)))
    return NULL;

  pdu->type = msgtype;
  pdu->tid = coap_new_message_id(session);
  pdu->code = m;

  /* Create uniqueness for this request */
  token++;
  if (!coap_add_token(pdu, sizeof(token), (unsigned char*)&token)) {
    coap_log(LOG_DEBUG, "cannot add token to request\n");
  }

  if (m == COAP_REQUEST_GET && observe) {
    /* Indicate that we want to observe this resource */
    coap_insert_list(options, new_option_node(COAP_OPTION_OBSERVE, 0, NULL));
  }

  if (options) {
    coap_add_options_list(pdu, options);
  }

  if (length) {
    coap_add_data(pdu, length, data);
  }

  return pdu;
}

**Comment by obgm** [comment]
I agree with most of your reasoning and the proposed changes as they significantly simplify working with libcoap.

**Comment by mrdeep1** [comment]
I will work on this and create the PR then when I get a chance

**Comment by mrdeep1** [comment]
Thinking about this further, there can be an even further implementation and remove the need to understand the order in which a PDU needs to get built.  The PDU is of the form

<---header--->|<---optional token---><---optional options--->0xff<---optional payload--->

and in the current code the token has to be added before the sorted options are added which has to be done before the payload is added.  The real challenge with the current code is that the options have to be added in the correct sorted order as each option contains not the option code, but a value for the option code that is the difference between the current and previous option codes.

If coap_add_option() is enhanced to work out the correct place in the PDU, move any data to the right of the place up by the appropriate amount, inset the new option information and then update the next option type offset as appropriate.  This then removes any requirement to know about option orders.

This could also be done for coap_add_token() which could then be done after options/data has been added.

Thoughts?

**Comment by baw-serafin** [comment]
@mrdeep1 Having to add the option is the correct order will inevitably lead to errors. I think other libs solve this by having the options in a separate list sort it and only after that serialize it and add it to pdu / assemble pdu

**Comment by mrdeep1** [comment]
My first cut of the code change was to pull the opt_list, sorting etc. out of examples/client.c and put them into the src/options.c to make them generally available.

The examples/coap-server.c code assumes you know the correct order to add in Options into the response packet, not making any use of building an opt_list and then inserting them in the correct order.

I then realized that it would not be difficult to enhance the building of the PDU code to support a random insertion of tokens, options / data into the PDU and the underlying logic put things into the correct order (and offsets etc.) in the PDU as per RFC7252.  I am not sure what errors this would lead to if it was assumed the PDU (although it currently is not) was opaque to the user application and people continued to use the current exposed functions.

Doing this smart insertions then leads to the possibility of things like libcoap adding in the Observe Option before the response packet is passed to the user handler for updating.

**Comment by mrdeep1** [comment]
PR #162 only makes use of the new optlist functions.  The enhancement for the insertion of tokens, options and data in random order has not been included in this PR.

**Comment by mrdeep1** [comment]
PR #162 now merged
