### ISSUE TITLE
Can libcoap4.3.5 support send broadcasts as a client?

### ISSUE THREAD

**Issue by Tkzccsk** [obgm/libcoap#1547]

**Comment by mrdeep1** [comment]
Yes, for posix networking, treated as a multicast packet, but only supported for IPv4 as there is no notion of broadcast for IPv6.

The server also needs to understand broadcast packets and treat them as multicast (I.e needs to delay response).

**Comment by Tkzccsk** [comment]
Thank you for answering. I'll describe the problem I'm having. I'm using lwip 2.1.2, libcoap 4.3.5, my local IP address is 192.168. 11.8, and I'm sending a broadcast to 192.168. 11.255. After packet capture and log analysis, the packet has been sent to the peer and the peer responds to the packet, but the local lwip intercepts the packet(**udp_input: not for us.**): the peer IP address does not match the IP address recorded in the local pcb. As a result, no proper PCB is found. The log is as follows:

> ip_input: iphdr->dest 0x80ba8c0 netif->ip_addr 0x80ba8c0 (0xba8c0, 0xba8c0, 0x8000000)
ip4_input: packet accepted on interface en
ip4_input: 
IP header:
+-------------------------------+
| 4 | 5 |  0x00 |        89     | (v, hl, tos, len)
+-------------------------------+
|    48202      |010|       0   | (id, flags, offset)
+-------------------------------+
|   64  |   17  |    0xe6ef     | (ttl, proto, chksum)
+-------------------------------+
|  192  |  168  |   11  |    1  | (src)
+-------------------------------+
|  192  |  168  |   11  |    8  | (dest)
+-------------------------------+
ip4_input: p->len 89 p->tot_len 89
pbuf_remove_header: old 0x344a6f58 new 0x344a6f6c (20)
udp_input: received datagram of length 69
UDP header:
+-------------------------------+
|      5683     |     50628     | (src port, dest port)
+-------------------------------+
|        69     |     0xf392    | (len, chksum)
+-------------------------------+
udp (192.168.11.8, 50628) <-- (192.168.11.1, 5683)
pcb (0.0.0.0, 50628) <-- (192.168.11.255, 5683)
pcb (0.0.0.0, 68) <-- (0.0.0.0, 67)
pcb (0.0.0.0, 16114) <-- (0.0.0.0, 0)
pcb (0.0.0.0, 5683) <-- (0.0.0.0, 0)
udp_input: calculating checksum
inet_chksum_pseudo(): checksumming pbuf 0x344a6f38 (has next 0x0) 
inet_chksum_pseudo(): pbuf chain lwip_chksum()=ffff
pbuf_remove_header: old 0x344a6f6c new 0x344a6f74 (8)
udp_input: not for us.

How can I solve this?

Also, why does this interface not use the local_if input?

`
coap_socket_connect_udp(coap_socket_t *sock,
                        const coap_address_t *local_if,
                        const coap_address_t *server,
                        int default_port,
                        coap_address_t *local_addr,
                        coap_address_t *remote_addr) {
  err_t err;
  struct udp_pcb *pcb;

  (void)local_if;
  (void)default_port;
  (void)local_addr;
  (void)remote_addr;
`

**Comment by mrdeep1** [comment]
Please see a fix in #1548 which supports multicast / broadcast for LwIP clients.

> Also, why does this interface not use the local_if input?

Good question.  I did not do the original LwIP implementation so don't know the history.  That said (but no testing done), there is no reason that I can think of why, if `local_if `is set, it cannot be used to pre-populate `pcb->local_ip` and `pcb->local_port` for the `udp_bind()` call.

**Comment by Tkzccsk** [comment]
> Please see a fix in #1548 which supports multicast / broadcast for LwIP clients.
> 
> > Also, why does this interface not use the local_if input?
> 
> Good question. I did not do the original LwIP implementation so don't know the history. That said (but no testing done), there is no reason that I can think of why, if `local_if `is set, it cannot be used to pre-populate `pcb->local_ip` and `pcb->local_port` for the `udp_bind()` call.

The response was fast and great, thank you very much. I can give it a try

**Comment by mrdeep1** [comment]
Updated with code using `local_if`  (if defined) just pushed to #1548.

**Comment by Tkzccsk** [comment]
Now I have a new problem. After sending multicast packets (192.168.10.2 to 192.168.10.255), the peer (192.168. 10.1, but I don't know that) responds, and then I need to send a unicast to the peer (192.168. 10.1). The problem is that I do not know the IP address of the peer. In the callback response, the IP address of the peer is the parameter `addr`, but it is not used or processed in the interface implementation. I think a new member variable `remote_info_from_package` can be added to `coap_session_t` struct to store the actual IP address of the response packet.

>static void
coap_recvc(void *arg, struct udp_pcb *upcb, struct pbuf *p,
           const ip_addr_t *addr, u16_t port) {
  coap_pdu_t *pdu = NULL;
  coap_session_t *session = (coap_session_t *)arg;
  int result = -1;
  (void)upcb;
  (void)addr;
  (void)port;

**Comment by mrdeep1** [comment]
#1548 updated to include a fix for this.  You can then get the sending peer's IP address out of the session using `coap_session_get_addr_remote()`.

**Comment by Tkzccsk** [comment]
After receiving the multicast response, `coap_session_get_addr_remote()` returns 192.168.10.255, not 192.168.10.1, because remote is assigned before sending, in two places:
1、coap_io_lwip.c/coap_socket_connect_udp

```c
 if (remote_addr) {
    coap_address_copy(remote_addr, &connect_addr);
  }
```
2、coap_session.c/coap_make_session：
  ```c
if (remote_addr)
    coap_address_copy(&session->addr_info.remote, remote_addr);
```

I want to get the IP address that actually returns the multicast response

**Comment by mrdeep1** [comment]
When you are 'connecting' the UDP session, the remote address will be your broadcast address.

Once you receive a response (handled by` coap_recvc()`), in the application handler you have defined (with `coap_register_response_handler()`), you will be able to get the responding peer's IP address using `coap_session_get_addr_remote()`.  The broadcast address gets updated to the IP address when there is a response.

**Comment by mrdeep1** [comment]
I'm assuming that you have the latest changes to #1548.

**Comment by Tkzccsk** [comment]
Sorry, I didn't see the latest changes. After I adapted the latest modification, it worked perfectly, thank you
