### ISSUE TITLE
Assertion ref > 0 fails for incomplete TLS handshake

### ISSUE THREAD

**Issue by obgm** [obgm/libcoap#155]
It seems that a `coap_session_release()` in `coap_session_accept()` is called with new session objects that have not yet set their ref counter to 1 (i.e. 
This can happen when `coap_tls_server_session()` fails (most due to `SSL_accept()` failing). This function is called from `coap_new_server_session()` in `coap_accept_endpoint()`. The first call to `coap_session_reference()` on a new session occurs in `coap_read()` after `coap_accept_endpoint()`.

Maybe it is safe to just remove the assertion in `coap_session_release()`?

Corresponding server debug output:

```
DEBG *** [server]:5684 <-> [client]:25008 TLS: new incoming session
DEBG SSL_accept:before SSL initialization
WARN SSL_accept:error in before SSL initialization
WARN   wrong version number at SSL routines:ssl3_get_record
coap-server: src/coap_session.c:78: coap_session_release: Assertion `session->ref > 0' failed.
```

**Comment by mrdeep1** [comment]
I think your real issue is in the change 46c908af8f6ee9c3a7180972783048e684985f06 and the below part should be reverted.

@@ -524,7 +524,7 @@ coap_session_accept(coap_session_t *session) {
         coap_session_send_csm(session);
       }
     } else {
-      coap_session_free(session);
+      coap_session_release(session);
       session = NULL;
     }
   }

**Comment by obgm** [comment]
This would fix this issue but is this the right thing to do?
The problem I see with this is that if in future somehow somewhere this session is actually referenced the `coap_session_free()`  would break the referencing.

**Comment by mrdeep1** [comment]
Perhaps there should be a call to coap_session_reference() just before the coap_session_release(session)

... and coap_session_connect() change may need to be reverted / updated  as well

@@ -499,7 +499,7 @@ coap_session_connect(coap_session_t *session) {
           coap_session_send_csm(session);
         }
       } else {
-       coap_session_free(session);
+       coap_session_release(session);
        return NULL;
       }
     } else {

**Comment by obgm** [comment]
Ok, I will change this as suggested. Looks a bit weird now...
