### ISSUE TITLE
coap-client sends corrupted packets when extended tokens are used

### ISSUE THREAD

**Issue by maribu** [obgm/libcoap#1552]
## Environment

- Build System:             GNU Make 4.3
- Operating System:         Ubuntu 24.04.1
- Operating System Version: 24.04.1
- Hosted Environment:       None

## libcoap Configuration Summary

```
./get_config.sh 
Last ./configure build

libcoap package version        : "4.3.5"
libcoap package source         : "v4.3.5-24-gd82f857f"
libcoap API version            : "3"
libcoap ABI version            : "3.2.0"
libcoap libtool SO version     : "5.0.2"
libcoap DTLS lib extn          : "-openssl"
host system                    : "x86_64-pc-linux-gnu"
build with server support      : "yes"
build with client support      : "yes"
build with proxy support       : "yes"
build with IPv4 support        : "yes"
build with IPv6 support        : "yes"
build with Unix socket support : "yes"
build with TCP support         : "yes"
build DTLS support             : "yes"
   -->  OpenSSL around         : "yes" (found OpenSSL 3.0.13)
        OpenSSL_CFLAGS         : ""
        OpenSSL_LIBS           : "-lssl -lcrypto "
add default names              : "yes"
build Observe Persist          : "yes"
build using epoll              : "yes"
enable small stack size        : "no"
enable separate responses      : "yes"
enable OSCORE support          : "yes"
enable Q-Block support         : "yes"
enable max logging level       : "none"
enable thread safe code        : "yes"
enable recursive lock check    : "yes"
build doxygen pages            : "yes"
    --> Doxygen around         : "yes" (/usr/bin/doxygen 1.9.8)
       -->  dot around         : "yes" (/usr/bin/dot 2.43.0)
build man pages                : "yes"
build unit test binary         : "no"
build examples                 : "yes"
install examples source        : "yes"
build with gcov support        : "no"
build shared library           : "yes"
build static library           : "yes"
```

```
git describe --tags --dirty --always
v4.3.5-24-gd82f857f
```

## Problem Description

```
$ examples/coap-client -a 'fe80::183:ade0:3cd0:d5b%enp1s0f0' -m get 'coap://[fe80::fec2:3dff:fe0b:cf49]/riot/board' -T deadbeefdeadbeef
Dec 11 18:19:11.410 WARN discard malformed PDU
Dec 11 18:19:11.410 WARN coap_send: PDU dropped as token too long (16 > 8)
```

Captured network traffic:

```
----
Frame 1: 84 bytes on wire (672 bits), 84 bytes captured (672 bits) on interface enp1s0f0, id 0
Ethernet II, Src: c4:c6:e6:46:dc:89 (c4:c6:e6:46:dc:89), Dst: Atmel_0b:cf:49 (fc:c2:3d:0b:cf:49)
Internet Protocol Version 6, Src: fe80::183:ade0:3cd0:d5b, Dst: fe80::fec2:3dff:fe0b:cf49
User Datagram Protocol, Src Port: 5683, Dst Port: 5683
Constrained Application Protocol, Confirmable, GET, MID:45889
    01.. .... = Version: 1
    ..00 .... = Type: Confirmable (0)
    .... 1101 = Token Length: 13
    Code: GET (1)
    Message ID: 45889
    Token: 030102030405060708090a0b0c
    [Expert Info (Warning/Malformed): option longer than the package]
        [option longer than the package]
        [Severity level: Warning]
        [Group: Malformed]
```

With the hex dump of the CoAP packet:
```
0000   4d 01 b3 41 03 01 02 03 04 05 06 07 08 09 0a 0b   M..A............
0010   0c 0d 0e 0f 10 50                                 .....P
```

### Expected Behavior

The send CoAP packet contains the specified Token and URI-Path

### Actual Behavior

A corrupted packet is send

### Steps to reproduce

Run `coap-client` and provide a Token then is longer than 8 byte, so that RFC 8974 is needed.

### Code to reproduce this issue

The provided `coap-client` example is used without any code changes.

### Side Note

The log output is not exactly ideal. Adding a warning when reducing the session's max Token Length in response to an RST message would be helpful. Before I looked into Wireshark, I assumed that libcoap never even tried to send out a request with an extended length token.

**Comment by mrdeep1** [comment]
Thanks for raising this.

As per [RFC8974 2.2.2 Trial and Error](https://www.rfc-editor.org/rfc/rfc8974.html#section-2.2.2), libcoap is sending out a packed to determine the server host supports extended tokens or not.  The Token used in the test packet is deliberately different from the one for the actual CoAP packet to send. 

The actual CoAP packet used to testing the server support is valid and not corrupted, unfortunately Wireshark does not decode it correctly.

Wireshark does not understand Extended Tokens.  It reports the length as 13, and as per [RFC 8974 2.1 Extended Token Length (TKL) Field](https://www.rfc-editor.org/rfc/rfc8974.html#section-2.1) it is not getting translated to the correct token length - which is the 0x3 leading token byte which makes a token length of 3 + 13 = 16..

If you add the `-T 16` option to the standard coap-server, you will see that all works as expected (but Wireshark still complains).

If you run coap-client with the -`v 7` option, you will see it reporting that it is 'Testing for Extended Token support'.

**Comment by maribu** [comment]
Thanks for the quick reply :heart:

> Wireshark does not understand Extended Tokens.

Indeed. What is worse that it does handle extended tokens up to 12 correctly (rather than flagging anything > 8 as out of spec, as I would expect any parser not implementing RFC 8974), but only starts to fail when there is an extended token length.

Sorry for the noise! :innocent:
