### ISSUE TITLE
Docker file source for obgm/libcoap:build-env

### ISSUE THREAD

**Issue by fstakem** [obgm/libcoap#158]
I noticed you were using docker to do the build. You docker image is on dockerhub but there is no source code for this. Can you post this in another repo? Currently pulling from an unknown docker image is a security vulnerability.

**Comment by obgm** [comment]
Sure, I can publish the creation script. As it is barely more than a Dockerfile to pull from debian:testing-slim, how about adding the script to the libcoap repository?

**Comment by obgm** [comment]
The build configuration now is in `build-env/Dockerfile.build-env`, see commit 767a24e. I am running `build-env/build.sh` to create the docker images.

**Comment by obgm** [comment]
Closing as resolved.
