### ISSUE TITLE
Need an invocation for pong_handler

### ISSUE THREAD

**Issue by hongnguyen-tma** [obgm/libcoap#159]
Hi,
In case of UDP or DTLS, the ping/pong mechanism is supposed to be as 
  + Client sends Empty confirmable message (code=0.0)
  + Server responds with Reset message
(Ref : https://tools.ietf.org/html/rfc7252#section-4.2)

If I'm correct, the current net.c/coap_dispatch() seems not invoking the pong_handler in case of receiving a Reset message. I think that the invocation for a pong_handler in case of UDP/DTLS, is going to be within this block of code : 
https://github.com/obgm/libcoap/blob/develop/src/net.c#L2046

net.c/coap_dispatch() : 
` COAP_MESSAGE_RST:
      .....
      if (sent) {
	coap_cancel(context, sent);

        if(sent->pdu->type==COAP_MESSAGE_CON && context->nack_handler)
          context->nack_handler(context, sent->session, sent->pdu, COAP_NACK_RST, sent->id);
      }
     // Invoke pong_handler
      if((session->proto == COAP_PROTO_UDP || session->proto == COAP_PROTO_DTLS) && 
            sent->pdu->type==COAP_MESSAGE_CON && COAP_PDU_IS_EMPTY(pdu) && 
            context->pong_handler) {
         context->pong_handler(context, session, sent->pdu, sent->id);
}`

Can you confirm if my understanding is correct?  We are in need of this pong_handler invocation, if  possible please add code in your next release. 
Thanks
Hong

**Comment by mrdeep1** [comment]
Hi Hong,

Strictly speaking, pong is only referred to in RFC8323 (CoAP over TCP).  

With the current code, if you have nack_handler defined, then the RST is passed into the handler with the reason of COAP_NACK_RST, which can be used as the pong equivalent.  Is this good enough for you?

There is an issue with your proposed code change (// Invoke pong_handler and following) in that the nack_handler can de-reference the session and so "if((session->proto" will be pointing to random memory if the nack_handler was called.

**Comment by hongnguyen-tma** [comment]
Hi mrdeep1
Thank you for promptly response. I made as your suggestion.

Hong
