### ISSUE TITLE
autogen dosn't work with autoconf 2.63

### ISSUE THREAD

**Issue by wanghengwen** [obgm/libcoap#16]
error message:
[HINT] You can run 'autogen.sh --clean' to remove all generated files by the autotools.

Found 'autoconf'.
Found 'aclocal'.
Found 'libtool'.

  --->  Found all needed tools! That's fine.

Generating needed autotools files for libcoap by running autoreconf ...
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force ${ACLOCAL_FLAGS} -I m4
configure.ac:27: warning: macro `AM_PROG_AR' not found in library
configure.ac:116: error: Autoconf version 2.64 or higher is required
m4/ax_check_compile_flag.m4:60: AX_CHECK_COMPILE_FLAG is expanded from...
configure.ac:116: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63

automake version:1.11.1  autoconf version:2.63

**Comment by tijuca** [comment]
Can you please try the follwing patch?
```
diff --git a/configure.ac b/configure.ac
index f316753..1dd6e70 100644
--- a/configure.ac
+++ b/configure.ac
@@ -24,8 +24,9 @@ AC_CONFIG_HEADERS([coap_config.h])
 
 AC_PROG_CC
 AM_PROG_CC_C_O
-AM_PROG_AR
 AC_CONFIG_MACRO_DIR([m4])
+m4_pattern_allow([AM_PROG_AR])
+AM_PROG_AR
 
 # enable the automatically build of shared and static libraries, the unit
 # tests needs the static library
```
This will expand the AM_PROG_AR only if available.

**Comment by obgm** [comment]
tijuca <notifications@github.com> writes:

> Can you please try the follwing patch?

After downgrading to automake-1.11.1/autoconf-2.63, I could reproduce
the error. Now, with your patch, I get this:

configure.ac:29: warning: macro `AM_PROG_AR` not found in library
configure.ac:117: error: Autoconf version 2.64 or higher is required
m4/ax_check_compile_flag.m4:60: AX_CHECK_COMPILE_FLAG is expanded from...
configure.ac:117: the top level
[...]
failed with exit status: 63

IMHO, the correct resolution of this bug is to update 
automake and autoconf.

Grüße
Olaf

**Comment by tijuca** [comment]
Well, yes. That's the typical Auotool hell. There are many various distributions out there with even more constellations of ancient versions for automake and autoconf. I suppose this report is about the anachronistic CentOS 5 there this two versions are to find.

We need to increase then the check AC_PREREQ([2.59]) to AC_PREREQ([2.64]) within configure.ac Even Debian Squeeze is using autoconf 2.67 so this should not be not aggressive. I can create a patch and would take the M4 macro expansion too, so the error message is even more clean.

**Comment by obgm** [comment]
Please do!

**Comment by obgm** [comment]
Thanks for providing the patch which is applied in commit a0b31e7.
