### ISSUE TITLE
tinydtls and openssl PSK DTLS incompatible

### ISSUE THREAD

**Issue by chrysn** [obgm/libcoap#160]
I've built the current develop branch (7872a80f) with different options: OpenSSL with `./configure --with-openssl --disable-documentation` and TinyDTLS with `./configure --with-tinydtls --disable-documentation --disable-shared`, and am comparing the examples' interoperability.

Inside each version, I can run `./coap-server -A 127.0.0.1` and have `coap-client coaps://127.0.0.1/ -u CoAP -k secretPSK` give me a valid result; however, I do not get any positive results when crossing them (but only various DTLS retries). Analyzing the exchanges in Wireshark with the DTLS protocol dissector configured to a PSK of 73656372657450534b (hex of 'secretPSK') can decode the tinyDTLS but not the OpenSSL data.

Now this may easily be a bug in one of the two DTLS implementations involved (and tbh I actually only ended up testing that in libcoap because here is the only mature code I found that tries uses them both consistently), but before I set off the library developers against each other: Could you verify that that the PSK is made available to the two libraries in a compatible way?

**Comment by obgm** [comment]
Will check. (I know of at least one bug in the version signaling in tinydtls that could be relevant here as well.)

**Comment by obgm** [comment]
No need to: That is the well-known bug I was referring to. I also have a partial fix for that already under test (your diff is unfortunately not the whole story). I will finish this asap and test again if that resolves chrysn's issue.

**Comment by obgm** [comment]
I have updated the submodule ext/tinydtls to the latest version of tinydtls/develop to fix the version number issue. tinydtls-based client to openssl-based server and vice versa so far worked for me. Can you please repeat your tests with the latest develop version?

**Comment by chrysn** [comment]
I have repeated the test after checking out the `develop` branch in the
ext/tinydtls submodule and rebuilding, and the the openssl and tinydtls
version now interoperate for me.

Thank you!

**Comment by obgm** [comment]
Closing as resolved by the tinydtls update.
