### ISSUE TITLE
Error cast const qualifier

### ISSUE THREAD

**Issue by arabine** [obgm/libcoap#161]
Last lines of util.h, the ugly cast is not tolerated by the GCC flag: -Werror=cast-qual

`uint8_t *coap_opt_value(coap_opt_t *opt);

COAP_STATIC_INLINE const uint8_t *
coap_opt_const_value( const coap_opt_t *opt ) {
  return coap_opt_value((coap_opt_t*)opt);
}
`

**Comment by arabine** [comment]
Ok, I have created a pull-request.

**Comment by mrdeep1** [comment]
Fixed in PR #173 now in develop
