### ISSUE TITLE
configure: error: ==> Install the package containg a2x

### ISSUE THREAD

**Issue by AlonsoCong** [obgm/libcoap#164]
When I compiled code, i found this error

configure: WARNING: ==> You want to build the examples binaries, that is also including the respective manpages but a2x was not found!
configure: error: ==> Install the package containg a2x (mostly asciidoc) or disable the build of the examples using '--disable-examples'.

thanks

**Comment by obgm** [comment]
The message clearly describes two options to fix your build environment for getting rid of this message.

Note that PR #139 will change this behavior.

**Comment by obgm** [comment]
Closed after PR #139 merge.
