### ISSUE TITLE
test uri 18 fails on windows

### ISSUE THREAD

**Issue by jcmichelou** [obgm/libcoap#167]
When running testdriver on windows with a debug build, t_parse_uri18 fails. This is because coap_new_string() does not initialize the buffer it allocates.
I think it should set the first byte to zero, so that if the string is not filled / zero-length like in this test case, it still is consistent. If that's ok I will submit a pull request.

**Comment by mrdeep1** [comment]
Replacing (in coap_new_string())
memset(s, 0, sizeof(coap_string_t));
with
memset(s, 0, sizeof(coap_string_t)+1);
is safe and fine from my perspective.

**Comment by mrdeep1** [comment]
I created coap_get_uri_path() (when replacing the hash functions) - and had assumed that if the resultant string length was 0, a string comparison would work if the lengths were equal, and that the memcmp() would be comparing 0 bytes.  coap_get_uri_path() does not (currently) null terminate the string for any uri_path length.  So, either the test t_parse_uri18 doing a memcmp check with length of 1 is incorrect, or we need to zero terminate the string returned by coap_get_uri_path().

**Comment by obgm** [comment]
Note that the behavior for `0` as the size parameter for the `mem*()` functions is undefined in C and therefore must be avoided.

For test_uri18, I might have been too strict. The rationale was that you have started to zero-terminate strings in some cases (starting with reserving an additional byte in coap_new_string()).  Because this might lead users to the—wrong—assumption that strings in libcoap might be zero-terminated, I have introduced a unit test to confirm that.

I would feel much better if we just removed that zero-termination stuff entirely.

**Comment by mrdeep1** [comment]
Makes sense to remove the +1 in coap_new_string(), fix test_uri18 and update coap_string_equal() to return 0 if string length is 0.

**Comment by jcmichelou** [comment]
Removing the zero termination will make coap_string_t incompatible with the libc string functions. Even making a simple printf will be tedious. I known you could use %.*s, and make sure you downcast the size_t to an int. I have no problem with that but I suspect many users will bang their head on it.
On the other hand it is more consistent with the fact that it could point anywhere into another structure that has a string in it and not require that string to be null terminated. But it's never used for that purpose currently.

**Comment by jcmichelou** [comment]
Unrelated, but I also noticed that in mem.c the size of a buffer for a coap_string_t is 12 bytes, which would leave 4 bytes for the string itself on embedded OS, whereas the well-known URI path is 16 bytes, so this is probably insufficient.

**Comment by mrdeep1** [comment]
Under Linux, coap_default_uri_wellknown is built correctly as the data is in another piece of memory (but does have a trailing zero).

(gdb) p coap_default_uri_wellknown    
$3 = {length = 16, s = 0x7ffff7bd5895 ".well-known/core"}

(gdb) x/20x &coap_default_uri_wellknown
0x7ffff7ddaf70 <coap_default_uri_wellknown>:    0x10    0x00    0x00    0x00    0x00    0x00    0x00    0x00
0x7ffff7ddaf78 <coap_default_uri_wellknown+8>:  0x95    0x58    0xbd    0xf7    0xff    0x7f    0x00    0x00
0x7ffff7ddaf80 <coap_error>:    0x41    0x00    0x00    0x00

(gdb) x/18c 0x7ffff7bd5895             
0x7ffff7bd5895: 46 '.'  119 'w' 101 'e' 108 'l' 108 'l' 45 '-'  107 'k' 110 'n'
0x7ffff7bd589d: 111 'o' 119 'w' 110 'n' 47 '/'  99 'c'  111 'o' 114 'r' 101 'e'
0x7ffff7bd58a5: 0 '\000'        0 '\000'

**Comment by jcmichelou** [comment]
Don't get me wrong, there is no problem on linux or windows. The size problem is for Contiki or other builds where the string buffer is statically allocated. coap_default_uri_wellknown will always be correct, but as I understand the code, but coap_get_uri_path() would not be able to allocate the string that is later compared with coap_default_uri_wellknown.

**Comment by mrdeep1** [comment]
Understood.   coap_get_uri_path() could be long.  I did change coap_malloc(... to coap_malloc_type(COAP_STRING,... in coap_new_string() (and coap_free change in coap_delete_string()) as requested by Olaf in #133 - perhaps that change needs to be reverted.

**Comment by obgm** [comment]
The change was exactly to make is reasonably useful for embedded devices with static memory pool allocators. You do not want (and need) malloc() there.

**Comment by jcmichelou** [comment]
Actually I think coap_malloc(...) is defined as coap_malloc_type(COAP_STRING,...) on embedded system because there is no dynamic heap. I think it's just a matter of setting a reasonable size, like 32 bytes.

**Comment by obgm** [comment]
Currently, `coap_malloc_type()` is defined as follows on all platforms except Contiki. On Contiki, there is indeed the 12 byte limitation that you are referring to. This could be changed, of course. But why is 32 bytes a good size?

```c
void *
coap_malloc_type(coap_memory_tag_t type, size_t size) {
  (void)type;
  return malloc(size);
}
```

**Comment by mrdeep1** [comment]
My suggestion would be to update the code in src/mem.c so that a build can change the default size if wanted by including in CFLAGS '-DCOAP_MAX_STRING_SIZE=xxx' when building.

#ifndef COAP_MAX_STRING_SIZE
#define COAP_MAX_STRING_SIZE yyy
#endif 

yyy (stab in the dark) of 256 I would think was reasonable to cover a normal URI path.

**Comment by obgm** [comment]
I just did that change, but with 64 instead of 256 bytes, as suggested. I have not seen examples for CoAP for embedded devices where URI paths including queries even come close to 64 bytes. Therefore, I chose 512 B pre-allocated space over 2 KiB.

**Comment by jcmichelou** [comment]
There remains the original question: should coap_string_t be zero-terminated or not ? If it is not a requirement, then the test case should be modified to not fail.

**Comment by obgm** [comment]
Absolutely. I would even refrain from allocating an extra byte for zero-termination that is a non-requirement.

**Comment by obgm** [comment]
...and the data type for s being changed to `uint8_t`. I could live with that for now.

(But in the long run, we would have to decide if URIs should instead be represented as wchar strings to be standards-compliant.)

**Comment by jcmichelou** [comment]
Just curious what standard you are referring to for wchar ? In the CoAP RFC a string is a sequence of bytes to interpreted as UTF-8 encoded. That seems reasonable as a compact representation, rather than 32-bit wide UCS-4 chars.

**Comment by obgm** [comment]
UTF-8 is just a representation on the wire. The application needs to convert this into their internal data representation, e.g. to be able to check if two strings are equal.
I do not think that this is an issue for constrained IoT devices where you could just hand-craft everything you need, but we are currently moving libcoap away from anything that might run on, say, class 1 devices. Thus, we can also think about the nice-to-haves to make libcoap conform to RFC 7252 some time...

**Comment by mrdeep1** [comment]
Actually, as I read the RFC, things should only be compared as opaque strings when looked at internally.  If they need to represented internally they could be converted, I guess, to wchar_t, for printing.

Libcoap is not also obeying 6.4.8 below - it just takes whatever string data is passed to it and copies into the option without encoding as appropriate in coap_add_option() and coap_opt_encode() - there is no decoding of any % + 2 hex digits to a byte before putting into the Option.

`3.2.  Option Value Formats

   string:   A Unicode string that is encoded using UTF-8 [RFC3629] in
             Net-Unicode form [RFC5198].

             Note that here, and in all other places where UTF-8
             encoding is used in the CoAP protocol, the intention is
             that the encoded strings can be directly used and compared
             as opaque byte strings by CoAP protocol implementations.
             There is no expectation and no need to perform
             normalization within a CoAP implementation (except where
             Unicode strings that are not known to be normalized are
             imported from sources outside the CoAP protocol).  Note
             also that ASCII strings (that do not make use of special
             control characters) are always valid UTF-8 Net-Unicode
             strings.
`
`6.4.  Decomposing URIs into Options

   8.  If the value of the <path> component of |url| is empty or
       consists of a single slash character (U+002F SOLIDUS "/"), then
       move to the next step.

       Otherwise, for each segment in the <path> component, include a
       Uri-Path Option and let that option's value be the segment (not
       including the delimiting slash characters) after converting each
       percent-encoding ("%" followed by two hexadecimal digits) to the
       corresponding byte.`

`6.5.  Composing URIs from Options

   6.   Let |resource name| be the empty string.  For each Uri-Path
        Option in the request, append a single character U+002F SOLIDUS
        (/) followed by the option's value to |resource name|, after
        converting any character that is not either in the "unreserved"
        set, in the "sub-delims" set, a U+003A COLON (:) character, or a
        U+0040 COMMERCIAL AT (@) character to its percent-encoded form.`

**Comment by jcmichelou** [comment]
From my experience UTF-8 is the de facto default string representation on linux. JSON is UTF-8 only, XML is UTF-8 by default and so are HTTP and HTML. 16-bit unicode is history since it brought more problems than it was supposed to solve as it morphed into UTF-16. For sure modern linux has 32-bit wchar_t but I doubt anybody would want to use this for logs or configuration files. Comparing strings for equality is not easier in UTF-8 or UCS-4. Only sorting requires UCS-4, but it’s a whole subject in itself, you know those strange languages like german with 4 different ordering methods ... So my opinion would be that the API takes UTF-8 strings, which matches CoAP, so no transformation is needed. When encoding coap URIs to options lists or the other way around, URI escaping with % should be taken into account, but to the best of my knowledge this is already the case and the code in libcoap follows the RFC rules.

**Comment by mrdeep1** [comment]
As I follow the code through coap_add_option() into coap_opt_encode(), I find no conversion to %+2hex - unless I am missing something.  The conversion of options back into a string is done correctly for URI_PATH and URI_QUERY is done as expected

**Comment by obgm** [comment]
The reason that you do not find the conversion is that the application is supposed to stuff in the correct format. Currently, this would mean UTF-8 and possibly percent-encoded string representations. As I was saying, this could be changed to something more convenient, letting libcoap do the conversion to UTF-8 before sending data over the network.
Personally, I do not favor using wide character strings in C code (and that is why the representation is as it is). I somehow get the impression that there is no strong opinion to change this in the near future...

**Comment by mrdeep1** [comment]
I do agree that coap_split_query() and coap_split_path()  do do the right thing.  However I think that libcoap should do the work for other options and not rely on the application having knowledge as to how things are to be encoded "over the wire".  I also see no need for w_char at this point and can't find anything in RFC7252 that is calling for it.

**Comment by obgm** [comment]
RFC 7252 is a protocol specification, i.e. it cares how things are represented on the wire. The question is how the implementation represents user data internally. For a user API, UTF-8 is usually not very convenient except for the 127 bit ASCII set.

**Comment by jcmichelou** [comment]
In the context of a CoAP API, I think UTF-8 is rather convenient. M2M text and endoints are going to be ASCII, so it keeps the code simple. Non-ASCII text will be coming from opaque user content and UTF-8 is quite good at ensuring no character is ever lost in encoding/decoding thanks to it supporting all of unicode code points, even those above 65535, and being endianness agnostic. For me this ability to transparently store and forward i18n text without ever deforming it is the most important thing. Not to mention direct interoperability with JSON.

**Comment by obgm** [comment]
> M2M text and endoints are going to be ASCII

The basic question is if this statement is true.  I see no indication for this.

**Comment by obgm** [comment]
To wrap this up, here is my proposal:

- [ ] Change `coap_string_t` to `coap_binary_t`.
- [ ] Change the data type of field `s` to `uint8_t`.
- [ ] Possibly add automatic percent-encoding for data that is passed into coap_add_ functions.

...and let everything else as is until someone has come up with a compelling reason to change the internal representation of URIs etc.

**Comment by mrdeep1** [comment]
Stepping back to look at the bigger picture, libcoap is a protocol layer that the application uses to transmit / receive information using a defined PDU.  The application should not need to know the protocol/PDU specifics, but just needs to know the APIs to use to setup / get / send the appropriate information.

In general, for data to be added to, or abstracted from the PDU is of type {size_t, uint8_t*}.  It is up to the application as to how it manages the 'string' data that goes in and out of the appropriate APIs, but the 'string' data put into libcoap by, say, the client must be the same 'string' data received by the server - even if there has to be a translation by libcoap when putting it into the PDU (decoding %hex and minimizing footprint) and abstracted from the PDU (encoding %hex if needed).

However, today, the application does need to know that data passed into libcoap has to be %hex encoded as appropriate as the receiving end will also see it as %hex encoded.  Data passed into libcoap is managed within libcoap as %hex encoded character strings where %hex is used if the character is not one defined by is_unescaped_in_path() with? and /.

So does the application need to know about the %hex encoding requirements?
Or should the application just pass in the appropriate binary data which is %hex encoded as required and get out the binary data after %hex decoding?

- My preference would be for the latter.  Today, I do not think this issue has been exercised as ASCII has been used.  The following refers to the latter choice.

The application decides if it is working with wchar, UTF-8 or whatever - this should all be transparent to libcoap.  Adding in an addition %hex conversion function in the application makes no sense to me.

As libcoap also uses these application facing APIs for handling data internally, my recommendation that all data (apart from in a PDU) is held internally in decoded format (minimizing footprint).  This then means that only the updating PDU and extracting from PDU functions do not need to do any necessary conversions.

The data types are unsigned integer (of various lengths), opaque, string and for payload, a set of well defined formats - e.g. application/json.

It only is string options that need to be decoded when adding to the PDU and encoded when abstracting from the PDU according to RFC7252.  However, if all data being passed around is in decoded format, there is no need for decoding / encoding as far as I can tell.

The string options are:
Uri-Host
Location-Path
Uri-Path
Uri-Query
Location-Query
Proxy-Uri
Proxy-Scheme

Looking at what libcoap does do and what changes may be required to support this.  This is only focusing on Options of type string
PDU Building
=========
coap_split_query() decodes %hex encoded string as into PDU - leave for backward compatibility
coap_split_path() decodes %hex encoded string as into PDU - leave for backward compatibility
coap_add_option() does not decode string type Options into PDU - No need to change

PDU Abstraction
===========
coap_get_query() encodes PDU URI_QUERY option - Fix - remove encoding
coap_get_uri_path() encodes PDU URI_PATH option - Fix - remove encoding
coap_opt_value() does nothing to the data (but should encode strings) - No need to change

Resource Definitions
=============
coap_resource_init() takes the URI 'as is' - which potentially conflicts with coap_get_uri_path() returning an encoded uri - Fix - either encode URI or stop coap_get_uri_path() encoding hte URI.

Summary - we have got away with this inconsistency as string usage to date has been with ASCII characters, not with other UTF-8 characters etc.

I agree that coap_binary_t should be used as the strings will not be %hex encoded  from the applications perspective.

I an happy to come up with a PR for the above changes.

**Comment by obgm** [comment]
I absolutely do not agree with your proposal. You cannot expect from the libcoap API user to deal with the percent-encoding and percent-decoding of characters that are reserved in a URI, so removing the decoding from `coap_get_query()` and `coap_get_uri_path()` is out of the question. Fixing `coap_resource_init()` to do the percent-encoding to be consistent would be ok for me.

**Comment by mrdeep1** [comment]
Not an issue if we keep URI %hex encoded within libcoap and expect the application to do the necessary %hex encoding/decoding.   I was raising this to get it thought through / understand what your design goals / expectations were here.

That actually makes the encoded URI char* as then only 7 bits are in use.  Do you want to keep them as uint8_t*?
- changing this would remove a lot of the need to do type casting in the libcoap code and applications.

The other Options that are of type string need to do the necessary %hex encoding / decoding as well.

If the application is supposed to be providing / reading  %hex encoded strings, then coap_resource_init() should not need to do any %hex encoding.

Going this way, coap_binary_t makes no real sense to change from coap_string_t as these are now %hex encoded strings.

**Comment by mrdeep1** [comment]
I have revisited all the uses of str and coap_string_t.  With the exception for token usage, payload in clients.c and teststr in test_options.c, every other usage appears to be an ascii with hex encoding string.

Would it make sense to use coap_binary_t for "token usage, payload in clients.c and teststr in test_options.c" and coap_string_t for the rest?  If we stay with uint8_t for coap_string_t, then coap_binary_t and coap_string_t will actually be identical, but is more obvious from the names as to their purpose.

The only API change would be for coap_method_handler_t, but the " str * query" parameter was only added in back in Aug 2017.

**Comment by mrdeep1** [comment]
Original issue in test_uri 18 fixed in PR #173 now in develop.

**Comment by obgm** [comment]
I suppose the other issues raised here have been resolved as matter-of-fact as well?

**Comment by mrdeep1** [comment]
The only thing of consequence outstanding was whether we want to make NUL the extra byte at the end of coap_string_t.

**Comment by obgm** [comment]
Right. I put an RFC on the mailing list just now.

**Comment by obgm** [comment]
Does PR #204 solve the remaining issue (zero-terminated strings vs. binary blobs)?

**Comment by mrdeep1** [comment]
I believe so

**Comment by obgm** [comment]
AFAICT everything has been resolved.
