### ISSUE TITLE
LICENSE.BSD has only two clauses and is identical to the simplified BSD license

### ISSUE THREAD

**Issue by Angel707** [obgm/libcoap#17]
COPYING  and README mention the revised BSD license which is a 3-clause BSD license but LICENSE.BSD has only two clauses and is identical to the simplified (2-clause) BSD license.

Thus, I think, the third clause is missing in LICENSE.BSD:
"Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission."

Contiki, I think, has a 3-clause BSD license.

**Comment by obgm** [comment]
Thanks for pointing this out. Now, the accompanying files correctly identify it as the simplified (2-clause) BSD license.
