### ISSUE TITLE
xmllint error when building libcoap

### ISSUE THREAD

**Issue by mcr** [obgm/libcoap#171]
Reading #26 did not solve my build problem.
I error out at:

    dooku-[pandora/libcoap/man](2.4.1) mcr 10187 %make
    /usr/bin/a2x --doctype manpage --format manpage coap_attribute.txt
    a2x: ERROR: "xmllint" --nonet --noout --valid "/corp/projects/pandora/libcoap/man/coap_attribute.xml" returned non-zero exit status 4
    Makefile:695: recipe for target 'coap_attribute.3' failed
    make: *** [coap_attribute.3] Error 1

Running a2x manually with -v -v:

    dooku-[pandora/libcoap/man](2.4.1) mcr 10188 %/usr/bin/a2x -v -v --doctype manpage --format manpage coap_attribute.txt
    a2x: args: ['-v', '-v', '--doctype', 'manpage', '--format', 'manpage', 'coap_attribute.txt']
    a2x: resource files: []
    a2x: resource directories: ['/etc/asciidoc/images', '/etc/asciidoc/stylesheets']
    a2x: executing: "/usr/bin/asciidoc" --backend docbook -a "a2x-format=manpage"  --doctype manpage --verbose  --out-file "/corp/projects/pandora/libcoap/man/coap_attribute.xml" "/corp/projects/pandora/libcoap/man/coap_attribute.txt"

    asciidoc: reading: /etc/asciidoc/asciidoc.conf 
    asciidoc: reading: /corp/projects/pandora/libcoap/man/coap_attribute.txt
    asciidoc: reading: /etc/asciidoc/docbook45.conf
    asciidoc: reading: /etc/asciidoc/filters/music/music-filter.conf
    asciidoc: reading: /etc/asciidoc/filters/latex/latex-filter.conf
    asciidoc: reading: /etc/asciidoc/filters/code/code-filter.conf
    asciidoc: reading: /etc/asciidoc/filters/graphviz/graphviz-filter.conf
    asciidoc: reading: /etc/asciidoc/filters/source/source-highlight-filter.conf
    asciidoc: reading: /etc/asciidoc/lang-en.conf
    asciidoc: writing: /corp/projects/pandora/libcoap/man/coap_attribute.xml

    a2x: executing: "xmllint" --nonet --noout --valid "/corp/projects/pandora/libcoap/man/coap_attribute.xml"

    I/O error : Attempt to load network entity http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd
    /corp/projects/pandora/libcoap/man/coap_attribute.xml:2: warning: failed to load external entity 
    "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"
    D DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"

Trying to open http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd in my browser works. (No magic http proxy or anything).  It feels like a package might be missing that would have provided a 
local copy of the docbookx.dtd.  I'm on Debian Jessie.

**Comment by mrdeep1** [comment]
As per

https://packages.debian.org/search?searchon=contents&keywords=docbookx.dtd&mode=path&suite=stable&arch=any

You appear to be missing the package docbook

**Comment by tijuca** [comment]
I can reproduce this if I remove docbook-xml which is only a Suggests on the package docbook. We should enhance the check inside the configure.ac file. I'm not sure how to archive this as the catalog files may be found on different places over the distributions.

You will probably need to install the packages `docbook`, `docbook-xml`if you haven't.

**Comment by mcr** [comment]
Thank you. The critical package was docbook-xml.

**Comment by mcr** [comment]
Maybe just
      make -C man || echo "Please install docbook-xml"

**Comment by tijuca** [comment]
That would not very helpful for other user that may hit the same problem. I prefer to give some advice what to do on the users side.

Seems (thanks to opensource) we just need to do some c&p as this is already implemented by other projects ...
https://mail.gnome.org/archives/commits-list/2015-January/msg05409.html
