### ISSUE TITLE
libcoap and DTLS with public keys

### ISSUE THREAD

**Issue by mcr** [obgm/libcoap#174]
It appears that recent code has added guards such that DTLS can be used unless a PSK is provided.
Previously, one could do server-authenticated-by-PKIX asymmetric key just fine.  I am bisecting to be sure that this really is the case, and that it was intentional.

**Comment by mcr** [comment]
A lot of bisects fail with:

    coap-client: src/coap_session.c:102: coap_session_free: Assertion `session->ref == 0' failed.

And others do not compile.  It's somewhere after:
commit 137789fbc703584b858a1845d8488c68de424880 

still investigating.

**Comment by mcr** [comment]
commit 137789f is a false positive, it also fails with the assertion.

**Comment by mrdeep1** [comment]
Hi,

I did the addition of the PKI support.  The intent is that for clients you set things up in this order

coap_new_context()
coap_new_client_session(), coap_new_client_session_pki() or coap_new_client_session_psk()

and for servers in this order

coap_new_context()
coap_context_set_psk() and/or coap_context_set_pki() if encryption is required
coap_new_endpoint()

There is a check to see that if the protocol is COAP_DTLS, then one of the _pki() or _psk() must be called prior to starting the actual DTLS session.

For servers, it is legitimate to set up both _psk and _pki, but you then have to make sure within the application code that the correct type is selected.

I have also seen with OpenSSL that if the first connection is PSK + DTLS, it will fail with no matching ciphers, but the subsequent attempts works.  If the first connection is PKI + DTLS, that works, then PSK + DTLS works for its first time.  It is a bug in OpenSSL - something to do with a RSA structure not properly initialized.

I'm not entirely sure about what you mean by needing a PSK for PKI to work.

**Comment by mcr** [comment]
okay, so let me give a longer explanation... I wanted to just open an issue and record my observations...
I'm primarily working on DTLS integration with the Ruby "David" CoAP server.  I am mostly successful, but testing ruby CoAP+ruby_openssl against itself fails to find certain issues, so I am also using coap-client. (I will eventually move to libcoap on OpenWSN and/or Contiki)
I was using something after your DTLS integration (checked out from github, sorry, I didn't record the sha1, but I can probably find it), which mostly did the right thing when I entered "coaps://...", and I didn't need a -k argument.
I was running into a problem where it seems that MID is remaining the same, and I'm caching a failing response (a 5.xx error), which is a bug at my end.  But then I asked... why is the MID the same across processes?   Maybe I'll git pull and see if it's a bug that is fixed.
My DTLS server has a certificate (ECDSA, prime256k1), and at the moment my client code does not have a client certificate (but it will...)
With the latest code, it (examples/coap-client) would not initiate DTLS unless -k was provided.  That may be a bug.  I want to insert the error but, I don't have it in front of me.  (BTW: It would be great if all commits always compiled. I know that it's a pain. I have a script/travis.yml for Openswan that does this if you want it, or I can send a pull request)
I'm almost done bisecting.

**Comment by mcr** [comment]
okay, so 070479269806f48c38ba6a50c3fa21b0aaa7ccf9 fails with:
   
    coap-client: src/coap_session.c:102: coap_session_free: Assertion `session->ref == 0' failed.

the few commits before that on that branch do not compile, so I can't test them.

commit eb84476fd1c682b7cbf691bf7391f84a096ac468, which is on the main branch just before your branch works. (And I don't need -k option)
commit 047c9fb082d6bba62ba461e5fdfc7451a5326687 also works, but the next ones on that branch fa6f292997bafe64e8bf74682994072fcb9c844d do not compile.

commit 4280e75a0c5a31a09ce11b8de0d94dcd365c6221 (develop head as of April 20) fails with:

    examples/coap-client -e "HELL0" -m POST coaps://fountain-test.sandelman.ca/e/rv

    Apr 27 17:36:44 EMRG cannot create client session

I would be happy to test any code. I could also put my code out there to test against if it helps.
I imagine that I will come to fix this in a few weeks anyway, as I have to write the C client anyway.

**Comment by mrdeep1** [comment]
Hi,

I will fix this in PR #179 .  The needed change is a 2 line delete which then enables a coap-client without PSK or PKI defined to talk to a coap-server that is PKI enabled with a certificate using OpenSSL.

diff --git a/src/coap_openssl.c b/src/coap_openssl.c
index a97a309..d9acd25 100644
--- a/src/coap_openssl.c
+++ b/src/coap_openssl.c
@@ -730,8 +730,6 @@ void *coap_dtls_new_client_session(coap_session_t *session) {
   coap_openssl_context_t *context = ((coap_openssl_context_t *)session->context->dtls_context);
   coap_dtls_context_t *dtls = &context->dtls;
 
\-  if (!context->psk_pki_enabled)
\-    goto error;
   ssl = SSL_new(dtls->ctx);
   if (!ssl)
     goto error;

**Comment by mrdeep1** [comment]
coap-client no longer requiring -k is fixed in PR #179 .

The coap_session_free() assertion was fixed in 46c908a and updated by f3c1542

Apologies for each commit not necessarily building - I was trying to follow the requirements of CONTRIBUTING by splitting the overall commit into the separate files for ease of tracking what was is going on on a per file basis.  Each Pull Request comprising of multiple commits are built as expected by travis

**Comment by obgm** [comment]
@mrdeep1, CONTRIBUTING wants small-size commits but of course, building should always be possible.

**Comment by mrdeep1** [comment]
@obgm, I am happy to create the PR in what ever way works best for you.  For example, if a header file has to be updated with a change, and then there are 2 source files dependent on that change, just committing the header file first causes the build to break and committing either source file first breaks the build as well, do you want all 3 files in the same commit - the initial subject line may not be long enough.  Things get more complicated if there are more files.

Would all 3 files being committed at the same time work for you with the commit message looking something like

header.h: New struct X
source1.c: Use struct X for ...
source2.c: Use struct X for ...

Other useful information ...

**Comment by obgm** [comment]
@mrdeep1 Usually, if multiple files are involved, I only mention the most important one (if it is header + source, then I sometimes do "file.[hc]: blabla").  In the past, I found it more important to have commits that contain everything that is needed to compile than to be too rigid with the style guide. Too long first lines in the commit message are not displayed nicely in GH and therefore should be avoided, though.

**Comment by mrdeep1** [comment]
@obgm I'm happy to do that moving forward.  Do you want me to re-factor pending PRs into a single commit (it will take a bit of time) ?

**Comment by obgm** [comment]
@mrdeep1 No, re-factoring the pending PRs is not necessary from my point of view.

**Comment by obgm** [comment]
Closing as the issue seems to be solved.
