### ISSUE TITLE
Need code to check notify observers of unknown_resource and using uri_path instead of uri_query in observer'subscription 

### ISSUE THREAD

**Issue by hongnguyen-tma** [obgm/libcoap#182]
Hi All
1) Is there any problem if adding code to notify observers of unknown resource? I 'm thinking of something like this

resource.c/ coap_check_notify()
`void
coap_check_notify(coap_context_t *context) {

  RESOURCES_ITER(context->resources, r) {
    coap_notify_observers(context, r);
  }
 
 // notify observers of unknown_resources
 if (context->unknown_resource) {
     coap_notify_observers(context, r);
 }
  
}`

or  if that is inconvenient,  an exposing for function "coap_notify_observers" (adding to function declaration into resource.h) so that it can be visible to higher application, is also enough. 

2) net.c / handle_request()
https://github.com/obgm/libcoap/blob/develop/src/net.c#L1868
Is it reasonable if modifying it like this ? I need this because my client uses uri-path instead of query. 

if (h) {
  str *query = coap_get_query(pdu);

 // use uri-path in case query is null
  if (!query) {
      query = coap_get_uri_path(pdu);
  }
  ...
}

Thanks
Hong

**Comment by mrdeep1** [comment]
Hi Hong,

Unfortunately, you cannot Observe an Unknown resource.

When an Observe is triggered and the GET handler is called, the request parameter is NULL, so the URI-Path cannot be determined from that, and if you abstract the URI-Path from the resource, you will not get the actual URI-Path (but just get '-Unknown-') and so you do not know which resource is being Observed to generate and send back the appropriate Response.  The Query is maintained by the observe logic and then is passed into the handler.  This then allows a resource to be observed, but the response can be filtered by the Query in the GET handler.

Trying to re-use Query to hold Path is not a good idea - especially if you go on to support the 'c=a', 'c=n' etc. query.

'man coap_resource' shows you in the examples how to handle the dynamic creation / deletion of Dynamic Resources triggered by a call to the Unknown Resource PUT handler.

**Comment by hongnguyen-tma** [comment]
Hi mrdeep1
Thanks for replying me.  

You mean that the reason for not be able to observe unknown resource is below, right? 
> When an Observe is triggered and the GET handler is called, the request parameter is NULL, so the URI-Path cannot be determined from that, and if you abstract the URI-Path from the resource, you will not get the actual URI-Path (but just get '-Unknown-') and so you do not know which resource is being Observed to generate and send back the appropriate Response. 


I think that the '-Unknown-' is the value reserved inside resource object. The uri-path from the  request will hold enough information for higher layer to know which resource being observed. 

When the handler get called, 
net.c#L1910 :
`h(context, resource, session, pdu, &token, query, response);`

it passed the 'query' which was retrieved from the request (pdu)  at 
net.c#L1868 :
`str *query = coap_get_query(pdu);`

So I think it also works if we use uri-path from the request (pdu) by calling  "coap_get_uri_path(pdu)"
※Note that this is just in case the result of coap_get_query(pdu) is NULL so it won't affect to other applications that use query. 

With the original uri-path from request,  which will include query part if existing (e.g 'c=a', 'c=n'), the higher layer can retrieve the observed resource. 

Please let me know your idea.
Thanks
Hong

**Comment by mrdeep1** [comment]
Hi Hong,

net.c#L1910 is called when handling the initial incoming request.

net.c#L731 in coap_notify_observers() is when an Observe has been triggered (dirty is set) and calls the GET handler.

Note that the request parameter is NULL as there is no incoming PDU.
`h(context, r, obs->session, NULL, &token, obs->query, response);`
So, you are not able to abstract the actual Uri-Path from the request as it is NULL.  The original PDU is not saved in the coap_subscription_t structure.

Uri-Path in the request does not include the Uri-Query - both of which go towards making up the overall Uri.  Combining them would be dangerous.

For example, it is possible to inform the libcoap logic to only trigger observable resources based on the Uri-Query parameter usingcoap_resource_notify_observers(), so that an unsolicited response can get generated based on the subset (based on the query) of the resource.

**Comment by hongnguyen-tma** [comment]
Hi mrdeep1
My apology. Let me correct my previous answer as below: 

1.  Regarding to using uri-path in case uri-query is NULL 

When handling initial incoming request,  
at net.c#L1868
`str *query = coap_get_query(pdu);`
 if we store uri-path (in case uri-query is null) into query,  that value will be set to observer' subscription at net.c#L1898
`subscription = coap_add_observer(resource, session, &token, query);`

Then,  when observe is triggered and GET handler is called at resource.c#L731
`h(context, r, obs->session, NULL, &token, obs->query, response);`
This time obs->query has value of uri-path at initial time, so the higher layer can have enough information to retrieve the resource back. 

※The above code change suggestion is because my higher application follows definition that query parameter is set inside URI-Path (which result in uri like this :  .well-known/test-app/v1/action/attr1=val1/attr2=val2

2.  Regarding to adding check-notify-observe for unknown-resource 

I think that this is not related to the first issue (using uri-path in case uri-query is NULL). 
The current source code can work if we add coap_notify_observe() for unknown_resource, right?   The first issue is just a kind of work-around for those higher applications that do not use uri-query but uri-path to store query information. 

Please let me know your idea.
Thanks
Hong

**Comment by mrdeep1** [comment]
Hi Hong,

You have to support third-party clients that will append queries as in ".well-known/test-app/v1/action/attr1=val1/attr2=val2?c=n" that want to use the 'c' (content) parameter - see https://tools.ietf.org/html/draft-ietf-core-comi-02  - even though the server does not have to act on them.

To overlay the usage of a parameter with a different parameter usage will give rise to errors - and cannot be a part of a core library.

There are 2 ways forward here.

1) Within the Unknown resource PUT handler, you create a resource, give it a generic GET handler, and set that resource as observable.  The resource then can be deleted as appropriate with either a Unknown resource  DELETE handler (you will know the Uri-Path from the request), or a DELETE handler for the created resource.

2) In libcoap, if an Observable GET request comes in and is handled by the Unknown resource GET handler, a copy of the PDU is kept in coap_subsubscription_t, and this PDU replaces the NULL in net.c#L731 `h(context, r, obs->session, NULL, &token, obs->query, response);`.  Obviously this saved PDU will need to get cleaned up when coap_subscription_t is cleaned up.  This does mean memory is required to save the PDU, but option 1 above needs more memory as well for the additional resources that need to be added in.

However, there is a fundamental issue with going down the option 2 route.  When coap_check_notify() is called, it will cause ALL observers of the unknown resource to get sent an unsolicited response, so the following 3 different requests will all get an update - even if it was only attr2=anotherval2 that changed.

".well-known/test-app/v1/action/attr1=val1/attr2=val2?c=n"
".well-known/test-app/v1/action/attr1=val1/attr2=diffval2?c=n"
".well-known/test-app/v1/action/attr1=val1/attr2=anotherval2?c=n"

This does not scale to 1000s of Observers on an Unknown GET resource as the server will be busy sending out 1000s of updates for every change, as well as your network will get very busy.  The only real way forward is with option 1.

**Comment by hongnguyen-tma** [comment]
Hi mrdeep1
Thanks for your suggestions. Let me clarify some things: 
1) With option 2, you agreed with adding check-notify-observers for unknown_resource, right? 
2) For option 2, 
> However, there is a fundamental issue with going down the option 2 route. When coap_check_notify() is called, it will cause ALL observers of the unknown resource to get sent an unsolicited response, so the following 3 different requests will all get an update - even if it was only attr2=anotherval2 that changed.

".well-known/test-app/v1/action/attr1=val1/attr2=val2?c=n"
".well-known/test-app/v1/action/attr1=val1/attr2=diffval2?c=n"
".well-known/test-app/v1/action/attr1=val1/attr2=anotherval2?c=n"

Can you explain a bit more what's the problem with this?  For my client application, different values of attr1, attr2 will result in different data. So it is quite straight that 3 subscribers will be created  with 3 requests above.

Hong

**Comment by mrdeep1** [comment]
Hi Hong,

Yes, for Option 2 you would have to add check-notify-observers for unknown_resource

So, when you call coap_resource_notify_observers() on a 'unknown' resource one time, it will set the dirty bit in the resource.  Then when coap_check_notify() is called from coap_write() called by coap_run_once(), coap_check_notify() will call coap_notify_observers() who will call the 'unknown' GET handler 3 times using my quoted case.  The server will then send out 3 unsolicited responses.  3 perhaps is an acceptable overhead.

If however you have 1000s of clients using the singular server (or perhaps 100s of clients monitoring 10 resources each), a single call to coap_resource_notify_observers() will then cause the 'unknown' GET handler to get called 1000s of times, which will then generate 1000s of packets.

The solution simply does not scale.  This potentially would flood your network with all of these packets - especially if each of the 1000s of resources is changing once per second and so coap_resource_notify_observers() is getting called 1000s of times per sec.  You are now talking of millions of packets per second getting generated.

**Comment by hongnguyen-tma** [comment]
Hi mrdeep1

Maybe I got  your point now. Because my unknown-resource doesn't have uri-query, so each subscribers will get query=NULL.  When calling coap_resource_notify_observers(), the only way is that I have to pass null value for 'query' parameter.  This will result in r-> dirty = 1 which then causes all subscribers of resource get notified.  This issue can be solved if the each subscriber of the unknown resource has a its own query, and when calling calling coap_resource_notify_observers(),  I passed the query of the target resource, so only the target one will bet notified, right? 

> You have to support third-party clients that will append queries as in ".well-known/test-app/v1/action/attr1=val1/attr2=val2?c=n" that want to use the 'c' (content) parameter - see https://tools.ietf.org/html/draft-ietf-core-comi-02 - even though the server does not have to act on them.

I haven't figured out what kind of third-party client that is?  Can you explain abit more?  If there is such client, how can it get notified by libcoap?  
Hong

**Comment by mrdeep1** [comment]
Yes, if they all have different queries, then that can be supported to reduce the traffic generation.

The third part clients are clients created by different manufactures that will talk to your server using (based on your port 4646 in a previous query and the use of ".well-known/../v1/" url) the DOTS protocol.  See https://tools.ietf.org/html/draft-ietf-dots-signal-channel-19#section-4.4.2 with regards to the 'c' query if my guess is correct.

**Comment by hongnguyen-tma** [comment]
Hi mrdeep1
I think that one client must use queries in an unique style : either in uri-query or uri-path.  If they already support normal queries (attr=val1, attr=val2) in uri-path,  the 'c' parameter (though defined as uri-query in CoMI) will also has to be supported in uri-path, otherwise it will look arbitrary.  So it may be reasonable for libcoap to consider using uri-path in case uri-query is NULL.  Please let me know your idea.

**Comment by mrdeep1** [comment]
Hi Hong,

To use Uri-Path if Uri-Query is NULL is fundamentally a bad design, as you will not be supporting only clients that are created by you, but by other manufacture's clients making use of the Observe support by using both the Uri-Path and Uri-Query.

Why are you not able to implement Option 1 where you create a resource for each new Uri-Path?

**Comment by hongnguyen-tma** [comment]
Hi mrdeep1

Can you explain  option1 a bit more. I haven't figured out how that work. 

Thanks
Hong

**Comment by hongnguyen-tma** [comment]
Hi mrdeep1
Correct me if I misunderstood.
I think that option1 can help to solve the first issue which I mentioned above (lacking of notification for unknown_resource) by creating resource behind unknown-resource.  Once the new resource is created and set as observable, it can be handled the notification instead of the unknown_resource.

But it seems not be able to help for the 2nd issue which I mentioned above (the incoming request for my higher application does not use uri-query, but uri-path), right? 

Hong

**Comment by mrdeep1** [comment]
Hi Hong,

The new resource that you create will be based on the Uri-Path (and NOT Uri-Query).  Then any incoming GET requests for that Uri-Path that have Observe set will cause things to get correctly set up (assuming you have defined a GET handler and said it is observable for the new resource) and a unsolicited response is sent every time you call coap_resource_notify_observers(new resource, NULL).

So 2nd issue is not actually an issue.  If you use a generic GET handler for all the new resources, then you just need to get the Uri-Path from the incoming resource definition to work out which resource's data you should be responding with following the call to coap_resource_notify_observers() which triggers the call to the GET handler.

**Comment by mrdeep1** [comment]
Hi Hong,

If you look at net.c#L1898, you will see that the Query is added to the observer by the call to coap_add_observer(() in handle_request().  This Query is passed into the GET handler whenever an unsolicited response it to be generated.  If the GET request that triggers the add subscriber request does not have a Uri-Query, then this is saved in the subscriber entry as NULL.

So Uri-Query is correctly handled by libcoap for the Observe/Subscriber logic.

**Comment by hongnguyen-tma** [comment]
Hi mrdeep1
By creating new resource while the unknown_resource handles PUT request,  we can create new resource with uri-path that identifies exactly one data item (e.g : ".well-known/test-app/v1/action/attr1=val1/attr2=val2 ).  Then when  GET request with observe option = 0 and exactly the same value uri-path  0 comes, libcoap  can use new resource to handle it.  

How about incoming GET request with observe = 0 and uri-path idendifies multiple data items (e.g ".well-known/test-app/v1/action/attr1=val1) ? I think that libcoap will use unknown-resource to handle that GET request again, which results in problem of query=NULL that was mentioned early at this issue.

**Comment by mrdeep1** [comment]
Hi Hong,

There is nothing stopping you creating an additional new resource (if it does not already exist) that is for ".well-known/test-app/v1/action/attr1=val1" as well as for ".well-known/test-app/v1/action/attr1=val1/attr2=val2" when the unknown PUT handler is invoked.

Then all you need to do in the generic GET handler is to return the list of information for all the sub resources when the invoking resource is just ".well-known/test-app/v1/action/attr1=val1".  Within he app, you just need to call coap_resource_notify_observers(".well-known/test-app/v1/action/attr1=val1", NULL) to cause this to happen for all the sub-resources.

**Comment by hongnguyen-tma** [comment]
Hi mrdeep1
I got your idea now.  There is one more consideration. As  the new resource is created when handling PUT request, so for example, in case of server being restarted,  all new resources will be lost, so I think the server will unable to handle observation for existing data, right?   Creating new resources for all existing data at startup time may help to solve, but server may crash if thousands of data existed.

Hong

**Comment by mrdeep1** [comment]
Hi Hong,

Interesting conundrum. If a persistent list of all the resources is maintained by the server, then all these resources can be re-created with the appropriate handlers.  The amount of resources is only limited by the amount of RAM available, and incoming requests do a hash lookup of the resources for speed.  So I would not expect the server to be crashing here (older code had issues with resource name (Uri-Path) clashes, but that has been fixed in the develop tree).

However, you cannot easily re-create all of the subscribers/observers of the resources, as coap_subscription_t contains a pointer to the subscribing session which is no longer available.  So, the clients would need to re-subscribe to continue to get unsolicited response updates.

That then begs the question as to how does the client know that the server restarted and so re-subscribes to observe the appropriate resources.  I don't have an answer to that at the moment.

**Comment by mrdeep1** [comment]
The only way that a client can know that a server has restarted is because an existing session fails.   This could happen some way into the future unless you are using a heartbeat mechanism using CoAP pings to continually check network connectivity (but obviously at not too high a rate!).
My suggestion would be that after an existing session fails, when the new session is established, that the client  re-subscribes using GET + Observe to all the resources that the client wants to monitor.

**Comment by hongnguyen-tma** [comment]
Hi mrdeep1

> My suggestion would be that after an existing session fails, when the new session is established, that the client re-subscribes using GET + Observe to all the resources that the client wants to monitor.

Actually, client has to send Get  to all resources twice,  one Get without Observe to create new-resources , another Get + Observe to create one subscriber for each created resource, right?

**Comment by mrdeep1** [comment]
The server should maintain a persistent list of resources so that when it restarts all the resources are re-created.

For the client, after re-establishing a new session should
GET a list of all current resources
PUT missing resources one by one
DELETE all unexpected resources one by one
GET + Observe for all the resources that should be observed

GET without Observe should never be used to create a resource - that is the responsibility of the PUT.

**Comment by tamnguyen-tma** [comment]
Mr. @mrdeep1 

I have a problem with coap_check_notify() function. Could you please to help me?
Currently, I follow to the process in option 1:

> Within the Unknown resource PUT handler, you create a resource, give it a generic GET handler, and set that resource as observable. The resource then can be deleted as appropriate with either a Unknown resource DELETE handler (you will know the Uri-Path from the request), or a DELETE handler for the created resource.

PUT: create the known resource and set observable to 1
GET with observer option: add subscriber into the resource
Then, set dirty of the resource to 1 and coap_run_once will call to coap_check_notify to make a notification message
In that time, I want to remove the resource after coap_check_notify is done. However, I do not know the time of coap_check_notify() function is run, so , I try removing the resource as soon as Get handler is called. Unfortunately, my program will be crashed if I do like that because coap_check_notify still use the resource that have already deleted before.

Could you please to give me some advice about this case? Is there another way to delete the resource after coap_check_notify is done?

**Comment by mrdeep1** [comment]
Interesting question.

Your program should not crash when deleting a resource with coap_delete_resource() and that should also delete any observer subscribers.  That is an issue that needs to be troubleshooted and fixed as appropriate.

However, your requirement of sending out one last observe update before the resource gets deleted means that you cannot delete the resource prior to the observe getting sent.  The only safe place to do this is after coap_run_once() is run - BUT coap_run_once() should not be called within a GET handler or equivalent - coap_run_once() should only be called from the main processing loop.

So, set up a pending resource delete chain within your GET handler and then delete anything off the chain after coap_run_once() has been run.

Likewise, it would be dangerous to call coap_check_notify() from within a GET handler as things are going recursive...

**Comment by tamnguyen-tma** [comment]
Dear Mr. @mrdeep1 

Correct me if I misunderstood about this solution:

>So, set up a pending resource delete chain within your GET handler and then delete anything off the chain after coap_run_once() has been run.

When Get handler is called, I should add the resource that need to be deleted later into a resource chain instead of deleting it at that time, then, the chain will be handled when coap_run_once() is done (before the next coap_run_once is run()).

Currently, I only use coap_run_once in the main processing loop.

Thank you

**Comment by mrdeep1** [comment]
Yes, I think you understand what needs to get done.

Normally, a resource should be deleted by a DELETE (or perhaps expire on some sort of internal timer), not as an action while processing a GET, so wonder if your design is correct here.

libcoap will certainly crash if doing a GET with observe set, the resource is deleted in the GET handler, and the response returned from the GET handler is not a 2.xx then the logic then tries to remove the subscriber (observe) from the now de-allocated resource.
