### ISSUE TITLE
libcoap name space violation: options_start

### ISSUE THREAD

**Issue by bagder** [obgm/libcoap#184]
After a successful build, I checked which symbols the library provides:

    nm .libs/libcoap-2-gnutls.a   | grep " T " | grep -v coap_
    0000000000000100 T options_start

`options_` doesn't seem like a prefix that this library should provide. I presume it should either not be exported or get a `coap_` prefix?

**Comment by obgm** [comment]
That is absolutely true.

**Comment by mrdeep1** [comment]
Issue now fixed
