### ISSUE TITLE
gcc -Wwrite-strings warning option

### ISSUE THREAD

**Issue by mrdeep1** [obgm/libcoap#185]
Do we want to include the "-Wwrite-strings" warning option to flag up when casting defined strings incorrectly?

And then fix the code as appropriate.

**Comment by obgm** [comment]
As the fix is really simple (and straight-forward), I have no objections):

```
diff --git a/include/coap/pdu.h b/include/coap/pdu.h
index 827d38e..afe50eb 100644
--- a/include/coap/pdu.h
+++ b/include/coap/pdu.h
@@ -132,7 +132,7 @@ struct coap_session_t;
  * @return     A zero-terminated string describing the error, or @c NULL if not
  *             found.
  */
-char *coap_response_phrase(unsigned char code);
+const char *coap_response_phrase(unsigned char code);
 
 #define COAP_ERROR_PHRASE_LENGTH   32 /**< maximum length of error phrase */
 
diff --git a/src/debug.c b/src/debug.c
index d82ab9b..f8a7bf7 100644
--- a/src/debug.c
+++ b/src/debug.c
@@ -71,7 +71,7 @@ coap_set_log_level(coap_log_t level) {
 }
 
 /* this array has the same order as the type log_t */
-static char *loglevels[] = {
+static const char *loglevels[] = {
   "EMRG", "ALRT", "CRIT", "ERR", "WARN", "NOTE", "INFO", "DEBG" 
 };
 
@@ -265,7 +265,7 @@ coap_print_addr(const struct coap_address_t *addr, unsigned char *buf, size_t le
 /** Returns a textual description of the message type @p t. */
 static const char *
 msg_type_string(uint16_t t) {
-  static char *types[] = { "CON", "NON", "ACK", "RST", "???" };
+  static const char *types[] = { "CON", "NON", "ACK", "RST", "???" };
 
   return types[min(t, sizeof(types)/sizeof(char *) - 1)];
 }
diff --git a/src/net.c b/src/net.c
index d9f5db5..ed64075 100644
--- a/src/net.c
+++ b/src/net.c
@@ -1426,7 +1426,7 @@ coap_new_error_response(coap_pdu_t *request, unsigned char code,
   uint16_t opt_type = 0;       /* used for calculating delta-storage */
 
 #if COAP_ERROR_PHRASE_LENGTH > 0
-  char *phrase = coap_response_phrase(code);
+  const char *phrase = coap_response_phrase(code);
 
   /* Need some more space for the error phrase and payload start marker */
   if (phrase)
diff --git a/src/pdu.c b/src/pdu.c
index 0722bbb..0ab2cb7 100644
--- a/src/pdu.c
+++ b/src/pdu.c
@@ -344,7 +344,7 @@ coap_get_data(coap_pdu_t *pdu, size_t *len, uint8_t **data) {
 #ifndef SHORT_ERROR_RESPONSE
 typedef struct {
   unsigned char code;
-  char *phrase;
+  const char *phrase;
 } error_desc_t;
 
 /* if you change anything here, make sure, that the longest string does not 
@@ -376,7 +376,7 @@ error_desc_t coap_error[] = {
   { 0, NULL }                  /* end marker */
 };
 
-char *
+const char *
 coap_response_phrase(unsigned char code) {
   int i;
   for (i = 0; coap_error[i].code; ++i) {
```

**Comment by mrdeep1** [comment]
Actually, it is a bit more  than this if #173 (-Wcast-qual) is there as this then throws up additional errors when -Wwrite-string is added.  For example in tests/test_pdu.c

static void
t_parse_pdu1(void) {
  uint8_t teststr[] = {  0x40, 0x01, 0x93, 0x34 };

is given a warning with both -Wcast-qual and -Wwrite-string

**Comment by obgm** [comment]
Interesting. From my POV, it should not complain for this use.

**Comment by mrdeep1** [comment]
If you put in your changes as above (with -Wwrite-strings in configure.ac as well), I will then rebase #173 and update as necessary

**Comment by mrdeep1** [comment]
Oops - my previous but one posting did not have the complete copy of the additional warning code - comment now updated.

**Comment by obgm** [comment]
Done.

**Comment by mrdeep1** [comment]
@obgm 

I'm working on updating PR #173 following this update - thanks for doing it.

Instead of parameters (especially quoted text strings) being typecast and passed in as "const uint8_t*" to functions such as coap_add_attr(), if the the function was defined with "const void*" as in

coap_attr_t *coap_add_attr(coap_resource_t *resource,
                           const void *name,
                           size_t nlen,
                           const void *value,
                           size_t vlen,
                           int flags);

Then the calls to coap_add_attr() would be like

coap_add_attr(r, "title", 5, "\"some attribute\"", 16, 0);

instead of

coap_add_attr(r, (const unsigned char *)"title", 5, (const unsigned char *)"\"some attribute\"", 16, 0);

which is considerably more readable for my tiring eyes.  coap_resource_init() (and other functions where you normally would normally pass in a quoted text parameter would be ideal candidates for this.

What do you think?
