### ISSUE TITLE
About DTLS

### ISSUE THREAD

**Issue by louisZL** [obgm/libcoap#19]
Has libcoap provided the DTLS security for CoAP?

**Comment by obgm** [comment]
There is no official DTLS support (yet) but there is a lot of example code how to integrate openssl and tinydtls (e.g. https://sourceforge.net/p/libcoap/code/ci/dcaf/tree/). The next release will have at least support for tinydtls.

**Comment by arauko9** [comment]
Hello,
I'm very interested in the tinydtls support for libcoap. Is there a schedule or a date for the next release?
Sorry if this is not the place for this question, I'm new to github.
Thank you.

**Comment by obgm** [comment]
The right place to ask this sort of question would be the libcoap-developers mailing list. Anyway: I will push a topic branch for testing that has support for DTLS with pre-shared keys using tinydtls next week. I envision the 4.2 release when this branch is successfully merged and tested.

**Comment by obgm** [comment]
I am closing this as there is now a topic branch for testing DTLS integration. General feedback is solicited on the libcoap-developers mailing list, specific bugs may be opened here.
