### ISSUE TITLE
Junk resource token values in iterative communication btw coap -client and coap-server

### ISSUE THREAD

**Issue by NitinLnt** [obgm/libcoap#20]
I am working on a dynamic plugin of CoAP protocol in my application, Issue I am facing is first time response is ok but 2nd time it shows "4.04 Not Found" error because pdu at client side is having some junk values.
Kindly help
Regards,
Nitin

**Comment by obgm** [comment]
This happens when the Uri-Path contains junk values. The library cannot guess what URI you intend to request but just sees what you have actually requested. If that URI is unknown, you will get a 4.40 response.

**Comment by NitinLnt** [comment]
everything is same as before even resource, I am just iterating and getting error. What I should do if I don't want to terminate coap-client and want to make get requests simultaneously.
