### ISSUE TITLE
coap-client and -server on debian for test

### ISSUE THREAD

**Issue by drvrh** [obgm/libcoap#203]
I have a problem with running the coap-server and coap-client. 
I start the coap-server with a command:
`coap-server -A xxx.xxx.xxx.xxx. `

I start the coap-client for put with a command:
`echo on | coap-client -m put -T cafe coap://xxx.xxx.xxx.xxx/led -f - `

and for get with the command 
`coap-client -m get -T cafe coap://xxx.xxx.xxx.xxx/led `

For get and put I get a 4.04 not found. I am doing the testing on Debian with install from this repository: https://packages.debian.org/sid/libcoap-1-0-bin

Do I have to write resource in any of the files or can I just create them when I publish something on a new resource?

**Comment by obgm** [comment]
Does the output of `coap-client coap://xxx.xxx.xxx.xxx/.well-known/core` list the resource `led`?

(Side note: the trailing "-f -" in your PUT request will not be processed as all options must precede the request URI.)

**Comment by drvrh** [comment]
Output is: 
</>;title="General Info";ct=0,</time>;if="clock";rt="Ticks";title="Internal Clock";ct=0;obs,</async>;ct=0

How to add new resource as "led"?

**Comment by obgm** [comment]
The code in `examples/coap-server.c` illustrates how to add resources (note that this will change a bit in libcoap-2). Basically, you need to do register your resources with a CoAP context `ctx` as follows:

```c
  coap_resource_t *r;
  r = coap_resource_init((unsigned char *)"led", 3, 0);
  coap_register_handler(r, COAP_REQUEST_GET, hnd_get_led);
  coap_register_handler(r, COAP_REQUEST_PUT, hnd_put_led);
  coap_add_resource(ctx, r);
```

The callback functions given as third argument to `coap_register_handler()` are defined as:

```c
typedef void (*coap_method_handler_t)
  (coap_context_t  *,
   struct coap_resource_t *,
   const coap_endpoint_t *,
   coap_address_t *,
   coap_pdu_t *,
   str * /* token */,
   coap_pdu_t * /* response */);
```

**Comment by drvrh** [comment]
Tnx, for answer. I added new resource and handler, but now I have a problem with library: 

`coap-server: error while loading shared libraries: libcoap-2-gnutls.so.0: cannot open shared object file: No such file or directory
`

Where do I have to add an argument to give a new directory for libraries? My libraries are saved in /usr/local/lib?

Do I do it in Makefile under ‘’prefix’’ argument?

**Comment by mrdeep1** [comment]
Unfortunately gnutls support is not yet available  for libcoap.  When running ./configure , add in the command line option --without-gnutls to stop the set up process finding the TLS library gnutls and trying to add it in.

**Comment by drvrh** [comment]
I added the libraries with `export LD_LIBRARY_PATH=/usr/local/lib`.... but the resource ‘’led’’ still isn’t seen if I look at `.well-know/core`

I added like this:

In init_resource:

```
  /* add resource "led" */
  r = coap_resource_init(coap_make_str_const("led"), 0);
  coap_register_handler(r, COAP_REQUEST_GET, hnd_get_led);
  coap_add_resource(ctx, r);
```

And handler for led:

```
static void
hnd_get_led(coap_context_t  *ctx UNUSED_PARAM,
             struct coap_resource_t *resource,
             coap_session_t *session,
             coap_pdu_t *request,
             str *token,
             str *query,
             coap_pdu_t *response){

  unsigned char buf[3];
  response->code = COAP_RESPONSE_CODE(205);
  coap_add_option(response,
                  COAP_OPTION_CONTENT_TYPE,
                  coap_encode_var_safe(buf, sizeof(buf),
                                       COAP_MEDIATYPE_TEXT_PLAIN),
                  buf);
  coap_add_option(response,
                  COAP_OPTION_MAXAGE,
                  coap_encode_var_safe(buf, sizeof(buf), 0x2ffff), buf);
  coap_add_data(response, strlen(LED_RESPONSE), (const uint8_t *)LED_RESPONSE);
}
```
This resource is made for a test, so my resource acts similar to the INDEX.

**Comment by drvrh** [comment]
I found out that I called the coap-server, which I installed from the debian repository and not the server I compiled. thanks everyone

**Comment by obgm** [comment]
Closing as PR #225 is now upstream.
