### ISSUE TITLE
How to create a Contiki CoAP DTLS server?

### ISSUE THREAD

**Issue by arabine** [obgm/libcoap#206]
Hello,
Is there an example to create a DTLS server using tinyDTLS?
Do I need to create one CoAP context dedicated to DTLS port?

**Comment by obgm** [comment]
You can configure libcoap with `--with-tinydtls --disable-shared` (you will need the tinydtls submodule for this) and then  `examples/coap-server.c` acts as DTLS server with tinydtls.

**Comment by obgm** [comment]
Basically, you pass `COAP_PROTO_DTLS` as flag to `coap_new_endpoint()`. Depending on the cipher suites you are planning to use, you need to initialize the DTLS subsystem properly. For a start, you can call `coap_context_set_psk()` to set a default pre-shared key for symmetric crypto.

**Comment by mrdeep1** [comment]
If you take the latest develop branch, build and install it as per this thread (see file BUILDING) for TinyDTLS but include the building of man pages (disabled by --disable-documentation in the examples in BUILDING unfortunately).  Then look at the coap_context man page (`man coap_context`) and scroll through to the "CoAP Server DTLS PSK Setup" example which may help you also here for creating standalone code.

**Comment by arabine** [comment]
I do not use "configure" command since my server is an embedded target Contiki (sorry I should have explained that) with a proprietary UDP stack.

This server is working properly in clear text, based on the example located in contiki/server.c.

I have indeed replace the coap_nodtls.c by the coap_tinydtls.c, but as far as I can read the code, I don't see any endpoint dedicated to DTLS... and my coaps requests are failing.

All my attempts to create new endpoints are failing (app is crashing).

**Comment by arabine** [comment]
Ok, things are getting a bit better. I had only one endpoint structure created in my custom coap_io.c. I have modified it with a more generic version:

```
#ifndef COAP_MAX_ENDPOINTS
#define COAP_MAX_ENDPOINTS 2
#endif

static struct coap_endpoint_t ep_list[COAP_MAX_ENDPOINTS];
static int ep_index = 0;

struct coap_endpoint_t *
  coap_malloc_endpoint(void)
{
	struct coap_endpoint_t *ep = &ep_list[ep_index];
	ep_index++;

    return ep;
}
```
And now my endpoint interface in living, without success but with a better log:

```
Data ind callback event on port 5684
Send event to thread
Receive task event
CoapIO Network read
* [0000:0000:0000:0000:0000:0000:0000:0000]:0 <-> [0000:0000:0000:0000:0000:0000:0000:0000]:0 DTLS: received 15 bytes
dtls_handle_message: FOUND PEER
got packet 21 (15 bytes)
new packet arrived with seq_nr: 5
new bitfield is : 10
** Alert: level 2, description 0
0 invalidate peer
removed peer [::]:0
```
