### ISSUE TITLE
coap URL parse `host item`

### ISSUE THREAD

**Issue by ustccw** [obgm/libcoap#215]
Hi,
some unexpected `host` happened when call `coap_split_uri` function to parse a given string:
https://github.com/obgm/libcoap/blob/118bbebbbc0979f0bfbd432121216120cb9febde/src/uri.c#L53

my code like the following:
```
const char* server_url = "coap://192.168.111.104:5683/espressif";
if (coap_split_uri((const uint8_t *)server_url, strlen(server_url), &url) = -1) {
   return;
} 
// coap URL parse success
printf("host:%s\r\n", (const char *)uri.host.s);
printf("path:%s\r\n", (const char *)uri.path.s);
printf("port:%d\r\n", uri.port);
```
here always got the log like the following:  
```
host:192.168.111.104:5683/espressif
path:espressif
port:5683
```
what i expected the `host` is `192.168.111.104`, rather than `192.168.111.104:5683/espressif`.
and how can i get the actual hostame or IP address?

please help to confirm it is a problem.

**Comment by mrdeep1** [comment]
uri.host is defined as type coap_str_const_t which has a length and uint8_t*.  So, if you were to do instead

```
printf("host:%*.*s\r\n", (int)uri.host.length), (int)uri.host.length), (const char *)uri.host.s);
printf("path:%*.*s\r\n", (int)uri.path.length), (int)uri.path.length), (const char *)uri.path.s);
printf("port:%d\r\n", uri.port);
```

you would get what you expected.

**Comment by ustccw** [comment]
wow! it works. 
thanks for your quick reply.
