### ISSUE TITLE
Observing multiple resources in parallel using coap-client fails (when # resources > 6?)

### ISSUE THREAD

**Issue by vdaele** [obgm/libcoap#216]
Apparently, there seem to be limits when observing multiple resources in parallel.

I tried the following command where I start observing the (same) Ikea Tradfri bulb N times by starting coap-client in a background process (I'm on Linux) using different ports  
(The same behavior is also observed when observing different bulbs)

```
for p in {2340..2347}; do coap-client -u <user> -k <key> -v 0 -s 90 -p $p -m get coaps://192.168.1.2:5684/15001/65539&  done
```

Afterwards, I toggle the bulb using the remote control and I would expect to get N notifications.

This goes well up to 6 parallel observes.  
However, when starting coap-client 8 (or 11 or ...) times, I also only get 6 repsonses.

Is this a limitation of coap-client? libcoap? The Ikea hub? My test-code?

Kind Regards,

Marc

**Comment by vdaele** [comment]
Additional observation: if I manually enter the following command multiple times (leaving enough time to get the initial response before starting the next one)

```
coap-client -u <user> -k <key> -v 0 -s 90 -m get coaps://192.168.1.2:5684/15001/65539&
```
All goes well as long as the number of simultaneous clients is <= 10.
When I create > 10 clients, I only get 10 notifications when I toggle the bulb.

**Comment by mrdeep1** [comment]
I think that there are 2 separate limits you are hitting here.

1) Max number of concurrent resources (10).  On the server, there is likely to be a limit of the number of Observers (or could be called Subscribers) as each Observer requires additional memory - which is likely to be limited in your bulb.  For example, the Contiki code has a default limit of 2 or 3 depending on the type of build.

2) Rapid transmission only getting 6 responses.  My suspicion is that there is a maximum UDP input queue in the bulb of either 6 packets, or size limit of 6 * size of UDP request packet.

**Comment by vdaele** [comment]
Thanks for the (quite likely) explanation!
