### ISSUE TITLE
tinydtls dtls-client and dtls server not doing handshaking

### ISSUE THREAD

**Issue by NitinLnt** [obgm/libcoap#22]
Hi,
          I am trying to communicate between tinydtls dtls-client and dtls server but handshake itself is not happeniing.
I am getting this error
Jan 15 19:40:56 ALRT setsockopt IPV6_PKTINFO: Protocol not available
please guide

**Comment by obgm** [comment]
This is the libcoap, issue tracker, not tinydtls.
But the error you get says everything you need to know: Your system does not support IPv6.
