### ISSUE TITLE
Future plans of adding Object Security?

### ISSUE THREAD

**Issue by vikram919** [obgm/libcoap#222]
The ietf draft [OSCoRE](https://tools.ietf.org/html/draft-ietf-core-object-security-13) is a light weight application layer security  of CoAP, are there any plans in near future of adding object security to libcoap?

**Comment by obgm** [comment]
Most likely, yes. But since oscore is application layer, you can start implementing it right away on top of libcoap.

**Comment by vikram919** [comment]
I would like to make an initial PR excluding observe and blockwise transfer? what do you say?

**Comment by obgm** [comment]
This would be great. Which COSE library do you intend to use?

**Comment by vikram919** [comment]
> Which COSE library do you intend to use?

[COSE-C](https://github.com/cose-wg/COSE-C)

**Comment by mp3patel19** [comment]
hi @vikram919  were you successful in implementing OSCORE in you application?

**Comment by obgm** [comment]
An OSCORE implementation for libcoap [has been contributed](https://gitlab.informatik.uni-bremen.de/obergman/libcoap/-/tree/oscore) by Peter van der Stok and is waiting for review/integration.

**Comment by mp3patel19** [comment]
HI, I am trying to run this https://gitlab.informatik.uni-bremen.de/obergman/libcoap/-/tree/oscore project to check OSCORE packets. However, I am not able to run examples<peter_oscore<coap_client.c properly. There are plenty of errors. Could you guide me how to run that project.
