### ISSUE TITLE
How to receive DTLS errors in client.c

### ISSUE THREAD

**Issue by vdaele** [obgm/libcoap#227]
When doing the following request (with an invalid key)

```
coap-client -u 5d9494c37f5d4f51bf981109529f76d -k aaaa -v 9 -m get coaps://192.168.1.2:5684/15001
```
I see in the logs

```
Jul 24 20:59:39 INFO ** Alert: level 2, description 20
Jul 24 20:59:39 ALRT 20 invalidate peer
Jul 24 20:59:39 DEBG *** removed transaction 16195
Jul 24 20:59:39 DEBG *** EVENT: 0x0200
Jul 24 20:59:39 DEBG *** removed session 0x1bb8f90
Jul 24 20:59:39 WARN received alert, peer has been invalidated
```

but I don't seem to get these errors in coap-client (client.c) itself.  Is that correct?
What is the best way to receive these (dtls?) kind of errors in client.c?

Thanks for your input,

Marc

**Comment by obgm** [comment]
Hm, I was almost sure that there is a PR to pass these errors to the application but I cannot find it. We would need to enhance the API accordingly if we wanted to pass these events to the user. Currently, you would have to deal with the underlying TLS library directly which is obviously not a good idea.

**Comment by obgm** [comment]
Following up on this: You can set an event handler in your application using `coap_set_event_handler()` but currently, the error reporting is nil (or close to nil). PR #183 starts delivering DTLS errors via `coap_handle_event()`.

**Comment by vdaele** [comment]
Thanks!  I've switched now to the latest version of the develop branch!
