### ISSUE TITLE
can't get lwip example to build?

### ISSUE THREAD

**Issue by Lotterleben** [obgm/libcoap#23]
Hi,
this is probably just my brain being foggy, but... For some reason I can't get examples/lwip/ to build. When I run make as instructed on the default branch (develop), I get:

    λ (/home/lotte/riot/libcoa/exampl/lwip) (develop)
    $ make server CC=gcc
    gcc -I. -I- -std=gnu99 -I../../include/coap -g3 -Wall -pedantic -Dopenbsd -DIPv4 -O0 -fpack-struct -Ilwip/src/include/ -Ilwip/src/include/ipv4/ -Ilwip-contrib/ports/unix/include/ -Ilwip-contrib/ports/unix/proj/minimal/   -c -o server.o server.c
    cc1: note: obsolete option -I- used, please use -iquote instead
    server.c:37:23: fatal error: lwip/init.h: No such file or directory
     #include <lwip/init.h>
                           ^
    compilation terminated.
    make: *** [server.o] Error 1

If I replace `-I-` with `-iquote` in the Makefile, I get:

    λ (/home/lotte/riot/libcoa/exampl/lwip) (develop)
    $ make
    cc -I. -iquote -std=gnu99 -I../../include/coap -g3 -Wall -pedantic -Dopenbsd -DIPv4 -O0 -fpack-struct -Ilwip/src/include/ -Ilwip/src/include/ipv4/ -Ilwip-contrib/ports/unix/include/ -Ilwip-contrib/ports/unix/proj/minimal/   -c -o server.o server.c
    server.c:37:23: fatal error: lwip/init.h: No such file or directory
     #include <lwip/init.h>
                           ^
    compilation terminated.
    make: *** [server.o] Error 1

When I switch to the master branch, I directly get to the second error message.
Am I missing something? Is this example still up to date? (All I’m looking for is a CoAP command line client, really)

**Comment by obgm** [comment]
You need to do `make lwip` in the `examples/lwip` folder first.
Unfortunately, that particular step seems broken in lwip:

```
$ make
cc -I. -iquote -std=gnu99 -I../../include/coap -g3 -Wall -pedantic -Dopenbsd -DIPv4 -O0 -fpack-struct -Ilwip/src/include/ -Ilwip/src/include/ipv4/ -Ilwip-contrib/ports/unix/include/ -Ilwip-contrib/ports/unix/proj/minimal/   -c -o server.o server.c
In file included from lwip/src/include/lwip/debug.h:35:0,
                 from lwip/src/include/lwip/opt.h:46,
                 from lwip/src/include/lwip/init.h:35,
                 from server.c:37:
lwip/src/include/lwip/arch.h:43:21: fatal error: arch/cc.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'server.o' failed
make: *** [server.o] Error 1
$ find lwip -name cc.h
$
```

**Comment by obgm** [comment]
Now, if all you need is a command-line client, why bother with the lwip build, anyway? Just configure libcoap with `--with-examples` and use `coap-client` from the examples folder. Or, install libcoap from the experimental apt-tree, if you happen to use Debian.

**Comment by Lotterleben** [comment]
Simple: Because I didn’t know that was possible ;) I tried it on both branches and got different flavours of `configure: WARNING: unrecognized options: --with-examples`, *but* it seems to build on master anyway :) Thanks!

**Comment by obgm** [comment]
I recommend using the develop branch and build like this:

```
./autogen.sh
./configure --enable-examples
```

**Comment by obgm** [comment]
Finally, the lwip example builds again :-)
