### ISSUE TITLE
About Max-Age option

### ISSUE THREAD

**Issue by hongnguyen-tma** [obgm/libcoap#234]
Hi All
Regarding to Max-age option and its usage, my understanding is as below.

+ Coap-server always responses with the same value for Max-Age option for the same kind of request (if the option is not set, it is default to be 60 seconds ) 
 + Coap-client caches response at its local, and use that response instead of requesting to server, as long as that response is still fresh (age < max-age).  It is the coap-client that has to implement the caching mechanism, checking expiry and sending refresh GET (libcoap does not provide these functions)

I'm not sure if it is correct or not.  Please share with me your understanding, thanks

**Comment by obgm** [comment]
Your understanding is almost correct. The origin server is not required to respond with the same resource representation within this time. A caching proxy usually would, though.

The client might cache a response locally as you have described. But it also does not have to (and libcoap's example client does not).

**Comment by hongnguyen-tma** [comment]
@obgm 
Thanks for your response. I got your idea.
