### ISSUE TITLE
Release version of libcoap-2?

### ISSUE THREAD

**Issue by samkumar** [obgm/libcoap#243]
I am looking for a release of libcoap to use for a project. However, all releases that I could find (on this page: https://github.com/obgm/libcoap/releases) were for libcoap-1.

In contrast, if I build the latest version in the develop branch, I get libcoap-2. Some examples, such as https://github.com/obgm/libcoap-minimal, require libcoap-2.

Is libcoap-2 ready for general use? If so, which version should I use? I'm looking for a stable release version, if possible. (Or should I use a release of libcoap-1 instead?)

**Comment by mrdeep1** [comment]
The develop branch is stable, and is expected to be released soon.  See https://sourceforge.net/p/libcoap/mailman/message/36346758/ - last update on 6th August 2018.

**Comment by samkumar** [comment]
@mrdeep1 Thanks for pointing me to the message board. It clarifies a lot. I will use the develop branch, and may upgrade to the new release when it happens.
