### ISSUE TITLE
sending a coap request to an unreachable server: missing notification?

### ISSUE THREAD

**Issue by vdaele** [obgm/libcoap#249]
As a test case, I want to send a coap request to an unreachable server.  
Precondition: my coap client app is started up correctly and I've been able to toggle the (Ikea) light on and off a few times.
Next, I unplug the network cable from the Ikea hub and try to toggle the light again.  
I notice that the packet is retransmitted 4 times (as expected I guess) and afterwards, I see in the logs `tid=44815: give up after 4 attempts`

However, there seems to be no notification/callback to the coap-client, right?
What would be the best way to get this information ? an extra call to coap_handle_event where the "give up" mesage is logged?  

Edit: I just noted that the comment before `coap_event_t` states 

> Scalar type to represent different events, e.g. DTLS events or retransmission timeouts

Thanks in advance,

Marc

**Comment by vdaele** [comment]
And on a similar note: If I send a request to a server using an old/wrong IP address, I see multiple times in the logs `retransmit handshake packet` and after 7 retries I see `removed transaction` from within `dtls_retransmit`.
However, I don't seem to get an error/notification in my client.

I do note a number of lines containing `DTLS_ALERT_HANDSHAKE_FAILURE` in the code.  Would it be sufficient to add a statement like `CALL(context, event, &node->peer->session, DTLS_ALERT_LEVEL_FATAL, DTLS_ALERT_HANDSHAKE_FAILURE)` right before the `remove transaction` logline in dtls.c?

**Comment by mrdeep1** [comment]
Do you have a NACK handler defined by coap_register_nack_handler()?  For confirmable messages, I would expect this to be getting called in your first case, otherwise in all cases for your second case.

**Comment by vdaele** [comment]
I don't have this handler defined (and I noticed some other handlers that might me interesting as well!).
I'll try adding one and update this issue accordingly!
Thanks!

**Comment by mrdeep1** [comment]
In your first case, encryption has been set up and then you drop the traffic.  In the second case, encryption has not been agreed between client and server - so a NACK is not so appropriate here.

Tinydtls is a separate project - libcoap is just using it for one of the DTLS type options, and so changes in the tinydtls code will not be integrated into libcoap.  The only possibility is changes to src/coap_tinydtls.c - the glue between libcoap and tinydtls.

The coap-client is setting a global timeout of 90 seconds - which when expired closes the session and triggers the NACK.

With `DTLS_DEFAULT_MAX_RETRANSMIT 7`, the 90 second timeout expires before the re-transmit count expires.  With `DTLS_DEFAULT_MAX_RETRANSMIT 3`, the re-transmits timeout before the global 90 second timeout.

PR #183 has many event/nack fixes, and it looks like this may already fix the issue you are highlighting.

**Comment by vdaele** [comment]
Is it correct that this PR #183 is not yet merged to the develop branch (I'm no git expert at all)?  If so, when do you expect that this merge will happen? I certainly prefer using your lib to modifying coap_tinydtls.c myself.

**Comment by mrdeep1** [comment]
Yes we are waiting on PR #183 to get merged in.  In terms of when, not sure, but would expect it to be soon. based on https://sourceforge.net/p/libcoap/mailman/message/36346758/ last update.

**Comment by obgm** [comment]
As PR #183 has been merged, can you check if this has solved this issue?

**Comment by vdaele** [comment]
Current status with the latest 4.2.0 prerelease:

- when disconnecting the hub and using CON messages, the nack_handler gets called ("give up after 4 attempts") after about 1'20" with reason=COAP_NACK_TOO_MANY_RETRIES.   
  - I can get a faster notification I guess by reducing COAP_DEFAULT_MAX_RETRANSMIT in coap_session.h to eg 1 or 2?
- when disconnecting the hub and using NON messages, no handlers seems to get called, right?  
  - Is there some way to detect this?  Can you somehow detect that the remote peer closed the socket? 
- when trying to connect to an invalid hub, the nack_handler gets called immediately with reason=COAP_NACK_TLS_FAILED

**Comment by mrdeep1** [comment]
1. Instead of changing COAP_DEFAULT_MAX_RETRANSMIT, use coap_session_set_max_retransmit() instead to define the local value.  See the coap_recovery(3) man page.
2. Correct - UDP is unreliable, and the use of NON does not guarantee any response, so libcoap will not generate any failure events.  However, the CoAP Ping is designed for this purpose of testing out link connectivity by sending an Empty Confirmable Message - see RFC7252 4.3.  Messages Transmitted without Reliability.
3. This is likely down to a the fact that the local device is unable to transmit the packet to the non existent address (as no arp entry could be created to send the packet to).

**Comment by vdaele** [comment]
Thanks a lot for your input (again!)

Marc
