### ISSUE TITLE
Does libcap support request to an broadcast?

### ISSUE THREAD

**Issue by auxor** [obgm/libcoap#250]
I use the coap-client post an request to an broadcast 192.168.1.255. It show "Permission denied". If the permission is fixed, can libcap handle more than one responses from the request to an broadcast address. 
In an local lan, there are more than one server handle the request to an broadcast address.

coap-client -m post -N -e '{xxxx}' coap://192.168.1.255/xxx/searchgw
v:1 t:NON c:POST i:1e66 {} [ ]
Aug 27 16:53:20 CRIT coap_send_impl: Permission denied

**Comment by mrdeep1** [comment]
No is the simple answer.  It does support multicast requests IF the server is enabled to support this.  See "RFC7252 8.  Multicast CoAP" for further information.  coap-server does support this if the -g option is defined.

You are however not using the latest code.

**Comment by auxor** [comment]
@mrdeep1 Thanks for you reply
