### ISSUE TITLE
How to use check_cert_revocation in the right way?

### ISSUE THREAD

**Issue by tamnguyen-tma** [obgm/libcoap#251]
Hi All,

May I ask some questions?
I don't understand clearly what is the purpose when set option check_cert_revocation=1? Do these check_cert_revocation, allow_no_crl, allow_expired_crl options effect with each other?

I configured for coap_dtls_pki same as the example as below:

  _if (ca_file) {
        dtls_pki.verify_peer_cert        = 1;
        dtls_pki.require_peer_cert       = 1;
        dtls_pki.allow_self_signed       = 1;
        dtls_pki.allow_expired_certs     = 1;
        dtls_pki.cert_chain_validation   = 1;
        dtls_pki.cert_chain_verify_depth = 2;
        dtls_pki.check_cert_revocation   = 1;
        dtls_pki.allow_no_crl            = 1;
        dtls_pki.allow_expired_crl       = 1;
        dtls_pki.validate_cn_call_back   = verify_cn_callback;
        dtls_pki.cn_call_back_arg        = NULL;
        dtls_pki.validate_sni_call_back  = NULL;
        dtls_pki.sni_call_back_arg       = NULL;
  }
  dtls_pki.pki_key.key_type = COAP_PKI_KEY_PEM;
  dtls_pki.pki_key.key.pem.public_cert = cert_file;
  dtls_pki.pki_key.key.pem.private_key = cert_file;
  dtls_pki.pki_key.key.pem.ca_file = ca_file;_

However, I got an error when my program run on function: SSL_connect(ssl). More specific, this error occur from openssl when it get crl (get_crl_delta()) to check_cert_revocation because have no any crl. If the option check_cert_revocation isn't set or set to 0, the problem won't happen. So, should I add crl(s) in somewhere or do something to fix it?

Warn log:
Aug 28 15:41:00 WARN     127.0.0.1:55013 <-> 127.0.0.1:4646 DTLS: unable to get certificate CRL: overridden: 'client.sample.example.com' depth=0

Thanks
Tam Nguyen

**Comment by mrdeep1** [comment]
Hi Tam,

When `dtls_pki.check_cert_revocation = 1`, then OpenSSL is told to CRL check the certificate.

If the certificate does not have a CRL this is deemed to be failure unless `dtls_pki.allow_no_crl = 1`, in which case the "No CLR" failure is overridden and the certificate is allowed through this check.
If the certificate does have a CRL, but it has expired, this can be overridden with `dtls_pki.allow_expired_crl = 1`.

So, your overridden message is saying that your certificate is being treated as valid, despite CRL checking enabled, but there is no CRL.

Is TLS not establishing?

**Comment by tamnguyen-tma** [comment]
Hi mrdeep1,
Thanks for replying me.

I'm using DTLS.
Actually, DTLS is established successfully.

 _Aug 28 17:36:43 DEBG *** 127.0.0.1:43480 <-> 127.0.0.1:4646 DTLS: session connected_ 

However, when client send a request message to server, the request isn't accepted because server can't get client certificate from session (SSL_get_peer_certificate(session->tls)). 
So, I think the problem is that the client certificate isn't verified successfully although session connected. Is it right?

Thanks,
Tam Nguyen

**Comment by mrdeep1** [comment]
Hi Tam,

Interesting.  I think that this is telling me that the client did not present a certificate - as if you are using pre-shared keys, not certificates.  Certainly with `dtls_pki.require_peer_cert = 1`, the client should be presenting a certificate else there will a permanent error (DTLS Fatal Alert generated).  This assumes that you are actually defining  ca_file, so you are going through the appropriate setup code

If the Certificate did not verify, then the server will terminate the DTLS session with a Fatal Alert.

SSL_get_peer_certificate(session->tls) certainly works for me when handling a CoAP event for event COAP_EVENT_DTLS_CONNECTED.

**Comment by mrdeep1** [comment]
Another thought.  OpenSSL 1.1.1 is not supported until PR #242 is merged in, so you need a 1.1.0 variant for this to work.
Another thought. SSL_get_peer_certificate() will only work once the (D)TLS session has fully connected - not while the Client and Server Hellos are still getting negotiated.

**Comment by tamnguyen-tma** [comment]
Hi mrdeep1,
Thanks for replying me.

Actually, for testing, my certificate is created by using gnutls-certtool that generates all my ca-files (server/client-key.pem, server/client-pub.pem, ca-cert.pem, crl.pem). However, currently, I use my crl.pem in nowhere because the setupData (coap_dtls_pki_t) use for creating ContextDTLS only need three ca-files(s/c-key.pem, s/c-pub.pem, ca-cert.pem).

Therefore, is there any problems about my setup data or contextDtls? Are these ca-file certificate?
I'm using openssl ver.1.1.0, so I don't think the problems is here.

Thanks,
Tam Nguyen

**Comment by mrdeep1** [comment]
With dtls_pki.check_cert_revocation = 0, do you have any issues with requests / responses not working?
If so, then that issue needs to be resolved first to remove any confusion when troubleshooting CRLs.

If there is a CRL URI in client.sample.example.com certificate - then OpenSSL will go and try to retrieve the specified CRL from that URI - which usually will be hosted somewhere external to your actual server.

From (which I assume was in the server logs)
`Aug 28 15:41:00 WARN 127.0.0.1:55013 <-> 127.0.0.1:4646 DTLS: unable to get certificate CRL: overridden: 'client.sample.example.com' depth=0`

`unable to get certificate CRL`
OpenSSL is unable to download the CRL
`overridden`
This error has been ignored(overridden)
`client.sample.example.com`
The actual Subject Name of theCertificate
`depth = 0`
This is the certificate, (CA would be 1 or higher depending on the CA certification path).

All this checking work is done in tls_verify_call_back(() in src/coap_openssl.c

**Comment by mrdeep1** [comment]
Did you get to the bottom of this issue?
I stumbled into something similar today (Client Certificate could not be found) when the libcoap code was built against OpenSSL 1.1.1, but PR #242 was not in the libcoap code.
