### ISSUE TITLE
Website SSL certificate is expired

### ISSUE THREAD

**Issue by tonnenpinguin** [obgm/libcoap#253]
This is probably not the place to report this, but I couldn't find any other contact details:

The libcoap.net certificate expired a few days ago (Tuesday, August 28, 2018 at 1:04:55 PM).
Any chance one of the admins reads this and could update to a new cert?
Thanks!

**Comment by obgm** [comment]
Yes, and the renewal process turned out to really suck. Thus, I will move to LE.

**Comment by obgm** [comment]
Done. Once the DNS caches have been updated, you should see a fresh certificate.

**Comment by tonnenpinguin** [comment]
Perfect, thanks!
