### ISSUE TITLE
coap-rd: update process fails

### ISSUE THREAD

**Issue by haukepetersen** [obgm/libcoap#254]
In the process of implementing a CoRE resource directory client library in RIOT (https://github.com/RIOT-OS/RIOT/pull/7428), it seems like I stumbled upon a bug in `libcoap`'s rd server. While the initial registration seems to work correctly (location path `rd/302b-6ddd0`), the rd returns a 4.05 error when trying to update the created entry (POST to uri-path `rd/302b-6ddd0`).

I am not 100% sure if my client does everything correct regarding the current resource directory draft, so it might as well a bug on my side. But since i recently verified the RIOT library working successfully with the `aiocoap` rd implementation, it points a little bit in the direction of `libcoap`?! 

Attached a wireshark dump showing my latest attempt:
![riot_coap-rd_updatefail](https://user-images.githubusercontent.com/620834/45497482-36e90700-b778-11e8-8892-d3c1740e3115.png)

[riot_coap-rd_updatefail.pcapng.zip](https://github.com/obgm/libcoap/files/2379900/riot_coap-rd_updatefail.pcapng.zip)

This should be the corresponding `libcoap` debug output:
```
Sep 13 16:56:40 DEBG *  [fe80::34ba:60ff:fe79:a604]:5683 <-> [fe80::34ba:60ff:fe79:a605]:5683 (if4) UDP: received 34 bytes
v:1 t:CON c:GET i:302a {449e} [ Uri-Path:.well-known, Uri-Path:core, Uri-Query:rt=core.rd ]
Sep 13 16:56:40 INFO create default response for .well-known/core
Sep 13 16:56:40 DEBG get_wkc_len: coap_print_wellknown() returned 38
Sep 13 16:56:40 DEBG *  [fe80::34ba:60ff:fe79:a604]:5683 <-> [fe80::34ba:60ff:fe79:a605]:5683 (if4) UDP: sent 47 bytes
v:1 t:ACK c:2.05 i:302a {449e} [ Content-Format:application/link-format ] :: '</rd>;ins="default";rt="core.rd";ct=40'
Sep 13 16:56:40 DEBG *  [fe80::34ba:60ff:fe79:a604]:5683 <-> [fe80::34ba:60ff:fe79:a605]:5683 (if4) UDP: received 83 bytes
v:1 t:CON c:POST i:302b {026a} [ Uri-Path:rd, Content-Format:application/link-format, Uri-Query:ep=RIOT-4527232323232323, Uri-Query:lt=60 ] :: '</node/info>,</sense/hum>,</sense/temp>'
Sep 13 16:56:40 DEBG call custom handler for resource 'rd'
Sep 13 16:56:40 DEBG *  [fe80::34ba:60ff:fe79:a604]:5683 <-> [fe80::34ba:60ff:fe79:a605]:5683 (if4) UDP: sent 20 bytes
v:1 t:ACK c:2.01 i:302b {026a} [ Location-Path:rd, Location-Path:302b-6ddd0 ]
Sep 13 16:56:49 DEBG *  [fe80::34ba:60ff:fe79:a604]:5683 <-> [fe80::34ba:60ff:fe79:a605]:5683 (if4) UDP: received 20 bytes
v:1 t:CON c:POST i:302c {2d86} [ Uri-Path:rd, Uri-Path:302b-6ddd0 ]
Sep 13 16:56:49 DEBG *  [fe80::34ba:60ff:fe79:a604]:5683 <-> [fe80::34ba:60ff:fe79:a605]:5683 (if4) UDP: sent 25 bytes
v:1 t:ACK c:4.05 i:302c {2d86} [ ] :: 'Method Not Allowed'
```

**Comment by mrdeep1** [comment]
The initial POST is used to create the resource (rd/302b-6ddd0) but this new resource only supports the GET, PUT and DELETE methods.  There is not a POST method - no idea as to why it is not included.

Line 459-464 of examples/coap-rd.c
````
  resource_val.s = loc;
  resource_val.length = loc_size;
  r = coap_resource_init(&resource_val, COAP_RESOURCE_FLAGS_RELEASE_URI);
  coap_register_handler(r, COAP_REQUEST_GET, hnd_get_resource);
  coap_register_handler(r, COAP_REQUEST_PUT, hnd_put_resource);
  coap_register_handler(r, COAP_REQUEST_DELETE, hnd_delete_resource);
````
but then the hnd_put_resource() code is not complete and always returns 5.01.

So, yes, your issue is that the coap-rd example (and it is really only a starting example) needs updating / fixing.

**Comment by haukepetersen** [comment]
So if it is simply the implementation of the update process as defined in Apendix A1 (https://tools.ietf.org/html/draft-ietf-core-resource-directory-14#appendix-A.1), this issue is for now solved for me (in that I am happy that it is not my client implementation doing something wrong...). Feel free to close it.
