### ISSUE TITLE
Question about ping/pong messages

### ISSUE THREAD

**Issue by vdaele** [obgm/libcoap#264]
I have a question: I want to send ping messages to check whether the connection to the server is still alive. I tried the code below (with corresponding handlers that just print a line when triggered) but that doesn't seem to be sufficient.  

```
    coap_context_set_keepalive(ctx, 5);
    coap_register_ping_handler(ctx, ping_handler_static);
    coap_register_pong_handler(ctx, pong_handler_static);
```

Do I have to send the ping messages myself? 
Should I somehow indicate that my session is reliable (I'm using UDP/DTLS)?

Thanks in advance,

Marc

**Comment by mrdeep1** [comment]
As per the documentation for  coap_context_set_keepalive(), this (currently) is only for reliable protocols - e.g. TCP /TLS. (ping/pong handlers you have defined are for TCP/TLS only as well)
````
* Set the context keepalive timer for sessions.
 * A keepalive message will be sent after if a session has been inactive,
 * i.e. no packet sent or received, for the given number of seconds.
 * For reliable protocols, a PING message will be sent. If a PONG has not
 * been received before the next PING is due to be sent, the session will
 * considered as disconnected.
````
As stated in Point 2 of my response in #249,
```` 
Correct - UDP is unreliable, and the use of NON does not guarantee any response, so libcoap will not generate any failure events. However, the CoAP Ping is designed for this purpose of testing out link connectivity by sending an Empty Confirmable Message - see RFC7252 4.3. Messages Transmitted without Reliability.
````
you need to manually send Empty Confirmable Messages (which act like a Ping) and they generate a RST response which you will detect in your Nack handler.

**Comment by vdaele** [comment]
Just to be sure that I understand it correctly:
I send eg every 5 seconds something like

```
        coap_pdu_t *ping = coap_pdu_init(COAP_MESSAGE_CON, COAP_SIGNALING_PING, 0, 1);
        coap_send(session, ping);
```

which will result in a nack_handler(reason=COAP_NACK_RST) (which is expected behavior) if the hub is still connected and which will result in a nack_handler(reason=COAP_NACK_TOO_MANY_RETRIES) when there is no connection anymore. Right?

**Comment by mrdeep1** [comment]
NO, you have to use (where tid is is unique per request, so you can detect which response you are working with).  COAP_SIGNALING_PING is only for TCP/TLS.
````
ping = coap_pdu_init(COAP_MESSAGE_CON, 0, tid, 0);
````
Otherwise, I believe you are right with the nack_handler.  It should be noted that the CON request is subject to all the repeat / retry timers.

**Comment by pegahnikbakht** [comment]
@mrdeep1  there is no way to keep a session alive in coap over DTLS? 

Thanks in advance.

**Comment by mrdeep1** [comment]
coap_context_set_keepalive() was updated to include DTLS - see https://github.com/obgm/libcoap/pull/376 .

**Comment by mrdeep1** [comment]
@vdaele @pegahnikbakht Can this be closed off now?

**Comment by vdaele** [comment]
Yes!
