### ISSUE TITLE
Support for multiple PSK

### ISSUE THREAD

**Issue by orienz** [obgm/libcoap#266]
Hello,

Is it possible to get the server running with support for multiple identities/keys? This is a very nice feature where a server side can assign specific keys to different users and be able to revoke them (remove).

A quick glance at coap context struct hints that this was not planned.

Thank you!

**Comment by orienz** [comment]
Sorry I overlooked get_server_psk callback in coap_context_t struct. Tested and it works perfect.

Another question that pops is.. once I get server running, how can I get client's DTLS identity in the method handlers? Tried psk_identity in coap_session_t but it's NULL.

Thanks!

**Comment by mrdeep1** [comment]
@orienz If you are providing your own version of coap_get_context_server_psk() to do the validation of identity, if you are accepting the identity and returning the PSK to use, there is no reason why you cannot update psk_identity in coap_session_t at this point.  You will need to coap_malloc() - see coap_new_client_session_psk() for what needs to be done as an example for the identity.  The psk_identity will then be available to any part of your application by referring to the appropriate coap_session_t.

**Comment by orienz** [comment]
Hi guys,
Thanks for your answers. 

@mrdeep1, that would probably work but session in this callback is declared as const. Prototype looks like: size_t(*get_server_psk)(const coap_session_t *session, const uint8_t *identity, size_t identity_len, uint8_t *psk, size_t max_psk_len);

Maybe the good place to copy identity to session would be just after calling get_server_psk callback in coap_tinydtls|openssl.c get_psk_info() function? I am using tinydtls right now.

Thanks!

**Comment by mrdeep1** [comment]
@orienz Does #335 help you here with the new API?

**Comment by orienz** [comment]
I will have to dig deeper into this but I don't think they help. These are mostly callbacks. I would need to identify the specific request so I know what identity the request is coming from.

You probably have your ideas how to use this, can you share them?

Thanks

**Comment by mrdeep1** [comment]
It has to be assumed that on detection of the client's identity (From the Client Hello packet), the server will need to use the correct PSK information to be able to continue with the encryption setup.

By setting `validate_id_call_back `in the new api PSK setup, the callback function will be presented with the identity (user) as provided in the Client Hello packet.  This callback function then returns with the correct PSK to use for the ongoing encryption setup.

The new coap_encryption man page (with the SNI support removed) has the following (if that helps)

````
       CoAP Server DTLS PSK Setup

           #include <coap2/coap.h>

           typedef struct id_def_t {
             char* id;
             coap_dtls_spsk_key_t key;
           } id_def_t;

           typedef struct valid_ids_t {
             int count;
             id_def_t *id_list;
           } valid_ids_t;

           /*
            * PSK Identity PSK selection Callback function
            */
           static coap_dtls_spsk_key_t *
           verify_id_callback(coap_bin_const_t *identity,
                              coap_session_t *session,
                              void *arg
           ) {
             valid_ids_t *valid_id_list = ( valid_ids_t*)arg;
             int i;

             /* Check that the Identity is valid */
             for (i = 0; i < valid_id_list->count; i++) {
               if (!strcasecmp((const char*)identity->s, valid_id_list->id_list[i].id)) {
                 return &valid_id_list->id_list[i].key;
               }
             }
             return NULL;
           }

           static coap_context_t *
           setup_server_context_psk (const char *hint,
                                     const uint8_t *key,
                                     unsigned key_len,
                                     valid_ids_t *valid_id_list,
           ) {
             coap_endpoint_t *endpoint;
             coap_address_t listen_addr;
             coap_context_t *context;
             coap_dtls_spsk_t dtls_psk;

             /* See coap_tls_library(3) */
             if (!coap_dtls_is_supported())
               return NULL;

             context = coap_new_context(NULL);
             if (!context)
               return NULL;

             memset (&dtls_psk, 0, sizeof (dtls_psk));

             /* see coap_encryption(3) */
             dtls_psk.version                 = COAP_DTLS_SVR_PSK_SETUP_VERSION;
             dtls_psk.validate_id_call_back   = verify_id_callback;
             dtls_psk.id_call_back_arg        = valid_id_list;
             dtls_psk.validate_sni_call_back  = NULL;
             dtls_psk.sni_call_back_arg       = NULL;
             dtls_psk.psk_key.hint            = (const uint8_t*)hint;
             dtls_psk.psk_key.hint_len        = hint ? strlen(hint) : 0;
             dtls_psk.psk_key.key             = key;
             dtls_psk.psk_key.key_len         = key_len;

             if (coap_context_set_psk2(context, &dtls_psk)) {
               coap_free_context(context);
               return NULL;
             }

             coap_address_init(&listen_addr);
             listen_addr.addr.sa.sa_family = AF_INET;
             listen_addr.addr.sin.sin_port = htons (5684);

             endpoint = coap_new_endpoint(context, &listen_addr, COAP_PROTO_DTLS);
             if (!endpoint) {
               coap_free_context(context);
               return NULL;
             }

             /* See coap_resource(3) */
             init_resources(context);

             return context;
           }
````

**Comment by mrdeep1** [comment]
@orienz Now that #335 is in the develop branch, does this help you at all?
In particular, psk_identity is provided in coap_session_t (see include/coap2/coap_session.h).

**Comment by mrdeep1** [comment]
@orienz Can this be closed off now?

**Comment by obgm** [comment]
Closed off as this functionality now is available for quite some time.
