### ISSUE TITLE
libcoap.net not loading in Chrome & Firefox

### ISSUE THREAD

**Issue by beriberikix** [obgm/libcoap#272]
When visiting the the latest https://libcoap.net in Chrome Latest (70.0.3538.102,) I see, "This page isn’t working; libcoap.net didn’t send any data.; ERR_EMPTY_RESPONSE." Visiting in Firefox I see a more helpful error saying, "Secure connection failed." Oddly enough, it loads in Safari.

I think this is related to the SSL certificate. Personally I use https://letsencrypt.org/, which is free and is used by many open source projects.

**Comment by obgm** [comment]
Thanks for bringing this to my attention. The certificate should be ok now (I have indeed missed to make the web server reload the LE certificate after update), and the server is also listening on port 443 on its IPv6 address which it did not for some reason.

However, the issue remains the same. Testing with openssl, I can see that TLS1.3 communication fails, TLS1.2 seems to work so far.

**Comment by mrdeep1** [comment]
It still is not working for me.  Using an older Chrome browser, it implies that Chrome etc. are rejecting the "Let's Encrypt Authority X3" information as per

![image](https://user-images.githubusercontent.com/35105050/48771575-a8ce5700-ecb9-11e8-87bf-80b8d6c90ffd.png)

**Comment by Rotzbua** [comment]
FF63 and FF60ESR can not connect. Both try to connect via tls1.3. Seems that the webserver do not serve site over tls1.3 properly. 

The used sever is: lighttpd/1.4.49

After short search I found a changelog by lighttpd:

- 1.4.51 - 2018-10-14
 * [mod_openssl] no renegotiation in TLS 1.3 (fixes #2912)

I guess that's the problem. So a webserver upgrade should fix the issue.

**Comment by obgm** [comment]
Thanks @Rotzbua for digging this up. Now running version 1.4.52 which looks much better. @beriberikix Can you confirm?

**Comment by beriberikix** [comment]
Confirmed! Thank you.
