### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [obgm/libcoap#291]
I would like to point out that identifiers like “[`_LIBCOAP_H_`](https://github.com/obgm/libcoap/blob/f584abc19e0b3a4e4a3d56aaad79515b55301398/include/coap2/libcoap.h#L10 "Update candidate")” and “[`_SESSION_H_`](https://github.com/obgm/libcoap/blob/49e8e43eebd013b137cee4b47e13b973e037f8be/include/coap2/coap_session.h#L9 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by obgm** [comment]
True. I am happy to merge if someone picks up the task to do the change.
