### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [obgm/libcoap#292]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages "Description for enumerated types") to stress their relationships?
- [COAP_SESSION_…](https://github.com/obgm/libcoap/blob/49e8e43eebd013b137cee4b47e13b973e037f8be/include/coap2/coap_session.h#L50)
- [COAP_TLS_LIBRARY_…](https://github.com/obgm/libcoap/blob/54956954ca62103acb26f320d90d1bb9e198e905/include/coap2/coap_dtls.h#L38)

**Comment by obgm** [comment]
Generally, yes.

As this introduces API changes where these symbols are passed as parameters, I think this would be something for v4.3.

**Comment by mrdeep1** [comment]
@elfring Now that #386 has been merged into develop branch, does this fix your concerns?

**Comment by elfring** [comment]
It seems so mostly.
Will any additional enumerations become relevant?

**Comment by mrdeep1** [comment]
Always open to suggestions as to where enums may make more sense than #define.

**Comment by mrdeep1** [comment]
Unfortunately where an enum had to be a byte in size (as they were a byte in a structure), those changes had to be reverted out as they would not build in a Windows environment.

Otherwise, can this be closed off now?

**Comment by obgm** [comment]
Closing for now due to lack of a portable solution.
