### ISSUE TITLE
Does the develop branch of libcoap support lwIP

### ISSUE THREAD

**Issue by fanghuaqi** [obgm/libcoap#3]
I tried to clone the source code, and follow the get started guide, but it seems the lwip example can't be  compiled successfully. So I am wondering if the lwip support is still under development?

**Comment by obgm** [comment]
Hi Fang Huaqi,

Fang Huaqi <notifications@github.com> writes:

> I tried to clone the source code, and follow the get started guide,
> but it seems the lwip example can't be compiled successfully. So I am
> wondering if the lwip support is still under development?

Last time I checked, the example worked, but I will look into this. (The
CI is still work in progress and hence has no job to check the lwip code.)

Best regards
Olaf

**Comment by fanghuaqi** [comment]
OK, thanks a lot, once you have some update for this test, could you kindly let me know, thanks a lot.

**Comment by chrysn** [comment]
the development head is currently missing the `CPPFLAGS=-DWITH_LWIP` flags, otherwise it at least builds and runs a very very limited demo server.

i'm in the process of updating the lwip port to integrate better with the latest libcoap infrastructure and will update this bug when mergable fixes are available.

**Comment by obgm** [comment]
I have added WITH_LWIP and checked that at least the build process works again.
You may want to check on non-posix platforms, though.

**Comment by Alveraz** [comment]
I want to know does POSIX means OS or stardart TCP/IP protocol?

**Comment by obgm** [comment]
POSIX as in https://en.wikipedia.org/wiki/POSIX. libcoap supports standard IP as in RFC 2460 (and some support for legacy IP as of RFC 792, though). No TCP yet.
