### ISSUE TITLE
Does libcoap support clients to create new resources using the post method

### ISSUE THREAD

**Issue by JustHzheng** [obgm/libcoap#310]
Has anyone tested or used the libcoap post method to create new resources, similar to the function provided by the sample code hnd_unknown_put？

**Comment by mrdeep1** [comment]
The PUT method updates or creates the resource specified by the URI and is idempotent.  The POST method can create or update a resource based on the content of the POST.  See https://tools.ietf.org/html/rfc7252#section-5.8.2 and https://tools.ietf.org/html/rfc7252#section-5.8.3 .

That said, there is no reason as to why POST cannot be used to create resources which can then be monitored with GET etc.  However the POST should not then call the newly created resource as done in hnd_unknown_put after resource creation.
