### ISSUE TITLE
How does the coap server join a multicast group

### ISSUE THREAD

**Issue by JustHzheng** [obgm/libcoap#311]
When I join a multicast group using "cop-server-g ff03::fc", I return an error" join: setsockopt: Protocol error"

**Comment by mrdeep1** [comment]
See created PR #312 where there is a fix for this.  `coap-rd -g ff03::fc` does work though.

**Comment by mrdeep1** [comment]
@JustHzheng Now that #312 is in the develop branch which fixes this issue, can you please confirm this fixes your issue and then close t his issue off ?
