### ISSUE TITLE
Platform specific support for random number generation

### ISSUE THREAD

**Issue by jitin17** [obgm/libcoap#313]
Currently, I am adding support for `tinydtls` in `libcoap` in [ESP_IDF](https://github.com/espressif/esp-idf). I don't see platform specific layer to add support for random number generation, as ESP_IDF uses an internal API to do so.

**Comment by mrdeep1** [comment]
@jitin17 How are you planning to add in tinydtls?
My plan was to make tinydtls a component within esp-idf and then change the file name coap-notls.[co] to the respective coap_coap_tinydtls.[co] in component.mk and CMakeLists.txt in components/coap/.  Then the client / server need to have a couple of additional functions to set up a PSK / Identity/User.

In answer to your question, an updated prng.h in tindtls/port/include should be all that is needed to handle what you are trying to do.

**Comment by jitin17** [comment]
@mrdeep1 I suppose `tinydtls` is already a part of `libcoap`, thus I believe there is no need to pull in `tinydtls` in `ESP-IDF`.

The problem I am facing is in `dtls_new_context`  function in `ext/tinydtls/dtls.c` file. If flag `WITH_POSIX` is enabled then `dtls_new_context` uses the following to generate random number:

```
FILE *urandom = fopen("/dev/urandom", "r");
fread(buf, 1, sizeof(buf), urandom) != sizeof(buf)
```
This doesn't work in ESP-IDF, which provides `esp_fill_random()` API to do so.

If my understanding is correct, then to solve issues like these we need platform-dependent layer illustrated in this PR: https://github.com/obgm/libcoap/pull/6.

**Comment by mrdeep1** [comment]
Ah - I had not appreciated that the `git clone --recursive` also pulled in ext/tinydtls with the updated libcoap-4.2.0 branch.  So, no need to do that separately.  As tinydtls is a separate product from libcoap, I have not control over that, apart from creating a PR.

It may be that we just have to add a modified version of dtls.c to coap/port directory.  I will take a look at this.

Certainly platform dependent trees may be the way to go - there are to many #ifdefs in the code as it is.

**Comment by mrdeep1** [comment]
@jitin17 For TinyDTLS, this is a work in progress to create some more platform independent code.

**Comment by mrdeep1** [comment]
@jitin17 The latest develop version of libcoap (641b5c174db6dc633a329c26642cd659358c9e97) has an updated version of tinydtls (9a3496119688047b6d8b79826f13425397d92e10) as a submodule which fixes this.

**Comment by jitin17** [comment]
This is great. I think there is a need to include  `esp_system.h` header in `ext/tinydtls/platform-specific/dtls_prng_espidf.c`.

**Comment by mrdeep1** [comment]
You are correct.  I discovered that when I went back to build things that were using all the latest code.

I am shortly (probably tomorrow morning if all goes well) about to push a PR request for https://github.com/mrdeep1/esp-idf/pull/new/libcoap-tinydtls which has DTLS enabled within libcoap.  If you could test this code out, it would be great as I do not have a ESP-IDF test environment.  You will need to make the URI for the coap_client something like coaps://127.0.0.1/Espressif to make it do DTLS.
[I have corrected dtls_prng_espidf.c as port/dtls_prng.c to make this build]

**Comment by jitin17** [comment]
@mrdeep1 Hey, any updates on raising a PR in esp-idf?

**Comment by mrdeep1** [comment]
@jitin17 When testing code (thanks @leenowell as I do not have a esp-idf test environment), it highlighted a couple of issues - the primary one being the excessive use of stack - in particular when logging is enabled - and there is a constrained stack with esp-idf.  There was a secondary issue where "WARN dtls_send_to_peer: cannot find local interface" was getting reported.

The constrained stack and handling the consequences of fixing  "WARN dtls_send_to_peer: cannot find local interface" have been fixed in tinydtls, and the code committed, but am waiting for libcoap to have the code version updated for the submodule tinydtls to get in the new changes.

There is a code fix for constrained stack in the libcoap code, but that has not been accepted yet.

When the git submodule tinydtls code version is updated and the constrained stack PR is accepted, then it makes sense to get this fixed code into esp-idf.

**Comment by obgm** [comment]
Looking at the constrained stack PR right now, will do the tinydtls submodule update immediately...

**Comment by mrdeep1** [comment]
Code fix has been pushed to https://github.com/espressif/esp-idf/pull/3345 .  `git clone -b libcoap-tinydtls --recursive https://github.com/mrdeep1/esp-idf.git` if you want to try it out.

**Comment by ghorbanis** [comment]
> Code fix has been pushed to [espressif/esp-idf#3345](https://github.com/espressif/esp-idf/pull/3345) . `git clone -b libcoap-tinydtls --recursive https://github.com/mrdeep1/esp-idf.git` if you want to try it out.

I tried to test code, but unfortunately, I did not succeed.
[out.log](https://github.com/obgm/libcoap/files/3245104/out.log)

**Comment by mrdeep1** [comment]
@ghorbanis Can you please try again with a clean clone?
I found a minor potential issue.

**Comment by sajadghorbani** [comment]
@mrdeep1 Yes, It worked fine.
Thank you
