### ISSUE TITLE
Synchronous transmission of large payloads?

### ISSUE THREAD

**Issue by shreyasbharath** [obgm/libcoap#316]
Hi,

I've been trialing the library successfully with asynchronous workflows - sending blockwise and non-blockwise requests/responses with small and large payloads.

However, one problem with asynchronous workflows is that you need to maintain state. If the payload is being encoded and you don't have enough memory to hold the entire encoded payload in memory, you have to stream the encoded payload out with block-wise transfers. Maintaining state in this scenario gets ugly very quickly.

An alternative to this is a a synchronous (i.e. blocking) workflow. Does (or can) the library support something like below?

```c
RequestHandler(resource, session, request, response)
{
  while (dataAvailable())
  {
    data = read_data();
    encoded_data = encode_data(data);
    send_blockwise_data(response, encoded_data);   // Sends block and awaits ACK
  }
}
```

**Comment by mrdeep1** [comment]
From the client's perspective, it must follow https://tools.ietf.org/html/rfc7959#section-2.4 and request the next block in the stream which the server then gives - all done making use of the BLOCK2 option to signify that this is a partial transfer or this is the next block required.

So, the simple answer to your question is no.

I assume that you need to encrypt the data as well as use the potential coaps layer encryption and cannot securely do what you want to do by protecting the data in transmission using coaps.

However, the BLOCK2 option by definition is using blocks, and if you are using a block cipher for your application layer encryption these block sizes could be married up making life a lot simpler as all of that lines up.

The coap_add_data_blocked_response() function is there to make things easy for those who do not want to write the code for "if this is a block request, find out which block and size and just send that data chunk back with all the needed coap options - oh and if the data is being observed handle that as well".  But there is nothing stopping you using that code in that function as a starting point, deciding whether you want to send the final size, ETag, Observe, etc. in your response.

Thus your pseudo code could then look something like

````
RequestHandler(resource, session, request, response)
{
   blockno = getblockno(request)
   blocksize= getblocksize(request)
   seek (blockno * blocksize)
   length = read (buffer)
   if (length > 0) {
      enc_data = encrypt (buffer, length)
      add_option(BLOCK2, appropriate bits - e.g. more)
      add_data (enc_data, length)
   }
   else {
      add_option(BLOCK2, no-more)
   }
}
````

**Comment by shreyasbharath** [comment]
Thanks for your response.

I agree with you, the client has to request the next block so the whole transfer is naturally asynchronous. 

However, the pseudocode you posted assumes the resource is `seekable`, this may not always be the case (especially if you are encoding the data!). For simple resources like files that approach works and I've been using it. 

Also, when you are crippled with a tiny amount of memory (say on an IoT device), you have to 
  - read your resource from non-volatile memory
  - encode the resource to fit the requested block size
  - repeat the above two steps until the last block is requested

The problem with this approach is having to maintain (complex) state in an asynchronous workflow.

Is there no way the library can provide the underlying `socket stream` as a parameter to a callback so you can synchronously send blocks (i.e. block until the next request from the client)?

Much like my original pseudocode - 

```c
RequestStreamHandler(resource, session, request, response, socket_stream)
{
  while (dataAvailable())
  {
    data = read_data();
    encoded_data = encode_data(data);
    send_blockwise_data(socket_stream, response, encoded_data);   // Sends block, awaits ACK and request for next block
  }
}
```

Thanks again for your help.

**Comment by mrdeep1** [comment]
coap_session_[sg]et_app_data() can be used to save away state in a session between requests for the next set of data.

I was trying to be more generic with seek / read / encrypt - an equivalent if you are just reading from memory could just be

`enc_data = encrypt (&memstart[blockno * blocksize], length)
`

However, you could start to define your own application protocol layered over coap(s) where you create a new COAP_CHUNK type option that contains the starting offset of the data that is getting sent back.  Then the pseudo code could look like

````
RequestHandler(resource, session, request, response,token)
{
  while (dataAvailable())
  {
    data = read_data();
    encoded_data = encode_data(data);
    create pdu
    add token to pdu
    add COAP_CHUNK to pdu indicating offset of data sent so far
    add data to pdu
    pdu->code = COAP_RESPONSE_CODE(205);
    coap_send()
  }
  add COAP_CHUNK option indicating end of stream
  response->code = COAP_RESPONSE_CODE(205);
}
````
Then the client needs to know how to handle COAP_CHUNK, getting unsolicited responses containing the interim blocks of data (in a similar way to receiving unsolicited observe responses).

[Note that the protocol only allows one CON waiting for ACK to be in flight at any time]

Then you need to think of protocol recover.y if there is packet loss.

**Comment by mrdeep1** [comment]
@shreyasbharath #554 is now a part of the develop branch and may simplify things considerably for you.  All the necessary state for the individual payloads of the body is maintained by libcoap and just the body of data is presented to, or received from the application.  Would this help you?

**Comment by obgm** [comment]
Closed off due to inactivity.
