### ISSUE TITLE
Questions on resource URI

### ISSUE THREAD

**Issue by gli-spirent** [obgm/libcoap#322]
How to register resouce like below with coap_resource_init, which is an example of RFC6990
<http://www.example.com/sensors/t123>;anchor="/sensors/temp";rel="describedby"

I tried the code below:
r = coap_resource_init(coap_make_str_const("http://www.example.com/sensors/temp123"), resource_flags);

What I got:
</http://www.example.com/sensors/temp123>;rel="describedby";anchor="/sensors/temp";

There is a '/' at the beginning. It's added by coap_print_link.

How can I make a resource like the exaple in the RFC and not start with '/'?

**Comment by mrdeep1** [comment]
I assume that you mean RFC6690 which predates RFC7252 when CoAP was formalized.

A CoAP resource is set up by a combination of coap_resource_init(), doap_add_attr(), coap_register_handler() and coap_add_resource() (see examples in the man page coap_resource_init for example).

So, your rel= and anchor= need to be set up by coap_add_attr() (which you may have already done based on your output response).

However, http:// makes no sense within a CoAP context.  rel=describedby is usually used to refer to external content, and therefore is not a (coap) resource  on the local server.

libcoap does not currently support the addition of a pseudo resource anchor that can be used to create output in the response to .well-known/core.

**Comment by gli-spirent** [comment]
Thanks for the quick response!
