### ISSUE TITLE
Output issue in client example

### ISSUE THREAD

**Issue by gli-spirent** [obgm/libcoap#326]
I had a pending pull request and don't want to mess up. It missed a '\n' in append_to_output of client.c if file is not specified, ie, it use stdout as output device.
It would make the output a little bit messy. Like below:
**_Apr 02 10:59:55 DEBG_** ** process incoming 2.05 response:
[ {"Temperature":"1","Source":"Spirent","Alarm":"80^C"} ]**_Apr 02 10:59:55 DEBG_** ***[::1]:58306 <-> [::1]:5683 UDP : session closed

static int
append_to_output(const uint8_t *data, size_t len) {
  size_t written;
  **unsigned char newline = '\n';**

  if (!file) {
    if (!output_file.s || (output_file.length && output_file.s[0] == '-'))
      file = stdout;
    else {
      if (!(file = fopen((char *)output_file.s, "w"))) {
        perror("fopen");
        return -1;
      }
    }
  }

  do {
    written = fwrite(data, 1, len, file);
    len -= written;
    data += written;
  } while ( written && len );

  **if(file == stdout)
  	fwrite(&newline, 1, 1, file);**
  fflush(file);

  return 0;
}

**Comment by mrdeep1** [comment]
Doing this this way will cause a lot of issues.  For example, if the returning data has had to be sent over in blocks (using CoAP Option BLOCK2) as the data is too large to fit into a single packet, then there will be random \n in the output which cannot easily be parsed.
