### ISSUE TITLE
is there a macro to control that not compile 'CoAP over TCP'?

### ISSUE THREAD

**Issue by luminais** [obgm/libcoap#330]
I'm using libcoap-4.2.0 with LWIP, and for reduse the flash size of libcoap, i wonder if there is a macro to control that not compile 'CoAP over TCP'. Not need proxy, also.

any other methods to reduse the flash size of libcoap will be appreciated.

**Comment by obgm** [comment]
That is on the roadmap, but currently no.

**Comment by obgm** [comment]
You might have a look into the **branch disable-tcp** if that improves things. Set `COAP_DISABLE_TCP` to 1 during compilation. I suspect that the gain will be not much as the LwIP port does not seem to use much from the TCP code.

**Comment by mrdeep1** [comment]
develop branch now supports this with using `--disable-tcp` option to `configure`

**Comment by obgm** [comment]
@luminais Do you think this issue can be closed?

**Comment by mrdeep1** [comment]
@luminais Can this be closed?

**Comment by luminais** [comment]
![image](https://user-images.githubusercontent.com/36399225/80483455-b137c080-8988-11ea-8dd6-7daeb97e8f1a.png)
think to use "#if !COAP_DISABLE_TCP" will be better, which can reduce the size of TEXT section

**Comment by mrdeep1** [comment]
You are absolutely correct.  I will get a fix out for it shortly.

**Comment by mrdeep1** [comment]
Fix is available in #496 which is waiting for a merge.
