### ISSUE TITLE
with lwip, until function coap_new_endpoint return, 'result' is not assigned to context->endpoint

### ISSUE THREAD

**Issue by luminais** [obgm/libcoap#334]
https://github.com/obgm/libcoap/blob/1d484849e881d6d2eb5099e189d85b84d995ac25/src/net.c#L472-L477
https://github.com/obgm/libcoap/blob/1d484849e881d6d2eb5099e189d85b84d995ac25/src/coap_io_lwip.c#L105-L128

**Comment by obgm** [comment]
You are right, this is indeed missing.

**Comment by mrdeep1** [comment]
libcoap LwIP support has been re-written in PR https://github.com/obgm/libcoap/pull/884, and so this should no longer be an issue as the standard coap_new_endpoint() function is now used.

**Comment by mrdeep1** [comment]
Fixed in #939.
