### ISSUE TITLE
Qestion about the flags of socket

### ISSUE THREAD

**Issue by gli-spirent** [obgm/libcoap#343]
Hi, @obgm,

I'm trying to adapt libcoap to ACE(http://www.dre.vanderbilt.edu/~schmidt/ACE.html) and found that the flags are similar to ACE's.
Eg, sockets in libcoap have COAP_SOCKET_CAN_READ, COAP_SOCKET_CAN_ACCEPT, COAP_SOCKET_CAN_WRITE and COAP_SOCKET_CAN_CONNECT while ACE has masks as below
![image](https://user-images.githubusercontent.com/41417529/56877237-23787b00-6a7f-11e9-9964-377f4f88ee95.png)

| Event Type  | Description |
| ------------- | ------------- |
| READ_MASK | Indicates input events, such as data on a socket or file  handle. A reactor dispatches the handle_input() hook method to process  input events. |
| WRITE_MASK | Indicates output events, such as when flow control abates. A  reactor dispatches the handle_output() hook method to process output  events. |
| EXCEPT_MASK | Indicates exceptional events, such as urgent data on a socket.  A reactor dispatches the handle_exception() hook method to process  exceptional events. |
| ACCEPT_MASK | Indicates passive-mode connection events. A reactor dispatches  the handle_input() hook method to process connection  events. |
| CONNECT_MASK | Indicates a nonblocking connection completion. A reactor  dispatches the handle_output() hook method to process nonblocking  connection completion events. |

Do they have the same meaning? Can I use 1:1 mapping between them?

**Comment by mrdeep1** [comment]
A quick read of ACE implies to me that you will need a ACE_Reactor for every file descriptor that libcoap uses.  This may be fine for a server with only UDP usage, but does not scale that well with TCP connections.

It does appear that with an ACE_Reactor, you may be able to use the 1:1 mapping, but I am still not yet convinced that this would properly work.  For example, you cannot just use (the misnamed) coap_write() for handle_output() hook method.

One of the things that has come up several times now is support for an epoll() interface for libcoap which would simplify a lot of things here.  Then you potentially could use ACE_Dev_Poll_Reactor.

**Comment by gli-spirent** [comment]
Thanks for your quick response, @mrdeep1
Yes, what in my mind is that I will use ACE_Dev_Poll_Reactor finally. And TCP connection is not in my plate in a near feature.

Reactor is not an issue for scale. We usually only need one for a thread.

**Comment by LiMinggang** [comment]
@mrdeep1, The default reactor in ACE uses select. The only thing related to scale is the number of sockets----there is a event object for each socket registered to the reactor.
So, the memory usage would be slightly increased after the changes while the loop in coap_write and coap_read will not be needed anymore.

BTW, I found the session objects inside coap_endpoint_t don't use the sock inside, am I correct? The session objects are for information saving only, aren't they?

**Comment by mrdeep1** [comment]
> BTW, I found the session objects inside coap_endpoint_t don't use the sock inside, am I correct? The session objects are for information saving only, aren't they?

No, you are not correct.  coap_write() picks up any sockets that are Read/Writable that are hanging off the endpoint.

````
coap_write()

    LL_FOREACH_SAFE(ep->sessions, s, tmp) {
      ...
        if (s->sock.flags & (COAP_SOCKET_WANT_READ | COAP_SOCKET_WANT_WRITE)) {
          if (*num_sockets < max_sockets)
            sockets[(*num_sockets)++] = &s->sock;
        }
      }
    }
````
  sock.flags can also be changed by the (D)TLS layers which you need to be careful with.

**Comment by LiMinggang** [comment]
Thanks a lot!, I missed the call to coap_socket_bind_udp in coap_new_end_point

**Comment by LiMinggang** [comment]
As for ACE, the code snippet you showed is not needed. All the sockets would be registered to select or epoll by the reactor. Once some events happened, the callback function of the socket would be called.

Thanks a lot!, I missed the call to coap_socket_bind_udp in coap_new_end_point

**Comment by mrdeep1** [comment]
OK.  

> Looks like the socket inside the session of endpoint is mainly for accepted sockets of TCP. UDP does not use it.

Actually, UDP does use the information used having done a recvmsg() to set up a unique session (based on 5 tuple) for ongoing traffic - especially needed if (D)TLS is being used (See call to coap_endpoint_get_session() in function coap_read_endpoint() which does create a new session if there is not a 5-tuple match).

In terms of your coding, things like a coap_endpoint_t or coap_session_t should not be accessed directly by application code, but only within libcoap as I would like to see them becoming opaque (#345).

**Comment by gli-spirent** [comment]
Wow! I'm not sure if #345 is a bad news for me.

My original plan is to refactor coap_run_once instead of accessing  coap_endpoint_t or coap_session_t directly although I have to expose the static functions, eg, coap_session_read, to ACE. The reason is that coap_write and coap_read use loops to iterate the sessions and select is used for I/O. Another reason is that I have to use a lot of contexts for coap servers in one process. 
So, I can not use coap_run_once easily. 
What I'm going to do is adding a bridge object of ACE for every socket to delegate the socket operation to ACE and move the code inside coap_write and coap_read to ACE based code which will not have the loops in  coap_write and coap_read because ACE would call the object only if the socket is ready for the events above and all sockets have been added to select or epoll already.
A timer would call a function similar to coap_write at the same time.

**Comment by mrdeep1** [comment]
Precisely why I brought #345  to your attention!

> I have to use a lot of contexts for coap servers in one process.

Not sure why you have to do this.  A generic context holding (D)TLS information will soon get the correct values for a specific session which is then used for the ongoing encryption.  If you are using PSK, then you would need #335 integrated into the develop branch (to change PSK information based on SNI/Identity).  PKI works fine as is.

I have started to look at implementing epoll() (assuming you are a Linux system) which should make your bridge object handling a lot simpler.  I think that only 2 functions need to be publicly exposed, which are as follows:

````
/**
 * Registers an epoll structure for the specified coap_context_t,
 *
 * This follows the epoll_create1() description with the addition
 * of @p context.
 *
 * The non-negative return can be used as a file descriptor to select() or
 * epoll() on.  All epoll_ctl() functions are handled internally by libcoap.
 *
 * NOTE: This file descriptor must not be closed by the application.
 *
 * NOTE: coap_epoll_create() must be called before coap_new_endpoint() after
 * coap_new_context() for servers, and before coap_new_client_session*() for
 * clients to get the file descriptors used by libcoap correctly
 * registered with epoll.
 *
 * @param context The CoAP context to register the epoll handler with.
 * @param flags EPOLL_CLOEXEC or 0 (see epoll_create1())
 *
 * @return Non negative file descriptor. In error @c-1 is returned.
 */
int coap_epoll_create(coap_context_t* context, int flags);

/**
 * Wait on the epoll file descriptor set up by coap_epoll_create().
 *
 * All epoll_ctl() + read + write functions as a result of libcoap internal
 * epoll_wait() call are handled internally by libcoap.
 *
 * @param context The CoAP context that the epoll_create() was registerd with
 * @param timeout_ms >0 time to wait before return in milli-seconds
 *                   0 Return immediately even if there is no epoll data
 *                   -1 Wait indefinately untin there is some epoll data
 *
 * @return >0 Number of active file descriptors that have been processed
 *         0 Timeout after timeout_ms milli-seconds
 *         -1 Error return - see epoll_wait()
 */
int coap_epoll_wait(coap_context_t* context, int timeout_ms);
````

Please let me know if I have missed something.

**Comment by LiMinggang** [comment]
Thanks a lot! @mrdeep1.

**Comment by mrdeep1** [comment]
I have made significant progress on getting libcoap to use epoll() internally (if there is epoll() support) and have it up and running.

The two exposed functions have been replaced with a single function 
````
/**
 * Get the libcoap internal epoll file descriptor for using in an application
 * select() or epoll_wait() call.
 *
 * @param context        The coap_context_t object.
 *
 * @return The epoll file descriptor or @c -1 if epoll is not available.
 */
int coap_context_get_epoll_fd(coap_context_t *context);
````
as libcoap will use epoll() internally if available, and exposes a single file descriptor that be a part of a select() call, or returned in an epoll_wait() event (EPOLLIN set).  coap_run_once() will handle all the necessary libcoap internal file descriptors as is currently is done now.

The only bit of work outstanding is to trigger a read event on the exposed fd when an internal re-transmit needs to take place - it looks like I will have to set up a separate time thread for that.  Re-transmits are currently handled whenever coap_run_once() is called (which might be some time later than when the timeout occurred).

**Comment by mrdeep1** [comment]
The code is now available in PR #347

**Comment by gli-spirent** [comment]
The only comment from me is that the code in run_once can be further optimized based on the epoll code from you.
What I did base on your code is:
1. Add another pointer in struct sock reference to endpoint or session
2. Decouple the code of coap_read and do the job right after epoll_wait becaue you already knows the sock, session and ctx and don't need to iterate all endpoints and sessions under the context

**Comment by gli-spirent** [comment]
Will close the issue because we are off the original topic
