### ISSUE TITLE
Building a Windows C++ Console (Visual Studio 2019) using libcoap as a library - deprecated undeclared identifier

### ISSUE THREAD

**Issue by afontaine-chipkin** [obgm/libcoap#363]
I am creating a Windows C++ console application using libcoap from the latest master branch found here: https://github.com/obgm/libcoap/commit/e66b9637445afa9d0c3c6ff256686a710a36aec3

When creating the main and including coap2/coap.h, I get the build errors stating that:

Error C2065 - 'deprecated': undeclared identifier: libcoap\include\coap2\pdu.h 266
Error C2065 - 'deprecated': undeclared identifier: libcoap\include\coap2\coap_event.h 86
Error C2065 - 'deprecated': undeclared identifier: libcoap\include\coap2\coap_event.h 97
Error C2065 - 'deprecated': undeclared identifier: libcoap\include\coap2\encode.h 90
Error C2065 - 'deprecated': undeclared identifier: libcoap\include\coap2\resource.h 520

The error is due to COAP_DEPRECATED not being defined properly.  In the libcoap.h where it is defined, we see the following:

```c
#ifndef COAP_DEPRECATED
#  if defined(__cplusplus)
#    define COAP_DEPRECATED __attribute__ ((deprecated))
#  else
#    if defined(_MSC_VER)
#      define COAP_DEPRECATED __declspec(deprecated)
#    else
#      define COAP_DEPRECATED __attribute__ ((deprecated))
#    endif
#  endif
#endif
```

While this does check for _MSC_VER, that is only if it is a C project and not a C++ one.

I was able to fix this by doing the following:

```c
#ifndef COAP_DEPRECATED
#  if defined(__cplusplus)
#    if defined(_MSC_VER)
#      define COAP_DEPRECATED __declspec(deprecated)
#    else
#      define COAP_DEPRECATED __attribute__ ((deprecated))
#    endif
#  else
#    if defined(_MSC_VER)
#      define COAP_DEPRECATED __declspec(deprecated)
#    else
#      define COAP_DEPRECATED __attribute__ ((deprecated))
#    endif
#  endif
#endif
```

Or perhaps, since it seems that it only matters whether it is Windows or not:
```c
#ifndef COAP_DEPRECATED
#  if defined(_MSC_VER)
#    define COAP_DEPRECATED __declspec(deprecated)
#  else
#    define COAP_DEPRECATED __attribute__ ((deprecated))
#  endif
#endif
```

**Comment by mrdeep1** [comment]
The last variant is the way to go.  It looks like it was my mistake when creating COAP_DEPRECATED and modeled it on the COAP_STATIC_INLINE.  I will generate a fix for the develop branch.
