### ISSUE TITLE
Windows C++ Console (Visual Studio 2019) - Unresolved external symbols - coap_cleanup, coap_startup

### ISSUE THREAD

**Issue by afontaine-chipkin** [obgm/libcoap#369]
Hello,

We are still using the coap-server example code in a c++ Windows console application in Visual Studio 2019.  After manually resolving the build errors mentioned in other issues, we are getting the following errors when building:

- Error LNK2019 unresolved external symbol "void __cdecl coap_cleanup(void)" (?coap_cleanup@@YAXXZ) referenced in function _main	
- Error LNK2019 unresolved external symbol "void __cdecl coap_startup(void)" (?coap_startup@@YAXXZ) referenced in function _main

Looking into this, it looks like these functions are declared in libcoap.h, but implemented in net.c

However, when looking at coap.h which is generated from coap.h.windows, the #include "libcoap.h" is not included in the same section as the other header files surrounded by the 

```c
#ifdef __cplusplus
extern "C" {
#endif

...

#ifdef __cplusplus
}
#endif
```

I resolved this issue by updating the coap.h.windows to move the #include "libcoap.h" with the other include files, then rebuilding the win32 libcoap project.

**Comment by obgm** [comment]
I think that the misplacement of the libcoap.h include in `coap.h.windows` is a bug. @jcmichelou can you confirm that putting `#include <libcoap.h>` outside `extern "C"` was not done on purpose?

**Comment by jcmichelou** [comment]
Hello Olaf,

Yes, obviously it should also be protected by extern “C” since it is C code.

Best regards,
Jean-Claude.
