### ISSUE TITLE
A more comprehensible example

### ISSUE THREAD

**Issue by mathieubrd** [obgm/libcoap#38]
Hi,

I'm trying to understand the server exemple but its 1200 lines and the lack of comments has discouraged me. Do you have simpler examples or at least function descriptions?

**Comment by adikabintang** [comment]
Hi mathieubrochard,

I'm also new to the CoAP as well as the Libcoap. I've found a good website explaining the CoAP server example using Libcoap [1]. The writer of the blog is Nikos Fotiou.

[1] http://respected-professor.blogspot.co.id/2015/11/a-hello-world-coap-server-using-libcoap.html

**Comment by obgm** [comment]
A minimal working example is provided in [libcoap-minimal](/obgm/libcoap-minimal). Closing.
