### ISSUE TITLE
coap_session_connected() can destroy session object

### ISSUE THREAD

**Issue by obgm** [obgm/libcoap#381]
`coap_session_connected()` calls `coap_wait_ack()` on the passed `session` object. In theory, `coap_wait_ack()` may return a value less than zero (i.e., `COAP_INVALID_TID`). When this happens and `COAP_PROTO_NOT_RELIABLE()` is true, `coap_delete_node()` will release the session object passed to `coap_session_connected()`. This would eventually lead to a crash in `coap_read_endpoint()`.

This issue was detected by Coverity scan with CID 1484380.

**Comment by mrdeep1** [comment]
As coap_read_endpoint() is only there for servers, when coap_session_release() is called, the session will not get deleted as the session type is not of type client. So, I am not convinced that this actually is an issue.

**Comment by mrdeep1** [comment]
When `coap_wait_ack()` is called by `coap_session_connected()`, it bumps the session reference number in `coap_wait_ack()`.  If `coap_delete_node()` does get called later in `coap_session_connected()`, then this simply decrements the reference count added by `coap_wait_ack()` and hence would never delete the session object by calling` coap_free_session(`).
I do not believe that this can ever be an actual issue.

**Comment by obgm** [comment]
Ok, closing for now.
