### ISSUE TITLE
Windows: Syntax Error on Scoped Enums in VC2017

### ISSUE THREAD

**Issue by obgm** [obgm/libcoap#394]
PR #386 has introduced scoped enums on Windows to control the storage size of enumeration values.
Visual Studio C/C++ 2017, version 10.0.15063.0, throws syntax errors for these scoped enums.

**Comment by obgm** [comment]
The reason for this error seems to be that scoped enums are C++ only.

**Comment by mrdeep1** [comment]
@obgm This can be closed off now.
