### ISSUE TITLE
Why pthread though?

### ISSUE THREAD

**Issue by andygikling** [obgm/libcoap#399]
@obgm - maybe I'm off base here, but why would the main-line C implementation of CoAP require pthread?  Most microcontroller designs don't have a pthread mechanism, many don't even have an RTOS.  

Can you please comment on the thought process here?

**Comment by mrdeep1** [comment]
The only possible use of pthread that I can find is in include/coap2/coap_mutex.h where pthreads can be used based on the different underlying supporting environment #ifdefs .

Mutex is only used for Stack Constrained environments to protect static variable usage as opposed to having the variables on the stack (the default).  In the case of Contiki, there are no mutexs and so coap_mutex_* is a no-op.

What errors / issues are you seeing here?

**Comment by andygikling** [comment]
Thanks for pointing that out.  Let me look a bit closer at this.

**Comment by obgm** [comment]
@mrdeep1 is correct: The pthread-dependency has been introduced for the mutex only.

**Comment by andygikling** [comment]
This won't build in win32 though - do we need another #define for that platform?  I'm not sure what the mutex calls are supposed to be for CRT but I could look into it.  I can't make this library compile on windows to save my life right now.

**Comment by mrdeep1** [comment]
@andygikling Please confirm that this can be closed now that #404 has been merged into the develop branch.

**Comment by andygikling** [comment]
Yes you can close this now.  The solution looks good.
Also, after grepping for the term COAP_CONSTRAINED_STACK, there's very little documentation.
Is there a central place in the library which describes what all the compiler switches available are and what they do?

**Comment by mrdeep1** [comment]
Documentation is being created by contributors, but there is nothing specifically on the compiler switches other than by running ./configure --help . You may want to look at #405 which gives some extra clues.

**Comment by andygikling** [comment]
Roger, understood.  Are we willing to add documentation to the README then?  Just curious - it's pretty light.  It doesn't even have a summary of the client/server example code.

**Comment by mrdeep1** [comment]
I have just created PR #407 to flesh out the README information.  Documentation can be found at https://libcoap.net/doc/reference/4.2.0/ and usage information on the client at https://libcoap.net/doc/reference/4.2.0/man_coap-client.html and the server at https://libcoap.net/doc/reference/4.2.0/man_coap-server.html .  Other manual pages in this documentation (a work in progress) document different function usage along with some examples.  Some of the man pages have been updated since the 4.2.0 release.

**Comment by mrdeep1** [comment]
@andygikling  Can this be closed off now?

**Comment by andygikling** [comment]
Yes please close - thanks again for all the help.
