### ISSUE TITLE
In libcoap enabled tinydtls observer is not working properly

### ISSUE THREAD

**Issue by NitinLnt** [obgm/libcoap#40]
Hello,  as mentioned above in coaps-server side resource was not resetting to dirty option so it was not sending the observer reply, now it is sending resource updates but it is not un-subscribing from observe option after timeout. It this related to select() write option as there it is mentioned as below.
        if (FD_ISSET(fd, &wfds))
            /\* FIXME */;
Please help

**Comment by obgm** [comment]
Please be more specific: Where is this code snippet located in libcoap? How can the error be reproduced? Can you provide a pcap trace?

**Comment by obgm** [comment]
Closing this as the latest development version seems not to be affected of this issue anymore.
