### ISSUE TITLE
COAP Client - Nonconfirmed GET not getting all the data

### ISSUE THREAD

**Issue by afontaine-chipkin** [obgm/libcoap#413]
I am using the coap_client.exe to poll coap.me/.well-known/core.

When using the default settings in coap_client.exe, all of the data is retrieved correctly:

Request:
  coap-client.exe -m get coap://coap.me/.well-known/core
Result:
```
</test>;rt="test";ct=0,</validate>;rt="validate";ct=0,</hello>;rt="Type1";ct=0;if="If1",</bl%C3%A5b%C3%A6rsyltet%C3%B8y>;rt="bl├Ñb├ªrsyltet├╕y";ct=0,</sink>;rt="sink";ct=0,</separate>;rt="separate";ct=0,</large>;rt="Type1 Type2";ct=0;sz=1700;if="If2",</secret>;rt="secret";ct=0,</broken>;rt="Type2 Type1";ct=0;if="If2 If1",</weird33>;rt="weird33";ct=0,</weird44>;rt="weird44";ct=0,</weird55>;rt="weird55";ct=0,</weird333>;rt="weird333";ct=0,</weird3333>;rt="weird3333";ct=0,</weird33333>;rt="weird33333";ct=0,</123412341234123412341234>;rt="123412341234123412341234";ct=0,</location-query>;rt="location-query";ct=0,</create1>;rt="create1";ct=0,</large-update>;rt="large-update";ct=0,</large-create>;rt="large-create";ct=0,</query>;rt="query";ct=0,</seg1>;rt="seg1";ct=40,</path>;rt="path";ct=40,</location1>;rt="location1";ct=40,</multi-format>;rt="multi-format";ct=0,</3>;rt="3";ct=50,</4>;rt="4";ct=50,</5>;rt="5";ct=50
```

The attached wireshark log shows the CON COAP traffic has 8 blocks of data.
![image](https://user-images.githubusercontent.com/19735056/65729996-323a7c80-e075-11e9-90ee-32be9e864cba.png)

However, when using doing the same GET using Nonconfirmed:

Request:
coap-client.exe -m get -N coap://coap.me/.well-known/core
Response:
```
</test>;rt="test";ct=0,</validate>;rt="validate";ct=0,</hello>;rt="Type1";ct=0;if="If1",</bl%C3%A5b%C3%A6rsyltet%C3%B8y>;rt="bl├
```

The application polls and successfully get Block 0 and makes the request for Block 1, but does not continue after that.  
![image](https://user-images.githubusercontent.com/19735056/65730080-74fc5480-e075-11e9-8dd5-c918a1c5ad22.png)

It looks like the application quits after making that second poll.

[COAPClientExampleLog_2019Sep26154845.zip](https://github.com/obgm/libcoap/files/3660177/COAPClientExampleLog_2019Sep26154845.zip)

**Comment by mrdeep1** [comment]
With the latest code on the develop branch, I am not having this issue with ether Linux or Windows.

What version of libcoap are you running with?

Adding in the -v7 option to get verbose logging may give you a clue here as to what is going on.

**Comment by obgm** [comment]
With non-confirmable operation, it might of course happen that either the request or the response got lost on the way. In this case, no further blocks will be requested. For example:

```
$ examples/coap-client -l2 -v7 -N coap://coap.me/.well-known/core
Sep 27 12:53:59 DEBG ***[local]:51858 <-> [remote]:5683 UDP : new outgoing session
Sep 27 12:53:59 DEBG sending CoAP request:
Sep 27 12:53:59 DEBG *  [local]:51858 <-> [remote]:5683 UDP : sent 29 bytes
v:1 t:NON c:GET i:8725 {} [ Uri-Host:coap.me, Uri-Path:.well-known, Uri-Path:core ]
Sep 27 12:53:59 DEBG timeout is set to 90 seconds
Sep 27 12:53:59 DEBG *  [local]:51858 <-> [remote]:5683 UDP : received 146 bytes
v:1 t:NON c:2.05 i:9b51 {} [ ETag:\xDE\xEA\x9A\x3E\x0E\xDA\xC4\x9B, Content-Format:application/link-format, Block2:0/M/128 ] :: '</test>;rt="test";ct=0,</validate>;rt="validate";ct=0,</hello>;rt="Type1";ct=0;if="If1",</bl%C3%A5b%C3%A6rsyltet%C3%B8y>;rt="bl\xC3'
Sep 27 12:53:59 DEBG ** process incoming 2.05 response:
</test>;rt="test";ct=0,</validate>;rt="validate";ct=0,</hello>;rt="Type1";ct=0;if="If1",</bl%C3%A5b%C3%A6rsyltet%C3%B8y>;rt="bl�Sep 27 12:53:59 DEBG found the M bit, block size is 3, block nr. 0
Sep 27 12:53:59 DEBG query block 1
Sep 27 12:53:59 DEBG *  [local]:51858 <-> [remote]:5683 UDP : sent 31 bytes
v:1 t:NON c:GET i:8726 {} [ Uri-Host:coap.me, Uri-Path:.well-known, Uri-Path:core, Block2:1/_/128 ]

   ...
   long time nothing
   ...

Sep 27 12:55:29 INFO timeout
Sep 27 12:55:29 DEBG ***[local]:51858 <-> [remote]:5683 UDP : session closed
```

**Comment by mrdeep1** [comment]
Good point. https://tools.ietf.org/html/rfc7959#section-1 

> The present
>    specification minimizes the constraints it adds to those base
>    exchanges; however, not all variants of using CoAP are very useful
>    inside a block-wise transfer (e.g., using Non-confirmable requests
>    within block-wise transfers outside the use case of Section 2.8 would
>    escalate the overall non-delivery probability).

Block-wise transfers should be confirmable to avoid the potential of additional losses.

**Comment by afontaine-chipkin** [comment]
Thank you for your help and suggestions.

The coap-client version being used is:

> coap-client.exe v4.1.2 -- a small CoAP implementation
> Copyright (C) 2010-2019 Olaf Bergmann <bergmann@tzi.org> and others
> 
> TLS Library: OpenSSL - runtime 3.0.0-dev, libcoap built for 3.0

When running the request with -v7:
coap-client.exe -l2 -v7 -N coap://coap.me/.well-known/core

I get the following responses:
Sep 27 08:44:30 DEBG ***[local]:58246 <-> 134.102.218.18:5683 UDP : new outgoing session
Sep 27 08:44:30 DEBG *  [local]:58246 <-> 134.102.218.18:5683 UDP : sent 29 bytes
v:1 t:NON c:GET i:4aaa {} [ Uri-Host:coap.me, Uri-Path:.well-known, Uri-Path:core ]
Sep 27 08:44:30 DEBG timeout is set to 90 seconds
Sep 27 08:44:30 DEBG *  [local]:58246 <-> 134.102.218.18:5683 UDP : received 146 bytes
</test>;rt="test";ct=0,</validate>;rt="validate";ct=0,</hello>;rt="Type1";ct=0;if="If1",</bl%C3%A5b%C3%A6rsyltet%C3%B8y>;rt="bl├Sep 27 08:44:30 DEBG found the M bit, block size is 3, block nr. 0
Sep 27 08:44:30 DEBG query block 1
Sep 27 08:44:30 DEBG *  1[local]:58246 <-> 134.102.218.18:5683 UDP : sent 31 bytes
v:1 t:NON c:GET i:4aab {} [ Uri-Host:coap.me, Uri-Path:.well-known, Uri-Path:core, Block2:1/_/128 ]
Sep 27 08:44:30 DEBG ***[local]:58246 <-> 134.102.218.18:5683 UDP : session closed

Based on the timestamps, there is no long period of time, the session closes immediately after sending the subsequent NON confirmed Get.

**Comment by mrdeep1** [comment]
OK.  Thanks for the background information - very useful.  Moving forward, the -l2 option is not needed - it simulates a lossy network.

You need to be running the latest code in the develop branch (fix is not in 4.2.0) or apply fix 422faa4fefbe79b69b683f1a779b65708541d81a (PR #363) 

Please confirm that using the develop branch fixes your issue.

**Comment by mrdeep1** [comment]
I may have partially misled you - for Windows, the version (incorrectly) reported 4.1.2 until #402 was merged into the develop branch.  The executable that you are running certainly has all the code in it up to March 12 2019 (which was when 4.2.0 was released) as the Copyright is the latest.  But #339 is needed to fix your issue.

**Comment by afontaine-chipkin** [comment]
I have updated to use the develop branch and that has fixed the issue I am seeing with coap-client.exe.

Thank you for your help!

**Comment by mrdeep1** [comment]
Excellent.  If you could close off this issue, it would be appreciated.

**Comment by afontaine-chipkin** [comment]
Updating to develop branch from master branch resolved this issue.
