### ISSUE TITLE
Request/response matching when using DTLS

### ISSUE THREAD

**Issue by pokgak** [obgm/libcoap#420]
I'm going through the DTLS part in libcoap and trying to understand how it works. For coap with DTLS, the following additional checks are defined to match the response received to the correct request in [Section 9.1.2 of the CoAP RFC](https://tools.ietf.org/html/rfc7252#section-9.1.2):

> 9.1.2.  Request/Response Layer
> 
>    The following rules are added for matching a response to a request:
>    The DTLS session MUST be the same, and the epoch MUST be the same.
>
>    This means the response to a DTLS secured request MUST always be DTLS
>    secured using the same security session and epoch.  Any attempt to
>    supply a NoSec response to a DTLS request simply does not match the
>    request and therefore MUST be rejected (unless it does match an
>    unrelated NoSec request).

How is this done in libcoap? I tried looking at the different `coap_dtls_receive()` provided for each DTLS stack and if I understand correctly, only decryption and event handling are done in those functions. I also looked at `coap_dispatch()` and found nothing related to matching DTLS session and epoch.

If the check is done in libcoap, can anyone help to point me to the correct place I should look at?

**Comment by mrdeep1** [comment]
Libcoap does the non-encrypted CoAP functionality and has a set of internal APIs to interface with the underlying (D)TLS libraries in the network stack.
````
Application
CoAP Layer      - libcoap
(D)TLS layer    - OpensSSL / GnuTLS / TinyDTLS
UDP/TCP layer   - Host O/S
````

It is the responsibility of OpenSSL, GnuTLS or TinyDTLS (the current set of supported (D)TLS libraries) to check the (D)TLS session (which is different from the CoAP session in libcoap) for correct / incorrect operation.  You need to read the respective (D)TLS library code.

Furthermore, encrypted traffic uses a different port to non-encrypted traffic and so these cannot use the same CoAP session as the port number is embedded into the key for the CoAP session and so enforces 9.1.2.  If non-encrypted traffic comes in over the encrypted port, it will not 'decrypt' as it is intercepted by the (D)TLS layer and will therefore get dropped.

**Comment by pokgak** [comment]
Thanks  for the explanation :)
