### ISSUE TITLE
How to build and run the coap server from the example file?

### ISSUE THREAD

**Issue by ameerhazo** [obgm/libcoap#422]
Hello everyone, I am a newbie on the theme of libcoap and Linux environments and I wanted to try and run the coap client and server from the example file. By using this tutorial on Youtube: https://www.youtube.com/watch?v=nzuaMiiM9gs&t=307s
,I managed to run the coap client but the command ./coap-server doesnt return anything for me on my terminal (I'm using the Windows Subsystem for Linux) terminal. I've tried doing this on my Ubuntu Linux 18.0.4 virtual machine aswell and the problem still persist. Any help at this point would be greatly appreciated. Thank you.

**Comment by mrdeep1** [comment]
In the first instance I would enable verbose logging in the coap-server by appending the -v9 option 
./coap-server -v9
and see what is reported (but looking at the video clip, this may be already set by the author on his copy of the source code, but the standard example code be default is -v4, so you would not see any DEBG messages).
If you are not seeing receipt of any packets, I would suspect that there is a firewall or iptables that is dropping packets sent to port 5683.

**Comment by ameerhazo** [comment]
> 
> 
> In the first instance I would enable verbose logging in the coap-server by appending the -v9 option
> ./coap-server -v9
> and see what is reported (but looking at the video clip, this may be already set by the author on his copy of the source code, but the standard example code be default is -v4, so you would not see any DEBG messages).
> If you are not seeing receipt of any packets, I would suspect that there is a firewall or iptables that is dropping packets sent to port 5683.

I've just tried your suggestion and it works now thank you so so much for helping a newbie like me. I can run two instances now just like in the video. 

I'm gonna tinker around with it now and try enabling tinyDTLS or OpenSSL with it. What a lot of difference a simple -v9 could do :D. Again, thank you and have a nice weekend.
