### ISSUE TITLE
How to handle  PROBING_RATE

### ISSUE THREAD

**Issue by lieunguyen-tma** [obgm/libcoap#423]
Hi @obgm 

Following https://tools.ietf.org/html/rfc7252#section-4.8, PROBING_RATE  is defined. However, in the source code, I can't find  PROBING_RATE. Could you please let me know where the  PROBING_RATE is handled in the source code?
Thank you

**Comment by mrdeep1** [comment]
libcoap does not support configuring PROBING_RATE or rate-limiting non responding non-confirmable traffic to PROBING_RATE.

This currently would need to be done in the application

**Comment by lieunguyen-tma** [comment]
Mr. @mrdeep1 

Thanks for your answer.
In the future, it will be supported in the libcoap, isn't it?

**Comment by mrdeep1** [comment]
There are no specific plans to implement PROBING_RATE in libcoap, it needs a volunteer to do it and will add in complexities for handling traffic that is rate limited.

The default PROBING_RATE of 1B/s is a low value and certainly is too low when using any heartbeat / keep-alive packets to keep NAT "warm".

````
https://tools.ietf.org/html/rfc8085#section-3.1.3 case 2

   2.  A second case of applications cannot maintain an RTT estimate for
       a destination, because the destination does not send return
       traffic.  Such applications SHOULD NOT send more than one UDP
       datagram every 3 seconds and SHOULD use an even less aggressive
       rate when possible.  Shorter values are likely problematic in
       many cases.
````

gives a reasonable suggestion as to what traffic rates should be when no responses are being seen.

**Comment by lieunguyen-tma** [comment]
Mr. @mrdeep1 

Thanks for your answer.
