### ISSUE TITLE
DTLS support for coap-rd

### ISSUE THREAD

**Issue by kb2ma** [obgm/libcoap#435]
I'd like to confirm gcoap's resource directory support works under DTLS, so it would be valuable to me for libcoap to support this feature. If this addition is relatively straightforward, I could try to implement it. I'd appreciate an outline of what needs to be done though.

**Comment by obgm** [comment]
If you are working on the current develop HEAD, the most important thing to do is to setup the keys to use. In `coap-server.c`, this is done in the helper function `fill_keystore()`. For pre-shared keys, you basically need the following, where `key`is your PSK and `key_length` is its length in bytes:

```c
coap_dtls_spsk_t dtls_psk;
memset (&dtls_psk, 0, sizeof(dtls_psk));
dtls_psk.version = COAP_DTLS_SPSK_SETUP_VERSION;
dtls_psk.psk_info.key.s = key;
dtls_psk.psk_info.key.length = key_length;
coap_context_set_psk2(ctx, &dtls_psk);
```

**Comment by obgm** [comment]
The older version had a function `coap_context_set_psk()` where you could just pass the key and length along with the context.

**Comment by mrdeep1** [comment]
@kb2ma Does #439 (not yet merged into develop) solve your requirements?

**Comment by kb2ma** [comment]
Thanks for the PR! I plan to try it out in the next few days.

**Comment by kb2ma** [comment]
I can confirm that with #439 the initial registration works with a RIOT client in PSK mode. That PR resolves this issue from my perspective.

**Comment by obgm** [comment]
@kb2ma Thank you!
