### ISSUE TITLE
Converting IPv4 to IPv6 multicast not working

### ISSUE THREAD

**Issue by nlykins** [obgm/libcoap#44]
I've set up a sample CoAP client application that can send requests and parse out the responses; however, I need to convert it to an IPv6 multicast solution to accommodate other pieces of a project. However, I'm not seeing any outgoing traffic after these changes. I only changed a handful of lines to make it support IPv6 and the application is running with no errors but no traffic is actually going out across the network. I made the following changes:

source.addr.sin6.sin6_family = AF_INET;
to
source.addr.sin6.sin6_family = AF_INET6;

src_addr.addr.sin.sin_addr.s_addr = inet_addr("0.0.0.0");
to
inet_pton(AF_INET6, "::1", &(source.addr.sin6.sin6_addr));

dst.addr.sin6.sin6_family = AF_INET;
to
dst.addr.sin6.sin6_family = AF_INET6;

dst_addr.addr.sin.sin_addr.s_addr = inet("192.168.1.210")
to;
inet_pton(AF_INET6, "bbbb::1", &(dest.addr.sin6.sin6_addr));

I've tested a multicast CoaP method through node-coap and I'm seeing a successful response back through it so I'm not sure where it's failing. Any thoughts? Thanks!

**Comment by obgm** [comment]
Closing off as this has been fixed.
