### ISSUE TITLE
Travis-CI is building stage test only 

### ISSUE THREAD

**Issue by obgm** [obgm/libcoap#452]
For some time now, travis has stopped building the additional stages (after test).

**Comment by mrdeep1** [comment]
Could this be down to an embedded space in `other platforms` breaking the logic somewhere?

**Comment by obgm** [comment]
Well, it did work before with this configuration but I will give it a try...

**Comment by gocarlos** [comment]
is there an option to change to github pipelines? this would allow mac, windows and linux testing easily: for reference https://github.com/bacnet-stack/bacnet-stack/pull/16/files

**Comment by obgm** [comment]
@gocarlos Any improvement here is welcome. Can you point me to some "getting-started documentation"?

**Comment by gocarlos** [comment]
@obgm https://github.com/features/actions

**Comment by obgm** [comment]
Thank you. I will have a look into this. For now, I have fixed the existing travis configuration and re-enabled the missing stages.
