### ISSUE TITLE
Print full payload on terminal

### ISSUE THREAD

**Issue by mselser** [obgm/libcoap#453]
Hello, when I receive a 1024 bytes coap message, the terminal only shows a little portion of it. Is there any way I could configure something to get the full string?

v:1 t:CON c:PUT i:5f2d {dbb52863d8e0d610} [ Uri-Path:S1 ] :: '\x0B\xAE\x0A\xF2\x0A\x11\x09\x14\x07\xF5\x06\xBD\x05r\x04\x10\x02\xA2\x010\xFF\xB6\xFE:\xFC\xC4\xFBY\xFA\x01\xF8\xB5\xF7\x80\xF6j\xF5q\xF4\x97\xF3\xDE\xF3M\xF2\xE4\xF2\xA4\xF2\x89\xF2\x9E\xF2\xDA\xF3>\xF3\xCD\xF4~\xF5S\xF6P\xF7g\xF8\x99\xF9\xE4\xFB=\xFC\xA6\xFE\x1D\xFF\x97\x01\x13\x02\x87\x03\xF8\x05X\x06\xA6\x07\xE0\x08\xFE\x0A\x03\x0A\xE5\x0B\xA1\x0C>\x0C\xAF\x0C\xFB\x0D\x1B\x0D\x10\x0C\xDB\x0C\x80\x0B\xFC\x0BO\x0A~\x09\x8D\x08|\x07P\x06\x0B\x04\xB7\x03L\x01\xD9\x00`\xFE\xE6\xFDn\xFB\xFE\xFA\x9C\xF9K\xF8\x0B\xF6\xE8\xF5\xE3\xF4\xF9\xF43\xF3\x90\xF3\x14\xF2\xC1\xF2\x97\xF2\x95\xF2\xC1\xF3\x15\xF3\x92\xF42\xF4\xF9\xF5\xE5\xF6\xEF\xF8\x15\xF9T\xFA\xA9\xFC\x0E\xFD~\xFE\xF7\x00q\x01\xEA\x03\\x04\xC7\x06 \x07^\x08\x8A\x09\x9C\x0A\x8C\x0BZ\x0C\x04\x0C\x8B\x0C\xE8\x0D\x19\x0D \x0D\x03\x0C\xB9\x0CG\x0B\xAD\x0A\xEB\x0A\x08\x09\x06\x07\xE5\x06\xAA\x05W\x03\xF8\x02\x8A\x01\x13\xFF\x99\xFE!\xFC\xAC\xFBC\xF9\xEA\xF8\xA3\xF7o\xF6]\xF5e\xF4\x8F\xF3\xDA\xF3K\xF2\xEB\xF2\xAE\xF2\x9A\xF2\xB2\xF2\xF2\xF3`\xF3\xF1\xF4\xA6\xF5'

This is the string I'm receiving, which is not the whole string.

Thanks

**Comment by mrdeep1** [comment]
My suggestion would be to try to add `CFLAGS="-DCOAP_DEBUG_BUF_SIZE=5000"` to the ./configure line - e.g.
````
./configure CFLAGS="-DCOAP_DEBUG_BUF_SIZE=5000"
````
and see if this helps you.  5000 is a stab in the dark number and will need tuning.

**Comment by mselser** [comment]
Thanks. Will try and comment

**Comment by obgm** [comment]
@mselser Does this help in any way?

**Comment by mselser** [comment]
Yes. This worked. Thank you very much
