### ISSUE TITLE
coap response code for Valid (2.03) is labeled COAP_RESPONSE_304

### ISSUE THREAD

**Issue by dyle71** [obgm/libcoap#456]
https://github.com/obgm/libcoap/blob/ef4c01df044b1f2bfca60c3425a0bfbb202c55f0/include/coap2/pdu.h#L166

Is this intentional? Since other response codes follow a clear pattern, but Valid seems to be "..._304" instead of "..._203". 

The RFC lists
"5.9.1.3.  2.03 Valid
This Response Code is related to HTTP 304 "Not Modified"."
So there is some explaination, albeit the value placed in COAP_RESPONSE_304 is 204...

This seems slightly confusing to me.

**Comment by mrdeep1** [comment]
These #defines were put in place for a change introduced between draft-ietf-core-coap-03 and draft-ietf-core-coap-04 in 2011 where what was 304 became 2.03.  This provided backward compatibility.

The COAP_RESPONSE_nnn backward compatible #defines should no longer be used and are not in use in the current code or examples.

**Comment by dyle71** [comment]
Ah, ok. Thx for the clarification. That's been quick. =)
