### ISSUE TITLE
Conflict with one letter pre-processor variable name in public header

### ISSUE THREAD

**Issue by glegall** [obgm/libcoap#46]
Hi, and thank you for making libcoap.

the public header "include/coap/encode.h" defines the pre-processor variable "E" (currently line 20, branch "develop"). However, this may mess up with other headers, that would use such a variable name for other things.

For example this can happen when using libcoap with C++ and class templates, that often use one letter names in class prototypes (in my case it occurs when also including curlpp in my project).

I suggest renaming this variable (which defines, I believe, the size of the CoAP packet header), into something longer and more explicit, like "ENCODE_HEADER_SIZE".

For anyone who may have the same issue, a workaround is to undefine the pre-processor variable E after including the libcoap headers. Here is an example:

```c
#include <coap.h>
#include <resource.h>

#undef E
```

Regards,
G. Le Gall

**Comment by obgm** [comment]
Thank you for pointing this out. I will fix it as suggested.

**Comment by obgm** [comment]
Fixed in commit c2dd6b4.
