### ISSUE TITLE
coap_io_process(COAP_RUN_NONBLOCK) blocks in select()

### ISSUE THREAD

**Issue by danadam** [obgm/libcoap#461]
In `coap_io.c`:
```c
#ifndef COAP_EPOLL_SUPPORT
  timeout = coap_io_prepare_io(...);
  if (timeout == 0 || timeout_ms < timeout)
    timeout = timeout_ms;

...

  if ( timeout > 0 ) {
    if (timeout == COAP_RUN_NONBLOCK)
      timeout = 0;
    tv.tv_usec = (timeout % 1000) * 1000;
    tv.tv_sec = (long)(timeout / 1000);
  }

  result = select(nfds, &readfds, &writefds, &exceptfds, timeout > 0 ? &tv : NULL);
```
if `timeout_ms` is `1` (i.e. `COAP_RUN_NONBLOCK`) or `coap_io_prepare_io()` returns `1` then `timeout` will be set to `0`, NULL will be passed to `select()` and `select()` will block.

Corresponding code for epoll doesn't have that problem:
```c
#else /* COAP_EPOLL_SUPPORT */
  timeout = coap_io_prepare_epoll(...);
  if (timeout == 0 || timeout_ms < timeout)
    timeout = timeout_ms;

...

    int etimeout = timeout;
    if (timeout_ms == COAP_RUN_BLOCK)
      etimeout = -1;
    else if (timeout_ms == COAP_RUN_NONBLOCK)
      etimeout = 0;

    nfds = epoll_wait(ctx->epfd, events, COAP_MAX_EPOLL_EVENTS, etimeout);
```

**Comment by mrdeep1** [comment]
Thanks for spending the time debugging this issue.  It is fixed in the pending #441 change as well as fixed in pending #462

**Comment by danadam** [comment]
AFAICT both of them will lead to up to 1ms busy loop if `coap_io_process()` is repeatedly called with a timeout (i.e. > 1) and `coap_io_prepare_io()` returns 1.

**Comment by mrdeep1** [comment]
I have reworked the code as per #463 so that COAP_RUN_NONBLOCK has a value of -1 instead of 1 to remove the potential of this 1ms busy loop.

**Comment by mrdeep1** [comment]
Now that #463 is merged into the develop branch. can you please confirm that your issue has been fixed - if so, please close this issue.

**Comment by obgm** [comment]
Closing.
