### ISSUE TITLE
Memory leaks when using coap in C++

### ISSUE THREAD

**Issue by maaikez** [obgm/libcoap#466]
Hello,

I use libcoap in my C++ code, see below. Until now I used version 4.2.0 but I just upgraded to 4.2.1 (but did not yet change the function names). 

When calling below code with valgrind, I get memory leaks (after calling this function 15 times):

1,080 (840 direct, 240 indirect) bytes in 15 blocks are definitely lost in loss record 86 of 93
  in CoAPController::sendClientMessage(std::string const&, unsigned char, std::vector<std::byte, std::allocator<std::byte> > const&, coap_fixed_point_t const&, bool) in coap/CoAPController.cpp:822
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: coap_pdu_init in /tmp/libcoap/src/pdu.c:82
  3: coap_handle_dgram in /tmp/libcoap/src/net.c:1564
  4: coap_handle_dgram_for_proto in /tmp/libcoap/src/net.c:1127
  5: coap_read_session in /tmp/libcoap/src/net.c:1238
  6: coap_io_do_events in /tmp/libcoap/src/net.c:1520
  7: coap_run_once in /tmp/libcoap/src/coap_io.c:1587
  8: CoAPController::sendClientMessage(std::string const&, unsigned char, std::vector<std::byte, std::allocator<std::byte> > const&, coap_fixed_point_t const&, bool) in coap/CoAPController.cpp:822
  9: testCoAP() in TestCoap/main.cpp:82
  10: main in TesCoap/main.cpp:128

19,770 (720 direct, 19,050 indirect) bytes in 15 blocks are definitely lost in loss record 93 of 93
  in CoAPController::sendClientMessage(std::string const&, unsigned char, std::vector<std::byte, std::allocator<std::byte> > const&, coap_fixed_point_t const&, bool) in coap/CoAPController.cpp:800
  1: malloc in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: coap_malloc_node in /tmp/libcoap/src/net.c:87
  3: coap_new_node in /tmp/libcoap/src/net.c:250
  4: coap_send in /tmp/libcoap/src/net.c:1003
  5: CoAPController::sendClientMessage(std::string const&, unsigned char, std::vector<std::byte, std::allocator<std::byte> > const&, coap_fixed_point_t const&, bool) in coap/CoAPController.cpp:800
  6: testCoAP() in TestCoap/main.cpp:82
  7: main in TestCoap/main.cpp:128

The application is running inside a docker container.

What am I doing wrong here? What do I forget?

Thanks in advance!

```
    static void responseHandler(struct coap_context_t */*context*/,
                                coap_session_t */*session*/,
                                coap_pdu_t */*sent*/,
                                coap_pdu_t *received,
                                const coap_tid_t id)
    {
        coap_show_pdu(LOG_DEBUG, received);

        int responseClass = COAP_RESPONSE_CLASS(received->code);
        if (responseClass == 2)
        {
            coap_log(coap_log_t::LOG_DEBUG, "CoAP: Message with id %d successfully sent.", id);
        }
        else
        {
            const char* responsePhrase = coap_response_phrase(received->code);

            std::stringstream message;
            message << "Sending CoAP message failed: ";

            if (responsePhrase == nullptr)
            {
                message << "error code: " << received->code;
            }
            else
            {
                message << responsePhrase;
            }

            message << ".";

            throw DescriptiveException(message.str());
        }
    }

void CoAPController::sendClientMessage(const std::string &path, uint8_t method,
                                           const std::vector<std::byte> &data, const coap_fixed_point_t &ackTimeout,
                                           const bool confirmable)
    {
        coap_context_t  *ctx = nullptr;
        coap_session_t *session = nullptr;
        coap_pdu_t *pdu = nullptr;

        coap_startup();

        /* create CoAP context and a client session */
        ctx = coap_new_context(nullptr);

        coap_address_t clientRequestAddress({0, {{0, {0}}}}

        if (!ctx || !(session = coap_new_client_session(ctx, nullptr, &clientRequestAddress,
                                                        COAP_PROTO_UDP)))
        {
            coap_log(coap_log_t::LOG_EMERG, "cannot create client session\n");
            cleanup(ctx, session);
            throw DescriptiveException("Cannot create client session");
        }

        /* Register response handler for this message. */
        coap_register_response_handler(ctx, responseHandler);

        /* Set confirmable. */
        uint8_t type = COAP_MESSAGE_CON;
        uint32_t blockTimeout = blockTimeoutClientConfirmable;
        if (confirmable == false)
        {
            /* Message is non-confirmable. */
            type = COAP_MESSAGE_NON;
            /* Do not block until something is received because nothing will be received. */
            blockTimeout = blockTimeoutClientNonConfirmable;
        }

        /* construct CoAP message */
        pdu = coap_pdu_init(type,
                            method,
                            messageId_++,
                            coap_session_max_pdu_size(session));

        if (!pdu)
        {
            coap_log( coap_log_t::LOG_EMERG, "cannot create PDU\n" );
            cleanup(ctx, session);
            throw DescriptiveException("Cannot create PDU");
        }

        /* add a Uri-Path option */
        if (!path.empty())
        {
            unsigned char buf[1024] = {0};
            unsigned char *sbuf = buf;
            size_t buflen = sizeof(buf);
            int32_t res = coap_split_path((const uint8_t*)path.c_str(), path.size(), sbuf, &buflen);
            coap_optlist_t *optlist = nullptr;
            while (res--)
            {
                if (!coap_insert_optlist(&optlist, coap_new_optlist(COAP_OPTION_URI_PATH, coap_opt_length(sbuf), coap_opt_value(sbuf))))
                {
                    cleanup(ctx, session, nullptr);
                    throw DescriptiveException("Cannot create uri path.");
                }
                size_t size = coap_opt_size(sbuf);
                sbuf += size;
            }

            coap_optlist_t *option = nullptr;
            for (option = optlist; option; option = option->next )
            {
                switch (option->number)
                {
                    case COAP_OPTION_URI_PORT :
                    case COAP_OPTION_URI_PATH :
                    case COAP_OPTION_URI_QUERY :
                    {
                        if (!coap_add_option(pdu, option->number, option->length,
                                     option->data))
                        {
                            cleanup(ctx, session, nullptr);
                            throw DescriptiveException("Could not add option for client message.");
                        }
                        break;
                    }
                    default:
                    ;
                }
            }

            coap_delete_optlist(optlist);
        }

        /* Set ack timeout, but only if message is confirmable. */
        if (confirmable)
        {
            coap_session_set_ack_timeout(session, ackTimeout);
        }

        /* Convert data to uint8_t array. */
        if (!data.empty())
        {
            const uint8_t *dataToSend = reinterpret_cast<const uint8_t*>(data.data());
            coap_add_data(pdu, data.size(), dataToSend);
        }

        /* and send the PDU */
        errno = 0;
        int sendResult = coap_send(session, pdu);
        int error = errno;
        if (sendResult == COAP_INVALID_TID)
        {
            cleanup(ctx, session, nullptr);
            throw DescriptiveException("Could not send CoAP message.");
        }

        if (error != 0)
        {
            cleanup(ctx, session, nullptr);
            throw DescriptiveException("Could not send CoAP message: " + std::string(strerror(error)));
        }

        try
        {
            /* Send message. */
            /* The handler can throw an exception, that's why the 'try/catch' is there. */
            sendResult = coap_run_once(ctx, blockTimeout);
            error = errno;
        }
        catch(const DescriptiveException &e)
        {
            cleanup(ctx, session);
            throw DescriptiveException("Could not send CoAP message with coap_run_once: " + std::string(e.what()));
        }

        if (sendResult == -1)
        {
            cleanup(ctx, session);
            throw DescriptiveException("Could not send CoAP message with coap_run_once.");
        }

        if (error != 0)
        {
            cleanup(ctx, session);
            throw DescriptiveException("Could not send CoAP message with coap_run_once: " + std::string(strerror(error)));
        }

        cleanup(ctx, session);
    }

    void CoAPController::cleanup(coap_context_t *context, coap_session_t *session)
    {
        if (session != nullptr)
        {
            coap_session_release(session);
        }

        if (context != nullptr)
        {
            coap_free_context(context);
        }

        coap_cleanup();
    }

```

**Comment by mrdeep1** [comment]
@maaikez It appears that you are getting an exception (which causes the application to exit, rather than properly clean up) when coap_run_once() is called.  In particular the function coap_handle_dgram() creates and destroys a pdu, but the valgrind log indicates that the pdu never gets destroyed.  This can only happen if there is an error in coap_dispatch() (or some called function) that is called from coap_handle_dgram().  This called function could be responseHandler().

I would get rid of the try/catch around coap_run_once() and fix that underlying exception.

**Comment by maaikez** [comment]
Thanks that makes it clear. I did throw an exception in the handler when a message could not be sent, for example when the endpoint is not ok. I don't know how else the calling function can know that a call failed. I will take a look into it and remove the 'throw'. Thanks a lot for answering the question

**Comment by mrdeep1** [comment]
If things are correctly set up, then I would not expect the underlying libcoap to fail with an (assert()) exception.  As this is a client application, I would not expect there to be a libcoap endpoint as the libcoap endpoint is typically used for listening servers, so a bit confused by your comment.

[RFC7252 refers to endpoints as an entity participating in the CoAP protocol - libcoap terminology has a listening libcoap endpoint, for which a libcoap session is set up connecting 2 RFC7252 endpoints.]

However, if there is a failure trying to connect/send to a remote endpoint that should have been caught when setting up the client session with coap_new_client_session() with an error return.

Looking at the address that you are trying to send the CoAP packet to
````
coap_address_t clientRequestAddress({0, {{0, {0}}}}
````
it is not a correct statement (missing at least  } and ; ), so is this just an anonymised address?
I would expect this code to be of the form (depends on the address family)
````
  coap_address_init(&clientRequestAddress);
  clientRequestAddress.sa.sa_family = AF_INET;
  clientRequestAddress.sin.sin_addr = ip_address;
  clientRequestAddress.addr.sin.sin_port = htons (5683);
````

I would not normally expect for a libcoap context to be set up and then torn down at the end of the send function, but to set up the context once and then reuse the same context.  Multiple sessions can then be associated withe same context and data sent / received over the appropriate sessions.  It is possible you may have come across an issue (by repeatably setting up / tearing down context) in the code here so it would be good to know where the code actually failed.

**Comment by maaikez** [comment]
@mrdeep1 When I send a request to for example the 'hello' endpoint and this endpoint does not exist, I receive a '4' code (response class 4) in the response handler. Or do you not call it an endpoint because it is a client request? Let's say the uri path.
Or if the server returned a not-4 code, I would like to know as well.
I threw the exception in the responseHandler to let the function that calls 'coap_run_once' know that there was an error during the request (in my case the 'sendClientMessage' function). I did not find out yet how else I can do that. sendResult is not < 0 and errno is 0 as well, when I remove the response handler. So how can I know somehting went wrong during the request?

Yes I created the address another way, this was just for the quick example, sorry. I actually used 'getaddrinfo' from netdb.h. Your way seems very clear as well. Maybe even better. Thanks.

I will change the code so it only creates the context once and try if that works well. 

By the way, I appreciate your explanations, thank you.

**Comment by mrdeep1** [comment]
In RFC7252, the endpoint is that of the endpoint of a connection, in this case you are asking for the 'hello' resource with the Uri-Path.  To quote RFC7252

> The path identifies a resource within the scope of the host and port.

To pass information back from your response handler, I would make use of
````
void coap_session_set_app_data(coap_session_t *session, void *data);
void *coap_session_get_app_data(const coap_session_t *session);
````
which could point to a structure set up prior to you doing `coap_send()` and you update information in that structure in the response handler.

**Comment by mrdeep1** [comment]
@maaikez Do you still need help, or can this be closed off now?

**Comment by maaikez** [comment]
Oh sorry, this can be closed I think. Thank you!
