### ISSUE TITLE
When is it necessary to issue coap_free_async?

### ISSUE THREAD

**Issue by pauluap** [obgm/libcoap#467]
In my server, I get async objects by calling `coap_register_async`.  When I do that and am finished with the async object, what exactly do I need to do with it to clean up?

Do I call

```
coap_remove_async(...);
coap_free_async(...);
```

or just one of them or neither?

**Comment by mrdeep1** [comment]
`coap_register_async()` both creates an async object and adds it to linked list for subsequent lookups (`using coap_find_async()`).
`coap_remove_async()` removes it from the linked list.  `coap_free_async()` deletes the async object.

So, you need to do both in the order `coap_remove_async() `followed by `coap_free_async()`.

**Comment by pauluap** [comment]
Hmm, thank you.  I was asking because I ran into the `assert(session->ref > 0)` failure when freeing one of the async objects.  I guess I must be double freeing, just need to find out how.

**Comment by mrdeep1** [comment]
It looks like a bug in `coap_free_context()` if there is an outstanding async request as the session is still referenced.  You will get a message such as
````
coap-server: src/coap_session.c:1138: coap_free_endpoint: Assertion `session->ref == 0' failed.
````
I will work on a fix.

**Comment by mrdeep1** [comment]
@pauluap See #468 for a possible fix.

**Comment by obgm** [comment]
Closed due to inactivity, fix is provided.
