### ISSUE TITLE
Has anybody ported libcoap on FreeRTOS + LWIP

### ISSUE THREAD

**Issue by fun-works** [obgm/libcoap#471]
I am trying to port libcoap on FreeRTOS + LWIP. I am finding it extremely difficult to resolve the declarations and some circular dependencies on header files(net.h specifically).

Can anybody help me on this ? Thanks in advance.

**Comment by obgm** [comment]
"Extremely difficult" is extremely difficult to address.  In general, the include order in `net.h` already works (cf. `examples/lwip/`). There is a header file `coap_forward_decls.h` with forward declarations that helps resolving dependencies.  Can you point out specific issues you have run into?

**Comment by mrdeep1** [comment]
The principle in #433 of making all the appropriate #include include the coap2/ prefix may help out with name clashes of, say, net.h

**Comment by ranjit4p** [comment]
More details:
I have a firmware code with FreeRTOS and LWIP is ported with. This setup is building successfully.
Now I want to add libcoap into it. Followings are the LWIP configuration:
#define NO_SYS                     1
#define LWIP_SOCKET            1
#define LWIP_NETCONN        1
#define LWIP_NETIF_API         1
#define MEMP_USE_CUSTOM_POOLS 0   -- **I believe, I can resolve the memory module porting. And use the existing mem_alloc() and mem_free(), which are already ported.**

I am having issue in resolving following errors at first:
```
compiling address.c...
../../Source/Component/libcoap-develop/include/coap2/net.h(809): error: unknown type name 'fd_set'
../../Source/Component/libcoap-develop/include/coap2/net.h(809): error: unknown type name 'fd_set'
../../Source/Component/libcoap-develop/include/coap2/net.h(810): error: unknown type name 'fd_set'
compiling async.c...
../../Source/Component/libcoap-develop/include/coap2/net.h(809): error: unknown type name 'fd_set'
../../Source/Component/libcoap-develop/include/coap2/net.h(809): error: unknown type name 'fd_set'
../../Source/Component/libcoap-develop/include/coap2/net.h(810): error: unknown type name 'fd_set'
compiling block.c...
../../Source/Component/libcoap-develop/include/coap2/net.h(809): error: unknown type name 'fd_set'
../../Source/Component/libcoap-develop/include/coap2/net.h(809): error: unknown type name 'fd_set'
../../Source/Component/libcoap-develop/include/coap2/net.h(810): error: unknown type name 'fd_set'
compiling coap_debug.c...
```

**Comment by ranjit4p** [comment]
After working for somtime, I could the above build issues. This was because of some inconsistent flags between the existing LWIP port and one that libcoap expects. However I am getting some more issues as follows:
In LWIP the `ip_addr_t` structure is defined as `struct ip4_addr {
  u32_t addr;
};`.

Now in `coap_io.c:166` file, it expects `sa`  as a field. In the `address.h`, this has been specifically for CONTIKI. I think I can not change the LWIP stuffs, because it is like that for LWIP. But, I believe there is some code missing for LWIP port in `coap_io.c` file. Can any body suggest if I am missing somthing ?

**Comment by obgm** [comment]
If `coap_io.c` is used at all there is something wrong. For LwIP, `coap_io_lwip.c` is used instead. Do you use `coap_config.h.lwip` and the (flags and rules from) `examples/lwip/Makefile`?

**Comment by fun-works** [comment]
This is solved now. Thanks for the support.
