### ISSUE TITLE
Coap sessions not closed if has observing clients

### ISSUE THREAD

**Issue by martinb001** [obgm/libcoap#472]
I'm using several  coap-clients  to observe a resource.
When I later try to close that resource (on the server side), I find that the sessions are not closed to the observing clients. They are closed first when the client stops observing. I assume the server should be able to forcefully end a session.
Anyway I found a workaround  to my problem.  It is not very pretty, but it seems to work. I assume there is a better way to solve the problem.

I created a pull request for this. 
https://github.com/obgm/libcoap/pull/474

**Comment by obgm** [comment]
Thank you. Closing after PR #474 has been superseded by PR #498.
