### ISSUE TITLE
Add a CR to output in coap-client when observing a resource

### ISSUE THREAD

**Issue by martinb001** [obgm/libcoap#473]
Using the coap-client (example/client.c) in observe mode.
./coap-client -m get coap://[::1]/test -s 100

Every time a the resource  is update on the server it will send data to the client that will be printed on stdout.  SInce I don't know how much data is sent I find it hard to determine when data starts and ends. I'm using python to decode.
I would like to have  a special special character (of choice) to be echoed after every set of data . This could be added as an extra option to the coap-client, so that the default behavior could stay the same. 
I've prepared a patch where I add a CR between every set of data. Please have a look. This works well in my test setup.

[0001-Copa-client-to-add-a-CR-to-output-when-observing.patch.gz](https://github.com/obgm/libcoap/files/4324163/0001-Copa-client-to-add-a-CR-to-output-when-observing.patch.gz)

**Comment by mrdeep1** [comment]
I certainly have been frustrated in the past by the output not being nicely formatted etc.  However, there has been a transfer of data which could be binary, and so this data should not be modified at all by the coap-client - it could be redirecting stdout to a file in other use cases.

If you want the data output by the coap-client nicely formatted for parsing etc.,  then however you are generating the observable data at the CoAP server end needs to be modified appropriately.

**Comment by martinb001** [comment]
Thanks for a quick reply! I do understand your view and I agree with what you write. 
The thing is that our coap server needs to be backwards compatible with other devices and adding any  information to the resource data will change the behavior of the system.
My thought was that if we could add an option where the user can specify a special character (could be CR, EOF, or any escape sequence) then it don't need to change the default behavior.  At the same time if I'm the only one with this problem I do understand the hesitation of adding anything. If, though, this can be useful to others as well,  I would be happy to see such a feature.
If not, I will just stay branched out.

**Comment by mrdeep1** [comment]
It is up to @obgm to finally arbitrate, but a `-n` option (no value) for the `coap-client` which adds in a `\n` makes sense to me.  `usage()` would also need updating, as well as `man/coap-client.tx.t.in` to reflect this new option.

**Comment by martinb001** [comment]
Would be much appreciated. Keeping my fingers crossed :-)

**Comment by obgm** [comment]
I have just merged PR #484 (sorry for the delay). Does this resolve your issue?

**Comment by obgm** [comment]
Closed as the issue seems to have been resolved.
