### ISSUE TITLE
DTLS handshake not working for libcoap client example and Californium server via x509 one-way authentication

### ISSUE THREAD

**Issue by PHameete** [obgm/libcoap#477]
# Issue

When connecting with the libcoap-client to my Californium Coap DTLS server using x509 certificates and one-way authentication I run into issues with the DTLS handshake. This fails with both openssl and gnutls, but at different points in the handshake.

For the server I am using a Lets Encrypt certificate (using ECDSA algorithm) issued for our domain `coap.blockbax.com` via ACME DNS01 challenge.

Connecting with the Californium client, and with [go-coap](https://github.com/go-ocf/go-coap) does work as expected.

# Versions used

* californium 2.1.0
* scandium 2.1.0
* go-coap - [master branch commit 298a26e
](https://github.com/go-ocf/go-coap/commit/298a26e4e9c8844001c831154de4b0b65d04f1d1)
* libcoap - [4.2.1 release branch](https://github.com/obgm/libcoap/tree/release-4.2.1)
* gnutls 3.6.9
* openssl 1.1.1c

# Log files

The following log files are attached (highest verbosity):

* libcoap example client (with gnutls) - [logs](https://github.com/obgm/libcoap/files/4393165/libcoap-client-gnutls.log)
* libcoap example client (with openssl) - [logs](https://github.com/obgm/libcoap/files/4393166/libcoap-client-openssl.log)

# Pcap files

A [zip with pcap files](https://github.com/obgm/libcoap/files/4393168/pcaps.zip) (captured UDP for port 5684) is attached for the following cases:

* libcoap client (with gnutls - not working)
* libcoap client (with openssl - not working)
* californium client (working)
* go-coap client (working)

**Comment by mrdeep1** [comment]
The fundamental issue here is that the server is sending the handshake packets with a data length of 2675 bytes (making the packet fragmented into several packets).  The default RX buffer size is 1472 and so the whole of the DTLS packet is not seen by libcoap - hence retries.

Ideally the Californium CoAP DTLS server should strive to not send large packet sizes creating fragmented packets which is not ideal in potentially lossy networks.  The 4 DTLS libraries supported by libcoap have all got their DTLS MTU sizes set to 1152 to get around this fragmentation issue.

The workaround in libcoap is to increase the RX buffer size to receive these larger packets.  This can either be hard coded or set as a compile time parameter - e.g.

$ ./configure CFLAGS="-DCOAP_RXBUFFER_SIZE=5000" <other options>
$ make

It may be that 5000 needs to be increased, but unlikely.

**Comment by PHameete** [comment]
Thanks @mrdeep1 I'll investigate that further. Is it even feasible to reduce packet size if the certificates field alone takes up 2350 bytes?

And do you have an idea what is going wrong in the gnutls case? It seems like the Hello Verify Request is ignored entirely.

**Comment by PHameete** [comment]
Hi @mrdeep1 setting the MTU to 1152 for our server results in a working case with openssl.

May I ask why the number 1152 was chosen as DTLS MTU?

**Comment by sbernard31** [comment]
>Ideally the Californium CoAP DTLS server should strive to not send large packet sizes creating fragmented packets which is not ideal in potentially lossy networks.

As @PHameete  says, the certChain itself take 2350 bytes, so I can't see any way to send a smaller packet from the californium/scandium perspective.

> The 4 DTLS libraries supported by libcoap have all got their DTLS MTU sizes set to 1152 to get around this fragmentation issue.

Do you call "fragmentation issue", just the fact that packet is fragmented ? If yes, I do not understand how setting the MTU to 1152 could avoid this "issue" ? A smaller MTU means more chance to have fragmentation :thinking:

**Comment by mrdeep1** [comment]
I do not know anything about the Californium DTLS server implementation.  What I do know is that GnuTLS has `gnutls_dtls_set_data_mtu()`, OpenSSL has  `SSL_set_mtu()` and mbedTLS has `mbedtls_ssl_set_mtu()` to instruct the TLS library to restrict the size of what it sends in a packet.  Yes, a Cert Chain may be more than a link MTU  (less protocol overhead), but there is something in the DTLS protocol that allows this to be split across several packets.  If put into a UDP packet that is larger than the link MTU supports, then this UDP packet will get fragmented over several packets and re-assembled at the remote network stack back into one packet.  libcoap was not expecting a re-assembled packet of the larger size and only read a part of it into memory for processing - hence issue.

See https://tools.ietf.org/html/rfc7252#section-4.6 for the choice of 1152 bytes.

In terms of GnuTLS, again, libcoap was only reading the first 1152 bytes of a bigger re-assembled packet before passing it to the GnuTLS logic.

@PHameete For reference, how did you set the packet size MTU for DTLS in Californium?

**Comment by PHameete** [comment]
I have now configured the MTU to 1152 in Californium. That causes the client to work using openssl. The client with gnutls still behaves as before - it seems to ignore the Hello Verify Request from the server. This request is only 102 bytes so definitely the fragmentation issue does not hold there.

@sbernard31 perhaps it is a good idea to change the default MTU for Californium to 1152 as well based on the information provided by @mrdeep1 to ensure maximum compatibility.

**Comment by sbernard31** [comment]
Maybe I'm wrong, but I see here 2 different issues mixed in one.

1. setting the MTU correctly to avoid fragmentation. (used to optimize sending data)
2. have a big enough buffer to read packet (even if they was fragmented)

Reading you I understand this is 2. which avoids the interoperability here. The network stack is able to handle the (undesirable) fragmentation, but libcoap is not able to read the whole packet. If I am right, I think you should consider to change the code to be able to read biggest packets.

> @sbernard31 perhaps it is a good idea to change the default MTU for Californium to 1152 

1152 is the CoAP message size (not MTU by the way) advised only when MTU is unknown. In Californium/scandium by default we are using [the MTU of the network interface](https://github.com/eclipse/californium/blob/2.2.0/scandium-core/src/main/java/org/eclipse/californium/scandium/DTLSConnector.java#L700) and if not known we use : 
```java
	public static final int DEFAULT_IPV6_MTU = 1280;
	public static final int DEFAULT_IPV4_MTU = 576
```
For now this behavior sounds good to me. I'm not sure we should change this (@boaks ?)

In perfect world, I think that when MTU does not match, an ICMP packet  [RFC1191] "Datagram Too Big" indications or ICMPv6 [RFC4443] "Packet Too Big" indications should be used.
Or after some retransmission(2or3), DTLS stack should try to fragment in smaller part.
(https://tools.ietf.org/html/rfc6347#section-4.1.1.1)

**Comment by mrdeep1** [comment]
Interesting - the gnutls issue appears to be gnutls version dependent (using latest develop branch of libcoap)
gnutls is 3.5.19 - works
gnutls of 3.6.4 - fails

This may be down to the comment in https://github.com/eclipse/californium/issues/1260
````
I looked at the libcoap client (with gnutls - not working) capture.

And I see several problems at client side :

the first CLIENT_HELLO use a Random of 32 \0 bytes, Cookie field MUST be empty.
then CLIENT_HELLO should be retransmitted using same parameters + the cookie in HELLO_VERIFY, in the capture Random change all the time.
(see https://tools.ietf.org/html/rfc6347#section-4.2.1)
````
Working gnutls pcap zip 
[gnutls-3.5.19.pcap.zip](https://github.com/obgm/libcoap/files/4395370/gnutls-3.5.19.pcap.zip)


libcoap does support non-standard builds where you can specify the RX buffer size.  Making the default larger will cause issues with constrained devices.  It is also unclear what the bigger size should be.

If Californium/scandium is using the MTU of the network interface to derive the data size available for the DTLS, why was a packet size of 2675 being sent?

**Comment by PHameete** [comment]
Thank you for testing with a previous version of gnutls @mrdeep1. I have opened an issue with gnutls on their Gitlab: https://gitlab.com/gnutls/gnutls/-/issues/960. I will let them know this is probably a regression issue as expected.

I agree with you it is unexpected that Californium was sending a 2675 byte DTLS message which is much larger than the MTU of my network interface (1500). In my opinion it would be preferred to use DTLS protocol fragmentation once the message exceeds the MTU (not IP fragmentation), so each DTLS (and CoAP!) message fits in a single IP packet. Interestingly, after changing the MTU to 1152 on the CoAP server, Californium did use DTLS fragmentation. I think that discussion should be continued here https://github.com/eclipse/californium/issues/1260#issuecomment-605217918

**Comment by PHameete** [comment]
@mrdeep1 @sbernard31 an update on the GnuTLS random zeroes issue: someone coincidentally ran into this bug as well and opened a merge request. I can try if that fixes the issue I observed at the start of next week.

**Comment by PHameete** [comment]
> If Californium/scandium is using the MTU of the network interface to derive the data size available for the DTLS, why was a packet size of 2675 being sent?

@mrdeep1 the MTU was determined to be 9001 as this server was running on an EC2 interface where the MTU is 9001 and Java can't determine the path MTU. In this case I should have set it to 1280 as recommended by RFC 7252.

**Comment by mrdeep1** [comment]
Yes, the GnuTLS patch fixes my gnutls 3.6.4.

Good to understand why the large packet was sent out.

**Comment by boaks** [comment]
Just to mention:
IP fragmentation is in my experience not that unreliable as frequently read. Instead, PMTU discovery seems to be missing much more frequently. 
In the most case, including this, the cause of the issue is not the MTU nor IP fragmentation, it's the receive buffer size. There are two "hello extension" to handle that, [RFC 6066, Maximum Fragment Length Negotiation](https://tools.ietf.org/html/rfc6066#section-4) and
[Record Size Limit](https://tools.ietf.org/html/rfc8449). Using them to signal a limited buffer size would help more than agree on a fixed size.

**Comment by PHameete** [comment]
@mrdeep1 FYI: the GnuTLS bug will be fixed in version 3.6.13

**Comment by mrdeep1** [comment]
@boaks Excellent pointers.  OpenSSL, GnuTLS and MbedTLS all appear to have support for RFC 6066 max_fragment_length.  However, this can only be set by the client and the server has no control of the RX buffer size.  RFC 8449 deprecates the max_fragment_length with record_size_limit which gives flexibility to both ends.  However it appears to only be supported by GnuTLS - which appears to have had  some issues along the way.

For RFC 6066, the max_fragment length can be 512, 1024, 2048 etc.  If 512, then this potentially expands out to 805 bytes https://tools.ietf.org/html/rfc6066#section-4 and so I assume that for 1024 this expands out to 1317 which is bigger than the 1152 DTLS MTU libcoap enforces for its transmissions.  Not sure without interoperability testing whether this matters.  My gut feeling is that this RFC 6066 enabling should be a runtime option within libcoap.

Certainly simpler for the likes of Californium/scandium to set the DTLS MTU based on the link IP MTU with a maximum IP MTU of 1500 if the interface exceeds that size when working with potentially constrained environments.

**Comment by sbernard31** [comment]
> Certainly simpler for the likes of Californium/scandium to set the DTLS MTU based on the link IP MTU with a maximum IP MTU of 1500 if the interface exceeds that size when working with potentially constrained environments.

@boaks starts to implement this : https://github.com/eclipse/californium/pull/1264

> Making the default larger will cause issues with constrained devices. It is also unclear what the bigger size should be.

Without the constrained devices restriction it could be very large as few KB of memory should not be an issue.
With the constrained devices restriction, maybe you should focus a buffer size compatible with a 1500 MTU ? I don't know if this will be acceptable for constrained devices ?

**Comment by mrdeep1** [comment]
@sbernard31 The RX buffer size is set to 1472 which is the IPv4 UDP data payload size for a interface MTU of 1500.  The IPv6 UDP payload is smaller so 1472 is fine and should be fine for constrained devices (there also is a libcoap compile time flag -DCCOAP_CONSTRAINED_STACK which moves the RX buffer from the stack into a mutex protected static variable).

**Comment by PHameete** [comment]
Can confirm I'm using an MTU of 1500 bytes now on Californium side and libcoap + openssl works well with this.

**Comment by mrdeep1** [comment]
@PHameete Many thanks for confirming this and testing it out.  I will look at getting RFC 6066 max_fragment_length implemented - but make it a run time option.

**Comment by boaks** [comment]
@mrdeep1 

Indeed, the 6066 is also not optimal for embedded, but available, The 800 is somehow very pessimistic. 

> 5 bytes of headers, 512 bytes of application data, 256 bytes of padding, and 32 bytes of MAC.

256 bytes padding depends on the cipher suite. It's not used for the normal handshake messages and I would not consider large paddings to be used for constraint use-cases. So, if a client signals 512 I guess, no useful server will send 200 padding bytes  :-).

The other  RFC 8449 is currently also not implemented for Californium/Scandium. It's on our list. Maybe a good idea to add that to tinydtls as well.

**Comment by obgm** [comment]
> Indeed, the 6066 is also not optimal for embedded, but available,

Actually, [RFC 7925](https://tools.ietf.org/html/rfc7925#section-15) even requires client-side support.

> The other RFC 8449 is currently also not implemented for Californium/Scandium. It's on our list. Maybe a good idea to add that to tinydtls as well.

Definitely!

**Comment by PHameete** [comment]
Works for the latest Californium build (2.4.0-SNAPSHOT). As https://github.com/eclipse/californium/issues/1260 is now closed, this can be closed as well. Thank you for your help on this!
