### ISSUE TITLE
valgrind reports overlapping source and dest ranges in memcpy in coap_io.c

### ISSUE THREAD

**Issue by john-carter** [obgm/libcoap#48]
Looking at [src/coap_io.c](https://github.com/obgm/libcoap/blob/a5b61409a5b0c5bb21bc0e926ce106cccfd94b83/src/coap_io.c)....

[On line 438](https://github.com/obgm/libcoap/blob/a5b61409a5b0c5bb21bc0e926ce106cccfd94b83/src/coap_io.c#L438) we have..

```
mhdr.msg_name = &(*packet)->src.addr.st;
```

And [on line 507](https://github.com/obgm/libcoap/blob/a5b61409a5b0c5bb21bc0e926ce106cccfd94b83/src/coap_io.c#L507) we have....

```
memcpy(&(*packet)->src.addr.st, mhdr.msg_name, (*packet)->src.size);
```

I'm not entirely sure whether line 507 should be deleted, or changed to a memmove, I suspect deleted.

**Comment by obgm** [comment]
Good catch. I tend to agree that line 507 should be deleted.

**Comment by obgm** [comment]
I have now removed that line after some testing, see commit 8054981.
