### ISSUE TITLE
 Single context for both a server and client with multiple sessions

### ISSUE THREAD

**Issue by luki63** [obgm/libcoap#481]
Hello,
I am trying make a coap "agent" by combining the example server and client into a single executible and would like some advice on how to impliment this.

The core functionality of the agent should include:

- A running server
- A client that can do multiple get/put requests to muitiple other agents
- Encryption using DTLS

Am I correct in understanding that a single context could work for both server and client, and then a session would be needed for each connection between the client and other agent's servers?

I do not think I will have to alter the server much. But for the client it looks like I will have to alter it so that it can handle multiple sessions. For example would I have to alter the message_handler function?

Is there any other considerations I should take?

Thanks.

**Comment by mrdeep1** [comment]
@luki63 Yes, a single coap_context works for both client and server functionality - along with (D)TLS support.

This has been done in #476  which is currently waiting for a merge into develop.  Here, there is the support for the coap-server acting as a coap-proxy with traffic coming into the server from a downstream client and then getting re-transmitted out acting as a client to an upstream server.

In the message_handler(), the incoming session will be unique for the different clients so you then can marry up the data as appropriate.  In #476 it works out which originator client to sent the response back to via the proxy_list[].

**Comment by luki63** [comment]
Thanks for your reply. 

Another quick question. The example client has a fair amount of global variables. I would assume for example method, uri, optlist, and payload will all have to be localized for each individual session. Is that correct? 

Thanks.

**Comment by mrdeep1** [comment]
Absolutely - any information that needs to be maintained over time, but it different for each client session will need to be localized.  You may want to consider maintaining the information associated with a coap_session_t by making use of the coap_session_set_app_data() / coap_session_get_app_data() functions for storing a pointer to a structure containing the data.

One point to stress is that libcoap access to a coap_context_t is not thread safe, so you cannot be using multiple threads for handling multiple clients.

**Comment by mrdeep1** [comment]
@luki63 Can this be closed off now?

**Comment by luki63** [comment]
Hi. Yes. Thanks for your help again.
