### ISSUE TITLE
libcoap - example client and server - missing (client) certificate request in handshake

### ISSUE THREAD

**Issue by boaks** [obgm/libcoap#486]
Version: current master using openssl 1.1.1, Ubuntu 18.04

```
libcoap/examples/coap-server -p 5683 -c server.pem -R trustStore.pem 
libcoap/examples/coap-client -m GET -c client.pem -R trustStore.pem coaps://127.0.0.1:5684/ 
```
Using x509 certificate based handshake, I miss the certificate request and so no client certificate is sent nor checked. According the server's help:

>  -n     		Disable the requirement for clients to have defined
> 	       		client certificates

I would assume, that usually client certificates are requested.

Wireshark capture of handshake
[libcoap-openssl.zip](https://github.com/obgm/libcoap/files/4518540/libcoap-openssl.zip)

**Comment by mrdeep1** [comment]
You need to use the -C opton as per coap-sserver man page to trigger client Certificate checking
````
        -C cafile       PEM file containing the CA Certificate that was used to
                        sign the certfile. If defined, then the client will be
                        given this CA Certificate during the TLS set up.
                        Furthermore, this will trigger the validation of the
                        client certificate.  If certfile is self-signed (as
                        defined by '-c certfile'), then you need to have on the
                        command line the same filename for both the certfile and
                        cafile (as in  '-c certfile -C certfile') to trigger
                        validation
````
The `-R` option is insufficient here.

**Comment by boaks** [comment]
Thanks! So the "certfile" refers to the other peer?
