### ISSUE TITLE
license for utlist.h and uthash.h missing in license, mbedtls missing?

### ISSUE THREAD

**Issue by gocarlos** [obgm/libcoap#491]
1. in `LICENSE` we have `getopt.c` which is only used in examples and normally not shipped as only for windows
2. we have notices about the crypto libs openssl, gnutls, tynydtls -> no mbedtls?
3. no notice about the vendored headers utlist.h and uthash.h?

should point 2 and 3 be in the `LICENSE`?

**Comment by gocarlos** [comment]
ideally we should also add an `SPDX` note to all files, as e.g. linux kernel, mbedtls and others do

**Comment by mrdeep1** [comment]
It is good to have a separate set of eyes to check over mission-creep!

Examples are shipped - e.g. https://packages.debian.org/buster/libcoap2-bin

MbedTLS was an oversight - needs to be fixed.

utlist.h is not needed by anyone building application code - only used internally for the builds.  

utlist.h is embedded in too many header files - this needs to be cleaned up and no longer shipped with built libraries and examples.  I don't think that this is required by applications.

That said I think that they should be in the LICENSE but they have been around a long time before I started any work on libcoap.

Licensing is not my forte.

**Comment by obgm** [comment]
Good point. The utlist license needs to be included as well as it is shipped (at least in the tar balls but strictly speaking, the code is in the binaries as well). I will add this.

**Comment by mrdeep1** [comment]
uthash.h is required for coap_resource_t and coap_session_t.  When these structures are made opaque, then uthash.h is no longer required to be shipped.

utlist.h is not shipped, but is used for creating the binary library files.

**Comment by gocarlos** [comment]
If libcoap uses code in the final library, then it needs to be added, independently of shipping it. E.g. an IoT device will normally not have any headers in the sysroot, still it needs a list of open source components

**Comment by obgm** [comment]
Commit 0fccf2e updates the LICENSE information accordingly. Including SPDX identifiers is actually a good idea, I will do this when preparing the release.

**Comment by obgm** [comment]
Closing off as the license information has been updated a while ago and SPDX identifiers now have been included for the libcoap core components.
