### ISSUE TITLE
Is there a way to determine if there are any outstanding packets to process?

### ISSUE THREAD

**Issue by afontaine-chipkin** [obgm/libcoap#494]
When using coap_run_once, the function returns the number of ms spent in the function or -1 for error but:

- Is there a way to determine if any work has been done?  (i.e. if any packets have been processed)
- Is there a way to determine if there are any other outstanding packets that still need to be processed?

Thanks

**Comment by mrdeep1** [comment]
coap_run_once() (now known as coap_process_io()) will process everything it can before returning.

> Is there a way to determine if any work has been done? (i.e. if any packets have been processed)

No is the simple answer - this information is not counted anywhere

> Is there a way to determine if there are any other outstanding packets that still need to be processed?

coap_context->sendqueue has a list of entries that waiting for confirmation of receipt by the peer.
It should be noted that applications should not access coap_context directly and there is a possibility in the future that coap_context_t will be made opaque to the applications.

**Comment by mrdeep1** [comment]
Closed as coap_io_pending() function is now available in develop branch.
