### ISSUE TITLE
RPK-based DTLS support

### ISSUE THREAD

**Issue by azhurtbayev-klikatech** [obgm/libcoap#500]
Hi there,

I'm looking for a client with RPK-based DTLS support, as it is a mandatory requirement of [RFC7252](https://tools.ietf.org/html/rfc7252#section-9).

I've found a [mailing list](https://sourceforge.net/p/libcoap/mailman/libcoap-developers/thread/09ae01d32bdf%2482716fd0%2487544f70%24%40jpshallow.com/#msg36035684) on this topic, and as I understood it was decided to postpone implementation of RPK, however there hasn't been any changes since that time (2017).

Also, I didn't find anything in source code related to RPK.

Am I missing something? Are there any updates/plans on this feature?

**Comment by mrdeep1** [comment]
At the time RPK was not properly supported within OpenSSL, GnuTLS and MbedTLS support was not there in libcoap and so the work was left on hold.

It is on the ToDo list and needs some time allocated to do the work.

**Comment by obgm** [comment]
RPK support is available with tinyDTLS.

**Comment by azhurtbayev-klikatech** [comment]
One more question - is it possible to add RPK support to the client sample when tinydtls is used?

**Comment by mrdeep1** [comment]
@azhurtbayev-klikatech The RPK setup interface for all the different TLS libraries needs to be added to libcoap (and coap-client / coap-server taught how to use it) before the RPK support can be used in TinyDTLS and other TLS libraries.  This can be done, but someone needs to work on it.

**Comment by mrdeep1** [comment]
PR #510 raised to include RPK support in libcoap.

**Comment by obgm** [comment]
Closed as PR #510 now has been merged.
