### ISSUE TITLE
Can libcoap support Mbedtls for TLS in the future?

### ISSUE THREAD

**Issue by sjtu-sp** [obgm/libcoap#514]
Excuse me, I'm a student from Shanghai JiaoTong University. I want to set a network environment which use CoAP and MbedTLS library, and I want that MbedTLS can support TLS protocol. I find that libcoap can support Mbedtls for only DTLS now, so I want to know if libcoap can support MbedTLS for TLS protocol in the future?

**Comment by obgm** [comment]
As far as I understand, this is on the roadmap.

**Comment by sjtu-sp** [comment]
Excuse me, I‘ve learned the coap_gnutls.c code recently, and I found that there's a callback function coap_sock_read(gnutls_transport_ptr_t context, void *out, size_t outl) in file coap_gnutls.c, I know this function is used to match coap with gnutls. But I don't know the specific differences between coap_sock_read() and the original callback function in gnutls_transport_set_pull_function(gnutls_session_t session, gnutls_pull_func pull_func). If I want to write the coap_sock_read() in coap_mbedtls.c, what should I need to do to make the callback function meet the requirements？

**Comment by mrdeep1** [comment]
You will need to provide code for the coap_tls_new_client_session(), coap_tls_new_server_session(), coap_tls_write() and coap_tls_read() functions.  The mbedtls equivalent to gnutls_transport_set_pull_function() is mbedtls_ssl_set_bio().  I would check to see how the dtls is done in gnutls and mbedtls and then look at tls in gnutls to give you a starting point for mbedtls' tls.

**Comment by sjtu-sp** [comment]
Yes, I've write code in those functions, and now I'm confused in coap_sock_read() and coap_sock_write(), I don't know the difference between coap_sock_read() and mbedtls_net_recv().

**Comment by mrdeep1** [comment]
If you look at coap_sock_read() in src/gnutls.c, you will see that in addition doing the recv(), it is modifying  c_session->sock.flags which is needed by the rest of the libcoap to function correctly.

**Comment by sjtu-sp** [comment]
OK, I will try~

**Comment by sjtu-sp** [comment]
Excuse me, I use libcoap_openssl to build a connect, I didn't modify any code in libcoap_openssl.c. I run server with listening a tcp port like: ./coap-server -p 58632, and then I run client as: ./coap-client -m get coaps+tcp://xxx.xxx.xxx.xxx:56832, the "xxx.xxx.xxx.xxx" is my computer's ip, however the server point out "Jun 27 15:58:23.656 ERR  **  [::ffff:xxx.xxx.xxx.xxx]:56832 <-> [::ffff:xxx.xxx.xxx.xxx]:38071 TCP : tid=0: already in-use - dropped", is that the problem of callback functions?~

**Comment by mrdeep1** [comment]
As `"already in-use - dropped"` does not exist in the develop branch, that has to be in your changes to the code.

If you use the example coap-server (built with openssl), you will need to provide it with additional options (e.g. define the PKI certificates using -c and -C options, as you are not defining certificates for coap-client, you also will need to add in the -n option on the coap-server command line) to set it up to listen for CoAP using TLS.  I assume that your coap-server is just using a modified src/coap_mbedtls.c

Once that is done, the examples coap-server will listen on port 58632 TCP and 58632+1 (56833) for TLS over TCP.  [Please note that your ports are defined as 58632 and 56832 - one of then has the 2nd and 3rd digits swapped].

So if you want to make a coaps+tcp:// connection, you will need to connect to the server on port 58633.

I also strongly recommend the use of the -v9 option for both the coap-client and the coap-server to aid debugging.

**Comment by mrdeep1** [comment]
See PR #704 for a working update to support TLS usage with Mbed TLS library.

**Comment by mrdeep1** [comment]
@sjtu-sp TLS support is now available in the Mbed TLS library.

Please confirm this works with you, and then please close off this issue if that is the case.

**Comment by sjtu-sp** [comment]
@mrdeep1 thank you!~
