### ISSUE TITLE
Separate lwip configuration files from code

### ISSUE THREAD

**Issue by christian-herber** [obgm/libcoap#527]
For integration purposes and flexibility, it is important to separate application code from configuration files (e.g. to include configuration files from a location outside of this git)

currently, the following config files are in the git:

- include/coap2/lwippools.h (this is quite odd. other applications might also need to define memory pools, so this shouldn't be in the main include directory)
- examples/lwip/lwipopts.h (same directory contains the header for server examples)

Propsed Solution:

Move both files into a separate folder examples/lwip/config
While we are at it, also move coap_config.h (respectively the link to it)

This will create a single folder containing the configuration files.

**Comment by mrdeep1** [comment]
libcoap LwIP support has been re-written in PR https://github.com/obgm/libcoap/pull/884, and so this should no longer be an issue.  Configuration files are now in the examples/lwip.config/ directory.

**Comment by mrdeep1** [comment]
Closed as fixed in https://github.com/obgm/libcoap/pull/926 which is now in the develop branch.  There is now a config directory.
