### ISSUE TITLE
Fix compiler warnings in lwIP build

### ISSUE THREAD

**Issue by christian-herber** [obgm/libcoap#528]
The lwip build is currently suffering from a lot of compiler warnings (mainly) due to unused parameters:

Just taking net.c as an example:

/libcoap/src/net.c:711:71: warning: unused parameter 'node' [-Wunused-parameter]
/libcoap/src/net.c:1108:27: warning: unused parameter 'ctx' [-Wunused-parameter]
/libcoap/src/net.c:1108:44: warning: unused parameter 'now' [-Wunused-parameter]
/libcoap/src/net.c:2577:12: warning: variable 'us' set but not used [-Wunused-but-set-variable]
/libcoap/src/net.c:2803:29: warning: format '%d' expects argument of type 'int', but argument 2 has type 'coap_tick_t' {aka 'long unsigned int'} [-Wformat=]

These issues should be fixed to clean the build output. For unused parameters, make it explicit they are not used e.g. by
(void) node;
and so on.

**Comment by mrdeep1** [comment]
libcoap LwIP support has been re-written in PR https://github.com/obgm/libcoap/pull/884, and so this should no longer be an issue.

**Comment by mrdeep1** [comment]
See #955 for a fix fir the compiler warnings.
