### ISSUE TITLE
with LWIP:session can not handle ACK message for CON pdu

### ISSUE THREAD

**Issue by luminais** [obgm/libcoap#529]

**Comment by obgm** [comment]
If you expect people investing their time for you, you might want to be a bit more explicit, e. g. provide a description of the failing scenario, logs, and a description how the observed behavior can be reproduced. People wont sit down and guess what you ate trying to tell them.

**Comment by mrdeep1** [comment]
libcoap LwIP support has been re-written in PR #884, and so this should no longer be an issue.

**Comment by mrdeep1** [comment]
Closed as fixed in https://github.com/obgm/libcoap/pull/926 which is now in the develop branch.
