### ISSUE TITLE
transfer large file

### ISSUE THREAD

**Issue by AngusWooster** [obgm/libcoap#533]
Hi
I modified your example code(client.c) to implement PUT method and transmit a file which is large than 1k byte.
It seems that the maximum size is limited as 1024 bytes.
I tried to modify the variable: block = { .num = 0, .m = 0, .szx = 6 }; to block = { .num = **2**, .m = 0, .szx = 6 }; 
It still can not work.

Can you please guide me how to do it. 
Sincerely

**Comment by mrdeep1** [comment]
With the standard coap-client in the develop branch this is done by adding in the` -b 1024` option as in
````
coap-client -m put -f README.md -b 1024 -v9 coap://example.com/test
````

**Comment by AngusWooster** [comment]
Thanks for prompt response.
It's clear how to set it.
