### ISSUE TITLE
Support: catch-all resource URI with parts of the URI?

### ISSUE THREAD

**Issue by dyle71** [obgm/libcoap#534]
Not a bug but a question or how-to:

I'm currently facing the issue to make a list of resources available. The concept is to have this uri:
```
host:port/foo/container/<id>
```
meaning: 
* host:port as usual
* `/foo` first part of the URI
* `/container` a resource which acts as a container like `/students`
* `/<id>` resource identifier, like `1`, `abc`, ...

However, due to the underlying model and the fact that CoAP is not the only way to manipulate the data, I refrain to create and register each known resource with the full path `/foo/container/id`. The elements in the container may come and go and therefore I'd like the container to have some "catch-all" functionality, i.e. I would like the handlers of resource `/foo/container` to also be called on `/foo/container/<id>` (e.g. `/foo/container/123`, ...). I'd then query the URI and check if an `id` (or else) has been passed or not at all and would create the response accordingly.

With this approach, I can handle a plethora of objects w/o bugging into deep with libcoap itself.

I failed to see this in the current libcoap since the resource URIs are hashed and either the URI matches in full or not at all. Some catch-all functionality seems not possible or am I mistaken?

**Comment by mrdeep1** [comment]
`coap_resource_unknown_init()` sets up a pseudo resource that, providing the appropriate (e.g. `GET`) handler is defined will match any resource request that is not defined.  So, you can use `PUT` to create the resource, use `GET` to determine if the resource is there etc.

See the man page for `coap_resource_unknown_init()` ( https://libcoap.net/doc/reference/4.2.1/man_coap_resource.html) which has some example code and look at  `examples/coap-server.c` for handling creation of new, unknown resources.

**Comment by dyle71** [comment]
Thx for the quick reply.

I see. I noticed that `coap_resource_unknown_init()` has been meant for `PUT` since this verb is explicitly mentioned. But obviously, other verbs do as well.

Yet, this is some catch-_really_-_really_-all resource since I cannot create two of these, can I?

If I want to do `/container-for-resources-of-type-A/<foo>`  and `/container-for-resources-of-type-B/<bar>`  (type-C, etc.), I have to do this by myself with the one and single unknown resource for all possible resources, matching the full URI path.

Therefore, the unknown resource provides a single default or otherwise outlet, if no other resource provides an exact match. Yes?

**Comment by mrdeep1** [comment]
Yes, if you call `coap_resource_unknown_init()` twice, the second definition will cause all of the first's information to 'go away'.  So, you can only have one instance of this which will (providing an appropriate request type handler is in place) call the appropriate unknown handler function if the request resource has not been defined.

Matching the URI-Path is made easier with the` coap_get_uri_path()` function (return needs to be subsequently deleted with `coap_delete_string()`). 

You could try defining the resource `/container-for-resources-of-type-A` etc. and then do a POST to that resource with something in the message body to define the sub element to create or update it.  Then you can check for the existence of the sub element by doing something like `GET /container-for-resources-of-type-A?id=foo` to check that `foo `exists or not.

**Comment by dyle71** [comment]
Yes, thx. Actually we do the last already by examining the query part of the URI. And it works. That's ok.

However, from a mere conceptional point of view, we'd prefer something of `/path/container/<id>` as URI and having the container resource picking the child resource at the time of access since the CoAP implementation has not the full authority of these resources at runtime.

Anyway: thx again for taking the time.
