### ISSUE TITLE
Example for ping and pong?

### ISSUE THREAD

**Issue by daohu527** [obgm/libcoap#544]
I read the keepalive related documents and tried it, but I can only receive ping/pong once, why not multiple times?

Below is the implemented code：
## client
```
    // set pong handler
    coap_register_pong_handler(ctx, [](struct coap_context_t *context, 
                                        coap_session_t *session,
                                        coap_pdu_t *received,
                                        const coap_tid_t id) {
                                    std::cout << "pong" << std::endl;
                                    std::cout << id << std::endl;
                                    std::cout << received->data << std::endl;
                                    });
      // set 1s
      coap_context_set_keepalive(ctx, 1);
```

## server
```
    coap_register_ping_handler(ctx, [](struct coap_context_t *context,
                                    coap_session_t *session,
                                    coap_pdu_t *received,
                                    const coap_tid_t id){
                                std::cout << "ping" << std::endl;
                                std::cout << id << std::endl;
                                std::cout << received->data << std::endl;                                
    });
```

But I just receive ping/pong first time, and next time there is nothing print!

## another try

Also I try to send the ping by "coap_session_send_ping" in client, but I receive "nack".
```
    while(true) {
      coap_session_send_ping(session);
      coap_io_process(ctx, 0);
    }
```

**Comment by mrdeep1** [comment]
I think that your issue is that `coap_context_set_keepalive(ctx, 1);` should not be set in pong handler, but should be set once when the `coap_context_t` is set up.  However, I cannot immediately think of why that would be the case.

Your **another try** will potentially be sending out a continual stream of packets.

The keepalive only triggers when the defined number of seconds have elapsed since the last PDU interchange. The following certainly works for me (look at the packet interchange every 5 seconds)
````
Server side
$ coap-server -d5 -v9
Client side
$ coap-client -m put -f TODO coap://127.0.0.1/test
$ coap-client -K 5 -s 60 coap://127.0.0.1/test
````
Use of setting up test is that it can be subscribed to, so that the coap-client does not immediately exit on the initial response.

A review of the verbose log may be useful to debug what is going on here.

**Comment by daohu527** [comment]
I try the test case you provided above, I found the code "**coap_context_set_keepalive(ctx, 1)**" and the command line both provide the some log in server side.  
```
Aug 25 09:16:59.931 DEBG dropped message with invalid code (0.00)
Aug 25 09:16:59.931 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:56458 (if1) UDP : sent 4 bytes
v:1 t:RST c:0.00 i:f83e {} [ ]
Aug 25 09:17:04.932 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:56458 (if1) UDP : received 4 bytes
v:1 t:CON c:0.00 i:f83f {} [ ]
```

seems there is a msg ping/pong send every 5s(in your case), but the problem is "the coap_register_pong_handler and coap_register_ping_handler" just call once.

**Comment by daohu527** [comment]
I notice the ping/pong handle are in 
https://github.com/obgm/libcoap/blob/1739507a1eee6f8831ca7221adaa8d5413527b7f/src/net.c#L2414-L2422

which "COAP_DISABLE_TCP " is 1, why need tcp to use ping and pong feature?

**Comment by mrdeep1** [comment]
Given that you are calling `coap_register_ping_handler()`, I would expect that `context->ping_handler` is not `NULL`.

However, you should only be setting up one `context` in the server, not a new context every time you want to do something different.  I suspect that you are setting up multiple contexts, but not calling` coap_register_ping_handler() `for each one.

COAP_PDU_IS_EMPTY() does not mean  that the is no PDU, it means that the PDU code is 0 and has no other information,  As defined by https://tools.ietf.org/html/rfc7252#section-1.2
````
   Empty Message
      A message with a Code of 0.00; neither a request nor a response.
      An Empty message only contains the 4-byte header.
````
and https://tools.ietf.org/html/rfc7252#section-4.1
````
   An Empty message has the Code field set to 0.00.  The Token Length
   field MUST be set to 0 and bytes of data MUST NOT be present after
   the Message ID field.  If there are any bytes, they MUST be processed
   as a message format error.
````
so that code in pdu.h is correct (and will not always be false) and not to be removed.

**Comment by daohu527** [comment]
@mrdeep1 thx!
I implemented it in the following way. You mean check the ctx in the server side? I will check if there is just one ctx in use.
## client
```
coap_context_set_keepalive(ctx, 1);
coap_register_pong_handler()
```

## server
```
coap_register_ping_handler()
```

**Comment by daohu527** [comment]
I finally found the problem. The cout can't print out message after first callback, the code is below.
```
    coap_register_pong_handler(ctx, [](struct coap_context_t *context, 
                                        coap_session_t *session,
                                        coap_pdu_t *received,
                                        const coap_tid_t id) {
                                    std::cout << "pong" << std::endl;
                                    std::cout << id << std::endl;
                                    std::cout << received->data << std::endl;     //  which is the problem
                                    });
```
If I delete the "std::cout << received->data << std::endl" then it print things well. Maybe the data is empty and cause some error. I will look at this question next，thanks for your help!

**Comment by daohu527** [comment]
I found the problem why not print out. "**If the pointer to the string is null, then all subsequent calls to cout stop working**"

Example
```
 const char* s=0;
 cout << "shown on cout\n";
 cout << "not shown" << s << "not shown either\n";
 cout << "by bye cout, not shown\n";
```

This can explain why it is printed the first time but not afterwards.

**Comment by mrdeep1** [comment]
Looking back at your original code samples
````
    coap_register_ping_handler(ctx, [](struct coap_context_t *context,
                                    coap_session_t *session,
                                    coap_pdu_t *received,
                                    const coap_tid_t id){
                                std::cout << "ping" << std::endl;
                                std::cout << id << std::endl;
                                std::cout << received->data << std::endl;                                
    });
````
when the executing code gets to the `coap_register_ping_handler()` statement, it evaluates and executes the `cout` statements, obtains a ptr to the result (NULL in this case) and then calls the` coap_register_ping_handler()` function which updates` context->ping_handler`.  So the call effectively ends up being (having done the `cout` stuff once)
````
coap_register_ping_handler(ctx, NULL);
````
Hence why the pings continue, but it only gets 'reported' once when the function is invocated.

**Comment by daohu527** [comment]
Sorry I didn't make it clear, **the "context->ping_handler" is null when I use the command line**, and when I used my own code, it's not null but just can't print out, which cause by "received->data". 

When I delete the "count << received->data << endl", it work well and can work every 1s print out "ping/pong".
