### ISSUE TITLE
How to pass data to coap_register_handler

### ISSUE THREAD

**Issue by daohu527** [obgm/libcoap#545]
I mean I have an c++ class CoapServer. and want to pass data in the response message callback (**coap_register_handler**).  
```c++
CoapServer::CoapServer(ServerConfig* config) {
  coap_startup();
  
  // Debug
  coap_set_log_level((coap_log_t)9);

  ctx = coap_new_context(nullptr);
  endpoint = coap_new_endpoint(ctx, &dst, COAP_PROTO_UDP);

  coap_str_const_t *uri = coap_make_str_const(resource_name.c_str());
  coap_resource_t *resource = 
      coap_resource_init(uri, COAP_RESOURCE_FLAGS_NOTIFY_NON);

    coap_register_handler(resource, COAP_REQUEST_GET, 
      [this](coap_context_t *ctx,                                      // which is the problem
         struct coap_resource_t *resource,
         coap_session_t *session,
         coap_pdu_t *request,
         coap_binary_t *token ,
         coap_string_t *query ,
         coap_pdu_t *response) {
        
        std::lock_guard<std::mutex> lock(this->data_mutex);     // Thread safe？？

        coap_add_data_blocked_response(resource, session, request, response, 
          token, COAP_MEDIATYPE_TEXT_PLAIN, 1, this->len_, this->data_);

      });
```

## question
1. If I use lambada and pass "this" into callback handler, there will be a compile error "lambada can not convert to coap_method_handler_t". Then how can I pass data into callback ? I found there is "  void *user_data;" in coap_resource_t, Can use this way? I don't want to use global variables.  

2. Then another question is if I use a user_data, how can I **concurrent execution the coap_method_handler_t callback**, I say If are multi requests, the response will linear execution?

**Comment by mrdeep1** [comment]
1. coap_resource_set_userdata() can be used to set ->user_data(), which can be then retrieved using coap_resource_get_userdata() inside the GET request handler.

2. libcoap is currently not multi-thread safe - there must only be one thread accessing the libcoap API.

**Comment by daohu527** [comment]
Why is the size not passed in? As is a void*

**Comment by mrdeep1** [comment]
Yes, that is the right way to go.  It is a generic pointer to an object which could be a simple string, a struct that contains just size and data, or some complex structure - the void* gives total flexibility.
