### ISSUE TITLE
How can I get multiple requests data?

### ISSUE THREAD

**Issue by daohu527** [obgm/libcoap#546]
1. I mean if there are multi requests arrived, then libcoap use epoll to get the data and call coap_register_handler one by one. If the coap_register_handler is blocked, then the whole process will blocked ?

2. next step, I want to collect multi requests data, the method I think of is to put the data into a lock-free queue in "coap register handler", and then the external program can read the data.

**Comment by mrdeep1** [comment]
1. Strictly speaking it is the handler registered by coap_register_handler() that is called, and yes, if there is blocking function in that handler then things will get choked up until the handler returns.

2.  When the handler returns, then the data visible to the handler gets deleted when the received PDU gets deleted.  So any queue pointers built in the handler are no longer valid.  Any incoming data in the handler must be processed in the handler.

**Comment by daohu527** [comment]
> When the handler returns, then the data visible to the handler gets deleted when the received PDU gets deleted. So any queue pointers built in the handler are no longer valid. Any incoming data in the handler must be processed in the handler.

So I must deep copy the data, and put it in a lock free queue.   


The reason for this is I want to confirm whether **multiple terminals have sent messages** to the server, and then do the next step.

**Comment by daohu527** [comment]
It looks like have to manage the memory myself.
