### ISSUE TITLE
How the server receives and sends data？

### ISSUE THREAD

**Issue by daohu527** [obgm/libcoap#547]
Because the server has to receive data all the time, I receive data in a while loop. Therefore, I am going to use one thread to execute the "coap server", and then use another thread to receive and send data. At this time, how do I call the "coap server" to receive and send data?  

Are there any good practices in this area? Because the examples I saw are all single-threaded.

**Comment by mrdeep1** [comment]
The code is not multi-threaded at present - separate application threads concurrently calling coap_*() functions will lead to things getting broken.

The server design is that the CoAP environment is set up, then there is a loop calling `coap_io_process()` (or `coap_run_once() `in older code versions).  If there is any i/o activity a sub function to coap_io_process() will call the appropriate callback handler to process the i/o or possibly call an event / failure handler.

There are some extra coap_*() calls in coap-server in het main i/o loop - mainly for doing async traffic (for testing response delays), or indicating that time has changed for anyone observing the time resource.  These being called by another thread are not thread-safe. 

So, keep all the coap_*() calls in the main i/o loop as in coap-server.

**Comment by obgm** [comment]
You can also use multiple CoAP contexts (as long as you use the malloc'ed  storage model), i.e., one context for your server application and one context for your client application. Transfer of application data then could be handled by some sort of MT-safe messaging queue.

**Comment by daohu527** [comment]
thx! @obgm @mrdeep1 

If it is only implemented in the main loop, it is difficult for me to deal with my business logic.  
```
coap_register_handler(resource, COAP_REQUEST_GET, func);  // my business code to get data

coap_resource_notify_observers(resource, nullptr);  // my business code to push data

while (1) {
  coap_io_process(ctx, COAP_IO_WAIT);
}
```

## multi thread
If just one thread, **I must do all business in the main thread**, I also need to do other things so I want to another thread put data to coap main thread, and then coap send and receive data.

receive data flow
```
coap client ---> coap server  --->  receive buffer (maybe a queue) -> another thread read from the buffer
```

put data flow
```
another thread send data to queue ---> queue ---> coap server(read from queue and send data) -> client
```

I try to init coap in one thread and pass the object(coap ctx and other things) to another thread then run but failed, It seems must init and run coap in one thread ?

**Comment by obgm** [comment]
CoAP init an run may be in different threads. What exactly happens when it fails?

**Comment by daohu527** [comment]
I deal with this example
```
#include <iostream>
#include <thread>
#include <memory>

class Task
{
public:
    void execute(std::string command)
    {
        for(int i = 0; i < 5; i++)
        {
            std::cout<<command<<" :: "<<i<<std::endl;
        }
    }
};
int main()
{
    std::shared_ptr<Task> taskPtr = std::make_shared<Task>();

    std::thread th(&Task::execute, taskPtr, "Sample Task");
    th.join();
    return 0;
}
```

## Coap
I create a class CoapServer, and do the init and main loop things in "init" func, and then in main loop, I will create another std::thread to run it. I didn't Push data, and when I start to run it's core dumped.
```
int main(int argc, char** argv) {
  std::shared_ptr<CoapServer> server = std::make_shared<CoapServer>();

  std::thread(&CoapServer::Init, server);

  while(true) {
    // server->Push("push", "coap123");      // which is disable when debug
    std::this_thread::sleep_for(std::chrono::microseconds(10));
  }

  return 0;
}
```

The core dump msg
```
Core was generated by `./bazel-bin/modules/interface/coap_interface/example/server'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f02a5ebac37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

**Comment by obgm** [comment]
DId you make sure that CoapServer::Init has finished before you start the CoAP server's main loop?
The abort pretty much looks like a failing `assert()`. When you compile the code with `-g` you can get more information on the failing part with gdb.

**Comment by daohu527** [comment]
Ok, I will try tomorrow.  
First I try in single thread, in the main loop I call  the same func(init), and then I change to multi-thread.

I will deal with the debug message.

**Comment by daohu527** [comment]
You are right! there are two mistakes.

1. Grammatical errors
```
std::thread(&CoapServer::Init, server);  // wrong
std::thread t1(&CoapServer::Init, server);  //right
```

2. Be sure to synchronize
The initialization thread will create a "resource", which will take some time, and then the main thread will immediately assign a value to the "resource", so illegal memory access will be made. It can work normally after modification.
```
  coap_resource_t *resource = config_resource_map[resource_name];

  if (resource == nullptr) {               // need to check resource is null
    coap_log(LOG_ERR, "CoapServer::Push resource is null!\n");
    return;
  }

  coap_resource_set_userdata(resource, reinterpret_cast<void*>(msg));
```

**Comment by daohu527** [comment]
Addition,

If server just notify the client, and client didn't send any data to server, the resource will destroy？？ I just send 2 notify to client and then there're no msg send again, when I send a ping/pong then the server can continues send notify msgs.
```
  while(true) {
    coap_resource_notify_observers(resource, nullptr);
    coap_io_process(ctx, COAP_IO_WAIT);
  }
```

**Comment by mrdeep1** [comment]
> If server just notify the client, and client didn't send any data to server, the resource will destroy？？ I just send 2 notify to client and then there're no msg send again, when I send a ping/pong then the server can continues send notify msgs.   while(true) {
    coap_resource_notify_observers(resource, nullptr);
    coap_io_process(ctx, COAP_IO_WAIT);
  }

What you describe is what I would expect.  You need to enable logging (`coap_set_log_level()`) to get a better understanding of what is happening in general.

The man pages on libcoap.net are getting out of date, however https://libcoap.net/doc/reference/4.2.1/man_coap_io.html states (using the old names)

> If timeout_ms is set to COAP_RUN_BLOCK, then coap_run_once() will wait indefinitely for the first new input packet to come in. 

which in the latest man page reads as

> If timeout_ms is set to COAP_IO_WAIT, then coap_io_process() will block until the next internal action (e.g. packet retransmit) if any, or block until the next packet is received whichever is the sooner and do the necessary processing.

so the `coap_io_process(ctx, COAP_IO_WAIT);` will wait until the next packet comes in (which is the client ping in your case) before sending off the next observe response.  Change `COAP_IO_WAIT `to, say, `1000`.

**Comment by daohu527** [comment]
Seems you are right. change the "coap_io_process(ctx, COAP_IO_WAIT)" to "coap_io_process(ctx, 1000)" works.

Addition,

Do I need to free the msg myself? I malloc the message call CoapMessage and then get it by "coap_resource_get_userdata" then after send the msg, I free the msg myself, but seems something wrong? I just receive 2 right msgs.

The log server side 
```
terra@in_dev_docker:/terra$ ./bazel-bin/modules/interface/coap_interface/example/server
Sep 03 20:48:41.604 DEBG created UDP  endpoint [::1]:5683
Sep 03 20:48:45.692 DEBG ***[::1]:5683 <-> [::1]:51223 (if1) UDP : new incoming session
Sep 03 20:48:45.692 DEBG *  [::1]:5683 <-> [::1]:51223 (if1) UDP : received 11 bytes
v:1 t:CON c:GET i:0000 {} [ Observe:0, Uri-Path:hello ]
Sep 03 20:48:45.692 DEBG call custom handler for resource 'hello'
Sep 03 20:48:45.692 DEBG create new subscription
Sep 03 20:48:45.692 DEBG *  [::1]:5683 <-> [::1]:51223 (if1) UDP : sent 21 bytes
v:1 t:ACK c:2.05 i:0000 {} [ ETag:\xB9\x71\x37\xED, Observe:0, Content-Format:text/plain, Max-Age:1 ] :: 'coap123'
Sep 03 20:48:45.692 DEBG *  [::1]:5683 <-> [::1]:51223 (if1) UDP : sent 22 bytes
v:1 t:NON c:2.05 i:0be5 {} [ ETag:\xB9\x71\x37\xED, Observe:1, Content-Format:text/plain, Max-Age:1 ] :: 'coap123'
Sep 03 20:48:46.692 DEBG *  [::1]:5683 <-> [::1]:51223 (if1) UDP : sent 22 bytes
v:1 t:NON c:2.05 i:0be6 {} [ ETag:\xC7\xDC\xCF\xB4, Observe:2, Content-Format:text/plain, Max-Age:1 ] :: 'hello\x003'
Sep 03 20:48:47.700 DEBG *  [::1]:5683 <-> [::1]:51223 (if1) UDP : sent 22 bytes
v:1 t:NON c:2.05 i:0be7 {} [ ETag:\xC7\xDC\xCF\xB4, Observe:3, Content-Format:text/plain, Max-Age:1 ] :: 'hello\x003'
Sep 03 20:48:48.703 DEBG *  [::1]:5683 <-> [::1]:51223 (if1) UDP : sent 22 bytes
v:1 t:NON c:2.05 i:0be8 {} [ ETag:\xC7\xDC\xCF\xB4, Observe:4, Content-Format:text/plain, Max-Age:1 ] :: 'hello\x003'
Sep 03 20:48:49.708 DEBG *  [::1]:5683 <-> [::1]:51223 (if1) UDP : sent 22 bytes
```

client side
```
terra@in_dev_docker:/terra$ ./bazel-bin/modules/interface/coap_interface/example/client
Sep 03 20:48:45.692 DEBG ***[::1]:51223 <-> [::1]:5683 UDP : new outgoing session
Sep 03 20:48:45.692 DEBG *  [::1]:51223 <-> [::1]:5683 UDP : sent 11 bytes
v:1 t:CON c:GET i:0000 {} [ Observe:0, Uri-Path:hello ]
Sep 03 20:48:45.692 DEBG ** [::1]:51223 <-> [::1]:5683 UDP : tid=0: added to retransmit queue (2313ms)
Sep 03 20:48:45.692 DEBG *  [::1]:51223 <-> [::1]:5683 UDP : received 21 bytes
v:1 t:ACK c:2.05 i:0000 {} [ ETag:\xB9\x71\x37\xED, Observe:0, Content-Format:text/plain, Max-Age:1 ] :: 'coap123'
Sep 03 20:48:45.692 DEBG ** [::1]:51223 <-> [::1]:5683 UDP : tid=0: removed
Received:
Sep 03 20:48:45.692 DEBG *  [::1]:51223 <-> [::1]:5683 UDP : received 22 bytes
v:1 t:NON c:2.05 i:0be5 {} [ ETag:\xB9\x71\x37\xED, Observe:1, Content-Format:text/plain, Max-Age:1 ] :: 'coap123'
Received:
Sep 03 20:48:46.692 DEBG *  [::1]:51223 <-> [::1]:5683 UDP : received 22 bytes
v:1 t:NON c:2.05 i:0be6 {} [ ETag:\xC7\xDC\xCF\xB4, Observe:2, Content-Format:text/plain, Max-Age:1 ] :: 'hello\x003'
Received:
Sep 03 20:48:47.700 DEBG *  [::1]:51223 <-> [::1]:5683 UDP : received 22 bytes
v:1 t:NON c:2.05 i:0be7 {} [ ETag:\xC7\xDC\xCF\xB4, Observe:3, Content-Format:text/plain, Max-Age:1 ] :: 'hello\x003'
Received:
```

The code 
```
    coap_register_handler(resource, COAP_REQUEST_GET,
        [](coap_context_t* ctx,
           struct coap_resource_t* resource,
           coap_session_t* session,
           coap_pdu_t* request,
           coap_binary_t* token,
           coap_string_t* query,
           coap_pdu_t* response) {
            // Get data
            auto msg = reinterpret_cast<CoapMessage*>(
                                  coap_resource_get_userdata(resource));

            if (msg == nullptr || msg->data == nullptr) {
              coap_log(LOG_ERR, "msg is null\n");
              coap_add_data(response, 13, (const uint8_t*)"Invalid value");
              return;
            }

            coap_add_data_blocked_response(resource, session, request, 
              response, token, COAP_MEDIATYPE_TEXT_PLAIN, 1, 
              msg->len, msg->data);
            
            // delete msg;                          // which seems wrong????
        });
```

**Comment by mrdeep1** [comment]
You need to spend time debugging the code (with gdb etc.) to verify that there are not coding errors before posting questions as it is difficult to second guess what is really happening and people responding have other deadlines to meet.  We want to help you in your use of libcoap if there are bugs etc. in libcoap, but realistically cannot provide general programming support.

Think 'who owns the `user_data `held by resource' and if that data is freed off, then subsequent `coap_resource_get_userdata(resource)` will return an invalid ptr etc. Ask what really needs to be done here?

Ask yourself why is `hellox\0003` 7 bytes long and should it only be 5 etc.

**Comment by daohu527** [comment]
Thank you for your reply, I will continue to debug tomorrow to see if I can find the problem
