### ISSUE TITLE
How the client distinguishs between different resources in observer

### ISSUE THREAD

**Issue by FelicxFoster** [obgm/libcoap#549]
In observer mode, If my client wants to get two different resources from server, how my client distinguishs between the two different resources when it gets the resources ? thx

**Comment by mrdeep1** [comment]
As said in #548 

> I would suggest that you use a unique token for each new request - https://libcoap.net/doc/reference/4.2.1/man_coap_pdu_setup.html so that you can match responses with requests.

Tokens are used by the client to match responses with requests.  An observe response is treated as an additional response to the initial request and therefore has the same token (only for the first block returned if the response body has to be broken up over several packets using BLOCK2 - requesting the next block should use a new token).  https://tools.ietf.org/html/rfc7252#section-2.2 states
````
   CoAP request and response semantics are carried in CoAP messages,
   which include either a Method Code or Response Code, respectively.
   Optional (or default) request and response information, such as the
   URI and payload media type are carried as CoAP options.  A Token is
   used to match responses to requests independently from the underlying
   messages (Section 5.3).  (Note that the Token is a concept separate
   from the Message ID.)
````
Your client code needs to track the Token used for each resource request that requests it is to be observed.
