### ISSUE TITLE
How to use certificates to encrypt traffic in coap-server/coap-client

### ISSUE THREAD

**Issue by Vitaliy69** [obgm/libcoap#553]
I generated 2 files by a command:

`openssl req -newkey rsa:2048 -x509 -sha256 -days 3650 -nodes -out cert.crt -keyout cert.key`

How do to use it to encrypt traffic?

Tried:

```
coap-server-openssl -c cert.pem -C cert.pem -d 10 -A 192.168.1.76
coap-client-openssl -m put coap://192.168.1.76/message -e "Hello" -c cert.crt -C cert.crt
```

But wireshark show plain text traffic.

**Comment by mrdeep1** [comment]
It is unusual to use the same certificate for both the client and server, but is OK.  If they are different, they need to be created by the same CA so that they can mutually authenticate each other.

https://libcoap.net/doc/reference/4.2.1/man_coap-server.html states
````
OPTIONS - PKI
(If supported by underlying (D)TLS library)

-c certfile
Use the specified PEM file which contains the CERTIFICATE and PRIVATE KEY information.
````
so certainly in your case you need to combine both `cert.crt` and `cert.key` into a single file.  In the develop branch, you can use the` -j` option instead as in
````
coap-server-openssl -c cert.pem -j cert.key -C cert.pem -d 10 -A 192.168.1.76
coap-client-openssl -m put coap://192.168.1.76/message -e "Hello" -c cert.crt -j cert.key -C cert.crt
````
All this presumes that libcoap has been compiled with underlying (D)TLS support and that you are linking against the appropriate library.  See https://libcoap.net/doc/reference/4.2.1/man_coap_encryption.html

As always, it is worth running the utilities with full logging (`-v9` option) enabled to see what actually is happening.

**Comment by Vitaliy69** [comment]
Thanks in advance!

> It is unusual to use the same certificate for both the client and server
What do you mean? Can I see an usual example, starting out from generating self-signed certificates in OpenSSL? 

I am having some trouble understanding encryption. Thought that the server should only have a private key and the client should have a public one. But there are more parameters in the documentation which confused me.

**Comment by mrdeep1** [comment]
Apologies - I missed that you used `cert.pem` and `cert.crt`, when you gave the one example of generating the two (output) files, and then used the different file names in the coap-client and coap-server examples.  So you would have been using 2 sets of certificate based files - which is more usual.  However, the other thing I also missed was that the URI should have started with `coaps://` not `coap://` saying that the session is to be encrypted.  I have updated my previous response accordingly.

Both ends have to have a public and private key and the public keys are exchanged during encryption session setup.  This means that end A can encrypt data with `public-B`, send it to B and then B can decrypt the data with `private-B` and vice-versa.  Mutual authentication (i.e. both ends trust each other) is done by the 2 public keys being signed (created) by a common CA.  The `coap-server` `-n` option can override this trust checking.

How to set up CAs and generate public/private keys from them using openssl is freely available on the internet.

**Comment by mrdeep1** [comment]
I would generally expect to see the usage being something like (modelling on your example - others may want to use different options that are not PKI specific) where the naming gives a better idea as to what is happening (I have also dropped the suffix -openssl to match the more generic name, not the name you built it as)
````
coap-server -c server.pem -j server.key -C ca.pem -d 10 -A 192.168.1.76
coap-client -m put coaps://192.168.1.76/message -e "Hello" -c client.pem -j client.key -C ca.pem
````
or for the client to use anonymous certificates (as does your browser when you connect to the internet using https:// - the server does not care who you are, but encryption is to be used) and the server is using a self-signed certificate (which you created in your initial example)
````
coap-server-openssl -c cert.crt -j cert.key -C cert.crt -d 10 -A 192.168.1.76 -n
coap-client-openssl -m put coaps://192.168.1.76/message -e "Hello"
````

**Comment by Vitaliy69** [comment]
> I also missed was that the URI should have started with coaps:// not coap://
Thank you! It was main main error. Ok, I generated self-signed certificates:

`openssl req -newkey rsa:2048  -x509  -sha256 -days 3650  -nodes -out cert.crt -keyout cert.key`

Then combined it into the single file:

`cat "cert.key" "cert.crt" > cert.pem`

Used 2 different for client and server. And got the errors on server side:

```
coap-server-openssl -c /home/vitaliy/cert_server/cert.pem -C /home/vitaliy/cert_server/cert.pem -d 10 -A 192.168.1.76 -v9
Sep 22 13:57:49 DEBG created UDP  endpoint 192.168.1.76:5683
Sep 22 13:57:49 DEBG created DTLS endpoint 192.168.1.76:5684
Sep 22 13:57:49 DEBG created TCP  endpoint 192.168.1.76:5683
Sep 22 13:57:49 DEBG created TLS  endpoint 192.168.1.76:5684
Sep 22 13:57:53 DEBG ***192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: new incoming session
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: received 282 bytes
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: sent 60 bytes
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: received 314 bytes
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: SSL_accept:before SSL initialization
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: SSL_accept:before SSL initialization
Sep 22 13:57:53 INFO SNI '192.168.1.76' requested
Sep 22 13:57:53 DEBG    192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: Using PKI ciphers
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: SSL_accept:SSLv3/TLS read client hello
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: SSL_accept:SSLv3/TLS write server hello
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: sent 1152 bytes
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: SSL_accept:SSLv3/TLS write certificate
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: SSL_accept:SSLv3/TLS write key exchange
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: SSL_accept:SSLv3/TLS write certificate request
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: sent 604 bytes
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: SSL_accept:SSLv3/TLS write server done
Sep 22 13:57:53 DEBG *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: received 15 bytes
Sep 22 13:57:53 INFO *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: SSL3 alert read:fatal:unknown CA
Sep 22 13:57:53 WARN *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: SSL_accept:error in error
Sep 22 13:57:53 WARN *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: tlsv1 alert unknown ca at SSL routines:dtls1_read_bytes
Sep 22 13:57:53 DEBG ***192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: session disconnected (reason 3)
Sep 22 13:57:53 DEBG ***EVENT: 0x0000
Sep 22 13:57:54 DEBG ***192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: session closed
```

On the client side:

```
coap-client-openssl -m put coaps://192.168.1.76/message -e "Hello World" -c /home/vitaliy/cert_client/cert.pem -C /home/vitaliy/cert_client/cert.pem -v9
Sep 22 13:57:53 DEBG ***192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: new outgoing session
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: SSL_connect:before SSL initialization
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: sent 282 bytes
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: SSL_connect:SSLv3/TLS write client hello
Sep 22 13:57:53 DEBG sending CoAP request:
Sep 22 13:57:53 DEBG ** 192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: tid=45715: delayed
Sep 22 13:57:53 DEBG timeout is set to 90 seconds
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: received 60 bytes
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: SSL_connect:SSLv3/TLS write client hello
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: SSL_connect:DTLS1 read hello verify request
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: sent 314 bytes
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: SSL_connect:SSLv3/TLS write client hello
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: received 1152 bytes
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: SSL_connect:SSLv3/TLS write client hello
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: received 604 bytes
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: SSL_connect:SSLv3/TLS read server hello
Sep 22 13:57:53 WARN     192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: self signed certificate: 'Vitaliy Gribko' depth=0
Sep 22 13:57:53 INFO CN 'Vitaliy Gribko' presented by server (Certificate)
Sep 22 13:57:53 DEBG *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: sent 15 bytes
Sep 22 13:57:53 INFO *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: SSL3 alert write:fatal:unknown CA
Sep 22 13:57:53 WARN *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: SSL_connect:error in error
Sep 22 13:57:53 WARN *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: certificate verify failed at SSL routines:tls_process_server_certificate
Sep 22 13:57:53 DEBG ***EVENT: 0x0200
Sep 22 13:57:53 DEBG ***192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: session disconnected (reason 3)
Sep 22 13:57:53 DEBG ***EVENT: 0x0000
Sep 22 13:57:53 DEBG ** 192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: tid=45715: not transmitted after disconnect
Sep 22 13:57:53 DEBG ***192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: session closed
```
 The content of cert.pem file:

```
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```

What have I done wrong?

**Comment by mrdeep1** [comment]
As mentioned previously, the 2 sets of certificates MUST be generated by the same CA for mutual authentication.  You have generated 2 sets of certificates that have no relationship with each other.
````
Server
Sep 22 13:57:53 WARN *  192.168.1.76:5684 <-> 192.168.1.76:36725 (if2) DTLS: tlsv1 alert unknown ca at SSL routines:dtls1_read_bytes
Client
Sep 22 13:57:53 INFO *  192.168.1.76:36725 <-> 192.168.1.76:5684 DTLS: SSL3 alert write:fatal:unknown CA
````
is returned as the server has no knowledge of the clients CA and vice versa when checking for mutual trust of each other.  Use of the `-n` option on the server will disable the mutual CA authentication.

**Comment by Vitaliy69** [comment]
> As mentioned previously, the 2 sets of certificates MUST be generated by the same CA for mutual authentication

Ok. 

Generate RSA private key (2048 bit):
`openssl genrsa -out private.pem 2048`

Generate a Certificate Signing Request (CSR):
`openssl req -sha256 -new -key private.pem -out cert.crt`

Generate a self-signed certificate that is valid for a year with sha256 hash:
```
openssl x509 -req -sha256 -days 365 -in cert.crt -signkey private.pem -out server.csr
openssl x509 -req -sha256 -days 365 -in cert.crt -signkey private.pem -out client.csr
```

Combine into single file:
```
cat "server.csr" "private.pem" > server.pem
cat "client.csr" "private.pem" > client.pem
```

Execute (-j is unknown option):

```
coap-server-openssl -c server.pem -C server.pem -d 10 -A 192.168.1.76 -v9
coap-client-openssl -m put coaps://192.168.1.76/message -e "Hello World" -c client.pem -C client.pem -v9
```

And get still:

```
Sep 22 16:56:52 INFO *  192.168.1.76:57190 <-> 192.168.1.76:5684 DTLS: SSL3 alert read:fatal:unknown CA
Sep 22 16:56:52 WARN *  192.168.1.76:57190 <-> 192.168.1.76:5684 DTLS: SSL_connect:error in error
```

This is seif-signed certificates from cert.crt. Perhaps this case does not work with self-signed certificates.

But all works fine with this case (use the same file for server and client):

```
coap-server-openssl -c server.pem -C server.pem -d 10 -A 192.168.1.76 -v9
coap-client-openssl -m put coaps://192.168.1.76/message -e "Hello World" -c server.pem -C server.pem -v9
```

Or in this case on any problems:

```
coap-server-openssl -c server.pem -C server.pem -d 10 -A 192.168.1.76 -v9 -n
coap-client-openssl -m put coaps://192.168.1.76/message -e "Hello World" -v9
```

Any ideas how can I fix "unknown CA" error?

**Comment by mrdeep1** [comment]
You have not generated a standalone CA which then the CSRs generated for the server/client need to be submitted to for the CA to signing and creation of the final PEM files.  I would be expecting a file named something like `ca-cert.pem` which is a copy of the CA certificate to be used with the `-C` option.

It would appear that you are missing steps in your procedure.

I would expect you to end up with a list of files named something like (for ease of working out which is connected with what)
````
ca-cert.pem
ca-key.pem

server-csr.pem
server-cert.pem
server-key.pem
server-cert+key.pem  (contains both CERT and KEY)

client-csr.pem
client-cert.pem
client-key.pem
client-cert+key.pem  (contains both CERT and KEY)  
````
created appropriately, and then be using `server-cert+key.pem` or `client-cert+key.pem` for the respective `-c` option and `ca-cert.pem` for the `-C` option.

**Comment by Vitaliy69** [comment]
Create a root key and certificate:
```
openssl genrsa -out rootCA.key 2048
openssl req -x509 -new -key rootCA.key -days 10000 -out rootCA.crt
```

Combine into single file (don't sure it step is required):
`cat "rootCA.crt" "rootCA.key" > rootCA.pem `

Generate server key:
`openssl genrsa -out server.key 2048`

Generate server certificate:
`openssl req -new -key server.key -out server.csr`

Sign server certificate by root one (CA):
`openssl x509 -req -in server.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out server.crt -days 5000`

Combine into single file:
`cat "server.crt" "server.key" > server.pem`

The same steps for client:
```
openssl genrsa -out client.key 2048
openssl req -new -key client.key -out client.csr
openssl x509 -req -in client.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out client.crt -days 5000

cat "client.crt" "client.key" > client.pem
```

server.pem and client.pen signed by the same CA (rootCA.crt).

Then I installed CA in the system (Ubuntu 20.04):

```
sudo mkdir /usr/share/ca-certificates/extra
sudo cp rootCA.crt /usr/share/ca-certificates/extra/rootCA.crt
sudo dpkg-reconfigure ca-certificates
sudo update-ca-certificates
```

Testing:
```
coap-server-openssl -c server.pem -C rootCA.pem -d 10 -A 192.168.1.76 -v9
coap-client-openssl -c client.pem -C rootCA.pem -m put coaps://192.168.1.76/message -e "Hello World" -v9
```

Anyway got the error:
```
Sep 23 14:32:32 INFO *  192.168.1.76:57058 <-> 192.168.1.76:5684 DTLS: SSL3 alert write:fatal:unknown CA
Sep 23 14:32:32 WARN *  192.168.1.76:57058 <-> 192.168.1.76:5684 DTLS: SSL_connect:error in error
Sep 23 14:32:32 WARN *  192.168.1.76:57058 <-> 192.168.1.76:5684 DTLS: certificate verify failed at SSL routines:tls_process_server_certificate
```

Also tried:

```
coap-server-openssl -c server.pem -C rootCA.crt -d 10 -A 192.168.1.76 -v9
coap-client-openssl -c client.pem -C rootCA.crt -m put coaps://192.168.1.76/message -e "Hello World" -v9
```

or

```
coap-server-openssl -c server.pem -C server.pem -R rootCA.crt -d 10 -A 192.168.1.76 -v9
coap-client-openssl -c client.pem -C server.pem -R rootCA.crt -m put coaps://192.168.1.76/message -e "Hello World" -v9
```

I'm confused. Have you tested this scenario on Linux with self-signed certificates?

It seems to me the server is rejecting the client certificate.

There are 3 different CA settings for TLS server:

The server chain provided to the client (SSL_CTX_add_extra_chain_cert): https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_add_extra_chain_cert.html

The CAs you announce to support to the client (SSL_CTX_set_client_CA_list): https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_client_CA_list.html

The CAs you actually use to verify (SSL_CTX_load_verify_locations): https://www.openssl.org/docs/man1.0.2/man3/SSL_CTX_load_verify_locations.html

You might be configuring your server with the wrong equivalent in your bindings.

Anonymous certificates with mutual authentication works fine only.

**Comment by Vitaliy69** [comment]
Execute the command:

```
openssl verify -CAfile rootCA.crt server.pem 
...
error 18 at 0 depth lookup: self signed certificate
error server.pem: verification failed
```

Seems I missed the instruction: 

> Whatever method you use to generate the certificate and key files, the Common Name value used for the server and client certificates/keys must each differ from the Common Name value used for the CA certificate. Otherwise, the certificate and key files will not work for servers compiled using OpenSSL.

I used the same Common Name for each certificate (rootCA.crt, server.crt, client.crt). It was wrong.

After changes:

```
openssl verify -CAfile rootCA.crt server.pem client.pem 
server.pem: OK
client.pem: OK
```

And coap-server/coap-client works fine!

Thanks for helping. Please, add commands above with my remarks to the manual.

**Comment by mrdeep1** [comment]
Certificate Revocation List (CRL) can be added to a certificate so that if a certificate is compromised, it can be revoked on checking the CRL.  Here, as there is no CRL, the TLS library CRL checker is complaining that there is no CRL to check against - which could be a fatal error (certificate is potentially unsafe to use) depending on your security requirements.  Here, libcoap has been configured by a parameter (not run-time configurable) passed to it by the server / client to override this behavior - hence warning.

I would expect to see the common name CN= to be of the form '`client.example.test`', not '`CoAP Client`'.

As there are primers out on the internet for setting up certificates, I am reluctant to create another one for libcoap.  This specific issue you raised can also be found in an internet search should other people be struggling in the same area.

**Comment by Vitaliy69** [comment]
Ok, TIA. The issue can be closed.
