### ISSUE TITLE
coap_network_send: No such device

### ISSUE THREAD

**Issue by dismirlian** [obgm/libcoap#559]
Hi all. In my application I open a client session to a server's IPv6 address. The UDP traffic goes through a "tunnel" network interface which can "disappear" and reappear later, if the program that created it crashes.

Everything works correctly until the network interface disappears and reappears; in this case, libcoap prints error messages: `coap_network_send: No such device`. I suspect this is because libcoap calls `connect` in `coap_socket_connect_udp`, and then `send` in `coap_network_send` instead of directly calling `sendto`. If my diagnosis is correct, is there a way of using libcoap without `connect`ing UDP sockets? If not, what could be the issue?

Thank you!

**Comment by mrdeep1** [comment]
I was not involved with the initial code design.  However, using connect() causes the interface, routing information etc. to get "cached", so your surmise looks to be correct as the tunnel interface will go away and get recreated at a different memory address.

Some studies have shown this to gives up to a 3 x kernel performance benefit when using send()/sendto() with connect() 

It also means that packets coming back from the peer are dropped if they do not come from the remote IP/port.

If the source port of the client changes, then RFC7252 indicates that this is to be treated as a different endpoint - e.g. different client

>    (Note that a client implementation can use the same token for any
>    request if it uses a different endpoint each time, e.g., a different
>    source port number.) 

so the source port needs to be maintained across any restart of the client session.

I suspect changing the network level code  to not use connect() is non-trivial as the non-Posix ports need to be considered as well. 

You could try adding in some code  that tries to re-connect on detection of ENODEV error in coap_network_send()

**Comment by dismirlian** [comment]
Hi @mrdeep1, thanks for your answer. Yes, I'm aware of the performance benefits. I implemented your suggestion and it works on my scenario, but I don't know if I've handled all the cases/platforms correctly; I seriously doubt it. Could you please review it?:

https://github.com/dismirlian/libcoap/commit/e3462e44628c3f37a0ed962a30e89767f06de078

Thank you!

**Comment by mrdeep1** [comment]
Your code certainly has a socket leak every time this happens.  I would have expected the updated code to only be in the send() section as it is only a send() issue.
````
  } else if (sock->flags & COAP_SOCKET_CONNECTED) {
  .... handle ENODEV
  } else {
````
  
As per

>        Some protocol sockets (e.g., datagram sockets in the UNIX and
>        Internet domains) may use connect() multiple times to change their
>        association.

I would be expecting you to just be doing a connect() on the existing socket, not coap_socket_connect_udp().

**Comment by dismirlian** [comment]
@mrdeep1, thanks for your support. It turns out I misdiagnosed the problem, I'm sorry for the confusion.

The issue is not with `COAP_SOCKET_CONNECTED` sockets, but with disconnected ones (I have also a server session running). For the client sessions, it works correctly if I don't bind the local interface.

The issue is with the server session, specifically, when the session is created with `coap_make_session`, libcoap assigns an interface index based on the packet index, and this is never updated if the interface gets recreated. My fix is as follows:

https://github.com/dismirlian/libcoap/commit/fe78be78c80a005ddd5b259a6f80d678be627a93

What do you think?

Thanks again.

**Comment by mrdeep1** [comment]
Ah, I had not realized that you were binding to the local interface as it is not normally something I do.

Linux will not use the same interface index number when an interface goes away and is rebuilt.  Your fix looks good and safe.

I suggest that you raise a PR for this.

**Comment by dismirlian** [comment]
Great, thanks for your support! I'll submit a PR.
