### ISSUE TITLE
Libcoap implementation in embedded devices 

### ISSUE THREAD

**Issue by ChayMa19** [obgm/libcoap#562]
Hello,

I want to implement the libcoap in my STM32 board.
I noticed that this lib is somehow dedicated to the Linux platform.
Is their any official library that I can use for boards like STM32 ?

Thank you for your help.

best regards,

**Comment by obgm** [comment]
libcoap is known to run on a number of STM32 boards. As it is designed to run on top of at least a minimal OS that provides a system clock and a network stack you should use some sort of operating system underneath.  Out of the box, libcoap supports Contiki, lwip, and RIOT.

**Comment by ChayMa19** [comment]
So, I can't implement it using RTOS ??

**Comment by obgm** [comment]
Not right out of the box. However, there is an esp-idf port which uses FreeRTOS underneath, so it should not be that difficult to adapt.

**Comment by ChayMa19** [comment]
Thank you for your help! I don't use the ESP32 board in my case. So, I think I should find other alternatives.
Thank you again for your information.

**Comment by obgm** [comment]
You are welcome. I take it that I can close off this issue.
