### ISSUE TITLE
libcoap/openssl example/coap-server ; certificate_authorities 

### ISSUE THREAD

**Issue by boaks** [obgm/libcoap#563]
Version 4.2.1

According [7.4.4. Certificate Request](https://tools.ietf.org/html/rfc5246#section-7.4.4) "A list of the distinguished names [X501] of acceptable certificate_authorities", is sent by the server.

If the example coap-server is started using:

`coap-server -p 5683 -c server.pem -C ca.pem -R trusts.pem` 
  
a ip-capture shows the DNs of the `ca.pem`, but not the ones of the `trusts.pem`.

For me this seems to be irritating. The documentation says:

```
 -c certfile
    Use the specified PEM file which contains the CERTIFICATE and PRIVATE KEY information. Note: if -k key is defined, you need to define -c cafile as well to have the server support both PSK and PKI. 
-n
    Disable the requirement for clients to have defined client certificates 
-C cafile
    PEM file containing the CA Certificate that was used to sign the certfile defined using -c certfile. If defined, then the client will be given this CA Certificate during the TLS set up. Furthermore, this will trigger the validation of the client certificate. If certfile is self-signed (as defined by -c certfile), then you need to have on the command line the same filename for both the certfile and cafile (as in -c certfile -C certfile) to trigger validation. 
-R root_cafile
    PEM file containing the set of trusted root CAs that are to be used to validate the server certificate. The -C cafile does not have to be in this list and is "trusted" for the verification. Alternatively, this can point to a directory containing a set of CA PEM files. 
```

If the -C cafile contains the CA Certificate  of the "certfile", why are the DNs of that cafile the used as "certificate_authorities"? I would have expected, that the DNs of the -R trusts.pem are used.

**Comment by boaks** [comment]
Let me add, I think it's a typo, that the -R roots are used to "validate the server certificate", I think, it should be the client certificate.

**Comment by boaks** [comment]
is the cafile really used for signing the certfile of this peer (server)?
Or is it used for signing of the certfile of the other peer (client)?

**Comment by mrdeep1** [comment]
Looking at outstanding PR #561 may help clarify some things here.

> a ip-capture shows the DNs of the ca.pem, but not the ones of the trusts.pem.

This is correct behavior.  It is defining a list of CAs (using DNs) for the client to search through its repositories to see if there are any certificates signed by a CA in the client list to use and to provide as a Client Certificate in the ongoing handshake.  If no CAs are provided, then the client does not need to return a Certificate (as usually happens when your browser visits a https site).  This is done (OpenSSL) by SSL_set_client_CA_list() and SSL_CTX_set_verify().  It should be noted that this CA list is not trusted per se.  libcoap does add the contents of ca.pem to the trusted CA list (potentially primed by trusts.pem), but not sure if this actually is needed for the server.

> Let me add, I think it's a typo, that the -R roots are used to "validate the server certificate", I think, it should be the client certificate.

Yes - this is a typo - good catch.  Will get it fixed.

> is the cafile really used for signing the certfile of this peer (server)?
> Or is it used for signing of the certfile of the other peer (client)?

ca.pem is used to trigger a request for a suitably signed certificate from the client.  If the server's certificate was also signed by the same CA, then checks can be put in place (are by default) to verify that both the client and server certificates are signed by the same CA and hence there is a level of mutual authentication and trust in place.  Normally I would expect to see a single CA in ca.pem, but it should also support a CA and zero or more Intermediate CAs in an authority chain.

For the client, `-C ca.pem` make less sense than using `-R trusts.pem` but the contents of ca.pem are added to the trust store so the client can validate the provided server certificate.

The different TLS libraries supported by libcoap are triggered to do the providing of the request for the client certificate in different ways - hence PR #561

**Comment by boaks** [comment]
```
-C cafile	PEM file containing the CA Certificate that was used to sign the certfile.
```

For me this is misleading. It doesn't to point to the certfile a few lines above in that docu. It points to that of the other peer. Adding that hint would make it in my opinion clearer.

```
If defined, then the client will be given this CA Certificate during the TLS set up.
```

Though this is the docu of the server, the server doesn't give the CA certificate to the client.

```
If certfile is self-signed (as defined by '-c certfile'), then you need to have on the command line the same filename for both the certfile and cafile (as in  '-c certfile -C certfile') to trigger validation
```

This doesn't make sense in my opinion! The -C is the CA of the **OTHER** peer's certificate. 

> This is correct behavior. 

If only the -C DNs are send by the server, then the other trusts in -R maybe not considered by the client.

**Comment by boaks** [comment]
> If no CAs are provided, then the client does not need to return a Certificate (as usually happens when your browser visits a https site).

[RFC5246 - 7.4.4. Certificate Request](https://tools.ietf.org/html/rfc5246#page-53)

> If the certificate_authorities list is empty, then the client MAY send any certificate of the appropriate ClientCertificateType, unless there is some external arrangement to the contrary.

[RFC5246 - 7.4.6. Client Certificate](https://tools.ietf.org/html/rfc5246#page-55)

> If no suitable certificate is available, the client MUST send a certificate message containing no certificates.

In my opinion, it's not the empty trusted issuer list, which cause the client not to send a certificate. But only sending a subset of the trusted issuers may end up in no suitable certificate.

**Comment by mrdeep1** [comment]
> In my opinion, it's not the empty trusted issuer list, which cause the client not to send a certificate. But only sending a subset of the trusted issuers may end up in no suitable certificate.

The TLS libraries supported by libcoap respond differently - and I think in one library there is a difference between DTLS and TLS.

#561 tries to make things consistent from the application control perspective.  I will update the help documentation in that PR to reflect and correct to what is happening in the different option usage.

**Comment by mrdeep1** [comment]
#561 currently has the following documentation in the man page for coap-server(3), which I will tweak (but already addresses some of your comments)
````
       -c certfile
           PEM file or PKCS11 URI for the certificate. The private key can be in the PEM file, or use
           the same PKCS11 URI. If not, the private key is defined by -j keyfile.

           Note: if -k key is defined, you need to define -c certfile as well to have the server support
           both PSK and PKI.

       -j keyfile
           PEM file or PKCS11 URI for the private key for the certificate in -c certfile if the
           parameter is different from certfile in -c certfile.

       -n
           Disable the requirement for clients to have defined client certificates. Disable remote peer
           certificate checking.

       -z
           Disable checking that local and peer certificates share a common CA (used for mutual
           authentication).

       -C cafile
           PEM file or PKCS11 URI for the CA certificate that was used to sign the certfile. If defined,
           then the client will be given this CA certificate during the TLS set up. Furthermore, this
           will trigger the validation of the client certificate. If certfile is self-signed (as defined
           by -c certfile), then you need to have on the command line the same filename for both the
           certfile and cafile (as in -c certfile -C certfile) to trigger validation.

       -J pkcs11_pin
           The user pin to unlock access to the PKCS11 token.

       -M
           Raw Public Key (RPK) PEM file that contains both PUBLIC KEY and PRIVATE KEY or just EC
           PRIVATE KEY. (GnuTLS and TinyDTLS support only) -C cafile not required.

       -R root_cafile
           PEM file containing the set of trusted root CAs that are to be used to validate the server
           certificate. The -C cafile does not have to be in this list and is "trusted" for the
           verification. Alternatively, this can point to a directory containing a set of CA PEM files.
````

**Comment by boaks** [comment]
> -z
>            Disable checking that local and peer certificates share a common CA (used for mutual
>            authentication).

That explains my confusion on the `-C` that `mutual authentication`is considered to be the standard and the arguments are designed for that case. But with that, self-signed will not match. Therefore the hint according self-signed seems for me to be irritating.

**Comment by boaks** [comment]
Anyway, with the idea, that -C is for a common CA, my interoperation tests works again. Thanks!

**Comment by mrdeep1** [comment]
Good that that works.  Hopefully my (yet to be) updated documentation will help others to understand the intent.

**Comment by mrdeep1** [comment]
coap-server help and man page updated (man page shown) which should now be clear in #561
````
       -c certfile
           PEM file or PKCS11 URI for the certificate. The private key can
           also be in the PEM file, or has the same PKCS11 URI. If not, the
           private key is defined by -j keyfile.

           Note: if -k key is defined, you need to define -c certfile as well
           to have the server support both PSK and PKI.

       -j keyfile
           PEM file or PKCS11 URI for the private key for the certificate in
           -c certfile if the parameter is different from certfile in -c
           certfile.

       -n
           Disable remote peer certificate checking. This gives clients the
           ability to use PKI, but without any defined certificates.

       -z
           Disable checking that server and client certificates were signed by
           a common CA (used for mutual authentication).

       -C cafile
           PEM file or PKCS11 URI that contains a list of one or more CAs that
           are to be passed to the client for the client to determine what
           client certificate to use. Normally, this list of CAs would be the
           root CA and and any intermediate CAs. Ideally the server
           certificate should be signed by the same CA so that mutual
           authentication can take place. The contents of cafile are added to
           the trusted store of root CAs. Using the -C or -R options will will
           trigger the validation of the client certificate unless overridden
           by the -n option.

       -J pkcs11_pin
           The user pin to unlock access to the PKCS11 token.

       -M
           Raw Public Key (RPK) PEM file or PKCS11 URI that contains both
           PUBLIC KEY and PRIVATE KEY or just EC PRIVATE KEY. (GnuTLS and
           TinyDTLS(PEM) support only).  -C cafile is not required.

       -R root_cafile
           PEM file containing the set of trusted root CAs that are to be used
           to validate the client certificate. As -C cafile list of CAs is
           already trusted, this option does not normally have to be used.
           Alternatively, this can point to a directory containing a set of CA
           PEM files. Using the -C or -R options will will trigger the
           validation of the client certificate unless overridden by the -n
           option.
````

**Comment by boaks** [comment]
> that contains a list of one or more CAs that are to be passed to the client for the client to determine what client certificate to use.

That's much clearer.

> that contains a list of one or more CAs certificates. The DNs of them are to be passed to the client to determine, which client certificate is to be used.

just as alternative

**Comment by mrdeep1** [comment]
I thought about using DN, recognizing that this is how it actually is done, but most users of libcoap apps may struggle with understanding what a CA is, let alone what a DN is as PKI is an alien language.  Ready to be corrected though!

**Comment by boaks** [comment]
I guess you're right about the DN.

**Comment by obgm** [comment]
@boaks Can you have a look at PR #561?

**Comment by boaks** [comment]
After the Californium 2.5.0 release (today) and some other "office" jobs, I will try to spend some time into test that. I guess, it will be at the weekend :-).

**Comment by boaks** [comment]
I've tested the openssl and tinydtls variants, for mbedtls the time was too short. I hope, I find some time the next days (or at the next weekend). 
For me, the new options/arguments for x509 improves the usage of the examples.

**Comment by boaks** [comment]
FMPOV, PR561 looks great!
