### ISSUE TITLE
Is multicast server supported only on IPv6?

### ISSUE THREAD

**Issue by szekelyisz** [obgm/libcoap#566]
It looks like `coap_join_mcast_group()` is IPv6 only. Is that intentional? Should it just work on v4 as well? Any gotchas implementing it for v4?

**Comment by mrdeep1** [comment]
There is no reason why IPV4 cannot be supported - it just needs to be coded and all libcoap code that does multicast checks need to be checked out as well.

**Comment by szekelyisz** [comment]
OK I can look into that. I guess as a first step `coap_join_mcast_group()` will have to test whether the provided group name maps to v4 or v6 address and proceed accordingly. Shall we just use the first result from `getaddrinfo()`? Or give priority to IPv6 over v4?

**Comment by mrdeep1** [comment]
getaddrinfo() currently has an IPv6 hint.
https://tools.ietf.org/html/rfc7252#section-12.8 defines what the registered CoAP multicast addresses are.
If the group name is not an IPv4 or IPv6 address, then  I believe that IPv6 should be given priority over IPv4.

**Comment by szekelyisz** [comment]
OK that makes sense.

There's a problem though with this and #570. If the group name is actually a DNS name, then it's impossible to know in advance whether it maps to an IPv4 or IPv6 address. But the interface specification is different: on IPv4 you specify the interface with its IP address, but on IPv6 you use the interface index. So far I'm using a single 32-bit integer to express both types which works well technically, but the caller has to know what to put there. So there's a possibility that the caller is expecting the name to resolve to a IPv4 address, and passes the address of the intended interface. If, in that case, the name happens to resolve to a v6 address at runtime, the call will most likely fail with 'no such interface' or something like that. How do you prefer to handle this situation? A few possible solutions:

* Pass one more parameter to `coap_join_mcast_group_intf()` that determines the address family and the interface specification parameter is handled accordingly. Most likely this will mean the entire function should respect that and resolve the name only to that address family (via a hint).
* Separate the parameters for the two address families. `coap_join_mcast_group_intf()` will accept two parameters to specify the interface, one for v4 and one for v6. This would make more sense if the entire function would work on IPv4 and IPv6 in parallel, meaning it would consider both v6 and v4 results from the address resolution and use the v4 interface specification for v4 results, and likewise for v6. I think technically this is the cleanest way, but its real-world usefulness is questionable.
* Ignore this, document it and move on.

What do you think? Any other ideas?

**Comment by mrdeep1** [comment]
In the IPv4 world, there is ioctl(fd,SIOCGIFNAME, &ifr) to get the interface name and then ioctl(fd, SIOCGIFADDR, &ifr) which maps the interface name to an IP address so a singular index parameter is fine. 

That said, it may be worth considering making the interface parameter not an index, but an interface name (or NULL if not to be used) as most people recognize the name, but have to go through some coding torture to determine what the interface index is.

However, I am not sure how well interface names are used in embedded OSes

**Comment by szekelyisz** [comment]
LwIP has named interfaces for sure.

Contiki doesn't matter here because the entire `coap_join_mcast_group` function is defined to a stub when WITH_CONTIKI is defined. ESP-IDF, which I'm working on this patch for, gets around this by not defining WITH_LWIP so it can rely on LwIP's socket API layer to do the job for this function for example.

But LwIP doesn't support these ioctls. I'll go take a look, it shouldn't be too hard to implement them.

**Comment by obgm** [comment]
PR #617 has been  merged to address this issue (containing parts of PR #587). Does this resolve the issue?

**Comment by obgm** [comment]
Closing off as resolved.
