### ISSUE TITLE
ipv4 multicast  send error

### ISSUE THREAD

**Issue by galaxyofo** [obgm/libcoap#57]
coap server join to multicast 224.10.10.11,  coap client send to server, it will occur error
***************************log
local 224.10.10.11
remote 192.168.1.110

Dec 13 15:45:44 CRIT coap_send_impl: Invalid argument
Dec 13 15:45:44 DEBG cannot send response for message 57659

modify   IN_MULTICAST(a->addr.sin.sin_addr.s_addr) to IN_MULTICAST(htonl(a->addr.sin.sin_addr.s_addr)) 
**************************
bug is clear!!!! please check it!
*********************************************
 static inline int 
  _coap_is_mcast_impl(const coap_address_t *a) {
    if (!a)
      return 0;
  
   switch (a->addr.sa.sa_family) {
   case AF_INET:
     return IN_MULTICAST(a->addr.sin.sin_addr.s_addr);
   case  AF_INET6:
     return IN6_IS_ADDR_MULTICAST(&a->addr.sin6.sin6_addr);
   default:  /* fall through and signal error */
     ;   
    }
   return 0;
  }
****************************************************

**Comment by obgm** [comment]
Thanks, the input to IN_MULTICAST indeed needs to be in host byte order. Commit 292b0f0 fixes that.
