### ISSUE TITLE
mbedtls - add support for DTLS 1.2 CID

### ISSUE THREAD

**Issue by boaks** [obgm/libcoap#572]
Would it be possible to add [DTLS 1.2 CID](https://datatracker.ietf.org/doc/draft-ietf-tls-dtls-connection-id/) support to the mbedtls binding?

coap_mbedtls.c, similar 

```
  mbedtls_ssl_conf_min_version(&m_env->conf, MBEDTLS_SSL_MAJOR_VERSION_3,
                               MBEDTLS_SSL_MINOR_VERSION_3);

  if ((ret = mbedtls_ssl_setup(&m_env->ssl, &m_env->conf)) != 0) {
    goto fail;
  }

#ifdef MBEDTLS_SSL_DTLS_CONNECTION_ID
  // enable passive DTLS CID support
  // requires to ensure/adjust the extension id in 
  // mbedtls - include/mbedtls/ssl.h
  // for compatibility to 53
  // see https://mailarchive.ietf.org/arch/msg/tls/3wCyihI6Y7ZlciwcSDaQ322myYY  
  // ssl.h ; #define MBEDTLS_TLS_EXT_CID                        53
  mbedtls_ssl_set_cid(&m_env->ssl, MBEDTLS_SSL_CID_ENABLED, NULL, 0);
#endif
  
  mbedtls_ssl_set_bio(&m_env->ssl, c_session, coap_dgram_write,
                      coap_dgram_read, NULL);
```

I've created also an issue [mbedtls - issue supporting CID](https://github.com/ARMmbed/mbedtls/issues/3892) to adapt to the assigned value.

**Comment by mrdeep1** [comment]
Reading https://tools.ietf.org/html/draft-ietf-tls-dtls-connection-id-08, is this to be set specifically for the client to indicate CID support, but not for the server to indicate that it will only be sending a zero length CID?

Should there not be consideration for the client to indicate what CID it wants to be used?
Do we want to be able to define the CID that the server wants to use?

**Comment by boaks** [comment]
Let me try to define:

cid - passive: the peer doesn't use a cid to manage it's encryption contexts, but supports to send records with a cid received from the other peer. A peer sends a cid with length 0 in the hello extension to indicate that.

cid - active: the peer  use a cid to manage it's encryption contexts, and to send records with a cid received from the other peer, if so. A peer sends a cid with length larger than 0 in the hello extension to indicate that
 
> is this to be set specifically for the client to indicate CID support,
>but not for the server to indicate that it will only be sending a zero length CID?

No, sending a cid of length 0 in the hello extension (cid -passive) maybe used in both roles.

mbedtls supports DTLS-CID for records, but AFAIK, it doesn't come with a encryption context management for that. That's left for the next layer. It's not too easy to implement. Therefore using cid length 0 to indicate, that it supports to include the other peer's cid for outgoing records, is the easy part to start with.
In my experience, to use cid actively is mainly required for a server with a fix address to communicate with clients, maybe through a NAT.

> Should there not be consideration for the client to indicate what CID it wants to be used?

The other peer sends the cid a peer must use for outgoing records. A peer only actively uses a cid to distinguish between encryption contexts, if a peer has a **encryption context management** implemented based on that cid.

> Do we want to be able to define the CID that the server wants to use?

Each peer, which actively uses a cid, must use unique cids for each peer and must manage the encryption contexts accordingly. 
 
So:
Use cid with length 0 (passive) in the hello extension is the easy part to start.
Use cid with length larger than 0 (active) in the hello extension requires a encryption context management and is the hard part.

**Comment by boaks** [comment]
Some good news about the `MBEDTLS_TLS_EXT_CID` value, it will be changed for future versions of mbedtls.

**Comment by mrdeep1** [comment]
Thanks for the background information - very useful.

I am not convinced that libcoap should ever do the encryption context management.  If it has to be done outside mbedTLS library, then I think that the application needs to control this.  To that end, we would need to come up with an API - future work.

With your code suggestion (moved into the DTLS only code, so as not to mess up when support is added to libcoap to support TCP/TLS for mbedTLS) is it safe/wise to always enable CID negotiations with zero length CID on both the client and server (subject to MBEDTLS_SSL_DTLS_CONNECTION_ID)?

**Comment by boaks** [comment]
> With your code suggestion (moved into the DTLS only code, so as not to mess up when support is added to libcoap to support TCP/TLS for mbedTLS) is it safe/wise to always enable CID negotiations with zero length CID on both the client and server (subject to MBEDTLS_SSL_DTLS_CONNECTION_ID)?

My idea was, that this is decided when build mbedtls with MBEDTLS_SSL_DTLS_CONNECTION_ID defined in mbedtls config.h. For me this is currently too early, to give an answer, if this is always "safe/wise". I don't know that :-).

**Comment by mrdeep1** [comment]
I do not think that this should be released in the libcoap code until mbedTLS have done a formal release with the corrected MBEDTLS_TLS_EXT_CID value and then this code should also be wrapped by a formal release version check.

I also am uncomfortable with forcing only passive support if MBEDTLS_SSL_DTLS_CONNECTION_ID is defined.  I think that this feature really needs to be under application API control and need to understand at some point what encryption context management actually involves and where it should be implemented layer wise.

**Comment by boaks** [comment]
> formal release

just to mention:
The IETF also hasn't released the RFC.

**But** DTLS Connection ID is in my opinion the very best for DTLS in the internet.

Let's wait. maybe someone else is also trying to use it.
