### ISSUE TITLE
Stuck in coap_io_process()

### ISSUE THREAD

**Issue by Delsian** [obgm/libcoap#576]
Found strange behaviour in my code and looking for any suggestion on how to resolve this.
My code running on Raspberry Pi and periodically sends packets to Zephyr-based CoAP server over IPv6:

```
                msg->ctx = coap_new_context( NULL );
                <prepading address, options and pdu>
                msg->session = coap_new_client_session(msg->ctx, 
                                NULL, &dst, COAP_PROTO_UDP);
                coap_register_response_handler(msg->ctx, message_handler);
                coap_send(msg->session, pdu);
                if(msg->msgtype == COAP_MESSAGE_CON) {
                    int result = coap_io_process( msg->ctx, 500);
                }
                coap_log( LOG_DEBUG, "Session elease\n");
                coap_session_release( msg->session );
            }
            coap_free_context( msg->ctx );
        }
    }
```

and execution never returns from coap_io_process()

But - MAGIC! - if I put any debug output in coap_io.c line 1219, it works as expected.

```
#ifndef RIOT_VERSION
int
coap_io_process(coap_context_t *ctx, uint32_t timeout_ms) {
  coap_log(LOG_DEBUG, ".");
  return coap_io_process_with_fds(ctx, timeout_ms, 0, NULL, NULL, NULL);
}
```

With simple printf or debug it not working, the only coap_log helps. Probably it depends on any timer-reading function?

In Wireshark  I see both sending and receiving packets.

Any recommendation please?

**Comment by mrdeep1** [comment]
Nothing immediately springs to mind.

However, I would have expected the receipt of a packet to trigger the situation where either `epoll_wait()` or `select()` returned to process the received packet, or the `epoll_wait()` or `select()` to timeout and return after 500 ms.
(`epoll_wait()` is used as an alternative for `select()` if there is epoll support unless you have compiled the libcoap code with the `--with-epoll=no` parameter to` ./configure`.)

As `epoll_wait()` or `select()` do not timeout, then there appears to be an issue with the clock timers - and the difference when using `coap_log()` v `printf()` is that the clock timers are touched to get the current time to output.

What are your ./configure options?

What is the configuration output summary from ./configure?

When debugging the code, are you able to get a callback list showing where the code is actually waiting on the response packet?

**Comment by Delsian** [comment]
Thanks for reply. Tried to recompile without epoll, but effect the same. Tomorrow will try to run a remote debugging session to check the exact place where waitng occurs.

**Comment by Delsian** [comment]
BTW, is this library thread-safe? May I use coap_io_process() in different threads without extra mutexes?

**Comment by mrdeep1** [comment]
The library is not thread-safe for the same coap_context_t *context.  So, coap_io_process() usage in different threads has to be using different contexts.  The majority of other coap_*() calls are not thread safe either, so contexts need to be watched there as well.

**Comment by Delsian** [comment]
need additional investigations
