### ISSUE TITLE
.gitignore issue

### ISSUE THREAD

**Issue by abierman** [obgm/libcoap#58]
I ran into an issue building libcoap on RHEL 7.3 (x86_64)

This only happened after the libcoap directory was checked back into a different git repo.
The configure step failed after a git pull.
The issue turned out to be the .gitignore file for the m4 directory

I changed the m4 text and this fixed the problem

-m4/
+m4/libtool.m4
+m4/ltoptions.m4
+m4/ltsugar.m4
+m4/ltversion.m4
+m4/lt~obsolete.m4

Note this text in .gitignore:

# warn about specific macros in the m4 directory if they missing
!m4/ax_*

This text gets overridden by the m4/ line

These 2 files need to be present for RHEL7 to work:
     m4/ax_check_compile_flag.m4
     m4/ax_check_link_flag.m4

**Comment by obgm** [comment]
Thanks. I have missed that you cannot override rules that ignore an entire directory. Your fix is now in commit 6468887.
