### ISSUE TITLE
Is it possible to build the examples statically linked?

### ISSUE THREAD

**Issue by boaks** [obgm/libcoap#585]
According `./configure --help` it's possible to build the libraries also as static link-library.

```sh
--enable-static[=PKGS]  build static libraries [default=yes]
```

Is it possible to build the examples (coap-client/coap-server) using these static link-libraries?
I didn't found a switch, maybe I have overseen that.

(I want to use the for tests and it's easier to include/deploy them as "self-contained executable".)

**Comment by mrdeep1** [comment]
Use `--disable-shared --enable-static --enable-examples` as `./configure` parameters.

**Comment by boaks** [comment]
Thanks!
