### ISSUE TITLE
coap_add_attr() in JSON format

### ISSUE THREAD

**Issue by ameerhazo** [obgm/libcoap#588]
I'm trying to show the attributes of my resources in JSON format but unfortunately this function only takes normal strings and quote and unquote (eg. "Sensor data": 1.212) doesnt work. Does anyone know how these attributes can take JSON formatted strings?

**Comment by mrdeep1** [comment]
The principle behind attributes for the resources is that they are used for Resource Discovery https://tools.ietf.org/html/rfc7252#section-7.2 where there is a name and value - both strings.  These are returned when requesting `coap://host/.well-known/core` and have names such as "title", "ct", "rt" etc. and have a well defined output format - see examples in https://tools.ietf.org/html/rfc6690#section-5 .

Your example `"Sensor data": 1.212` does not easily fit into this. I would be expecting that `rt="Sensor data"` could be a starting point.

Are you really trying to store / report on the data associated with a resource?  This can be held as JSON, and when added to the payload in a request/response, the Content-Type Option must be COAP_MEDIATYPE_APPLICATION_JSON.

**Comment by ameerhazo** [comment]
Hello @mrdeep1, thanks for the reply to my question. Yes, I agree my example that I've given was a bad example for the attribute of a resource. My department is doing a project on description of IoT devices and we're using JSON to describe the resources of a server during resource discovery. A short example of the resource description in JSON format could look like this:

{
  "id": "/things/01:02:03:04:05:06",
  "title": "Multisensor 1",
  "security": [
    "basic_sc"
  ]
}

I could use "id" and "title" as attributes just fine but a description like "security" like you said, wouldnt fit well with resource discovery format.

**Comment by mrdeep1** [comment]
You may want to look at the work done in https://www.ietf.org/archive/id/draft-ietf-core-links-json-10.txt , in particular figures 4 and 5.
