### ISSUE TITLE
Does libcoap with LwIP supports Client applications ?

### ISSUE THREAD

**Issue by fun-works** [obgm/libcoap#591]

**Comment by mrdeep1** [comment]
I don't see why it should not be able to do this.  There currently is only a server example, and it should not be difficult to add a client example if someone wants to volunteer.

**Comment by Borodkov** [comment]
Hello
Thanks for your time and work with this lib

--

may be "_it should not be difficult to add a client example_", but can you (@mrdeep1 or @obgm) help in this questions:
  - how to create client session with lwip, that will be equal to client in libcoap-minimal repo? 
  - coap_io_lwip.c tested with coap client build?

what I try to do:
coap_session_t *session = coap_new_client_session(ctx, &src, &dst, COAP_PROTO_UDP);
-> coap_session_t *session = coap_session_create_client(ctx, local_if, server, proto);
   -> and in line 823 of coap_session.c
      -> https://github.com/obgm/libcoap/blob/df9071c93efff2e648257314198268c7c1d79980/src/coap_session.c#L819

and next, in coap_io_lwip.c, in function coap_socket_connect_udp()
https://github.com/obgm/libcoap/blob/df9071c93efff2e648257314198268c7c1d79980/src/coap_io_lwip.c#L193

finaly, I **goto error**; and session == NULL, and I'm here with the same problem as topic starter

--

sry for my english

**Comment by mrdeep1** [comment]
PR #884 has been raised which provides LwIP coap-client support.

**Comment by mrdeep1** [comment]
Closed as fixed in https://github.com/obgm/libcoap/pull/926 which is now in the develop branch.  Client support is now available.
