### ISSUE TITLE
Pre-configured server public key

### ISSUE THREAD

**Issue by flaz83** [obgm/libcoap#592]
Hi,
I'm working with embedded devices and CoAP with RPK (TinyDTLS). Using your library I made a working prototype.
Now I'm working on an optimization: I would like to configure public server key on device memory so It hasn't to be exchange on every handshake. Is it possible? Maybe it has to be overriden the function get_ecdsa_key of tinyDTLS?
Right now I made it work by manually editing TinyDTLS handshake function.
Thanks a lot,
Flavio

**Comment by obgm** [comment]
The certificate exchange is an intrinsic part of the DTLS handshake. libcoap which just uses the underlying DTLS library has no way to change that.

**Comment by obgm** [comment]
Closing off since this is an issue of the underlying DTLS library.
