### ISSUE TITLE
Is there any usage example of tinydtls ciphersuite TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8?

### ISSUE THREAD

**Issue by WEN-XUE** [obgm/libcoap#608]
Hi everyone,

I want to use the sample programs coap-server and coap-client of libcoap/examples for coaps transmission and the ciphersuite uses TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8. but i don't know how to use it.

In issue #510 , I know that I should add a parameter -M to select a rpk_file. But I still don’t know which file to select.

If i use ciphersuite TLS_PSK_WITH_AES_128_CCM_8, my server and client will execute the following instructions and it will work normally.
server:
   ./coap-server -k 1234 -v9
client:
   ./coap-client coaps://[127.0.0.1]/time -k 1234 -u CoAP -v9

So if I use ciphersuite TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 I only need to add the [-M rpk_file] parameter and it will work properly?
For example below
server:
   ./coap-server [-M rpk_file] -v9
client:
   ./coap-client coaps://[127.0.0.1]/time [-M rpk_file] -v9

Can someone tell me how to do?

Thanks you in advance.

**Comment by mrdeep1** [comment]
You need to create a set of RPK certificates and use them for the client and server with the -M option.

As per #510, 
````
openssl ecparam -genkey -name prime256v1 -noout -out ec_pair.pem
````
Note that only GnuTLS and TinyDTLS builds support RPK.

**Comment by WEN-XUE** [comment]
hi @mrdeep1 ,

Thank you very much for your help, I can use TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 ciphersuite normally now.

But now I want to ask another question.
Do you know how tinydtls establishes certificates?
Because if I use the tinydtls sample program for ciphertext data transmission and change the ciphersuite from TLS_PSK_WITH_AES_128_CCM_8 to TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8, I only need to set the macro variable DTLS_CONF_ECC to 1, without generating additional certificates file.

I tracked the code of tinydtls, there are three variables in dtls_send_certificate_ecdsa function cert_asn1_header, key->pub_key_x and key->pub_key_y.
It seems that the certificates are a combination of these three variables. 
I don't know if there is any problem with my understanding.

Thanks you in advance.

**Comment by obgm** [comment]
tinydtls does not support X.509 certificates, just the more lightweight RPKs. If you want full-fledged certificate support, you should switch to one of the other TLS libraries supported by libcoap.

**Comment by WEN-XUE** [comment]
Hi @obgm ,
Thank you for responding to my question and i know it now.
