### ISSUE TITLE
how to contribute to libcoap? 

### ISSUE THREAD

**Issue by chenglin-li** [obgm/libcoap#62]
Hello libcoap admin

our team is interested in libcoap, and we add some new features for libcoap, how can we contribute our source code to libcoap? are there any process or standard to follow? 
1. can anyone contribute source code to libcoap?
2. or our new Dev feature need to follow libcoap's technical roadmap ? 

please give commnets, Thanks.

**Comment by obgm** [comment]
Hi,

Thanks for expressing your interest. Contributions are highly appreciated. To start with, there is [some information](https://libcoap.net/contribute.html) on the [libcoap web site](https://libcoap.net), and more detailed information on licensing, code style, etc. is included with the libcoap sources in a file called [CONTRIBUTE](https://raw.githubusercontent.com/obgm/libcoap/develop/CONTRIBUTE).
