### ISSUE TITLE
SIOCGIFINDEX undefined on MacOS BigSur

### ISSUE THREAD

**Issue by saidjawad** [obgm/libcoap#636]
./configure --enable-dtls --with-openssl --enable-examples --disable-doxygen --disable-manpages
....
libcoap configuration summary:
      libcoap package version : "4.3.0rc1"
      libcoap library version : "3.0.0"
      libcoap API version     : "2"
      libcoap DTLS lib extn   : "-openssl"
      host system             : "x86_64-apple-darwin20.3.0"
      build with TCP support  : "yes"
      build DTLS support      : "yes"
         -->  OpenSSL around  : "yes" (found OpenSSL 1.1.1k)
              OPENSSL_CFLAGS  : "-I/usr/local/Cellar/openssl@1.1/1.1.1k/include"
              OPENSSL_LIBS    : "-L/usr/local/Cellar/openssl@1.1/1.1.1k/lib -lssl -lcrypto"
      enable small stack size : "no"
      build doxygen pages     : "no"
      build man pages         : "no"
      build unit test binary  : "no"
      build examples          : "yes"
      build with gcov support : "no"
      build shared library    : "yes"
      build static library    : "yes"
make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in .
  CC       src/libcoap_2-openssl_la-address.lo
  CC       src/libcoap_2-openssl_la-async.lo
  CC       src/libcoap_2-openssl_la-block.lo
  CC       src/libcoap_2-openssl_la-coap_asn1.lo
  CC       src/libcoap_2-openssl_la-coap_cache.lo
  CC       src/libcoap_2-openssl_la-coap_debug.lo
  CC       src/libcoap_2-openssl_la-coap_event.lo
  CC       src/libcoap_2-openssl_la-coap_hashkey.lo
  CC       src/libcoap_2-openssl_la-coap_gnutls.lo
  CC       src/libcoap_2-openssl_la-coap_io.lo
  CC       src/libcoap_2-openssl_la-coap_mbedtls.lo
  CC       src/libcoap_2-openssl_la-coap_notls.lo
  CC       src/libcoap_2-openssl_la-coap_openssl.lo
  CC       src/libcoap_2-openssl_la-coap_prng.lo
  CC       src/libcoap_2-openssl_la-coap_session.lo
  CC       src/libcoap_2-openssl_la-coap_tcp.lo
  CC       src/libcoap_2-openssl_la-coap_time.lo
  CC       src/libcoap_2-openssl_la-coap_tinydtls.lo
  CC       src/libcoap_2-openssl_la-encode.lo
  CC       src/libcoap_2-openssl_la-mem.lo
  CC       src/libcoap_2-openssl_la-net.lo
src/net.c:3202:48: error: use of undeclared identifier 'SIOCGIFINDEX'
result = ioctl(ctx->endpoint->sock.fd, SIOCGIFINDEX, &ifr);
                                                                 ^
src/net.c:3210:40: error: no member named 'ifr_ifindex' in 'struct ifreq'
mreq6.ipv6mr_interface = ifr.ifr_ifindex;
                                        ~~~ ^
2 errors generated.
make[2]: *** [src/libcoap_2-openssl_la-net.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by mrdeep1** [comment]
@saidjawad Thanks for reporting this.  The changes and hence fix for this is in #637.  Please confirm this works for you as I do not have a MAC.

**Comment by saidjawad** [comment]
@mrdeep1  Thank you! Your patch fixed the issue.

**Comment by obgm** [comment]
@saidjawad Thanks for checking PR #637. I suppose, this issue now can be closed off?

**Comment by saidjawad** [comment]
Yes, thanks!
