### ISSUE TITLE
TCP support?

### ISSUE THREAD

**Issue by nginxsantos** [obgm/libcoap#64]
Hi,
Does it support transport over TCP?

Regards, Santos

**Comment by malinengineer** [comment]
No, it does not.
There's a PR (https://github.com/obgm/libcoap/pull/47) that implements TCP, but who knows when that's going to be merged..

**Comment by obgm** [comment]
Correct -- as you can see, there are some issues that need to be sorted out. But it's at the top of the TODO-list...
