### ISSUE TITLE
coap_dtls.c

### ISSUE THREAD

**Issue by flukkyy** [obgm/libcoap#641]
hello,
after trying to compile the *.c and *.h files in a C project i had many errors and tried to fix theme until i stomped on 91 errors in the coap_openssl.c file saying that it can't find some functions. after some research in the libcoap manual i found that this functions are located in the coap_dtls.c file but this particular file doesn't exist in the github repository.
should i add this file manually or it is not required and i need to change something else.
thanks in advance!

**Comment by mrdeep1** [comment]
I would only be expecting the *.c files to be compiled which will be including the *.h files, but am not expecting the *.h files to be compiled themselves.

coap_dtls.c is not a valid file (but was in a very old dtls branch that is significantly out of date) and so MUST NOT be added.  I would however be expecting that the function definitions required by coap_openssl.c (apart from the OpenSSL ones) would be defined in coap_dtls.h and other files in the include/coap2 directory.

**Comment by flukkyy** [comment]
yes sir, i was wrong as i was looking at the libcoap manual 4.2.0 which is differ from the current version as you mentioned before.

what do you mean by `am not expecting the *.h files to be compiled themselves.` because am putting all of the *.h files together with the  `coap.h` file and i linked them with the project as i am using eclipse for this one.

so, if you don't mind i will post the list of errors am getting so you can maybe help me a little. 

11:39:15 **** Incremental Build of configuration Debug for project coap ****
make all 
Building file: ../src/coap/src/coap_openssl.c
Invoking: GCC C Compiler
gcc -I"/home/iat/Documents/coap/coap/include" -I/usr/local/ssl/include -I/usr/local/ssl/include/libxml2 -I/home/iat/Documents/coap/coap/src/coap/imc -include/home/iat/Documents/coap/coap/src/coap/imc/address.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_internal.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_config.h -include/home/iat/Documents/coap/coap/src/coap/imc/async.h -include/home/iat/Documents/coap/coap/src/coap/imc/bits.h -include/home/iat/Documents/coap/coap/src/coap/imc/block.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_block_internal.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_cache.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_cache_internal.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_debug.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_dtls.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_event.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_forward_decls.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_hashkey.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_io.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_mutex.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_prng.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_resource_internal.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_riot.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_session.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_session_internal.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_subscribe_internal.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_tcp_internal.h -include/home/iat/Documents/coap/coap/src/coap/imc/coap_time.h -include/home/iat/Documents/coap/coap/src/coap/imc/encode.h -include/home/iat/Documents/coap/coap/src/coap/imc/libcoap.h -include/home/iat/Documents/coap/coap/src/coap/imc/mem.h -include/home/iat/Documents/coap/coap/src/coap/imc/net.h -include/home/iat/Documents/coap/coap/src/coap/imc/option.h -include/home/iat/Documents/coap/coap/src/coap/imc/pdu.h -include/home/iat/Documents/coap/coap/src/coap/imc/resource.h -include/home/iat/Documents/coap/coap/src/coap/imc/str.h -include/home/iat/Documents/coap/coap/src/coap/imc/subscribe.h -include/home/iat/Documents/coap/coap/src/coap/imc/uri.h -include/home/iat/Documents/coap/coap/src/coap/imc/uthash.h -include/home/iat/Documents/coap/coap/src/coap/imc/utlist.h -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/coap/src/coap_openssl.d" -MT"src/coap/src/coap_openssl.o" -o "src/coap/src/coap_openssl.o" "../src/coap/src/coap_openssl.c"
Finished building: ../src/coap/src/coap_openssl.c
 
Building target: coap
Invoking: GCC C++ Linker
g++ -L/usr/local/ssl/lib -L/home/iat/Documents/coap/coap/src/coap/imc -o "coap"  ./src/system/src/system.o  ./src/coap/src/address.o ./src/coap/src/async.o ./src/coap/src/block.o ./src/coap/src/coap_asn1.o ./src/coap/src/coap_cache.o ./src/coap/src/coap_debug.o ./src/coap/src/coap_event.o ./src/coap/src/coap_gnutls.o ./src/coap/src/coap_hashkey.o ./src/coap/src/coap_io.o ./src/coap/src/coap_mbedtls.o ./src/coap/src/coap_notls.o ./src/coap/src/coap_openssl.o ./src/coap/src/coap_prng.o ./src/coap/src/coap_session.o ./src/coap/src/coap_tcp.o ./src/coap/src/coap_time.o ./src/coap/src/coap_tinydtls.o ./src/coap/src/encode.o ./src/coap/src/mem.o ./src/coap/src/net.o ./src/coap/src/option.o ./src/coap/src/pdu.o ./src/coap/src/resource.o ./src/coap/src/str.o ./src/coap/src/subscribe.o ./src/coap/src/uri.o   -lssl -lcoap-2 -lcrypto -lpthread -ldl -lrt
./src/coap/src/coap_openssl.o: In function `sk_SSL_CIPHER_num':
/usr/local/include/openssl/ssl.h:824: undefined reference to `OPENSSL_sk_num'
./src/coap/src/coap_openssl.o: In function `sk_SSL_CIPHER_value':
/usr/local/include/openssl/ssl.h:824: undefined reference to `OPENSSL_sk_value'
./src/coap/src/coap_openssl.o: In function `sk_GENERAL_NAME_num':
/usr/local/include/openssl/x509v3.h:165: undefined reference to `OPENSSL_sk_num'
./src/coap/src/coap_openssl.o: In function `sk_GENERAL_NAME_value':
/usr/local/include/openssl/x509v3.h:165: undefined reference to `OPENSSL_sk_value'
./src/coap/src/coap_openssl.o: In function `sk_GENERAL_NAME_pop_free':
/usr/local/include/openssl/x509v3.h:165: undefined reference to `OPENSSL_sk_pop_free'
./src/coap/src/coap_openssl.o: In function `coap_dtls_is_supported':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:154: undefined reference to `OpenSSL_version_num'
./src/coap/src/coap_openssl.o: In function `coap_tls_is_supported':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:176: undefined reference to `OpenSSL_version_num'
./src/coap/src/coap_openssl.o: In function `coap_get_tls_library_version':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:195: undefined reference to `OpenSSL_version_num'
./src/coap/src/coap_openssl.o: In function `coap_dtls_startup':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:204: undefined reference to `OPENSSL_init_ssl'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:205: undefined reference to `OPENSSL_init_ssl'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:206: undefined reference to `OPENSSL_init_crypto'
./src/coap/src/coap_openssl.o: In function `coap_dgram_create':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:242: undefined reference to `BIO_set_init'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:243: undefined reference to `BIO_set_data'
./src/coap/src/coap_openssl.o: In function `coap_dgram_destroy':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:252: undefined reference to `BIO_get_data'
makefile:57: recipe for target 'coap' failed
./src/coap/src/coap_openssl.o: In function `coap_dgram_read':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:260: undefined reference to `BIO_get_data'
./src/coap/src/coap_openssl.o: In function `coap_dgram_write':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:287: undefined reference to `BIO_get_data'
./src/coap/src/coap_openssl.o: In function `coap_dgram_ctrl':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:312: undefined reference to `BIO_get_data'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:318: undefined reference to `BIO_get_shutdown'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:321: undefined reference to `BIO_set_shutdown'
./src/coap/src/coap_openssl.o: In function `coap_dtls_generate_cookie':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:376: undefined reference to `BIO_get_data'
./src/coap/src/coap_openssl.o: In function `coap_dtls_info_callback':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:596: undefined reference to `SSL_get_state'
./src/coap/src/coap_openssl.o: In function `coap_sock_create':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:602: undefined reference to `BIO_set_init'
./src/coap/src/coap_openssl.o: In function `coap_sock_read':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:613: undefined reference to `BIO_get_data'
./src/coap/src/coap_openssl.o: In function `coap_sock_write':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:629: undefined reference to `BIO_get_data'
./src/coap/src/coap_openssl.o: In function `coap_dtls_new_context':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:732: undefined reference to `HMAC_CTX_new'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:738: undefined reference to `SSL_CTX_set_options'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:739: undefined reference to `BIO_meth_new'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:742: undefined reference to `BIO_ADDR_new'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:745: undefined reference to `BIO_meth_set_write'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:746: undefined reference to `BIO_meth_set_read'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:747: undefined reference to `BIO_meth_set_puts'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:748: undefined reference to `BIO_meth_set_ctrl'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:749: undefined reference to `BIO_meth_set_create'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:750: undefined reference to `BIO_meth_set_destroy'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:754: undefined reference to `TLS_method'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:761: undefined reference to `BIO_meth_new'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:764: undefined reference to `BIO_meth_set_write'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:765: undefined reference to `BIO_meth_set_read'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:766: undefined reference to `BIO_meth_set_puts'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:767: undefined reference to `BIO_meth_set_ctrl'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:768: undefined reference to `BIO_meth_set_create'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:769: undefined reference to `BIO_meth_set_destroy'
./src/coap/src/coap_openssl.o: In function `coap_dtls_context_set_spsk':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:843: undefined reference to `SSL_set_options'
./src/coap/src/coap_openssl.o: In function `coap_dtls_context_set_cpsk':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:874: undefined reference to `SSL_set_options'
./src/coap/src/coap_openssl.o: In function `get_san_or_cn_from_cert':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:1788: undefined reference to `ASN1_STRING_get0_data'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:1819: undefined reference to `CRYPTO_strndup'
./src/coap/src/coap_openssl.o: In function `tls_server_name_call_back':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2082: undefined reference to `SSL_CTX_set_options'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2087: undefined reference to `TLS_method'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2108: undefined reference to `SSL_clear_options'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2109: undefined reference to `SSL_CTX_get_options'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2109: undefined reference to `SSL_set_options'
./src/coap/src/coap_openssl.o: In function `psk_tls_server_name_call_back':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2180: undefined reference to `SSL_CTX_set_options'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2185: undefined reference to `TLS_method'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2208: undefined reference to `SSL_clear_options'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2209: undefined reference to `SSL_CTX_get_options'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2209: undefined reference to `SSL_set_options'
./src/coap/src/coap_openssl.o: In function `coap_dtls_context_set_pki':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2593: undefined reference to `OpenSSL_version_num'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2594: undefined reference to `OpenSSL_version_num'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2622: undefined reference to `OpenSSL_version_num'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2623: undefined reference to `OpenSSL_version_num'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2655: undefined reference to `SSL_set_options'
./src/coap/src/coap_openssl.o: In function `coap_dtls_free_context':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2706: undefined reference to `HMAC_CTX_free'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2708: undefined reference to `BIO_meth_free'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2710: undefined reference to `BIO_ADDR_free'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2715: undefined reference to `BIO_meth_free'
./src/coap/src/coap_openssl.o: In function `coap_dtls_new_server_session':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2751: undefined reference to `SSL_set_options'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2758: undefined reference to `BIO_get_data'
./src/coap/src/coap_openssl.o: In function `coap_dtls_new_client_session':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2881: undefined reference to `BIO_get_data'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2885: undefined reference to `SSL_set_options'
./src/coap/src/coap_openssl.o: In function `coap_dtls_free_session':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2920: undefined reference to `SSL_in_init'
./src/coap/src/coap_openssl.o: In function `coap_dtls_get_timeout':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:2983: undefined reference to `BIO_get_data'
./src/coap/src/coap_openssl.o: In function `coap_dtls_hello':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3005: undefined reference to `BIO_get_data'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3014: undefined reference to `DTLSv1_listen'
./src/coap/src/coap_openssl.o: In function `coap_dtls_receive':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3042: undefined reference to `SSL_in_init'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3044: undefined reference to `BIO_get_data'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3062: undefined reference to `SSL_is_init_finished'
./src/coap/src/coap_openssl.o: In function `coap_dtls_get_overhead':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3111: undefined reference to `SSL_CIPHER_get_cipher_nid'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3129: undefined reference to `SSL_CIPHER_get_digest_nid'
./src/coap/src/coap_openssl.o: In function `coap_tls_new_client_session':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3170: undefined reference to `BIO_set_data'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3199: undefined reference to `SSL_is_init_finished'
./src/coap/src/coap_openssl.o: In function `coap_tls_new_server_session':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3222: undefined reference to `BIO_set_data'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3257: undefined reference to `SSL_is_init_finished'
./src/coap/src/coap_openssl.o: In function `coap_tls_free_session':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3270: undefined reference to `SSL_in_init'
./src/coap/src/coap_openssl.o: In function `coap_tls_write':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3291: undefined reference to `SSL_is_init_finished'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3298: undefined reference to `SSL_is_init_finished'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3326: undefined reference to `SSL_is_init_finished'
./src/coap/src/coap_openssl.o: In function `coap_tls_read':
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3357: undefined reference to `SSL_is_init_finished'
/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3363: undefined reference to `SSL_is_init_finished'
./src/coap/src/coap_openssl.o:/home/iat/Documents/coap/coap/Debug/../src/coap/src/coap_openssl.c:3389: more undefined references to `SSL_is_init_finished' follow
collect2: error: ld returned 1 exit status
make: *** [coap] Error 1
"make all" terminated with exit code 2. Build might be incomplete.

11:39:17 Build Failed. 91 errors, 0 warnings. (took 2s.426ms)

**Comment by mrdeep1** [comment]
The log output is only complaining about missing OpenSSL functions.  If you want to use OpenSSL as your (D)TLS library to provide `coaps://` support, then you must have the OpenSSL development libraries installed in your IDE and referred to them as a part of your project. 

If you do not want (D)DTLS support at all, then I would expect that none of `HAVE_LIBTINYDTLS`, `HAVE_OPENSSL`, `HAVE_LIBGNUTLS` or `HAVE_MBEDTLS `are defined in `coap_configi.h.`

**Comment by flukkyy** [comment]
yes i want to use OpenSSL as the DTLS library so thank you @mrdeep1 for pointing me in the right direction.

**Comment by flukkyy** [comment]
hello @mrdeep1, i successfully managed to build my project and it compiles fine without any errors or warnings thanks to your support.
i just have one question, is the `libcoap/examples/coap_client.c ` can serve as a good code for me to learn how to use the functions of the library, or, is it just for usage purposes for the library.
what i want to say is, can this code ( after modifications of course) be used in other programs related to the library

**Comment by mrdeep1** [comment]
examples/coap-client.c is a good starting point to develop your client code.  Yes, it used to exercise different functionality as well, so there may be code that is not relevant to you.  You may want to look at [libcoap-minimal](https://github.com/obgm/libcoap-minimal) for an example as well.

The only thing of note is that the coap-client sends a single request, waits for a (perhaps set of) response and then exits.  You may want to think about doing multiple requests. by not prematurely exiting.

**Comment by flukkyy** [comment]
thank you, i'll check the other example too.

`The only thing of note is that the coap-client sends a single request` do you mean that it is only for the coap-client.c in the examples folder, or, in general, the coap protocol can only send one request at a time.

**Comment by mrdeep1** [comment]
I was referring to the example coap-client capability.  I refer you to https://tools.ietf.org/html/rfc7252#section-4.7 about concurrent limitations.
