### ISSUE TITLE
excution of coap-client.c automatically

### ISSUE THREAD

**Issue by flukkyy** [obgm/libcoap#642]
hello,
after typing coap-client in terminal it exuctes the `coap-client.c` and then if i need to get resources from the server i just need to provide the method and server and resource's name. `coap-client -m get coap://127.0.0.1/time`

well, my question is: is it possible to change the code in the `coap-client.c` to make it run on it's own without me typing any of the above manually. what i want is a script that runs and excute the code automatically.

**Comment by mrdeep1** [comment]
You can make your own client code using libcoap do whatever you want as a CoAP Client talking to a CoAP Server using the CoAP protocol.  The documentation at https://libcoap.net/documentation.html tells you about all the C functions available to do this.
As mentioned previously, https://github.com/obgm/libcoap-minimal may help you here - it uses hard coded information.

**Comment by flukkyy** [comment]
i checked the libcoap-minimal, and it seems like its outdated if am not wrong, 
here is the log after compiling the *.c file

12:46:41 **** Incremental Build of configuration Debug for project coap ****
make all 
Building file: ../src/src/system/src/test.c
Invoking: Cross GCC Compiler
gcc -I/home/iat2/Documents/CoAP/coap/src/src/coap/imc/ -I"/home/iat2/Documents/CoAP/coap/include" -I/usr/local/ssl/include -I/usr/local/ssl/include/libxml2 -I/usr/local/include -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/address.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/async.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/bits.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/block.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap.h.in -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap.h.windows -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap.h.windows.in -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_asn1_internal.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_block_internal.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_cache.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_cache_internal.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_config.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_debug.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_dtls.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_event.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_forward_decls.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_hashkey.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_internal.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_io.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_mutex.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_prng.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_resource_internal.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_riot.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_session.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_session_internal.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_subscribe_internal.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_tcp_internal.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_time.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/encode.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/libcoap.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/mem.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/net.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/option.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/pdu.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/resource.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/str.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/subscribe.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/uri.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/uthash.h -include/home/iat2/Documents/CoAP/coap/src/src/coap/imc/utlist.h -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/src/system/src/test.d" -MT"src/src/system/src/test.o" -o "src/src/system/src/test.o" "../src/src/system/src/test.c"
In file included from /home/iat2/Documents/CoAP/coap/src/src/coap/imc/net.h:24:0,
                 from /home/iat2/Documents/CoAP/coap/src/src/coap/imc/async.h:18,
                 from <command-line>:32:
/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_io.h:68:8: warning: "/*" within comment [-Wcomment]
 #endif /* COAP_EPOLL_SUPPORT */
         
In file included from <command-line>:32:0:
/home/iat2/Documents/CoAP/coap/src/src/coap/imc/coap_io.h:68:8: warning: "/*" within comment [-Wcomment]
 #endif /* COAP_EPOLL_SUPPORT */
         
../src/src/system/src/test.c: In function ‘main’:
../src/src/system/src/test.c:38:39: error: expected expression before ‘[’ token
   coap_register_response_handler(ctx, [](auto, auto, auto,
                                       ^
../src/src/system/src/test.c:40:48: error: expected ‘)’ before ‘{’ token
                                          auto) {
                                                ^
../src/src/system/src/test.c:56:19: error: ‘reinterpret_cast’ undeclared (first use in this function)
                   reinterpret_cast<const uint8_t *>("hello"));
                   ^~~~~~~~~~~~~~~~
../src/src/system/src/test.c:56:19: note: each undeclared identifier is reported only once for each function it appears in
../src/src/system/src/test.c:56:36: error: expected expression before ‘const’
                   reinterpret_cast<const uint8_t *>("hello"));
                                    ^~~~~
make: *** [src/src/system/src/test.o] Error 1
src/src/system/src/subdir.mk:18: recipe for target 'src/src/system/src/test.o' failed
"make all" terminated with exit code 2. Build might be incomplete.

12:46:42 Build Failed. 6 errors, 2 warnings. (took 244ms)

**Comment by flukkyy** [comment]
i checked the libcoap-minimal and  now i have a general idea of what i should be doing.
well, for now i have a question and its a dumb one so bare with me, in the `libcoap/examples` and the `libcoap-minimal` examples there is a server and a client script, and in a project there should be only one main(). so, how can i execute them, what i mean to say, how can i execute the server's script so the client's script can be executed and connect to the server provided in the script

on ubuntu i open a terminal for the server and another one for the client but in a C project how can i make this work.

**Comment by mrdeep1** [comment]
@flukkyy This is not the correct forum for general programming questions / project design etc.  This forum is to do with specific libcoap issues / bugs / enhancements etc.

That said, you are likely to run into many issues with having both the client and server in the same application talking to each other (true as well when libcoap is not being used) without a clear design being in place. I would not recommend doing this.

**Comment by flukkyy** [comment]
thank you sir for everything you said, helped me a lot.
