### ISSUE TITLE
Deleting libcoap

### ISSUE THREAD

**Issue by flukkyy** [obgm/libcoap#656]
hello, 
while the libcoap 4.3 is still in developing phase and it is changing i had some problems making a project with it, and, after i successfully managed to make it work, i cloned the lastes version with the lastest changes. so in my pc i have a coap2 and coap3 folders and my project shows a problems like this one `error: cannot convert ‘coap_request_t’ to ‘coap_pdu_code_t’ for argument ‘2’ to ‘coap_pdu_t* coap_pdu_init(coap_pdu_type_t, coap_pdu_code_t, coap_mid_t, size_t)’ coap_session_max_pdu_size(session));`

so my question is how can i restore the previous version i had or, how can i delete the newest changes made to the library.
is deleting the `coap3` folder in `/usr/local/include` will solve the problem or not.?

**Comment by mrdeep1** [comment]
Your actual compilation issue is down to you needing to change, for example, COAP_REQUEST_GET to COAP_REQUEST_CODE_GET which is not necessarily intuitive.

If you want to revert, you will need to remove /usr/include/coap3, /usr/local/lib*/libcoap3-* and /usr/local/lib*/pkgconfig/libcoap-3*pc and rebuild with an earlier version of code.

My recommendation is that you continue to work with the latest code and fix compilation issues as  the code is more rigorous in its checking, giving rise to less possible mistakes..  For the example you gave, look at the coap_pdu_code_t enum and choose the appropriate ones.  Another area of consequential change is the callback handlers parameters (e.g. for coap_register_handler()).

**Comment by mrdeep1** [comment]
See [Upgrade 4.2.1 to 4.3.0](https://github.com/obgm/libcoap/wiki/Updating-application-code-from-4.2.1-to-4.3.0)    for further information on upgrading to 4.3.0
