### ISSUE TITLE
data encryption

### ISSUE THREAD

**Issue by flukkyy** [obgm/libcoap#663]
hello, 

i have some basic questions but it seems i cant  figure out what needs to be done, i don't know much about data encryption, so what i want to know is: the functions described in man[ coap_encryption(3)](https://libcoap.net/doc/reference/develop/man_coap_encryption.html) sufficient to establish the handhshake client/server and the public keys exchange? if not, can anyone show me the right way to do it. and i am supposed to work with the OpenSSL version 1.1.1g.

**Comment by mrdeep1** [comment]
See coap_endpoint_client(3) and coap_endpoint_server(3) for the general principals. coap_encryption(3) gives you the specific parameter details.

**Comment by flukkyy** [comment]
hello @mrdeep1, can you help me with this;
i tried creating a client code with the help of the examples from `/example/coap-client.c` and  `libcoap-minimal-master/client.cc`, well i managed to get data from local server or the coap.me server i even add function to update data.. until now all works just fine.. 
for the data encryption with psk i copied the functions `valid_ihs_t` `ih_def_t` `verify_cn_callback ``verify_ih_callback` `setup_psk` from the `coap-client.c` and added them to my code as they are.
in main() i added
 ```
  const uint8_t key=0x12 ;
  const uint8_t user=0x10;
``` 
``` 
coap_dtls_cpsk_t *dtls_psk = setup_psk(&user, user_len,
                                                     &key, key_len);
(session= coap_new_client_session_psk2(ctx, nullptr, &dst,
          COAP_PROTO_DTLS,dtls_psk))```



each time i run the server and the client i get re transmission timeout 
 here is the log file
[log.txt](https://github.com/obgm/libcoap/files/6391554/log.txt)

i don't know if this will help or not but when i change the port back to 5683 and protocol to COAP_PROTO_UDP everything works.

**Comment by mrdeep1** [comment]
The log file is telling me that the encryption parameter definitions in the client / server are not the same.  When testing this kind of stuff, my recommendation is that you use the example program unchanged at one end with all of the appropriate parameters, and then test out your modified code at the other end.

What certainly is unclear from your example is what `user_len` and `key_len` values are.  Given your definitions for `key` and `data`, I would say that they must be 1 - as you have only provided a single byte of information - correct?

Furthermore, the `-k` key value of `c` from your log file is hex 0x63, not 0x12.

**Comment by flukkyy** [comment]
you're right, after i commented, i noticed the wrong hex value and changed it, 

> When testing this kind of stuff, my recommendation is that you use the example program unchanged at one end with all of the appropriate parameters

do you mean that i need to execute the `coap-server` and `coap-client `with the same parameters before testing my code ?
because i tried doing that, and as far as i can see the connection is only using the UDP protocol and not the DTLS protocol.
here is the log for the client side :  [client_log.txt](https://github.com/obgm/libcoap/files/6398304/client_log.txt)
log for the server side :  [server_log.txt](https://github.com/obgm/libcoap/files/6398309/server_log.txt)

when testing like this should i put `-p 5684`, or, it should pick up the right port automatically because it says that the DTLS port is 5684.

**Comment by obgm** [comment]
You should use `coaps:` if you want to use CoAP over a secure channel (e.g., DTLS).

**Comment by flukkyy** [comment]
thank you, totally forgot about that.
can you tell me which  **functions  responsible for providing the cipher suites needed for the encryption**. i dont understand how the libcoap chooses the right cipher suite and is it possible to add others? if so where ?
i read the  #632  thread, and so for me who wants to work with openssl, should i change the coap_openssl.c file to add a cipher suite ? 

actually i am so confused with all this encryption thing and all these new information. so, please bear with me as i am asking a lot of simple questions.

**Comment by obgm** [comment]
No worries. The cipher suite selection is specific to the underlying TLS library. For OpenSSL, you will find the following code in [coap_openssl.c](../blob/develop/src/coap_openssl.c#L87-97):

```c
#ifndef COAP_OPENSSL_CIPHERS
#if OPENSSL_VERSION_NUMBER >= 0x10101000L
#define COAP_OPENSSL_CIPHERS "TLSv1.3:TLSv1.2:!NULL"
#else /* OPENSSL_VERSION_NUMBER < 0x10101000L */
#define COAP_OPENSSL_CIPHERS "TLSv1.2:!NULL"
#endif /* OPENSSL_VERSION_NUMBER < 0x10101000L */
#endif /*COAP_OPENSSL_CIPHERS */

#ifndef COAP_OPENSSL_PSK_CIPHERS
#define COAP_OPENSSL_PSK_CIPHERS "PSK:!NULL"
#endif /*COAP_OPENSSL_PSK_CIPHERS */
```

This means that the ciphers can be changed at compile time, e.g. by passing other cipher suites during configure (see [source code documentation](../blob/develop/src/coap_openssl.c#L42)).

**Comment by flukkyy** [comment]
that was helpful thank you @obgm, but i still can't figure out:

1.  how can the library choose the best cipher suite.
2.  in code, what are the functions to use when setting up psk or cipher suite exchange.
3. is it wrong to use the `coap-server -v 9 -k c -u c` with this [code](https://github.com/obgm/libcoap/files/6404350/test_client.txt)
) ?

**Comment by mrdeep1** [comment]
It ultimately is OpenSSL that negotiates and decides on a common and acceptable cipher/algorithm. Libcoap can only provide a list of acceptable ciphers to OpenSSL.  This list can be compiled in as described previously.

Unless you have a very specific requirement, I would leave things alone here.

Providing you pass in the appropriate parameters to the client setup psk2 connection nothing else needs to be done.

Not sure what the -u c parameter is on the server invocation line.

For security, having a key as a single character is not really recommended

**Comment by flukkyy** [comment]
i understand, actually am not trying to add any ciphers for now, i just want to create a secure connection with encrypted data.

the -u parameter is for the identity ( is it wrong?), and i don't understand what it means by identity, so i am just giving it a value?

the single character as key is just for testing that's all.

**Comment by mrdeep1** [comment]
The `-u c` parameter on a server invocation is not needed unless the` -P` (ongoing proxy connection) is being used.  As per the coap-server usage information (run `coap-server -?`)
````
        -u user         User identity for pre-shared key mode (only used if
                        option -P is set)
````
In terms of Identity, this is defined in https://tools.ietf.org/html/rfc4279#section-7.3 .  Common usage is to call this the user, hence the `-u` option.

I have no idea why you are getting a multicast error, but you need to make sure that that you have fixed all compiler warnings in code.  I see that `open_session()` never actually creates a session for non DTLS connections.

**Comment by flukkyy** [comment]
hello,
i wanted to make sure to only connect to DTLS connections that's why i removed these lines : 
```
else {  /* Non-encrypted session */
      session = coap_new_client_session(ctx, bind_addr, dst, proto);
    }
```
and it seems like the multicast error is coming from here, i don't know why but it can only connect using UDP.

**Comment by mrdeep1** [comment]
The compiler (if you have enabled compiler warnings) should be telling you that the variable `session` is un-initialized in this case in the `get_session()` function, and so `session `has a random value when subsequently used and hence random results.

Please spend time checking your code for basic coding logic errors before raising issues that are actually not libcoap specific.

**Comment by flukkyy** [comment]
well, the compiler warnings is enabled and the variable session is not un-initialized, the `get_session()` function works fine, but  you're right i need to spend more time on my code. thank you for all your support.
