### ISSUE TITLE
How to add custom URI path and response to the coap-server? 

### ISSUE THREAD

**Issue by SalvaHasan** [obgm/libcoap#673]
I recently installed libcoap and tried the coap-server and coap-client examples, there are some predefined paths in it such as 
`coap-client -m get coap://[::1]/.well-known/core` and `coap-client -m get -T cafe coap://[::1]/time` with predefined responses. I want to add my own code to it `coap-client -m get coaps://[::1]/sensordata` with a response.
How do I go about it? 
I could not find any detailed documentation for this library.

**Comment by mrdeep1** [comment]
`.well-known/core` is an internal resource, `time `is a defined resource in `examples/coap-server.c`  You will need to add in `sensordata `as a resource and define the appropriate request handlers as per [coap_resource(3)](https://libcoap.net/doc/reference/develop/man_coap_resource.html).  The full documentation can be found at https://libcoap.net/doc/reference/develop/

**Comment by obgm** [comment]
For all software packages, it is a good start to look at the [README file](../blob/main/README.md). There, you will find a section "Documentation" that refers to the [libcoap homepage](https://libcoap.net) where the online documentation is hosted, including the API reference for different versions of libcoap, and a reference to [libcoap-minimal](/obgm/libcoap-minimal) which also shows how to create custom server resources.
