### ISSUE TITLE
Tradfri preshared key response 4.00 (bad request)

### ISSUE THREAD

**Issue by denimjeans** [obgm/libcoap#677]
Hi, I have lately a strange issue when using coap-client  with tradfri. It was working fine for years, but now when I try to get a new preshared key I receive an error 4.00 / an empty response like:
` 

> examples/coap-client -m post -u "Client_identity" -k my_tradfri.gw.key  -e '{"9090":"random1"}' "coaps://192.168.200.164:5684/15011/9063" -v 10 
> May 12 12:25:18 DEBG created DTLS endpoint 0.0.0.0:51601
> v:1 t:CON c:POST i:4650 {} [ ]
> May 12 12:25:18 DEBG sending CoAP request:
> v:1 t:CON c:POST i:4650 {} [ Uri-Path:15011, Uri-Path:9063 ] :: '{"9090":"random1"}'
> May 12 12:25:18 DEBG *** new session 0x5bc7c8
> May 12 12:25:18 DEBG call dtls_write
> May 12 12:25:18 DEBG *** add 0x5bd6d0 to sendqueue of session 0x5bc7c8
> May 12 12:25:18 DEBG timeout is set to 90 seconds
> May 12 12:25:18 DEBG received 60 bytes on fd 3
> May 12 12:25:18 DEBG received 95 bytes on fd 3
> May 12 12:25:18 DEBG received 25 bytes on fd 3
> May 12 12:25:18 DEBG received 14 bytes on fd 3
> May 12 12:25:18 DEBG received 53 bytes on fd 3
> May 12 12:25:18 DEBG *** EVENT: 0x01de
> May 12 12:25:18 DEBG received 33 bytes on fd 3
> May 12 12:25:18 INFO ** application data:
> v:1 t:ACK c:4.00 i:4650 {} [ ]
> May 12 12:25:18 DEBG *** removed transaction 9335
> May 12 12:25:18 DEBG ** process incoming 4.00 response:
> v:1 t:ACK c:4.00 i:4650 {} [ ]
> 4.00
> May 12 12:25:18 DEBG *** removed session 0x5bc7c8

`

`coap-client v4.1.2 -- a small CoAP implementation`

any Idea what changed or what I am doing wrong? It was working 1 x and I have a key which is working now. but next time I need a new key I believe I will have an issue. Probably the GW requires a reboot??

Thanks
OktO

**Comment by denimjeans** [comment]
same with the latest libcoap 4.3.0rc2

>  examples/coap-client -m post -u "Client_identity" -k my_tradfri.gw.key  -e '{"9090":"random2"}' "coaps://192.168.200.164:5684/15011/9063" -v 100
May 12 12:41:26.961 DEBG ***192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: new outgoing session
May 12 12:41:26.961 DEBG CoAP Client restricted to (D)TLS1.2 with Identity Hint callback
May 12 12:41:26.962 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:before SSL initialization
May 12 12:41:26.962 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: sent 277 bytes
May 12 12:41:26.962 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:SSLv3/TLS write client hello
May 12 12:41:26.963 DEBG sending CoAP request:
May 12 12:41:26.963 DEBG ** 192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: mid=0xd886: delayed
May 12 12:41:26.963 DEBG timeout is set to 90 seconds
May 12 12:41:26.963 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: received 60 bytes
May 12 12:41:26.963 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:SSLv3/TLS write client hello
May 12 12:41:26.963 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:DTLS1 read hello verify request
May 12 12:41:26.964 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: sent 309 bytes
May 12 12:41:26.964 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:SSLv3/TLS write client hello
May 12 12:41:26.965 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: received 103 bytes
May 12 12:41:26.965 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:SSLv3/TLS write client hello
May 12 12:41:26.965 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: received 25 bytes
May 12 12:41:26.965 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:SSLv3/TLS read server hello
May 12 12:41:26.965 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:SSLv3/TLS read server done
May 12 12:41:26.965 DEBG got psk_identity_hint: ''
May 12 12:41:26.965 INFO Identity Hint '' provided
May 12 12:41:26.965 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:SSLv3/TLS write client key exchange
May 12 12:41:26.966 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:SSLv3/TLS write change cipher spec
May 12 12:41:26.966 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: sent 109 bytes
May 12 12:41:26.966 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:SSLv3/TLS write finished
May 12 12:41:26.968 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: received 14 bytes
May 12 12:41:26.968 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:SSLv3/TLS write finished
May 12 12:41:26.969 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: received 53 bytes
May 12 12:41:26.969 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:SSLv3/TLS read change cipher spec
May 12 12:41:26.969 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL_connect:SSLv3/TLS read finished
May 12 12:41:26.969 CIPH *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: Using cipher: PSK-AES128-CCM8
May 12 12:41:26.969 DEBG ***EVENT: 0x01de
May 12 12:41:26.969 DEBG ***192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: session connected
May 12 12:41:26.969 DEBG ** 192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: mid=0xd886: transmitted after delay
May 12 12:41:26.969 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: sent 61 bytes
v:1 t:CON c:POST i:d886 {} [ Uri-Path:15011, Uri-Path:9063 ] :: '{"9090":"random2"}'
May 12 12:41:26.970 DEBG ** 192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: mid=0xd886: added to retransmit queue (2500ms)
May 12 12:41:26.970 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: received 33 bytes
v:1 t:ACK c:4.00 i:d886 {} [ ]
May 12 12:41:26.970 DEBG ** 192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: mid=0xd886: removed
May 12 12:41:26.971 DEBG ** process incoming 4.00 response:
4.00
May 12 12:41:26.971 DEBG *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: sent 31 bytes
May 12 12:41:26.971 INFO *  192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: SSL3 alert write:warning:close notify
May 12 12:41:26.971 DEBG ***EVENT: 0x0000
May 12 12:41:26.971 DEBG ***192.168.200.77:34458 <-> 192.168.200.164:5684 DTLS: session closed

**Comment by mrdeep1** [comment]
Thanks for checking against the latest code.

The [4.00](https://tools.ietf.org/html/rfc7252#section-5.9.2.1) response is from your server, so it is telling you that it does not like the POST request.

Either the tradfri is confused and needs restarting, or the formation of the request you are providing is broken.

The provided data looks like it is JSON, so I would have expected you to have included the coap-client option `-t 50` to indicate this.  If the URI path was bad, I would have expected [4.04](https://tools.ietf.org/html/rfc7252#section-5.9.2.5) .

**Comment by denimjeans** [comment]
thanks for your reply. 
-t 50 or rebooting does not make any difference unfortunately. 
I am using tradfri version :

> "9029": "**1.13.25**",

hope someone have similar issues resolved and can provide me any hints?

**Comment by mrdeep1** [comment]
I would say that the tradfri is the issue - I do not know this product but 1.13.25 update only came out recently.  I would look at the trafdri logs to see what it is saying (e.g. when did the update occur, are any errors being reported etc.)

It is possible that the tradfri does not like an empty token - try adding `-T aa` to see if that makes a difference.

Otherwise, this really is a question for a tradfri forum as it is the server returning the 4.00 (Bad Request) response and I can see nothing wrong in the request.

**Comment by denimjeans** [comment]
mrdeep1, thank you for your fast response :-)
I am now one step further, just for documentation purposes if anyone else should have the same, would be good to reply here):
After using a different user - OKOKOK instead of random2 - I get a key. Trying again with the same user gives again 4.00. Seems so that the user can be used only once for generating a key. At least for in within a short time. probably in 6 weeks it might look different. If you face the same issue, just try to use a different username. 

Thanks again, 
Oktay
