### ISSUE TITLE
cannot connect using the coap-server.c

### ISSUE THREAD

**Issue by flukkyy** [obgm/libcoap#689]
hello, am trying to test the libcoap client/server examples on a local network between 2 PCs.
am using the libcoap 4.3.0 version on ubuntu 18.04.
i launched the `coap-server.c` on one PC and the` coap-client.c` on the other one but there is no response, the client re-transmit until the timeout,
Q1 : i want to know if using the `coap-server.c` this way is right or wrong?

another thing, when i tried to test the client with  the test server provided by coap [http://coap.me/](http://coap.me/). the same thing happened and no response is sent. this was working before changing the vmware network configuration from NAT to bridged ( this is needed to receive an ip address from the local network).
Q2; is there something am doing wrong or should be changed.

**Comment by mrdeep1** [comment]
I assume that you mean the `coap-serve`r compiled from `coap-server.c` and c`oap-client` compiled from` coap-client.c`.  I assume that the 2 PCs are in separate VMs running on the same host.

> Q1 : i want to know if using the coap-server.c this way is right or wrong?

If network connectivity is there, then providing you are pointing the coap-client to the coap-server's IP address that it is listening on, then this will work if there is no firewall etc. between the 2 PCs.

I would check first that your coap-client can talk to a coap-server running in the same VM (use 127.0.0.1 as the IP address) to verify that the coap-client and coap-server are good to use.

> Q2; is there something am doing wrong or should be changed.

Given that your client cannot get out to coap.me (I am assuming that you are simply doing `coap-client -v7 coap://coap.me`), then if your coap-client is good (as checked out in the all in the same VM test) then you have a network routing issue to get to the internet for the VM.  If you are trying to use IPv6, that can add in another layer of complexity.

**Comment by flukkyy** [comment]
the 2 VMs are installed on different hosts,

I would check first that your coap-client can talk to a coap-server running in the same VM (use 127.0.0.1 as the IP address) to verify that the coap-client and coap-server are good to use.

**Comment by flukkyy** [comment]
heyy,
i have a question regarding the `coap-server`.. like i said i am trying to connect two PCs on two different hosts i want to know if i am doing something wrong or not
PC1 has ip address xxx.xxx.xxx.5
PC2 has Ip address xxx.xxx.xxx.6
these two IPS are registered on the local network and there is no firewall problems
here is what i am doing
1.  i open the server on PC1 : coap-server -v7 -A xxx.xxx.xxx.5
Jun 02 16:00:36.281 DEBG created UDP  endpoint xxx.xxx.xxx.5:5683
Jun 02 16:00:36.281 DEBG created TCP  endpoint xxx.xxx.xxx.5:5683

2. i launch the client from PC2 : coap-client -m get coap://xxx.xxx.xxx.5:5683/time
nothing happens until timeout.

i don't know but i think there is a problem here, like how is the connection gonna be established. is it enough to just launch the server and client.
 and maybe the problem is within the VM, blocking the traffic or something like that.

what i want to know is: in an ideal environment  opening the server on PC1 and launching the client on PC2 would i get the  response i want or not.
thanks!!

**Comment by mrdeep1** [comment]
There is nothing obviously wrong with what you are doing.
1. Please confirm that if you start the `coap-client` on `PC1 `that all works with the client getting a time response.
2. Try running` coap-server` without the `-A` option
3. Please add the `-v7` option to` coap-client` to see if there are any DEBG clues.
4. What is your code version?
````
coap-client -? 2>&1 | head -7
git describe --tags
````
5. On `PC2`, does `ping xxx.xxx.xxx.5` get a response?
6. What does` arp -a` report immediately following the running of `coap-client` or `ping`?

**Comment by flukkyy** [comment]
1. if you mean to change the client and server between the` 2 PCs`, yes i did try that, and no response is being sent. if you mean to just test the `coap-client` with `127.0.0.1` i did and it works fine.
2. i  already did that, and still no response.
3. the -v7 option to the `coap-client` just tells me that the client is re-transmitting the request 1,2,3 and 4 times until the 90 sec timeout.
4. i am using the  v4.3.0rc2 version of the libcoap.
5. yes, i tested the ping on both PCs and there is a response.
6. idk what this command  `arp -a` do but  it showed all the PC connected to the local network and PC1 is one of them.

i am starting to think its a problem related to the VMware.

**Comment by flukkyy** [comment]
> PC1 is a VM running in HOST1
> PC2 is a VM running in HOST2

yes thats correct and the OS is Windows 10 for both.
i don't think its a port problem, 5683 is open when i checke
i tested this command `  sudo lsof -i -P -n` on PC1 : 
```
coap-serv 2959            iat2    5u  IPv6  75305      0t0  UDP *:5683 
coap-serv 2959            iat2    6u  IPv6  75306      0t0  TCP *:5683 (LISTEN)
```
you said when using ipv6 is complicated, so maybe this is the problem ?

 when changing the interface to bridged network interface the connection is blocked whenever i try to reach the `coap.me` server,
but when using the NAT interface i can connect to `coap.me`

**Comment by flukkyy** [comment]
hi, i want to add that i tested` 2 Ubuntu` `PCs `on the same `HOST1 `and ii worked, i received a response.
i even tested using `VMware Workstation Pro 15.5` and `Virtual box 6.0`.
so, pretty much the problem is with  the VM blocking the traffic between the `PC1` on `HOST1 `and `PC2 `on `HOST2`.

**Comment by mrdeep1** [comment]
As everything works for VMware within HOST1, but not between HOST1 and HOST2 I would say that you need to check the firewall settings on HOST1 and HOST2 to make sure that they are allowing the VMware logic to send / receive over the Window network interface.  As you are using Windows 10 for the hosts, checkout what Windows Defender Firewall is doing / has enabled / is blocking for the VMware application.

**Comment by flukkyy** [comment]
i tried checking the firewall and windows defender but found nothing wrong, so, i think the best solution is to install Ubuntu on another partition alongside windows 10.
