### ISSUE TITLE
URI query parsing returns to long option sizes

### ISSUE THREAD

**Issue by patgrosse** [obgm/libcoap#69]
I would like to parse the URI query parameters of GET requests. The important part of the code:
```c++
coap_opt_iterator_t opt_iter;
coap_opt_filter_t f = {};
coap_opt_t *q;
coap_option_filter_clear(f);
coap_option_setb(f, COAP_OPTION_URI_QUERY);
coap_option_iterator_init(request, &opt_iter, f);
while ((q = coap_option_next(&opt_iter)) != nullptr) {
    unsigned char *value = coap_opt_value(q);
    size_t size = coap_opt_size(q);
    ...
}
```
Parsing the type parameter is always correct but the name parameter causes problems:

Request: `GET coap://127.0.0.1/call/name?name=testint&type=1`
`size`: 13 (should be 12)
`value` truncated to `size`: `name=testint`

Request: `GET coap://127.0.0.1/call/name?name=testdouble&type=1`
`size`: 17 (should be 15)
`value` truncated to `size`: `name=testdoublet`

Now the funny part: if I switch the order of the parameters, everything is working fine.

EDIT: It's not working fine, only the `name` string is correctly determined in it's size, but the `type` int has an additional char at it's end.

Am I using the `coap_option_*` functions wrongly?

Used libcoap version: b425b15
Compiler definitions: `-O0 -DWITH_POSIX`
Used compiler: `gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)` (I used g++)

**Comment by patgrosse** [comment]
More tests with this snippet:
```c++
...
        unsigned char *value = coap_opt_value(q);
        size_t size = coap_opt_size(q);
        printf("Param: %.*s\n", (int) size, value);
...
```
GET `coap://127.0.0.1/call/name?random=testdouble&type=1`:
Param: random=testdoublet
Param: type=1E

GET `coap://127.0.0.1/call/name?id=1&type=1`:
Param: id=1
Param: type=1t

**Comment by obgm** [comment]
`coap_opt_size()` returns the number of bytes occupied by the entire option, i.e. including the option's numeric identifier and length field. You should try `coap_opt_length()` instead to get only the length of the option value.

**Comment by patgrosse** [comment]
Thank you for your quick response. Using `coap_opt_length()` solved it :)
