### ISSUE TITLE
how to config example client/server

### ISSUE THREAD

**Issue by cbargiela** [obgm/libcoap#690]
I am trying to use the example client server with RPK. Connecting several clients to a server how should I configure the clients and the server

**Comment by mrdeep1** [comment]
I assume that you have looked at the documentation for [coap-server](https://libcoap.net/doc/reference/develop/man_coap-server.html) and [coap-client](https://libcoap.net/doc/reference/develop/man_coap-client.html) to see how to configure them for using RPK (Note that only later versions of `GnuTLS `and `TinyDTLS `(D)TLS libraries are supported).

If you then search (under Issues Tab) for `RPK `(overwrite `is:issue is:open` to get everything) you will find #510 which may also help you.

Otherwise, if there is an issue, you need to be specific in what libcoap version, what you are doing and what is failing.

**Comment by cbargiela** [comment]
Sorry, I already ran the example, now I want to know if the server can have the public keys of the clients loaded to avoid the negotiation.
If the Libcoap library allows it.

**Comment by obgm** [comment]
I am not sure what you are asking. In case of RPK you would always have to "pre-load" the possible clients' public keys, i.e. you would craft the key verification callback to check a client's RPK against those RPKs you know.  In case of X509 certificates, you would most likely go with the SNIs and do a certificate check relying on the PKI.

**Comment by cbargiela** [comment]
Sorry I'm asking for the RPK case. in which format I must Pre-load de possible clients, and which funtion  I must use to do dis.

Regrds!!

**Comment by mrdeep1** [comment]
You need the Public Key in ASN.1 format for all of your clients (which starts with something like 0x30, 0x59, 0x30, 0x13, ...).  There are no libcoap functions provided to load in RPK certificates other than the one used to load in the RPK certificate for sending off to the peer (which is handled by the underlying (D)TLS library).

In the server, if `validate_cn_call_back `is defined when setting up the PKI/RPK, then the defined function is called which has the following parameters
````
typedef int (*coap_dtls_cn_callback_t)(const char *cn,
             const uint8_t *asn1_public_cert,
             size_t asn1_length,
             coap_session_t *coap_session,
             unsigned int depth,
             int validated,
             void *arg);
````
`cn `will be set to "`RPK"` if RPK and the peer's presented certificate is held in `asn1_public_cert `and `asn1_length`.

**Comment by cbargiela** [comment]
thanks, for the last answer!!!
If I use -h flag, what i must fill in hint_to_match field, and in use_user field??
with_key could be EC private key o EC public key  
could you give me an example, sorry by my english

**Comment by mrdeep1** [comment]
The peer will only pass across the Public Key when the certificate is requested.

The -h option is PSK, not PRI/RPK and so not relevant for you.

If you look at `coap_dtls_context_set_pki()` in src/coap_tinydtls.c. and the work done under `case COAP_PKI_KEY_PEM_BUF:`, there may be some functions (e.g. `pem_decode_mem_asn1()`) that may help you.  The example coap-server does not provide the functionality you are looking for - you need to separately load in and save the RPK public certs which can then be matched against in an updated `validate_cn_call_back()` for validity.

**Comment by cbargiela** [comment]
ok, sorry, at this moment i'm trying to understand how it works the example using the files match_hint_file in the client and match_identity_file in the server instead of RPK

**Comment by mrdeep1** [comment]
The client code is building an array `valid_ihs.ih_list[]` (of depth `valid_ihs.count`) , one per non comment line when reading an input file.  Each line in this case has 3 entries, comma separated (hint_to_match , use_user , with_key).  Then in the `verify_ih_callback()` function it is looking for the hint that the server provides (against `hint_to_match`) and then uses the appropriate PSK `user `(identity) and `key `for the ongoing session encryption.

In your case you need to read in the different valid client public RPKs and then in the `validate_cn_call_back()` check to see if the RPK is known (`return 1;`) or not (`return 0;` to invalidate the connection).

**Comment by mrdeep1** [comment]
@cbargiela Have you been able to get things working now?  If so, please close off this issue.

**Comment by cbargiela** [comment]
.
