### ISSUE TITLE
coap-client -O option output.

### ISSUE THREAD

**Issue by flukkyy** [obgm/libcoap#698]
## Environment

- libcoap version (4.3.0rc2):

- Build System:             [Make|]
- Operating System:         [Linux]
- Operating System Version: [ 20.04 ]
- Hosted Environment:       [none]

## Problem Description

hi! this s not a problem.. it's more like a question about the option -O in the [libcoap-manual-pages](https://libcoap.net/doc/reference/4.3.0rc2/man_coap-client.html) in the manual it says : 
``` Add option num with contents of text to the request. If the text begins with 0x, then the hex text (two [0-9a-f] per byte) is converted to binary data. ```
i don't understand what this option really do. 

### Expected Behavior
when i tested like this : `coap-client -O 7 -m get coap://[::]/time` i was waiting to receive the port number in the server log but i got an error, so, after reading the [5.10 Option Definition](https://datatracker.ietf.org/doc/html/rfc7252#section-5.10) of the RFC7252 and the libcoap manual page, i entered a random number `-O 7,10` .
i don't really get what the `text` purpose here.

### Actual Behavior

after adding `-O 7,10` the server log showed something like this 
``` v:1 t:CON c:GET i:9ad6 {} [ Observe:0, Uri-Port:12592, Uri-Path:example_data, Content-Format:text/plain, Hop-Limit:16, Accept:text/plain ] ```
the `uri-port : 12592` is actually the hex data of `0x3130`. 
after i tried other examples i noticed that it always have the same pattern like this `-O 7,YZ ` and the `uri-port` i got is `0x3Y3Z`

so this `option -O `what does it really do if not showing the options of the request.

**Comment by obgm** [comment]
Well, `-O` does what it says: It adds a CoAP option to the request. With `-O 7,10`, you have added the CoAP option 7 (Uri-Port) with its value set to the text "`10`" which is 0x3130 according to the ASCII table. With `-O 7,YZ`, you should have seen "Uri-Port: 595A".

**Comment by flukkyy** [comment]
yes i understand that much, but what's the utility of adding a port number of my own? isn't it supposed to show the port 5683 ?

**Comment by mrdeep1** [comment]
If you look at the man page for `coap_pdu_access` (or include/coap3/pdu.h) you will see that the option URI_PORT has a value of 7.

So, what you are doing here is instructing coap-client to include/update the option 7 with a value that is represented by "10" - or 0x3130.

So coap-client is reporting the final set of options sent over the wire with the  included/updated Uri-Port (-O 7) and with a value of 12592 (binary value for ASCII  "10") (-O 7,10).

This normally is used to support some obscure (perhaps not RFC defined) option.

**Comment by obgm** [comment]
Please understand that `coap-client` is provided with libcoap as a tool for testing CoAP implementations. Therefore, it has a set of command line options for advanced users who want to do things that have no direct support in libcoap. Users who do not have a use case for this may safely ignore those options.

**Comment by flukkyy** [comment]
i understand now, this is what i was looking for 
> This normally is used to support some obscure (perhaps not RFC defined) option.
thank you @obgm , @mrdeep1 !!
