### ISSUE TITLE
Delayed responses lost

### ISSUE THREAD

**Issue by JohanZackrisson** [obgm/libcoap#699]
## Environment

- Latest from git, docker build included in example
- Build System:             Make
- Operating System:         Linux
- Operating System Version: [archlinux:latest]

## Problem Description

When having multiple requests in flight on the same session, responses are lost.

A test case based on coap-client can be found at,
https://github.com/JohanZackrisson/libcoap-bug/tree/multiple-requests

I've also included a Dockerfile that can be used to build and run the testcase.

// Detailed problem description goes here.

### Expected Behavior

Both responses should be logged.

### Actual Behavior

The second response seems to be lost and never processed.

### Steps to reproduce

1. git clone https://github.com/JohanZackrisson/libcoap-bug/tree/multiple-requests libcoap-bug
2. cd libcoap-bug
3. docker build -t libcoap-test -f ./docker/Dockerfile .
4. docker run libcoap-test

### Code to reproduce this issue

https://github.com/JohanZackrisson/libcoap-bug/tree/multiple-requests

## Debug Logs

```
Jun 08 15:32:39.187 DEBG ***172.17.0.2:42858 <-> 134.102.218.18:5683 UDP : new outgoing session
Jun 08 15:32:39.187 DEBG sending CoAP request:
Jun 08 15:32:39.187 DEBG *  172.17.0.2:42858 <-> 134.102.218.18:5683 UDP : sent 17 bytes
v:1 t:CON c:GET i:f4f3 {} [ Uri-Host:coap.me, Uri-Path:test ]
Jun 08 15:32:39.187 DEBG ** 172.17.0.2:42858 <-> 134.102.218.18:5683 UDP : mid=0xf4f3: added to retransmit queue (2688ms)
Jun 08 15:32:39.187 DEBG sending CoAP request 2:
Jun 08 15:32:39.187 DEBG ** 172.17.0.2:42858 <-> 134.102.218.18:5683 UDP : mid=0xf4f4: delayed
Jun 08 15:32:39.187 DEBG timeout is set to 90 seconds
Jun 08 15:32:39.228 DEBG *  172.17.0.2:42858 <-> 134.102.218.18:5683 UDP : received 81 bytes
v:1 t:ACK c:2.05 i:f4f3 {} [ ETag:0xdaef2db6cf17f031, Content-Format:text/plain ] :: 'welcome to the ETSI plugtest! last change: 2021-06-08 15:31:33 UTC'
Jun 08 15:32:39.228 DEBG ** 172.17.0.2:42858 <-> 134.102.218.18:5683 UDP : mid=0xf4f3: removed
Jun 08 15:32:39.228 DEBG ** 172.17.0.2:42858 <-> 134.102.218.18:5683 UDP : mid=0xf4f4: transmitted after delay
Jun 08 15:32:39.229 DEBG *  172.17.0.2:42858 <-> 134.102.218.18:5683 UDP : sent 17 bytes
v:1 t:CON c:GET i:f4f4 {} [ Uri-Host:coap.me, Uri-Path:test ]
Jun 08 15:32:39.229 DEBG ** 172.17.0.2:42858 <-> 134.102.218.18:5683 UDP : mid=0xf4f4: added to retransmit queue (2438ms)
Jun 08 15:32:39.229 DEBG ** 172.17.0.2:42858 <-> 134.102.218.18:5683 UDP : mid=0xf4f4: removed
Jun 08 15:32:39.229 DEBG ** process incoming 2.05 response:
welcome to the ETSI plugtest! last change: 2021-06-08 15:31:33 UTCJun 08 15:32:39.229 DEBG ***172.17.0.2:42858 <-> 134.102.218.18:5683 UDP : session closed

**Comment by mrdeep1** [comment]
The second response is not lost - the client just does not wait for it.  Do the following change
````
-    while(!quit && !(ready && !doing_getting_block && coap_can_exit(ctx)))
+    while(!quit)
````

**Comment by JohanZackrisson** [comment]
Ah, thank you. Updated the repo with the fix.
I've got another bug i'm trying to reproduce where I loose delayed messages and i thought i had a minimized test case, but no luck.
I'll try again to see what i can come up with.

You can close this in the meantime.

**Comment by JohanZackrisson** [comment]
I could give some background in what i'm running into..
I manage to get into a situation where a request gets "stuck", there is a delayed message in the queue. But it is never picked up and processed..
Unfortunately its part of a bigger application which is hard to minimize.

**Comment by JohanZackrisson** [comment]
I'll include a trace for our real error case, maybe you can see whats going on.
We are using non-encrypted UDP.
Seems like the confirm reply is never received by the client or that the client never gives up waiting for the ACK.

`Jun 07 08:15:42.011 DEBG ***192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : new outgoing session
Jun 07 08:15:42.020 DEBG *  192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : sent 323 bytes
v:1 t:CON c:POST i:3c68 {} [ Uri-Path:m, Content-Format:65060, Uri-Query:001000000000002 ] :: binary data length 296
<<1bfd010064fbfd3445db4a149ac8e11ca02fe5b53f1f2819d919b7490074dbf9193721c7ff778e6f095a669b4a54008f22a9488613fe746f50aa7389ea104086a8f8b9880d70676229f169c49bfbcaa1ce3a41b2e0bf661340d16844b842e9d3cbe70bf9362c22598aa43e3d25589a4373295e4fee9fd1f4f214faecbb7f6f2f0096e8fdbdcef74c89a5312eca81e4c064fbffcdc8d629db46a7fdf17aabbc46540d843c9006086c7c64deaf712ac3b17a9f342e2f27fa613e91dcd5b25d6814b3856afd3ac8678be53abe3ddca7e6aff7861ba2381955ba6f9b20a440b6b1175230838ea0065e0a56d1040ea63a205d6367a184639a8cc785e2ae98df30b3b767dddd38a6494c8e9d916e4f88c41c93153f2ac10bcd811d6502e4c3c9f36865bb183f923229f400>>
<<. . . . d . . 4 E . J . . . . . . / . . ? . ( . . . . I . t . . . 7 ! . . w . o . Z f . J T . . " . H . . . t o P . s . . . @ . . . . . . p g b ) . i . . . . . . : A . . . f . @ . h D . B . . . . . . 6 , " Y . . > = % X . C s ) ^ O . . . . . . . . . . o / . . . . . . . L . . 1 . . . . . d . . . . . ) . F . . . z . . F T . . < . . . l | d . . q * . . z . 4 . / ' . a > . . . . ] h . . . j . : . g . . : . = . . . . . . . . 8 . U . o .   . @ . . . R 0 . . . . ^ . V . . . . :   ] c g . . c . . . . . . . . 0 . . g . . 8 . I L . . . n O . . . . . ? * . . . . . e . . . . . h e . . ? . 2 ) . . >>
Jun 07 08:15:42.020 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c68: added to retransmit queue (2844ms)
Jun 07 08:15:43.715 DEBG *  192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : received 79 bytes
v:1 t:ACK c:2.05 i:3c68 {} [ Content-Format:65060 ] :: binary data length 71
<<1b5400e0c5f236ad68bf3dff385a83691241abc0061cb834e0b4d2aad3e090fb4e9c4461fe6726b914529f98b9edb792fbdac888295547ad4b26553402c0a83aa6e71e10840b03>>
<<. T . . . . 6 . h . = . 8 Z . i . A . . . . . 4 . . . . . . . . N . D a . g & . . R . . . . . . . . . . ) U G . K & U 4 . . . : . . . . . . . >>
Jun 07 08:15:43.716 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c68: removed
Jun 07 08:15:44.982 DEBG *  192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : sent 127 bytes
v:1 t:CON c:POST i:3c69 {} [ Uri-Path:m, Content-Format:65060, Uri-Query:001000000000002 ] :: binary data length 100
<<1b7500408cc4384672c4e64bd17a3b25d9884569363f7b60c605518a6c72041339308d5a7030b94e0e5c7ef9b7636d91062e611e63e3d924b19d6e2e249de3d82fdaf68eaa9cc41883685381f65af3bc3e1640adef1e5156a3e6642fce2c09f745cc2e05>>
<<. u . @ . . 8 F r . . K . z ; % . . E i 6 ? { ` . . Q . l r . . 9 0 . Z p 0 . N . \ ~ . . c m . . . a . c . . $ . . n . $ . . . / . . . . . . . . h S . . Z . . > . @ . . . Q V . . d / . , . . E . . . >>
Jun 07 08:15:44.982 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c69: added to retransmit queue (2250ms)
[2021-06-07 08:15:44.982] [console] [info] <SIMULATOR> Fetching configuration: 608677a1-bc39-448b-8881-a4df20c58530:0
Jun 07 08:15:44.982 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c6a: delayed
Jun 07 08:15:45.212 DEBG *  192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : received 4 bytes
v:1 t:ACK c:2.04 i:3c69 {} [ ]
Jun 07 08:15:45.212 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c69: removed
Jun 07 08:15:45.212 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c6a: transmitted after delay
Jun 07 08:15:45.212 DEBG *  192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : sent 29 bytes
v:1 t:CON c:PUT i:3c6a {} [ Uri-Path:h, Content-Format:text/plain, Uri-Query:001000000000002 ] :: '0001'
Jun 07 08:15:45.212 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c6a: added to retransmit queue (2625ms)
Jun 07 08:15:45.212 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c6a: removed
Jun 07 08:15:45.471 DEBG *  192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : received 79 bytes
v:1 t:ACK c:2.05 i:3c6a {} [ Content-Format:65060 ] :: binary data length 71
<<1b5400e0c5f236ad68bf3dff385a83691241abc0061cb834e0b4d2aad3e090fb4e9c4461fe6726b914529f98b9edb792fbdac888295547ad4b26553402c0a83aa6e71e10840b03>>
<<. T . . . . 6 . h . = . 8 Z . i . A . . . . . 4 . . . . . . . . N . D a . g & . . R . . . . . . . . . . ) U G . K & U 4 . . . : . . . . . . . >>
Jun 07 08:15:55.981 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c6b: delayed
Jun 07 08:16:05.982 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c6c: delayed
Jun 07 08:16:15.981 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c6d: delayed
Jun 07 08:16:16.981 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c6e: delayed
Jun 07 08:16:27.980 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c6f: delayed
Jun 07 08:16:37.982 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c70: delayed
Jun 07 08:16:41.987 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c71: delayed`

**Comment by JohanZackrisson** [comment]
I think i've found the issue.
We have an external select that waits for activity on the socket, with no timeout.
Which meant we ended up in a situation where the coap library never got the chance to service the queues.

Sorry to bother you.
But great work with the library and for the help.

**Comment by mrdeep1** [comment]
Depending on your host OS, you can use epoll and hence have a single file descriptor for the libcoap activity and then you can do a select() on the libcoap epoll fd and any any other fd/socket that you want (see `man coap_io` for examples).

**Comment by mrdeep1** [comment]
The second line of
````
Jun 07 08:15:45.212 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c6a: added to retransmit queue (2625ms)
Jun 07 08:15:45.212 DEBG ** 192.168.10.248:60172 <-> 54.220.233.198:5683 UDP : mid=0x3c6a: removed
````
is the big clue.  coap_cancel_all_messages() is being called and it is removing all entries that match the token, and in this case the entry just added to the retransmit queue which has the same token as the previous request / response (MID = 3c69).  Tokens should be unique for each request / response pair - you currently are using zero length tokens.

I would consider using `coap_session_new_token()` to get a unique token per Request (See examples in `man coap_pdu_setup`).  The downside is that you need to track different tokens in the Response message_handler function.

**Comment by JohanZackrisson** [comment]
Yup, thats basically what we are doing.

I thought that was the issue, but even with a separate timeout we are getting stuck and no packages are delivered.
The library only says that the package is delayed and it never times out the one its waiting for.

**Comment by mrdeep1** [comment]
In the trace above, you are using the same token - which is empty, as denoted by the `{}` in for example
````
v:1 t:ACK c:2.04 i:3c69 {} [ ]
````
A non zero length token would look something like
````
v:1 t:ACK c:2.04 i:3c69 {61626364} [ ]
````

**Comment by mrdeep1** [comment]
For your libcoap-bug code, you need to do something like
````
$ git diff
diff --git a/main.c b/main.c
index 895a5e1..1960695 100644
--- a/main.c
+++ b/main.c
@@ -187,6 +187,7 @@ static coap_pdu_t *coap_new_request(coap_context_t *ctx,
   if (!(pdu = coap_new_pdu(msgtype, m, session)))
     return NULL;
 
+  coap_session_new_token(session, &the_token.length, the_token.s);
   if (!coap_add_token(pdu, the_token.length, the_token.s)) {
     coap_log(LOG_DEBUG, "cannot add token to request\n");
   }
@@ -312,6 +313,8 @@ static coap_response_t message_handler(coap_session_t *session COAP_UNUSED,
   if (coap_get_log_level() < LOG_DEBUG)
     coap_show_pdu(LOG_INFO, received);
 
+#if 0
+  /* TODO - check against all used tokens */
   /* check if this is a response to our original request */
   if (!check_token(received)) {
     /* drop if this was just some message, or send RST in case of
@@ -323,6 +326,7 @@ static coap_response_t message_handler(coap_session_t *session COAP_UNUSED,
     }
     return COAP_RESPONSE_OK;
   }
+#endif
 
   if (rcv_type == COAP_MESSAGE_RST) {
     coap_log(LOG_INFO, "got RST\n");
````

**Comment by JohanZackrisson** [comment]
Tested it in our codebase and it works!
Thank you for helping me track this down.

Whats strange is that it didn't help doing
```
coap_session_init_token
```
after session initiation. It still sent request with an empty token.

**Comment by JohanZackrisson** [comment]
Now I see.
The automatic token is only done when a new session is created.
This means that if you are sending multiple requests using the same session the token is not increased automatically.
Is this a real bug or expected behaviour?

**Comment by mrdeep1** [comment]
It is expected behavior unfortunately.  The application needs to track the token used for at least:

- A request that contains 'Observe this resource' option so that the client knows what to do with unsolicited responses (RFC 7641).
- A request that contains 'Observe this resource' option so that the 'Observe' can be subsequently cancelled on the server by the client (multiple resources may be being Observed and only one of them needs to be cancelled).
- Matching a response to a particular request.

I agree that this is not obvious in the coap-client example - which is basically written for testing the sending out a single request and getting back a single response (and potential unsolicited responses if Observing a Resource) so unique tokens per request are not needed.  I will look at updating the coap-client to be more obvious for Token usage (it is documented in the manual pages examples, but you need to know where to start looking).

**Comment by JohanZackrisson** [comment]
Perfect!
Thanks again for all your help and feedback. Hopefully anyone else with the same issue can find this bug and figure out what to do.

**Comment by mrdeep1** [comment]
No problem.  As a FYI, PR #701 has been created to aid others to not fall into this 'issue'.

**Comment by mrdeep1** [comment]
@JohanZackrisson Please close this issue if there is nothing else related to this issue.

**Comment by obgm** [comment]
Closing off as resolved.
