### ISSUE TITLE
More portability

### ISSUE THREAD

**Issue by jsjeong** [obgm/libcoap#7]
Hi,

I think it's not easy to port libcoap to other platforms neither POSIX, Contiki, nor lwIP.
Is there any guide for it?
I don't want to add another `#ifdef` ~ `#endif` blocks into libcoap code.

Like coap_io.c that has `CUSTOM_COAP_NETWORK_SEND` and `CUSTOM_COAP_NETWORK_READ`, I think other codes (including net.c) also should have preprocessors for more portability.

Regards,
Jongsoo

**Comment by franc0is** [comment]
@jsjeong funny timing! I have started work on splitting the platform code off into cleaner modules. See https://github.com/obgm/libcoap/pull/6.

**Comment by jsjeong** [comment]
@franc0is Wow! Before merging your pull, I'll do my work from fork of your work. Thank you very much for your work. :+1:

**Comment by franc0is** [comment]
It's not nearly finished yet, but it's a start! Any input is appreciated.

**Comment by obgm** [comment]
I have started refactoring a bit, see [1] as the work on PR #6 seems to have stalled. At least, I got no reaction on my comments and hence will close this bug for now.

[1] https://sourceforge.net/p/libcoap/mailman/message/34974708/
