### ISSUE TITLE
Retrieve raw data

### ISSUE THREAD

**Issue by flukkyy** [obgm/libcoap#703]
## Environment

- libcoap version : 4.3.0rc2

    
- Build System:             [Make]
- Operating System:         [Linux]
- Operating System Version: [20.04]
- Hosted Environment:       [None]

## Problem Description

hi, i want to know how to retrieve data on their raw format (HEX format) same way as in wireshark, after the `end of option marker 0xFF  `i want to store the payload HEX data  in a buffer.
i read the `coap_get_data()` function but it only returns the length and data pointer of the specified PDU.

i know that i should be looking in the `coap-server.c` receive function but i dont know where to look exactly! :(

**Comment by obgm** [comment]
`coap_get_data()` gives you the raw data (length number of bytes starting at the data pointer). How you represent that data in your output (hex or anything else) is up to you. You may consult the function `print_readable()` in coap_debug.c to see how to output bytes in human-readable hexadecimal notation.

**Comment by flukkyy** [comment]
i still don't get it completely, but can you provide me with the function or the command or anything that print out the response. the coap_io_process() returns the time spent in processing the response but where is the response to print in the coap-server.c

**Comment by mrdeep1** [comment]
If you run the` coap-server` with the` -v 7` option, you will see the request PDU and the response PDU printed out by the underlying libcoap using [coap_show_pdu()](https://libcoap.net/doc/reference/develop/man_coap_logging.html)

When the request handler (as defined by [coap_register_handler()](https://libcoap.net/doc/reference/develop/man_coap_handler.html)) in `coap-server` is called, there is a pointer to the `request `and `response `PDUs - and when the code returns from this function `response`  will get sent back to the client as appropriate (as updated by this handler).  To analyze the information in these PDUs in the request handler, see [coap_pdu_access](https://libcoap.net/doc/reference/develop/man_coap_pdu_access.html).

[coap_io_process()](https://libcoap.net/doc/reference/develop/man_coap_io.html) checks to see if there is any thing to send, or if there is pending receipt data it calls the appropriate registered handler to process that data.

**Comment by flukkyy** [comment]
thank you so much that was very helpful! 

another unrelated question. is the `post` method not implemented ?  or i should write the code same way as for the put method in the `coap-server.c` ?

**Comment by mrdeep1** [comment]
examples/coap-server.c is just that - an example, and so does not have every possible combination and availability functionality. 

You can write the code to do whatever you want, but you must follow the usage rules as defined in RFC7252 - in particular https://datatracker.ietf.org/doc/html/rfc7252#section-5.8 for request handlers - if your code is going to successfully interact with other CoAP applications.

**Comment by obgm** [comment]
@flukkyy As your question has been answered, I think this issue can be closed off?
