### ISSUE TITLE
Parsing coap_get_data() JSON.

### ISSUE THREAD

**Issue by ameerhazo** [obgm/libcoap#705]
Environment
libcoap version: 4.3
Build System: CMake
Operating System: Windows
Operating System Version: [ ]
Hosted Environment: ESP-IDF

Hi everyone, I'm using libcoap 4.3 on the ESP32 to process and validate JSON data. I'm using the coap_get_data() API to get the JSON payload from the coap request (able to print out the data as a string). I've tried using the cJSON library of the ESP IDF to parse the JSON payload to no success. How would you go about parsing a JSON Payload with your JSON library? Were you able to do that with your JSON library?

Many thanks,
Ameer

**Comment by obgm** [comment]
This seems to be a cJSON question rather than a libcoap question. Anyway, coap_get_data() gives you a pointer to a byte sequence and a length (cf. the documentation). If I read the cJSON documentation correctly, you need to pass these to cJSON_ParseWithLengthOpts().

**Comment by ameerhazo** [comment]
Hello @obgm, I've asked the question on the cJSON Github page and havent gotten any answers yet. I'm asking it here to see if they are able to parse the JSON Payload that has been separated out from the request message using the libcoap API. Thanks for the suggestion, I'll give it a try. Sorry if the question is quite misplaced.

**Comment by mrdeep1** [comment]
The only issue that I have come up against is the JSON is malformed and hence parsing failure.  Take your string printed output and use a JSON lint validator - e.g. https://jsonlint.com for verificaton.

**Comment by obgm** [comment]
I suppose you cannot expect people to answer fast to questions that you could have answered yourself by reading the documentation. The issue tracker is merely a tool for bringing issues with the code to the attention of the developers. Most open source projects have mailing lists for answering questions related to the usage (so does libcoap as can be found in the documentation).

**Comment by ameerhazo** [comment]
Hello @mrdeep1 thanks for the suggestion, the JSON payload that I'm trying to send to the server has been validated before I had this issue and the payload is indeed valid. 

Hello @obgm, once again I apologize if the question is misplaced. I have gone through the documentation as well as the examples of the cJSON API I'm using to parse the payload and have used it based on the examples given.
