### ISSUE TITLE
CoAP/MQTT communication

### ISSUE THREAD

**Issue by flukkyy** [obgm/libcoap#706]
hi, 
does the libcoap library has any way of communication with the mqtt protocol.. 
i am looking for a solution to make my coap client read the data(json format) from an mqtt server.. or make the coap client subscribe to the mqtt..

1. is it possible to do it.
2. **does the libcoap support this kind of communication.**
3. any kind of information about this topic is appreciated.
thanks!

**Comment by obgm** [comment]
libcoap does not support MQTT as it is a completely different protocol. Of course, you could take an MQTT implementation of your choice and integrate with libcoap.
If you just need some sort of multiprotocol gateway, take a look at OpenHAB and similar projects. These usually have support for CoAP and MQTT and provide higher-level APIs for smart home applications based on those transports.
