### ISSUE TITLE
code for POST Method

### ISSUE THREAD

**Issue by flukkyy** [obgm/libcoap#710]
## Environment

- libcoap version (4.3.0 rc2):

- Build System:             [Make]
- Operating System:         [Linux]
- Operating System Version: [ ]

Hi, am trying to code the `POST` method to use for creation of resources, when reading the` coap-server.c` i noticed the `hnd_unknown_put()` and `hnd_put()` and as said in the description :  
```
/*
 * Regular PUT handler - used by resources created by the
 * Unknown Resource PUT handler
 */ 
```
so:
1.  How can i test the resource creation using these  2 functions?
2. As the POST and PUT methods are practically the same (correct me if i am wrong), can i use the same code as PUT for the POST method. 
( i tried the same code, i added  `hnd_post` to one of my resources and tried to update it with another value, i got code error `4.06 Not Acceptable`)

thanks!!

**Comment by obgm** [comment]
You need to run `coap-server` with `-d` to enable dynamic creation of resources. Sending a `PUT` request to a resource that does not already exist on that server triggers `hnd_unknown_put()` (which might call `hnd_put()`). 

`POST` and `PUT` have a lot in common. A successful `PUT` results in creation of the resource named in the request URI whereas this is not necessarily the case for `POST`. For the dynamic creation of resources, only `PUT` is supported.

**Comment by obgm** [comment]
**man coap-server** says:

```
       -d max
           Enable support for creation of dynamic resources when doing a PUT up to a limit of max. If max is reached, a 4.06
           code is returned until one of the dynamic resources has been deleted.
```

I suppose that is what happened here.

**Comment by flukkyy** [comment]
thanks for the quick reply! that was really helpful! 

what if i don't want the resources to be dynamic, is it possible to save the resources permanently in the server even after a crash

**Comment by obgm** [comment]
Making them persistent does not work out of the box. You would need to store a representation of the resource on disk, containing the resource URI, media type, size and actual data. At startup, this serialized data needs to be turned into resources, pretty much like `hnd_unkown_put()` does.
