### ISSUE TITLE
Client Asynchronous Requests 

### ISSUE THREAD

**Issue by flukkyy** [obgm/libcoap#712]
-

## Environment

- libcoap version 4.3.0 rc2

    
- Build System:             [Make|]
- Operating System:         [Linux]
- Operating System Version: [ ]

Hi,
i have a question about asynchronous requests, i read the man page [coap_async](https://libcoap.net/doc/reference/4.3.0/man_coap_async.html)  i was able to receive delayed responses, but, what if i want to do delayed requests?
for example: 
first, all my resources have a 15sec delay!!

let's say that am sending the first request at 08:00:01 -> will be received at 08:00:16
second request will be sent at 08:00:05 -> received at 08:00:20 .

the two requests are targeting different resources.
until now, this works fine!

so, what i am trying to do, is to only send the second request when i received the response for the first request: 
that means, after receiving the first request at 08:00:16, the second request will be sent at 08:00:16 and received at 08:00:31

i tried doing an `if` condition with the `COAP_RESPONSE_CODE_CONTENT` on the `coap_send_large` but didn't work.

i read the #700 and  #701 but the added  -`G option` is to send the same request multiple times with different tokens.

**Comment by obgm** [comment]
A very basic and portable solution is to store the time of the last received response in a variable and check periodically if your wait time has expired. If so, send the new request and reset the timer variable. Look at the call to `coap_io_process()` in coap-client.c to see how to pass a timeout value and the subsequent `if` to see how the timeout is handled.

**Comment by mrdeep1** [comment]
There is nothing stopping you in the client code's response handler generating a new PDU and then sending off the new request to do it immediately.

**Comment by flukkyy** [comment]
inside the response handler i can create a second request to be sent after receiving the first one ? is that what you are saying ?
and what if, am gonna be sending requests whenever the client receive data to send, is creating a second request in the response handler will make it work ?
i think doing it with a timeout is more efficient, right ?

**Comment by mrdeep1** [comment]
It is difficult to second guess what your ultimate design is - I was offering a potential solution which may or may not work for you. I was responding to:-

> so, what i am trying to do, is to only send the second request when i received the response for the first request:
