### ISSUE TITLE
ResponseHandler seems to be unactivated when using Blockwise Transfer

### ISSUE THREAD

**Issue by cs1488** [obgm/libcoap#717]
We use the libcoap libary to get familiar with the concepts and made some progress so far.
We could set up a Server and a Client to send regular coap requests, handle it properly and get a reply.
However when we switched to a blockwise transfer, we encountered a problem/bug?.

When we use dummy data with a size of 1024, the responseHandler gets active and presents the data on stdout.

When we increased the size of data to 2048, the data is split into seperate blocks, as expected. (We confirmed that in wireshark)
The second Block gets 0 in M so the Client should recognize that the transfer is done but the response handler is not called.

When increasing the size of data further e.g. 4096, the second Package gets an one in the field of M.
So further Packages should be send, but are not.
In Wireshark we get the icmp Destination unreachable (Port unreachable) error.

I add our response Handler, that seems to be unactivated.

``
    coap_response_t RESP_handler( coap_session_t* session,
    const coap_pdu_t *sent, const coap_pdu_t *received,
    const coap_mid_t mid){
   
    fprintf(stderr, "Test1.\n"); // I get here when payload is 1024 else not.
    uint8_t *dataptr;
    size_t datasz;
    size_t offset;
    size_t total;

    coap_show_pdu(LOG_WARNING, received);

    /* retreive the payload data */
    /*
    coap_get_data(
        received,                       // received pdu
        &datasz,                        // received data size
        (const uint8_t **) &dataptr     // pointer to the received data
    );
    */
    fprintf(stderr, "Test2.\n"); // I get here when payload is 1024 else not.
    coap_get_data_large(
        received,                       // received pdu
        &datasz,                        // received data size
        (const uint8_t **) &dataptr,    // pointer to the received data
        &offset,
        &total
    );
    
    ReceivedDataLen = datasz;
    ReceiverDataBuf = malloc( datasz * sizeof(uint8_t) );
    if( ReceiverDataBuf == NULL ) {
        fprintf(stderr, "Fatal error: out of memory.\n");
        exit(EXIT_FAILURE);
    }

    for(size_t i = 0; i < datasz; ++i) {
        ReceiverDataBuf[i] = dataptr[i];
    }
    

    return COAP_RESPONSE_OK;
}`
We hope you can help us, to set the response Handler up in the right way.

Best Regards

**Comment by mrdeep1** [comment]
Have you called `coap_context_set_block_mode(context, COAP_BLOCK_USE_LIBCOAP)`  or `coap_context_set_block_mode(context, COAP_BLOCK_USE_LIBCOAP|COAP_BLOCK_SINGLE_BODY)` at any point in your client code?

In general, to handle blocks, you need to look at [coap_block(3)](https://libcoap.net/doc/reference/develop/man_coap_block.html).

Another potential issue is that calling `coap_io_process()` is not in a loop so that the second packet is never processed after the first call to `coap_io_process()`.

> for(size_t i = 0; i < datasz; ++i) {
>     ReceiverDataBuf[i] = dataptr[i];
> }

Consider using `memcpy(ReceiverDataBuf, dataptr, datasz);`.

**Comment by cs1488** [comment]
Thank you for the fast reply.
We called `coap_context_set_block_mode(context, COAP_BLOCK_USE_LIBCOAP|COAP_BLOCK_SINGLE_BODY)`
in our Client_init function.

I tried adding a for loop around the `coap_io_process()` and now it works.
Where is the best "place" to call this method?

I assumed that this function would be called internally after the system "recognizes" that there is a blockwise transfer, especially with the new update, which aims to shift the session handling from application to libcoap.
Maybe that could be a feature in the future.

Thank you again, for helping us out here.
Best Regards

**Comment by mrdeep1** [comment]
Others have stumbled into the need of how to properly code this.  As per [coap_io(3)](https://libcoap.net/doc/reference/develop/man_coap_io.html)
````
       The coap_io_process() function will process any outstanding
       packets to send for the specified context, process any available
       input packets and then wait for processing any new input
       packets, or for when to re-transmit a packet, for up to
       timeout_ms milli-seconds before returning. There are 2 special
       case timeout_ms values.
...
       There are two methods of how to call coap_io_process().

        1. Have coap_io_process() called from within a while() loop.
           Under idle conditions (no input traffic) coap_io_process()
           will then get called every timeout_ms, but more frequently
           if there is input / retransmission traffic.

        2. Wait on the file descriptor returned by
           coap_context_get_coap_fd() using select() or an event
           returned by epoll_wait(). If read is available on the file
           descriptor, call coap_io_process() with timeout_ms set to
           COAP_IO_NO_WAIT.

           NOTE: This second method is only available for environments
           that support epoll (mostly Linux) with libcoap compiled to
           use epoll (the default) as libcoap will then be using epoll
           internally to process all the file descriptors of the
           different sessions.
````
The returning from `coap_io_process()` allows the application to go off and do other things (which could simply be to exit the app) before processing the next set of CoAP packets.
