### ISSUE TITLE
Incorrect output using blockwise transfer

### ISSUE THREAD

**Issue by cs1488** [obgm/libcoap#718]
[DebugOutput.txt](https://github.com/obgm/libcoap/files/6759888/DebugOutput.txt)
## Environment
- Operating System:         Linux On 2 Systems (MX Linux on localhost, and Ubuntu to Raspbian)

## Problem Description

When using blockwise transfer received and sent data do not match.
Our Dummy Data are just numbers ascending from 0-255 and then again until the data is filled.
We tried different sizes (2048, 4096, 8192 Bytes).
We could confirm the data in the first blocks via stdout and wiresharks.
But in the last blocks the data seem to be corrupted. 

The data is ok before added by coap_add_data_large()

I tried to use the coap_log() function, i got a print in the stdout, that i will share, there you can see the difference in the data.
The Level was DEBUG (Under LEVEL Warning the Payload displaced seems to match, but actually is not.)

### Expected Behavior

Data in Destination = Data in Source

### Actual Behavior

Data in Destination != Data in Source

### Steps to reproduce

Send data with coap_add_data_large that consist of periodically ascending numbers?

# Code 
### Response Handler that calls ``coap_add_data_large()``
```c
void dummy_GET_Handler( coap_resource_t *resource, 
    coap_session_t *session, const coap_pdu_t *req, 
    const coap_string_t *query, coap_pdu_t *resp) {
    
    uint8_t dummydata[DUMMY_SIZE];

    /* print request pdu info */
    coap_show_pdu(LOG_WARNING, req);

    /* add the response code 2.05 (basically the same purpose as HTTP 200 OK)*/
    coap_pdu_set_code(resp, COAP_RESPONSE_CODE_CONTENT);

    /* get the dummy data */
    read_dummy(dummydata, DUMMY_SIZE);
    /*
    fprintf(stderr, "--------------- Dummy Data ---------------\n");
    for(int i = 0; i < DUMMY_SIZE; ++i) {
        if( ( (i+1) % 32) == 0)
            fprintf(stderr, "%d\n", (short) dummydata[i]);
        else 
            fprintf(stderr, "%d ",  (short) dummydata[i]);
    }
    fprintf(stderr, "\n------------------------------------------\n");
    */
    /* prepare the dummy data for blockwise transfer */
    coap_add_data_large_response(
        Resource_Dummy,             // corresponding resource
        session,                    // session handled by libcoap
        req,                        // incoming request
        resp,                       // response
        query,                      // incoming query
        COAP_MEDIATYPE_TEXT_PLAIN,  // mediatype utf-8 (don't care)
        1,                          // maxage (-1 = don't care)
        0,                          // etag (0 = don't care)
        DUMMY_SIZE,                 // size of data
        dummydata,                  // data
        NULL,                       // func pointer to release heap data
        NULL                        // application pointer (don't care)
    );    

    /* print the response pdu info */
    //coap_show_pdu(LOG_WARNING, resp);
    coap_show_pdu(LOG_DEBUG, resp);
}


```
### Function to produce the dummy data
```c
static void read_dummy( uint8_t *data, size_t size ) {
    for(int i = 0; i < size; ++i) {
        data[i] = i % 256;
    }
}
```

## Debug Logs

```
See DebugOutput.txt
```
Best Regards

**Comment by mrdeep1** [comment]
The variable `dummydata `is no longer available when the function `dummy_GET_Handler()` returns as it is allocated on the stack and will be overwritten by any other function that is subsequently called that uses the same stack space.

On returning from `dummy_GET_Handler()`, the first packet is sent off containing the first 1024 bytes and then when sending the second packet etc. it will contain whatever is currently in `dummydata `stack location which could now be different.

As per [coap_block(3)](https://libcoap.net/doc/reference/develop/man_coap_block.html) (in particular, the last sentence)
````
The coap_add_data_large_response() function is responsible for handling the server’s large responses to requests. 
coap_add_data_large_response() should be used as a direct replacement for coap_add_data() if it is possible that the length of data
will not fit into a single server’s response pdu. This function adds in the initial part of the payload data of length length to the PDU
pdu. release_func (if not NULL) and app_ptr are used for releasing the data when the body transfer is complete.
````
So, you have 2 choices here.
1. Allocate the `dummydata `and then free it off using the `release_func `callback and provide the data location in `app_ptr`
2. Make `dummydata `a `static `(not that clean in my opinion)

**Comment by mrdeep1** [comment]
@cs1488 Does this fix your issue?  If so, please confirm and close off this issue.

**Comment by cs1488** [comment]
Yes that fixes the issue. 
Thank you
