### ISSUE TITLE
Missing COAP_TICKS_PER_SECOND factor in example/coap_server.c

### ISSUE THREAD

**Issue by rosolar** [obgm/libcoap#72]
In line 510 of the coap_server.c example a multiplication factor is missing. Instead

`if ( nextpdu && nextpdu->t <= COAP_RESOURCE_CHECK_TIME )`

it should be 

`if ( nextpdu && nextpdu->t <= COAP_RESOURCE_CHECK_TIME * COAP_TICKS_PER_SECOND )`

nextpdu->t is in milliseconds and the check time is in seconds, so conversion is needed.

**Comment by obgm** [comment]
Thanks for pointing this out. This is fixed in commit 771f013.
