### ISSUE TITLE
TCP is received, but UDP is not

### ISSUE THREAD

**Issue by flukkyy** [obgm/libcoap#724]
## Environment

- libcoap version : 4.3.0
- 
- Build System:             [Make]
- Operating System:         [Linux]
- Operating System Version: [ 20.04]
- Hosted Environment:       [None]

## Problem Description

i added my `coap-server` to a gateway and its working fine,
the server is running perfectly fine, the `ip:port` is tested using different commands such as `nmap` , `telnet` and others, each time it shows that the port is open and the connection is a success.

My problem is that there's no response from the server over UDP , `wireshark` is showing that the requests are being sent and  re-transmitted until timeout.
when tested with TCP it works and i receive a response from the server.
After some research, i thought that the gateway doesn't support `NAT loopback`, so i tried sending requests from another connection (i used my phones 4G). I even disabled firewall on the gateway too, But no success either.

i thought it's a problem with the server configuration, but i cant seem to find anything out of the ordinary.

**Comment by mrdeep1** [comment]
On the gateway, confirm that the server is listening on the coap port using netstat -an or similar, and confirm the listening address is remotely accessible (e.g. not loop back).
If the server is to be accessed using multicast iP then that needs to be set up as well.

**Comment by mrdeep1** [comment]
You need to add in the appropriate multicast listening address using the coap-server -g option as per the documentation

For the server, have you enabled -v9 to get full logging to confirm that it not seeing any traffic coming up the network stack to the application?
