### ISSUE TITLE
tiny.c example id generation is broken

### ISSUE THREAD

**Issue by Grabber** [obgm/libcoap#735]
## tiny.c
```
id = rand() & INT_MAX;
```

## pdu.c

```
assert(mid >= 0 && mid <= 0xffff);
```

replace with:
```
id = rand() & 0xffff;
```

**Comment by mrdeep1** [comment]
Thank for reporting this.  I have created a PR for it in #736, but using the current libcoap method for getting the latest mid.

**Comment by mrdeep1** [comment]
PR #736 has now been merged.  Please confirm the fix works for you and if so, then please close this Issue.
