### ISSUE TITLE
DTLS branch build errors

### ISSUE THREAD

**Issue by Gr3yh0und** [obgm/libcoap#75]
Hey Olaf,
I checked out your DTLS branch because I need a simple coap client that supports DTLS with PSK. When I try to build tinyDTLS I receive the following errors:
> config.status: error: cannot find input file: `dtls_config.h.in'
> ...
> dtls.c:20:22: fatal error: tinydtls.h: No such file or directory
>  #include "tinydtls.h"
>                       ^
> compilation terminated.
> <builtin>: recipe for target 'dtls.o' failed
> make: *** [dtls.o] Error 1

When I compare the file dir structure to the normal tinyDTLS I see that a couple of .h and .in files are missing. Do you think it would be possible for you to do a quick check on that?

Thanks in advance!

**Comment by obgm** [comment]
After a recursive clone, did you run configure in the tinydtls subdirectory?

**Comment by Gr3yh0und** [comment]
I did a clone, `git submodule update --init --recursive`, then a `autoreconf` in the `ext/tinydtls` dir followed by `./configure` and `make`.

**Comment by malinengineer** [comment]
@Gr3yh0und Follow these steps and let us know if it works:

```
git checkout dtls
git submodule update --init --recursive
./autogen.sh
./configure --disable-shared
make
```

**Comment by Gr3yh0und** [comment]
@malinengineer and @obgm : Thanks for the quick help. It is building now an I can run the example server/client!

**Comment by tijuca** [comment]
Feel free to provide a updated Readme file.

**Comment by Gr3yh0und** [comment]
Done in: #81
