### ISSUE TITLE
BUG: error while loading shared libraries: libtinydtls.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SalvaHasan** [obgm/libcoap#753]
I have installed Libcoap on Raspberry Pi 4 and used `./configure --disable-documentation --enable-examples --with-tinydtls --enable-shared` during configuration. I am unable to run any scripts from within libcoap/examples such as coap-client, coap-server etc. 
It works fine if I configure it without dtls using --disable-dtls 
@obgm

**Comment by mrdeep1** [comment]
You have not stated which version of libcoap you are trying to build.  What is it?
Did you do a `git clone` to get the libcoap source?
Have you followed the instructions for TinyDTLS in the file `./BUILDING`?
Are there any error messages when running `./configure` or `make`?
Have you tried `--disable-shared`?

**Comment by SalvaHasan** [comment]
Here are the steps I followed: 
```
 sudo git clone https://github.com/obgm/libcoap.git
 cd libcoap
 sudo git submodule init
 sudo git submodule update
 sudo ./autogen.sh
 sudo ./configure  --disable-documentation --enable-examples --with-tinydtls --enable-shared
 sudo make
 sudo make install
```
No I did not get any errors at any step and yes I have also tired it with disable-shared

**Comment by mrdeep1** [comment]
My preference for the building would have been (but would make no difference here)
````
 git clone https://github.com/obgm/libcoap.git
 cd libcoap
 git submodule init
 git submodule update
 ./autogen.sh
 ./configure  --disable-documentation --enable-examples --with-tinydtls --enable-shared
 make
 sudo make install
````
So that the risk of inadvertantly trashing something is considerably reduced.


Try doing 
````
 sudo /sbin/ldconfig
````
and see if that makes it work.

**Comment by SalvaHasan** [comment]
I tried it with `--disable-shared`  on another Pi and it works. I'm gonna try with a fresh install of Raspberry Pi OS. 
Thanks.
