### ISSUE TITLE
Make coap_pdu_parse() public

### ISSUE THREAD

**Issue by obgm** [obgm/libcoap#755]
`coap_pdu_parse()` used to be a public function prior to version 4.3 and was put into the internal API to hide implementation details.

As this function is very useful in unit tests that craft CoAP messages to be fed back into libcoap, I would like to see it in the public interface again unless I am missing an important reason why this should be hidden.

**Comment by mrdeep1** [comment]
No specific reason as to why it was hidden.  I will raise a PR to make it visible.

**Comment by obgm** [comment]
Thanks!
