### ISSUE TITLE
" large body receive internal issue " error when receiving observed resource via block-wise transfer

### ISSUE THREAD

**Issue by sixdenip** [obgm/libcoap#758]
## Problem

I'm trying to send data using block-wise transfer and Observable resources. I managed to send large data before but now I'm getting the message ``large body receive internal issue`` and I don't know what it means...
On the client side, only the first packet is transmitted (with the block-specific options, which it's not supposed to).
Of course I set ``    coap_context_set_block_mode(ctx, COAP_BLOCK_USE_LIBCOAP | COAP_BLOCK_SINGLE_BODY);
    coap_register_option(ctx, COAP_OPTION_BLOCK2);`` at the beginning of my code.
I tried to remove the custom options that I added and the same thing happened.

## Server-side:

```
v:1 t:CON c:2.05 i:9c31 {} [ Observe:54, Content-Format:application/octet-stream, 2048:\x77\x61\x76\x65\x66\x6F\x72\x6D\x5F\x31\x37\x37\x32\x2E\x72\x61\x77, 2050:\x73\x61\x6D\x70\x6C\x65 ] :: binary data length 21200940
<<binary data>>

Oct 05 18:11:37.686 INFO Response sentOct 05 18:11:37.686 DEBG *  [::]:5680 <-> [::1]:60383 UDP : sent 1070 bytes
v:1 t:CON c:2.05 i:9c31 {} [ ETag:0x37, Observe:54, Content-Format:application/octet-stream, Block2:0/M/1024, Size2:21200940, 2048:\x77\x61\x76\x65\x66\x6F\x72\x6D\x5F\x31\x37\x37\x32\x2E\x72\x61\x77, 2050:\x73\x61\x6D\x70\x6C\x65 ] :: binary data length 1024
<<binary data>>
```

## Client-side:

```
v:1 t:CON c:2.05 i:9c31 {} [ ETag:0x37, Observe:54, Content-Format:application/octet-stream, Block2:0/M/1024, Size2:21200940, 2048:\x77\x61\x76\x65\x66\x6F\x72\x6D\x5F\x31\x37\x37\x32\x2E\x72\x61\x77, 2050:\x73\x61\x6D\x70\x6C\x65 ] :: binary data length 1024
<<binary data>>

Oct 05 18:11:38.238 DEBG ** [::1]:60383 <-> [::1]:5680 UDP : large body receive internal issue
v:1 t:CON c:2.05 i:9c31 {} [ ETag:0x37, Observe:54, Content-Format:application/octet-stream, Block2:0/M/1024, Size2:21200940, 2048:\x77\x61\x76\x65\x66\x6F\x72\x6D\x5F\x31\x37\x37\x32\x2E\x72\x61\x77, 2050:\x73\x61\x6D\x70\x6C\x65 ] :: binary data length 1024
<<binary data>>
```

Thanks for your help.

**Comment by mrdeep1** [comment]
`coap_register_option(ctx, COAP_OPTION_BLOCK2);` is not required as the option is already known about.

The first record that you report on the client side is a response, not a request.  Hence why you are seeing the Block2 option. 

What is the actual request (or are you just expecting an unsolicited response)?

As the log entries provided all have` i:9c31`, it is my suspicion that these are retried/retransmitted responses as each new request / response should have its own unique `message id`.

Are you doing the Observe set up request when also sending data in the same packet - if so, you should be using FETCH Instead of GET.

`large body receive internal issue` is reported when the `lg_crcv` structure has not been set up, or has prematurely been freed off and there is an unexpected unsolicited response.

Your issue may be that you are not using Tokens that are unique per request so that responses can be correctly matched by the originating request - see [Token](https://datatracker.ietf.org/doc/html/rfc7252#section-5.3.1) and [coap_session_new_token(3)](https://libcoap.net/doc/reference/develop/man_coap_pdu_setup.html)

**Comment by sixdenip** [comment]
Thanks for you fast response. This is the request :`` v:1 t:CON c:GET i:9c31 {} [ Observe:0, Uri-Path:sample, Uri-Path:waveform ]``
But in my app it supposed to be the only one, as every response should be unexpected updates from the server.
I am, I'll look into FETCH.
I've tried a quick fix by adding a token, now the blocks are transfering but it stops after 13 blocks, I have to investigate more.
But how am I supposed to use token with an observable resource ? Since I'm supposed to set it in the request from the client but there's no request.

**Comment by mrdeep1** [comment]
As you do not have any data in your GET request, there is no need to use FETCH as an alternative.

As per [4.1 Request](https://datatracker.ietf.org/doc/html/rfc7641#section-4.1), everything is matched on the endpoint / token.

When a request is recieved by the server to Observe a resource, the response is the current state of the resource along with the Observe option to indicate that the Observe subscription was successful.  The token used in this request is the same token that will be used in any response associated with this Observe. 

A resource being Observed can send off an unsolicited response at any time (within reason - sending off many unsolicited responses at once is not recommended...).

I would look at what is reported with respect to `lg_crcv` information - this structure should remain throughout the lifetime of potentially recieving an unsolicited Observe response.

The large size of 21200940 (21M) should work fine (there is a limit of 1G) - the receiving logic should generate a block of memory with this size to receive the data into.  I do not recognize your option that has a number value of 2048, but do not think that this is the issue.

What is in the logs around the failure circa the 13th recieved block?

**Comment by mrdeep1** [comment]
Using the standard `coap-client` and `coap-server`, `21200940` transfers with no issue.

**Comment by mrdeep1** [comment]
Just seen a potential issue - checking into it.

**Comment by mrdeep1** [comment]
Good that increasing the time between triggering the unsolicited responses is a good workaround. 

> Side question : any way to find out there's a block transfer currently happening ? Currently I just check the current value of coap_io_process()

Not from the application layer.  I need to do this type of check in a lower layer (not start a new transmission until the previous one has finished), but cover the case when a client has elected not to recieve all of the body of data that spans multiple payloads.

The delaying/dropping of the next unsolicited response is already handled in the case of the body of data fitting into a single packet and the previous response transmission using CON has not yet been ACK'd by the client (likely down to a lossy network).
