### ISSUE TITLE
Trouble in unit testing because of static method handler

### ISSUE THREAD

**Issue by iamniki01** [obgm/libcoap#766]
Hi @obgm , @cladmi @biodranik 

I am developing coap server and coap client, where coap server publish and consume data from Apache Kafka. Since all method handler are static, I was not able to test and see console output while testing. So is there any alternative method to get rid off from the static methods. If there any ways to get rid off from this static method that can solve many of my problem. 

Unfortunately I have no error, but I am facing difficulty while testing (only static method logs and console outputs can't see while unit testing). To check my main functionality, the response from client and server is really required. Please help me with this.
 Any leads or information will be helpful ☺️

**Comment by biodranik** [comment]
How do static methods relate to logs? If there is a log in the code, but it is not printed, then it means that either your print doesn't work, or your method is not called.

**Comment by iamniki01** [comment]
Not exactly, hope I can clearly explain my problem, I have static void  getHandler (argss) and static void putHandler (argss) (i .e these are are the types of coap_method_handler_t) which is registered in coap_register_handler. When get or put is called register handler invokes the particular handler. Here in my getHandler there is lot of things happening like adding data, topic to kafka for each client will receive response from server. So now the client receive response in static method called as response handler () was invoked by coap_register_reaponse_handler() . Now both client and server handlers are static. I can't see response in test. So I tried to get rid off from the static method but it is not happening. Is there any way to get rid off from this static method handlers? Or is there any technique to send and receive response from server and client? Hope, now it is clear🙂

**Comment by mrdeep1** [comment]
To help our understanding, I need to split this out into different areas
1. Separate application coap-client initiates a GET/PUT to different application coap-server (can be on same host or different hosts)
2. coap-server recieves GET/PUT and libcoap logic directs request to getHandler() or putHandler() as appropriate.
3. when getHandler() or putHandler() return from function, this causes libcoap to send a response back to coap-client depending on how the response PDU (last parameter of coap_method_handler_t) is updated.  The coap-client then recieves the response via its registered response handler.

coap_register_response_handler() is for client logic and so is not normally called in a coap-server, but is used in a coap-client.  However, if you have a coap-proxy (acting as a server and then forwarding on CoAP requests as a client), coap_register_response_handler() can be used in the specific client part of the coap-proxy logic.

Now, as I understand what you are saying, your getHandler updates / gets some information from Apache Kafka and then should be updating the response PDU before exiting the getHandler function.

The information exchange with  Apache Kafka can take some time and all this can be done while still executing code in getHandler() before sending the response when the function returns (known as a piggy-back response).  It is also possible to send back an empty ACK followed at a later stage with what is known as separate response.  See [coap_async(3)](https://libcoap.net/doc/reference/develop/man_coap_async.html)

From a testing perspective, I would initially use the libcoap example coap-client against your provided coap-server to test out / debug what is happening by using verbose logging (-v9 option) and then once you aer happy with the requests/responses doing what is expected, then customize your coap-cleint as appropriate.

**Comment by iamniki01** [comment]
Hi @mrdeep1 ,

Thanks for your brief, My server and client is running fine. If i am able to run in local host with my resource name "coapHandler". Even getHandler and putHandler sending ack to client and receiving confirmation. For me it is running completely fine if I able to run it locally. Even I can see the response from both client and server. But if i run same in my unit test (using gtest) no response is printing but test is passing. That mean inside everything is working as expected. But static method debug logs and piggy back response from getHandler is not visible.  So if I want to make it visible, I should get rid off from "static". But if I remove static coap_register_handler will throw an error. 

Again I used coap_register_response_handler() in client only. My straight forward question is how can I use getHandler and putHandler without static. Also, I would like to say all my functionalities are working and client and server communication is working fine. But only facing problem with unit testing. Now it is more clear.

**Comment by mrdeep1** [comment]
OK, I think I better understand your issue.  You want to be able to use getHandler() and putHandler() in a (possibly separate) unit test suite.

I would then just remove static from the the 2 functions and then separately define the functions (in a .h file that both coap-server build and unit test build have access to them) in theform of
````
void
getHandler(coap_resource_t *resource,
             coap_session_t *session,
             const coap_pdu_t *request,
             const coap_string_t *query,
             coap_pdu_t *response);
````
so that
````
  coap_register_handler(r, COAP_REQUEST_GET, getHandler);
````
works.  After your unit test calls getHandler(), it can do a `coap_show_pdu(COAP_LOG_WARNING, response); `to show what the response PDU looks like

**Comment by iamniki01** [comment]
Thanks that you finally got my point, I did it in same way, and removed static from both the function and did it as you mentioned but I got an error like this. 
```
error:error invalid use of non-static member function 'void CoapServerAPI:: getHandler(coap_resource t", .......) in  (void)coap_register_handler(resource, COAP_REQUEST GET, getHandler);
```
I tried in many ways, But I can't get rid off this static method.

**Comment by obgm** [comment]
You are trying to call a member function from C which does not work because the pointer to the class instance is missing. One way to make this work would be to pass a pointer to the object as application data with the context or the session and then use [bind](https://en.cppreference.com/w/cpp/utility/functional/bind) to call you getHandler() method. But this would steal some of the robustness gained by using C++.

I strongly advise against calling object methods from C callbacks unless you know exactly what you are doing and the issues this technique has.

**Comment by iamniki01** [comment]
Thanks @obgm @mrdeep1,

As @mrdeep1 said it will work with separate header file. But it make my design so complicated and its really impossible to access payload name and other constructor variables. @mrdeep1 even though I used separate header file I cant see debug logs in test suite
```
//file1.hpp, this is to test only not original code

inline void get_Handler(coap_resource_t *resource,
                                   coap_session_t *session,
                                   const coap_pdu_t *request,
                                   const coap_string_t *query,
                                   coap_pdu_t *response)
    {
        std::cout << "POST request from Client \n";
        coap_add_data(response, 5, (const uint8_t *)"Hello!");
        coap_show_pdu((coap_log_t)LOG_WARNING, response);
    }


```
test suite output
```
//test suite output, here where is DEBG ACK?

Nov 05 09:38:53.592 DEBG created UDP  endpoint 127.0.0.1:5683
constructed
initializing resource test
SERVER STARTED ...
Nov 05 09:38:53.593 DEBG ***127.0.0.1:46421 <-> 127.0.0.1:5683 UDP : new outgoing session
constructed
called GET
Nov 05 09:38:53.593 DEBG ** 127.0.0.1:46421 <-> 127.0.0.1:5683 UDP : lg_crcv 0x55bfbbdc2380 initialized
Nov 05 09:38:53.593 DEBG *  127.0.0.1:46421 <-> 127.0.0.1:5683 UDP : sent 12 bytes
v:1 t:CON c:GET i:0a43 {} [ Observe:0, Uri-Path:test, Content-Format:application/json ]
Nov 05 09:38:53.593 DEBG ** 127.0.0.1:46421 <-> 127.0.0.1:5683 UDP : mid=0xa43: added to retransmit queue (2375ms)
Nov 05 09:38:55.968 DEBG ** 127.0.0.1:46421 <-> 127.0.0.1:5683 UDP : mid=0xa43: retransmission #1
Nov 05 09:38:55.969 DEBG *  127.0.0.1:46421 <-> 127.0.0.1:5683 UDP : sent 12 bytes
v:1 t:CON c:GET i:0a43 {} [ Observe:0, Uri-Path:test, Content-Format:application/json ]
1
SERVER SHUTDOWN ...
called destructor of Client
Nov 05 09:38:55.972 DEBG ** 127.0.0.1:46421 <-> 127.0.0.1:5683 UDP : lg_crcv 0x55bfbbdc2380 released
Nov 05 09:38:55.972 DEBG ***127.0.0.1:46421 <-> 127.0.0.1:5683 UDP : session closed
called destructor
```


As @obgm mentioned I already used std::bind still it throw an error(if I am doing right). So below I attached error and initializing a resource. I will attach and error of my code.
```
//class public method  with initializing resource
bool CoapServerAPI::addResource(std::string &name, bool pullable)
    {
        using namespace std::placeholders;
        coap_pdu_t *responses;
        unsigned char buf[3];
        int status= false;
        coap_str_const_t *res_uri = coap_make_str_const(name.c_str());
        std::cout << "initializing resource " << res_uri->s << std::endl;
        coap_resource_t *resource = coap_resource_init(res_uri, COAP_RESOURCE_FLAGS_NOTIFY_CON);
        if (resource == nullptr)
        {
            std::cerr << "Can't init resource" << std::endl;
            //throw std::invalid_argument("Can't init resource");
            return SUCCESS;
        }
        //coap_set_log_level(LOG_DEBUG);
   
        coap_register_handler(resource, COAP_REQUEST_GET, std::bind(&CoapServerAPI::getHandler, this, _1,_2,_3,_4,_5));
       // coap_register_handler(resource, COAP_REQUEST_PUT, putHandler);
        coap_resource_set_get_observable(resource, 1);

        coap_add_resource(this->ctx, resource);
        /* while (true) {
        coap_run_once(ctx, 0); 
        coap_resource_notify_observers(resource, NULL); 
        } */
        status = true; 
        return status;
    }
```

here the error for invoke get

```
coap_server.cpp:101:68: error: cannot convert 'std::_Bind_helper<false, void (*)(coap_resource_t*, coap_session_t*, const coap_pdu_t*, const coap_string_t*, coap_pdu_t*), CoapServerAPI*, const std::_Placeholder<1>&, const std::_Placeholder<2>&, const std::_Placeholder<3>&, const std::_Placeholder<4>&, const std::_Placeholder<5>&>::type' to 'coap_method_handler_t' {aka 'void (*)(coap_resource_t*, coap_session_t*, const coap_pdu_t*, const coap_string_t*, coap_pdu_t*)'}
  101 |         coap_register_handler(resource, COAP_REQUEST_GET, std::bind(&CoapServerAPI::getHandler, this, _1,_2,_3,_4,_5));
      |                                                           ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                    |
      |                                                                    std::_Bind_helper<false, void (*)(coap_resource_t*, coap_session_t*, const coap_pdu_t*, const coap_string_t*, coap_pdu_t*), CoapServerAPI*, const std::_Placeholder<1>&, const std::_Placeholder<2>&, const std::_Placeholder<3>&, const std::_Placeholder<4>&, const std::_Placeholder<5>&>::type
```
Please help me with this, If any wrong in my approach please correct it. Thanks again :)

**Comment by mrdeep1** [comment]
getHandler() is only ever invoked server-side, i.e. on receipt of the request, so I am not surprised that anything from this handler is written into the client logs as it never would be called.  Your server is not sending back any response.

As your server code is not functioning, I re-iterate

> From a testing perspective, I would initially use the libcoap example coap-client against your provided coap-server
> to test out / debug what is happening by using verbose logging (-v9 option) and then once you aer happy with the
> requests/responses doing what is expected, then customize your coap-cleint as appropriate.

Alternatively, use the standard examples coap-server and and test your client code out against that.

Your getHandler() needs to include a statement of the form (to indicate the response code)
````
     coap_pdu_set_code(response, COAP_RESPONSE_CODE_CONTENT);
````

**Comment by iamniki01** [comment]
Hi @mrdeep1 and @obgm ,

Thanks for your response and explanation, Both my server and client is working fine. As @mrdeep1 said, server was not connecting only in test because I totally forgot to use coap_io_process, It was used in main but not in test, now I am able to see piggy back response in test and app.  Is there any approach other than coap_response_handler_t to get response code using coap_pdu_get_code (this code may use to test suite only). Thanks again.

**Comment by mrdeep1** [comment]
> Is there any approach other than coap_response_handler_t to get response code using coap_pdu_get_code
> (this code may use to test suite only). 

Nothing comes to mind.  A call to the response handler confirms that a response has been recieved for a request (assuming Tokens match) and the response code can only easily be extracted at that point.  Yuu may also need to register a nack handler using coap_register_nack_handler() in case there are any transmission issues.

**Comment by iamniki01** [comment]
Hi @mrdeep1 , Thanks again for your response. In this moment, I have no issue with transmission. Thanks again for your time and explanation:) I am closing this issue now.

**Comment by iamniki01** [comment]
@mrdeep1 @obgm,

Why my server is not handling two request (get and put) at a same time with same resource name. I need a generic asynchronous server where it should accept all requests from a single or multiple clients? How I can handle this? I defined coap_register_asynch in both get and put handler. Server will not accept other method (either put or get) untill response is send. How can I  solve this issue?

**Comment by mrdeep1** [comment]
I'm struggling to understand what you are doing here.  It could be your client is waiting for a response before sending the next (but different) request, or your coap-method_t callback handle function is not returning, or you are not calling coap_io_process() outside of the callback handler to recieve the next queued incoming request.

I assume that you have called coap_register_handler() separately for GET and PUT on the same resource [coap_handler(3)](https://libcoap.net/doc/reference/develop/man_coap_handler.html) and that you are following the recommendations in [coap_async(3)](https://libcoap.net/doc/reference/develop/man_coap_async.html).  Look at the examples provided in those man pages.

I would increase the verbosity oflogging  [coap_set_log_level(3)](https://libcoap.net/doc/reference/develop/man_coap_logging.html) and look to see what the log files are telling you.

**Comment by iamniki01** [comment]
Hi @mrdeep1 ,

I called get and put from two diff. clients with same resource name. Yes, in server side it accepts only one request and also set log level to see logs. Below are my logs where I called both get and put from two different client instances.

```
initializing resource PAYLOAD
constructed
SERVER STARTED ...
constructed
Nov 10 12:16:34.598 DEBG ***127.0.0.1:50838 <-> 127.0.0.1:5683 UDP : new outgoing session
constructed
called GET
called PUT
Nov 10 12:16:34.598 DEBG ** 127.0.0.1:39862 <-> 127.0.0.1:5683 UDP : lg_crcv 0x55791d40a090 initialized
Nov 10 12:16:34.599 DEBG ** 127.0.0.1:50838 <-> 127.0.0.1:5683 UDP : lg_crcv 0x7f1e640011c0 initialized
Nov 10 12:16:34.599 DEBG *  127.0.0.1:39862 <-> 127.0.0.1:5683 UDP : sent 15 bytes
v:1 t:CON c:GET i:93b5 {} [ Observe:0, Uri-Path:PAYLOAD, Content-Format:application/json ]
Nov 10 12:16:34.599 DEBG *  127.0.0.1:50838 <-> 127.0.0.1:5683 UDP : sent 31 bytes
Nov 10 12:16:34.599 DEBG ***127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : new incoming session
Nov 10 12:16:34.599 DEBG *  127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : received 15 bytes
v:1 t:CON c:GET i:93b5 {} [ Observe:0, Uri-Path:PAYLOAD, Content-Format:application/json ]
Nov 10 12:16:34.599 DEBG v:1 t:CON c:PUT i:8399 {} [ Observe:0, Uri-Path:PAYLOAD, Content-Format:application/json ] :: 'ADDITIONAL DATA'
Nov 10 12:16:34.599 DEBG ** 127.0.0.1:50838 <-> 127.0.0.1:5683 UDP : mid=0x8399: added to retransmit queue (2125ms)
call custom handler for resource 'PAYLOAD'
Nov 10 12:16:34.599 DEBG create new subscription 0x7f1e5c000da0 key 0x8343e1d0
Nov 10 12:16:34.599 GET Request from Client
Nov 10 12:16:34.599 DEBG    127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : Request for delayed for 0.000 secs
Nov 10 12:16:34.599 INFO Option number 6 is not defined as repeatable
DEBG ** 127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : mid=0x93b5: added to retransmit queue (2719ms)
0x7f1e5c002000 new consumer established.
0x7f1e5c002000 Consumer listening on topic: PAYLOAD_tm
Nov 10 12:16:36.725 DEBG ** 127.0.0.1:50838 <-> 127.0.0.1:5683 UDP : mid=0x8399: retransmission #1
Nov 10 12:16:36.725 DEBG *  127.0.0.1:50838 <-> 127.0.0.1:5683 UDP : sent 31 bytes
v:1 t:CON c:PUT i:8399 {} [ Observe:0, Uri-Path:PAYLOAD, Content-Format:application/json ] :: 'ADDITIONAL DATA'
Nov 10 12:16:37.318 DEBG ** 127.0.0.1:39862 <-> 127.0.0.1:5683 UDP : mid=0x93b5: retransmission #1
Nov 10 12:16:37.318 DEBG *  127.0.0.1:39862 <-> 127.0.0.1:5683 UDP : sent 15 bytes
v:1 t:CON c:GET i:93b5 {} [ Observe:0, Uri-Path:PAYLOAD, Content-Format:application/json ]
SERVER SHUTTINGDOWN ...
KAFKACLIENT 0x7f1e5c002000 return consume timeout: 10
KAFKACLIENT 0x7f1e5c002000 return consume timeout: 10
Timeout to Consume Data
Nov 10 12:16:40.831 DEBG removed subscription 0x7f1e5c000da0 with token '' key 0x8343e1d0
Nov 10 12:16:40.831 DEBG *  127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : sent 46 bytes
v:1 t:ACK c:5.03 i:93b5 {} [ Observe:0, Content-Format:application/json ] :: 'ERROR-503: Unavailable of payload data'
Nov 10 12:16:40.831 INFO Retransmit async response
Nov 10 12:16:40.831 DEBG *  127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : sent 4 bytes
v:1 t:ACK c:0.00 i:81f7 {} [ ]
called destructor of Client
Nov 10 12:16:40.832 DEBG ** 127.0.0.1:50838 <-> 127.0.0.1:5683 UDP : lg_crcv 0x7f1e640011c0 released
Nov 10 12:16:40.832 DEBG ***127.0.0.1:50838 <-> 127.0.0.1:5683 UDP : session closed
called destructor of Client
Nov 10 12:16:40.832 DEBG ** 127.0.0.1:39862 <-> 127.0.0.1:5683 UDP : lg_crcv 0x55791d40a090 released
Nov 10 12:16:40.832 DEBG ***127.0.0.1:39862 <-> 127.0.0.1:5683 UDP : session closed
called destructor
```

Here, you can see put has been called from client but server is busy with get handler.
Below is code for async, 

```
above I am just initalizing and giving resource name.
if (coap_async_is_supported())
        {
            coap_register_handler(resource, COAP_REQUEST_GET, getHandler);
            coap_register_handler(resource, COAP_REQUEST_PUT, putHandler);
            coap_resource_set_get_observable(resource, 1);
            coap_context_set_keepalive(this->ctx, 10);

            coap_add_resource(this->ctx, resource);
             }
```

**Comment by iamniki01** [comment]
Actually yes, even though two instances were created and called the next request is in queue until it sends response to the client. After the responses were sent to client, then it will take queued request. coap server wants to take two request at a time (similar like thread running two process at a time).Requests should not stay in queue, all requests should start together without being in a queue. How to deal with it ?

**Comment by mrdeep1** [comment]
libcoap does not currently support multi-threading (and should not be coded therefore using multiple threads).  So, requests will be read sequentially off the network stack (by coap_process_io()).

It is not easy to disentangle your log file for server specific activity which is the main area you are trying to troubleshoot.  It would be helpful to have that being seperate.  If I have worked it out correctly, the server logs looks something like
````
S Nov 10 12:16:34.599 DEBG ***127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : new incoming session
S Nov 10 12:16:34.599 DEBG *  127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : received 15 bytes
S v:1 t:CON c:GET i:93b5 {} [ Observe:0, Uri-Path:PAYLOAD, Content-Format:application/json ]
S call custom handler for resource 'PAYLOAD'
S Nov 10 12:16:34.599 DEBG create new subscription 0x7f1e5c000da0 key 0x8343e1d0
S Nov 10 12:16:34.599 GET Request from Client
S Nov 10 12:16:34.599 DEBG    127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : Request for delayed for 0.000 secs
S Nov 10 12:16:34.599 INFO Option number 6 is not defined as repeatable
S DEBG ** 127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : mid=0x93b5: added to retransmit queue (2719ms)
S 0x7f1e5c002000 new consumer established.
S 0x7f1e5c002000 Consumer listening on topic: PAYLOAD_tm
S SERVER SHUTTINGDOWN ...
S Nov 10 12:16:40.831 DEBG removed subscription 0x7f1e5c000da0 with token '' key 0x8343e1d0
S Nov 10 12:16:40.831 DEBG *  127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : sent 46 bytes
S v:1 t:ACK c:5.03 i:93b5 {} [ Observe:0, Content-Format:application/json ] :: 'ERROR-503: Unavailable of payload data'
S Nov 10 12:16:40.831 INFO Retransmit async response
S Nov 10 12:16:40.831 DEBG *  127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : sent 4 bytes
S v:1 t:ACK c:0.00 i:81f7 {} [ ]
S called destructor
````
First obvious thing that needs fixing is
````
S Nov 10 12:16:34.599 INFO Option number 6 is not defined as repeatable
````
Looks like you are adding in the Observe option causing a failure.  Are you taking some sort of error exit here?
The next thing that troubles me (multithreading?)
````
S DEBG ** 127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : mid=0x93b5: added to retransmit queue (2719ms)
````
as there is no leading date stamp.  There may be some missing logs here. However, this implies to me that you are trying to send something (a new PDU) from within the GET handler using coap_send().  When the GET handler function returns, it will send off the response PDU - you do not need to create a new response PDU.  When the async logic fires / times out, it will generate the appropriate response PDU for you and will call the GET handler to fill in the the current information that is available to respond with.

Why are you delaying for 0 seconds for the async response as in
````
S Nov 10 12:16:34.599 DEBG    127.0.0.1:5683 <-> 127.0.0.1:39862 (if1) UDP : Request for delayed for 0.000 secs
````

**Comment by iamniki01** [comment]
Hi @mrdeep1 , Thanks for your description. Yes, I was manually adding and throwing error. Now, I removed it. Since Libcoap is capable of doing it and also yes, I was adding response for every error thorw. Even now I removed it. I am just setting code. However, Its good to know that it wont support multiple request at a time. I was trying to test multiple request at a time. But, now I dropped this test. Thanks for your explaination. But I am still wondering how COAP_OBSERVE will work and how it will notify if resource is changed. If you have time please explain me and without request how it will notify to clinet? After a client request, client get response back from server and it is done. after that how can it able send observe and notify?

**Comment by mrdeep1** [comment]
The mechanism for Observe is detailed in [RFC 7641](https://datatracker.ietf.org/doc/html/rfc7641).

libcoap handle this by detecting the Observe option in a request (register interest or cancel) and sets up (or cancels) what is known in libcoap as a subscription for the particular resource.  Then whenever the server detects a change in data (or decides data needs to be sent anyway) `coap_resource_notify_observers()` needs to be called.  Then the next time` coap_io_process()` is called, the unsolicited Observe response is sent.  See [coap_observe(3)](https://libcoap.net/doc/reference/develop/man_coap_observe.html).

**Comment by iamniki01** [comment]
Hi @mrdeep1 , Thanks for your reply ``` coap_resource_notify_observers()``` I added this in my PutHandler. But to see the changes client should be up and running right. But as example client will exit after it get response back from server. How can I overcome this issue ?

**Comment by mrdeep1** [comment]
The standard examples coap-client has the `-s duration` option to handle this - see [coap-client(5)](https://libcoap.net/doc/reference/develop/man_coap-client.html)
