### ISSUE TITLE
Option -G causes client core dump and CoAP NSTART parameter question

### ISSUE THREAD

**Issue by jqiaobln** [obgm/libcoap#767]
I'm running the latest libcoap code. When I use the option '-G 2' with coap-client to send 2 identical requests, it caused core dump due to "free(): double free detected in tcache 2". 

After tracing the code, I think it is caused by the calling of **release_func** near the end of **coap_add_data_large_internal**, which is a function pointer to **free_xmit_data**. My understanding for this piece of code is it is deleting the CoAP session after the PDU is copied to payload.  

My questions is: does it make sense to delete session here? Setting up and tearing down a new session (DTLS session in my case) for each request is certainly too much overhead and inefficient. When NSTART parameter is set to more than 1, won't it be better to send multiple requests out in 1 session and let CoAP protocol handle the concurrent outstanding interaction?

**Comment by mrdeep1** [comment]
It would be good if you can provide the complete line of how you are trying to invoke coap-client (with all the options etc etc.) - no need for certs as I can provide my own to do the testing.  If put/get large data, then i just need to know the data size.

`release_func()` should not be doing anything with the session, only decrementing any data reference count and potentially freeing off the data.

In general, it is not recommended to be playing with NSTART as other Congestion Control parameters may also need changing.

Keeping the (D)TLS session going over multiple requests/responses is a good move.

**Comment by boaks** [comment]
> When NSTART parameter is set to more than 1, won't it be better to send multiple requests out in 1 session and let CoAP protocol handle the concurrent outstanding interaction?

My feeling is, this is misinterpreting the specification. NSTART 1 is mainly used to prevent congestion. It's not related to the scope of a DTLS session/association. Depending on the library (O, I'm not too common with libcoap, though much more with java / Californium) it works easily to send several request, waiting for the responses before sending the next, within one DTLS session.

**Comment by jqiaobln** [comment]
> It would be good if you can provide the complete line of how you are trying to invoke coap-client (with all the options etc etc.) - no need for certs as I can provide my own to do the testing. If put/get large data, then i just need to know the data size.
> 
> `release_func()` should not be doing anything with the session, only decrementing any data reference count and potentially freeing off the data.
> 
> In general, it is not recommended to be playing with NSTART as other Congestion Control parameters may also need changing.
> 
> Keeping the (D)TLS session going over multiple requests/responses is a good move.

Please find below command line:

coap-client -u ID -k PSK -v 9 -m post coaps://testserver:5784/location -f location.json -t application/json

The json file has 123 bytes.

As of sending multiple requesting in 1 DTLS session, in coap-client.c I found below code:

/* Send out the request 'n' times (default is 1) */
for (i = 0; i < repeat_count; i++)
{
if (!(pdu = coap_new_request(ctx, session, method, &optlist, payload.s, payload.length)))
{
goto finish;
}
coap_log(LOG_DEBUG, "sending CoAP request:\n");
if (coap_get_log_level() < LOG_DEBUG)
coap_show_pdu(LOG_INFO, pdu);
coap_send(session, pdu);
}

From the debug output, when repeat_count > 1, a new DTLS session is created for every new request. How we can send multiple requests in 1 DTLS session? It will be great if you can show some examples or give tips. Thanks.

**Comment by jqiaobln** [comment]
> > When NSTART parameter is set to more than 1, won't it be better to send multiple requests out in 1 session and let CoAP protocol handle the concurrent outstanding interaction?
> 
> My feeling is, this is misinterpreting the specification. NSTART 1 is mainly used to prevent congestion. It's not related to the scope of a DTLS session/association. Depending on the library (O, I'm not too common with libcoap, though much more with java / Californium) it works easily to send several requests, waiting for the responses before sending the next, within one DTLS session.

I totally agree with you: NSTART is at CoAP level, not in the scope of DTLS session. DTLS is just there to provide a secure channel between 2 sockets, on top of it CoAP deals with all the message traffic handling logic.

**Comment by mrdeep1** [comment]
Thanks for providing the detail behind the issue which aided the debugging.

Only one DTLS session is set up and used.  coap_new_request() only allocates a new PDU for sending it over whatever communication channel is being used (DTLS in your case).

The bug is in coap-client - it is not allocating a new set of data to send using coap_new_request() which is then freed off when that particular request has been transmited using the following coap_send().  This is fixed by creating a new set of data for each coap_new_request() call.  As it is possible for the data to be larger than fits in a single packet, this transmitted data has then to be kept over multiple (internal to libcoap) packet transmissions and released at the sending of the last packet at which point free_xmit_data() is invoked as defined by coap_add_data_large_request().

A fix has been raised in PR #768 with the fix being below.
````
diff --git a/examples/coap-client.c b/examples/coap-client.c
index 890909b..050d876 100644
--- a/examples/coap-client.c
+++ b/examples/coap-client.c
@@ -1760,7 +1760,18 @@ main(int argc, char **argv) {
 
   /* Send out the request 'n' times (default is 1) */
   for (i = 0; i < repeat_count; i++) {
-    if (! (pdu = coap_new_request(ctx, session, method, &optlist, payload.s, pa
+    uint8_t *data = NULL;
+    size_t data_len = 0;
+    if (payload.length) {
+      /* Create some new data to use for this iteration */
+      data = coap_malloc(payload.length);
+      if (data == NULL)
+        goto finish;
+      memcpy(data, payload.s, payload.length);
+      data_len = payload.length;
+    }
+    if (! (pdu = coap_new_request(ctx, session, method, &optlist, data,
+                                  data_len))) {
       goto finish;
     }
 
@@ -1833,6 +1844,7 @@ main(int argc, char **argv) {
   coap_free(ca_mem);
   coap_free(cert_mem);
   coap_free(key_mem);
+  coap_free(payload.s);
   for (i = 0; i < valid_ihs.count; i++) {
     free(valid_ihs.ih_list[i].hint_match);
     coap_delete_bin_const(valid_ihs.ih_list[i].new_identity);
````
PLease confirm that fixes your issue.

**Comment by jqiaobln** [comment]
> Thanks for providing the detail behind the issue which aided the debugging.
> 
> Only one DTLS session is set up and used. coap_new_request() only allocates a new PDU for sending it over whatever communication channel is being used (DTLS in your case).
> 
> The bug is in coap-client - it is not allocating a new set of data to send using coap_new_request() which is then freed off when that particular request has been transmited using the following coap_send(). This is fixed by creating a new set of data for each coap_new_request() call. As it is possible for the data to be larger than fits in a single packet, this transmitted data has then to be kept over multiple (internal to libcoap) packet transmissions and released at the sending of the last packet at which point free_xmit_data() is invoked as defined by coap_add_data_large_request().
> 
> A fix has been raised in PR #768 with the fix being below.
> 
> ```
> diff --git a/examples/coap-client.c b/examples/coap-client.c
> index 890909b..050d876 100644
> --- a/examples/coap-client.c
> +++ b/examples/coap-client.c
> @@ -1760,7 +1760,18 @@ main(int argc, char **argv) {
>  
>    /* Send out the request 'n' times (default is 1) */
>    for (i = 0; i < repeat_count; i++) {
> -    if (! (pdu = coap_new_request(ctx, session, method, &optlist, payload.s, pa
> +    uint8_t *data = NULL;
> +    size_t data_len = 0;
> +    if (payload.length) {
> +      /* Create some new data to use for this iteration */
> +      data = coap_malloc(payload.length);
> +      if (data == NULL)
> +        goto finish;
> +      memcpy(data, payload.s, payload.length);
> +      data_len = payload.length;
> +    }
> +    if (! (pdu = coap_new_request(ctx, session, method, &optlist, data,
> +                                  data_len))) {
>        goto finish;
>      }
>  
> @@ -1833,6 +1844,7 @@ main(int argc, char **argv) {
>    coap_free(ca_mem);
>    coap_free(cert_mem);
>    coap_free(key_mem);
> +  coap_free(payload.s);
>    for (i = 0; i < valid_ihs.count; i++) {
>      free(valid_ihs.ih_list[i].hint_match);
>      coap_delete_bin_const(valid_ihs.ih_list[i].new_identity);
> ```
> 
> PLease confirm that fixes your issue.

I can confirm the issue is fixed. Also thanks for the explanation on how requests are transmitted. 

If I want to test NSTART parameter, e.g. NSTART = 2, is the easiest way to block server responding to the client's requests, so a 2nd request will be sent without the 1st request being ACKed, however no 3rd, 4th requests should be sent as that will exceed NSTART parameter?

**Comment by jqiaobln** [comment]
> It would be good if you can provide the complete line of how you are trying to invoke coap-client (with all the options etc etc.) - no need for certs as I can provide my own to do the testing. If put/get large data, then i just need to know the data size.
> 
> `release_func()` should not be doing anything with the session, only decrementing any data reference count and potentially freeing off the data.
> 
> In general, it is not recommended to be playing with NSTART as other Congestion Control parameters may also need changing.
> 
> Keeping the (D)TLS session going over multiple requests/responses is a good move.

When you mentioned other congestion control parameters, did you mean below:

name              | default value |
                   +-------------------+---------------+
                   | ACK_TIMEOUT       | 2 seconds     |
                   | ACK_RANDOM_FACTOR | 1.5           |
                   | MAX_RETRANSMIT    | 4             |
                   | NSTART            | 1             |
                   | DEFAULT_LEISURE   | 5 seconds     |
                   | PROBING_RATE      | 1 byte/second 

Do you have recommendations on how they should be adjusted?

**Comment by mrdeep1** [comment]
Thanks for confirming that all now works.

If the client application cannt send a request because of the NSTART limit being hit due to the current CON sessions in flight, then liboap will queue the request and only transmit it once the outstanding count has dropped below NSTART (assuming any previously queud packet has also been sent).

The Congestion Control parameter values (which you have located) have been defined as best practice to prevent the overloading of network bandwidth, network devices etc.  They should only be modified if you know what you are doing.  In a production environment, they really should not be changed at all.  You will need to have a good understanding of Congestion COntrol as well as a good knowledge of RFC7252 (and other CoAP RFCs) to give a good reason as to why you must change one of thevalues.

**Comment by mrdeep1** [comment]
@jqiaobln Now that #773 (a successor to #768) has been merged into the develop branch, please confirm that all is working for you and then close off this Issue.

**Comment by mrdeep1** [comment]
@jqiaobln Please free to re-open this issue if there still is a problem.
