### ISSUE TITLE
Add support for multicast GET requests in coap-client

### ISSUE THREAD

**Issue by alexislacasse** [obgm/libcoap#777]
When making a multicast GET request using the coap-client, the client exit after receiving the first response and do not wait for response from other servers.

The behaviour that I expected from coap-client was :

- Check if address is multicast
- If so, call `coap_io_process` until timeout expire

The code required would look like :

```
while(ms > 0)
{
  ret = coap_io_process(context, ms);
  if(ret == -1)
  {
    break;
  }
  ms -= ret;
}
```

**Comment by mrdeep1** [comment]
@alexislacasse Please see PR #778 which has be raised to handle your requirement.

**Comment by alexislacasse** [comment]
@mrdeep1 Thanks for the quick response! I'll try your fix later today and will let you know if it works. May I know which file you changed to fix this issue? I've looked at the PR and it seems like the changes are mostly related to TLS.

**Comment by mrdeep1** [comment]
No - it was my bad putting in the wrong PR - sorry - just updated my comment.

**Comment by mrdeep1** [comment]
@alexislacasse Is this now all working as expected?  If so, please close off this Issue.

**Comment by mrdeep1** [comment]
@alexislacasse Now that the fix has been merged into the develop branch, can you please confirm that your issue has been resolved and close off this issue.

**Comment by mrdeep1** [comment]
@alexislacasse Please free to re-open this  issue if there still is a problem.
