### ISSUE TITLE
server with COAP_BLOCK_USE_LIBCOAP and COAP_BLOCK_SINGLE_BODY behaves incorrectly on multiple block-wise transfers with same client session

### ISSUE THREAD

**Issue by jmgraeffe** [obgm/libcoap#782]
## Environment

- libcoap version: v4.3.0-57-gdf9071c
- Build System: CMake
- Operating System: Linux & Windows
- Operating System Version: Ubuntu 20.04.3 LTS
- Hosted Environment: None

## Problem Description

When sending a request that initiates block-wise transfer to a server that a) uses flags `COAP_BLOCK_USE_LIBCOAP` and `COAP_BLOCK_SINGLE_BODY` and b) processed a request with block-wise transfer from the same endpoint with the same client port (same client session) before, the server does not continue to request blocks by sending a continue message. Instead it passes control to the request handler, providing a request PDU with the data of the first request, thus resulting in application-dependent acknowledgement.

### Expected Behavior

- client sends request for transferring message A with Block1 option indicating first block (more bit 1)
- server answers request with ACK containing status `2.31 Continue` and Block1 option
- ...
- client sends request or transferring message A with Block1 option indicating last block (more bit 0)
- server answers request with ACK containing user-defined status (in example `2.04 Changed`)
    - request handler gets data from message A
- client sends request for transferring message B with Block1 option indicating first block (more bit 1)
- server answers request with ACK containing status `2.31 Continue` and Block1 option
- ...
- client sends request or transferring message B with Block1 option indicating last block (more bit 0)
- server answers request with ACK containing user-defined status (in example `2.04 Changed`)
    - request handler gets data from message B

And so on.

### Actual Behavior

- client sends request for transferring message A with Block1 option indicating first block (more bit 1)
- server answers request with ACK containing status `2.31 Continue` and Block1 option
- ...
- client sends request or transferring message A with Block1 option indicating last block (more bit 0)
- server answers request with ACK containing user-defined status (in example `2.04 Changed`)

So far so good.

- client sends request for transferring message B with Block1 option indicating first block (more bit 1)
- server answers request with ACK containing user-defined status (in example `2.04 Changed`)
    - request handler gets data from message A

And so on.

### Steps to reproduce

1. compile code to reproduce issue
2. start server (implements simple endpoint with `COAP_BLOCK_USE_LIBCOAP` and `COAP_BLOCK_SINGLE_BODY` flags on context)
3. run client (makes requests doing block-wise transfer, one after another with same client session)

### Code to reproduce this issue

https://github.com/jmgraeffe/libcoap-playground/tree/blockwise_libcoap_single_body

## Debug Logs

[server_log.txt](https://github.com/obgm/libcoap/files/7619668/server_log.txt)
[client_log.txt](https://github.com/obgm/libcoap/files/7619661/client_log.txt)

## Other items if possible

- [x] Does what you are trying to do work under any configuration.  Detail what
works.

There is no problem when a new client session is initiated for every new message to transfer. Also, the server seems to be the problem because the client appears to send the correct request (more bit 1, correct syntax etc.).

- [ ] Network configuration that is not straightforward. Detail any networking
that may have NAT or firewalls that might affect what is going on.

**Comment by mrdeep1** [comment]
Thanks for providing all the detailed information and a method to reproduce the issue.

There are 2 things here.

First, each PUT should be using a unique token to match up response to request.  A starting suggestion would be
````
$ git diff client.c
diff --git a/client.c b/client.c
index 97285d1..4c58006 100644
--- a/client.c
+++ b/client.c
@@ -59,6 +59,9 @@ int main(int argc, char const *argv[]) {
        coap_session_set_app_data(session, &ack_received);

        for (int i = 0; i < 10; ++i) {
+               uint8_t token[8];
+               size_t tokenlen;
+
                pdu = coap_pdu_init(COAP_MESSAGE_CON, COAP_REQUEST_CODE_PUT, coap_new_message_id(session), coap_session_max_pdu_size(session));
                if (!pdu) {
                        printf("Could not create CoAP PDU!\n");
@@ -66,6 +69,8 @@ int main(int argc, char const *argv[]) {
                        rc = 1;
                        goto cleanup;
                }
+               coap_session_new_token(session, &tokenlen, token);
+               coap_add_token(pdu, tokenlen, token);

                // dummy data
                uint8_t data[4096];
````
Second, you need to be running with code from PR #740 which is waiting to be merged into develop branch.

**Comment by jmgraeffe** [comment]
Thanks for the suggestions.

> First, each PUT should be using a unique token to match up response to request. A starting suggestion would be

The example now contains adding a token explicitly. However, this does not fix the problem. The libcoap client did actually provide a unique token without the need to specify one explicitly, which is sufficient for demonstration purposes.

Also, libcoap will change the token for the continue messages anyway by itself. And iirc the RFC does not say explicitly to have the same token throughout one block-wise transfer "process", but correct me if I'm wrong.

> Second, you need to be running with code from PR #740 which is waiting to be merged into develop branch.

Sorry, should have mentioned that I already tried the branch of your PR to verify that this is not a duplicate issue. The problem stays the same.

**Comment by mrdeep1** [comment]
When I tested out your code, I needed both the token fix and #740 to get it to worked as I was expecting.

**Comment by jmgraeffe** [comment]
If I check out the `block_fix` branch of your libcoap fork, with the token added explicitly, the behaviour is exactly the same as before.

What do you expect? Maybe I'm expecting the wrong thing.

**Comment by mrdeep1** [comment]
I now can see what you are seeing with your code - apologies for creating confusion.

However, using the standard libcoap examples/coap-server.c with a 1 line addition to support PUT to "", all is working when using your client (I think).
````
diff --git a/examples/coap-server.c b/examples/coap-server.c
index 959d149..56abceb 100644
--- a/examples/coap-server.c
+++ b/examples/coap-server.c
@@ -1754,6 +1755,7 @@ init_resources(coap_context_t *ctx) {
 
   r = coap_resource_init(NULL, 0);
   coap_register_handler(r, COAP_REQUEST_GET, hnd_get_index);
+  coap_register_handler(r, COAP_REQUEST_PUT, hnd_put_example_data);
 
   coap_add_attr(r, coap_make_str_const("ct"), coap_make_str_const("0"), 0);
   coap_add_attr(r, coap_make_str_const("title"), coap_make_str_const("\"General
````
I'm trying to work out why your server is not working as expected.

**Comment by jmgraeffe** [comment]
`coap-server.c` uses `COAP_BLOCK_USE_LIBCOAP` by default but not `COAP_BLOCK_SINGLE_BODY`. So without having had a deep dive into libcoap's code, my guess would be that the problem is connected to that.

**Comment by mrdeep1** [comment]
Using the `coap-server -L3` option for coap-server enables both `COAP_BLOCK_USE_LIBCOAP` and `COAP_BLOCK_SINGLE_BODY`.

**Comment by mrdeep1** [comment]
Putting in some other debugging changes characteristics - look like a timing / packet arrival ordeing issue.

**Comment by mrdeep1** [comment]
I think that we are running into this and the code is getting confused
https://datatracker.ietf.org/doc/html/rfc7959#section-2.5
````
   The Block1 Option provides no way for a single endpoint to perform
   multiple concurrently proceeding block-wise request payload transfer
   (e.g., PUT or POST) operations to the same resource.  Starting a new
   block-wise sequence of requests to the same resource (before an old
   sequence from the same endpoint was finished) simply overwrites the
   context the server may still be keeping.  (This is probably exactly
   what one wants in this case -- the client may simply have restarted
   and lost its knowledge of the previous sequence.)
````
I will look later as to whether is is possible (based on tokens) to properly differentiate between the concurrent transmissions.

**Comment by jmgraeffe** [comment]
But in my example code there are no concurrent transmissions. It looks like some context is not freed or overwritten properly when a new block-wise sequence begins, even if the old one finished successfully.

**Comment by jmgraeffe** [comment]
Seems to solve the problem :)

**Comment by obgm** [comment]
PR #740 now has been merged. Does that entirely resolve this issue?

**Comment by jmgraeffe** [comment]
Yes it does. Thank you!
