### ISSUE TITLE
How to check if resource is being observed?

### ISSUE THREAD

**Issue by panekk** [obgm/libcoap#789]
Hello,

Is there a possibility to check if the resource is observed at the time? I thought about using `coap_resource_notify_observers()` (I can accept potential side effect of sending the notification) because I thought it will return 0 if there are no subscribers, but it works partially. Before setting up an Observe it returns 0, but after setting it up and cancelling, it returns 1 (the subscribers field is not NULL).

**Comment by mrdeep1** [comment]
If there is one more observe subscription created by clients, then the resource subscribers linked observer list will have a value, so coap_resource_notify_observers() will return 1.  If the last remaining observe subscription is removed by a client, then the resource subscriber linked observer list will be NULL, so coap_resource_notify_observers() will return 0.

My surmise is that you are not correctly cancelling the observe subscription.

**Comment by panekk** [comment]
Thank you for the response. I checked it one more time and I found the problem, I called `coap_resource_notify_observers()` too early and the server didn't process the Reset message yet.
