### ISSUE TITLE
coap-client gets not installed when using cmake

### ISSUE THREAD

**Issue by franzhollerer** [obgm/libcoap#797]
I use cmake to build and install libcoap as this provides the necessary cmake/libcoap/libcoap*.cmake files for the  cmake find_package() command.

I perform the following steps to build and install the library:

```
$ cmake -DCMAKE_INSTALL_PREFIX=~/opt/x86_64 -DBUILD_SHARED_LIBS=ON -DENABLE_DTLS=OFF -DENABLE_EXAMPLES=ON -DENABLE_TCP=OFF -DENABLE_TESTS=OFF -S . -B build -G Ninja
$ cmake --build build -v -j --target all
$ cmake --build build -v -j --target install
```
I see that ./build/coap-client exists, but it is not installed into the target directory, which is ~/opt/x86_64/bin in my case.

**Comment by mrdeep1** [comment]
@franzhollerer Please see PR #799 for a fix to install the example programs.  Please confirm that this works for you.
