### ISSUE TITLE
Retransmit is a protocol detail and should not be implemented in the client

### ISSUE THREAD

**Issue by franc0is** [obgm/libcoap#8]
All of the POSIX examples implement the re-transmit part of the standard in the application code, mostly to make up for the fact that it isn't implemented in the library itself.

E.g. in examples/client.c:

```
  [...]
  while ( !(ready && coap_can_exit(ctx)) ) {
    FD_ZERO(&readfds);
    FD_SET( ctx->sockfd, &readfds );

    nextpdu = coap_peek_next( ctx );

    coap_ticks(&now);
    while (nextpdu && nextpdu->t <= now - ctx->sendqueue_basetime) {
      coap_retransmit( ctx, coap_pop_next( ctx ));
      nextpdu = coap_peek_next( ctx );
    }
  [...]
```

This is unsanitary and breaks many of the abstractions in obvious ways. For example, the coap_context_t object when compiled with -DWITH_POSIX keeps a reference to the socket so that - and this is the only reason as far as I can tell - the client can use it in its re-transmit code.

The Contiki & lwIP ports implement re-transmit in the library, which makes the above fact even more puzzling.

**Comment by obgm** [comment]
Your observation is correct. This is some artifact that needs
cleanup. Before proceeding with this, please note that there are change
proposals to move the network I/O callbacks into the endpoint structure
and to factor out platform-specific code:

https://sourceforge.net/p/libcoap/mailman/libcoap-developers/thread/559A02B3.7060109%40netcommwireless.com/#msg34268958
https://sourceforge.net/p/libcoap/mailman/libcoap-developers/thread/1434009375.4418.11.camel%40sastrion.pl/#msg34196444

**Comment by obgm** [comment]
This has been resolved in the meantime by the `coap_io_process()` interface. Closing.
