### ISSUE TITLE
cmake - libcoap - tinydtls - warning: "HAVE_ARPA_INET_H" redefined

### ISSUE THREAD

**Issue by boaks** [obgm/libcoap#808]
Using commit 7d6903d8570678a93b7ef8ebf1877fe1e93d0551 I followed `BUILDING` with cmake (version  3.22.1).

I use

```
cmake ..  -DDTLS_BACKEND=tinydtls -DENABLE_TCP=OFF -DENABLE_DOCS=OFF
```

with that, I get 

> In file included from /home/achim/repos/libcoap-tinydtls/build/include/tinydtls/tinydtls.h:41:0,
>                  from /home/achim/repos/libcoap-tinydtls/src/coap_tinydtls.c:30:
> /home/achim/repos/libcoap-tinydtls/build/include/tinydtls/dtls_config.h:14:0: warning: "HAVE_ARPA_INET_H" redefined
>  #define HAVE_ARPA_INET_H 1
>  
> In file included from /home/achim/repos/libcoap-tinydtls/include/coap3/coap_internal.h:29:0,
>                  from /home/achim/repos/libcoap-tinydtls/src/coap_tinydtls.c:18:
> /home/achim/repos/libcoap-tinydtls/build/coap_config.h:34:0: note: this is the location of the previous definition
>  #define HAVE_ARPA_INET_H "1"

did I something wrong? Seems, that include two different auto-generated `???_config.h` results in that.

**Comment by mrdeep1** [comment]
No idea how this sneeked through.  Fix is in #809.

**Comment by boaks** [comment]
PR #809 solves this issue.

**Comment by mrdeep1** [comment]
#809 has now been merged.  If there are no more issues to do with this issue, can you please close this Issue.

**Comment by obgm** [comment]
Closing as resolved.
