### ISSUE TITLE
Blockwise Transfer does not include URI path and content type after first block

### ISSUE THREAD

**Issue by rbeere** [obgm/libcoap#811]
## Environment

- libcoap version : master

## Problem Description

I try to send a large body within a POST request. Server side is Californium Coap server.
I am using block mode  COAP_BLOCK_USE_LIBCOAP|COAP_BLOCK_SINGLE_BODY

After sending the second block I get a 4.08 response from the Californium server -> 'request block1 offset 1024 doesn't match the current position 0!'

I digged a bit deeper and found out that the Server is sending this response because it considers the second block to be a new connection/message.  The reason is that the identifier to find an existing message for a new block1 message is build by a combination of peers address, and URI-path.

It seems that libcoap does send the URI Path option only in the first message/block of a blockwise transfer. So when the second block is received by the Californium server it cannot identidy the existing blockwise transfer because it's missing the URI and so created a new blockwise transfer and is expecting the first Block with number zero. ....and thus is responding with:  'request block1 offset 1024 doesn't match the current position 0!'

I took a look into the code of lobcoap which is handling the blockwise transfer. To verify my assumption I hardcoded the URI I use and added it via coap_add_option ( COAP_OPTION_URI_PATH to the PDU just before sending the next block via coap_send_internal in method coap_handle_response_send_block.  ....and it helped. The server was then able to identify the original blockwise transfer and considered the new block as the second one of the running transfer.
But I got another error message back from the server complaing about missing Content-Format.  That's why I also hardcoded the format via coap_add_option ( COAP_OPTION_CONTENT_FORMAT ).  

This finally helped and I could transmit the whole blockwise transfer successfully.

I could not find out how to get the original URI and content-format withing the coap_handle_response_send_block function to replace the hardcoded URI and content-format by getting the from the session-context or so.

I also took a look into the RFC and I guess it's correct that the URI should be send with each block, at least it is like that in the examples in the RFC.

I could not find out if it is specified that content-format must be sent with each block.

### Expected Behavior

in blockwise transfers each block message should include URI and content-format options

### Actual Behavior

URI and content format are only sent with first block-

### Steps to reproduce

1. do blockwise transfer (POST) with Californium as server
2. it should at least produce 2 blocks ( block no 1 is working, it fails at the 2nd block )

### PDU logs without changes:

-> v:1 t:CON c:POST i:49a4 {0100000003} [ Uri-Path:data, Content-Format:application/json, Block1:0/M/1024, Size1:18579 ] 
<- v:1 t:ACK c:2.31 i:49a4 {0100000003} [ Block1:0/M/1024 ]

-> v:1 t:CON c:POST i:49a5 {0200000002} [ Block1:1/M/1024, Size1:18579 ] 
<- v:1 t:ACK c:4.08 i:49a5 {0200000002} [ Block1:1/M/1024 ] :: 'request block1 offset 1024 doesn't match the current position 0!'

### PDU logs with my changed code:

-> v:1 t:CON c:POST i:79ab {0100000003} [ Uri-Path:data, Content-Format:application/json, Block1:0/M/1024, Size1:17067 ] 
<- v:1 t:ACK c:2.31 i:79ab {0100000003} [ Block1:0/M/1024 ]

-> v:1 t:CON c:POST i:79ac {0200000002} [ Uri-Path:data, Content-Format:application/json, Block1:1/M/1024, Size1:17067 ] 
<- v:1 t:ACK c:2.31 i:79ac {0200000002} [ Block1:1/M/1024 ]

.......14 more blocks

-> v:1 t:CON c:POST i:79bb {1100000002} [ Uri-Path:data, Content-Format:application/json, Block1:16/_/1024, Size1:17067 ] 
<- v:1 t:ACK c:2.05 i:79bb {1100000002} [ Content-Format:text/plain, Block1:16/_/1024 ]

finished successfully.

**Comment by mrdeep1** [comment]
@rbeere Thanks for raising this issue.  However, I am unable to reproduce where the second payload does not contain the Uri-Path: and Content-Format.

It is valid for Californium to be rejecting the second block as Uri-Path: etc are a part of the cache-key which is not matching on the second request.

What is the actual version of libcoap that you are using - the `master` branch no longer exists (now is known as `main`)?

If you are using a git clone, your current version can be found using `git describe --tags`.

My testing was done using the `develop` branch code
```` 
Window 1

$ examples/coap-server -v8 -d5 -L3
````
````
Window 2 (note that post is only recently supported in the coap-server, you may need to use put)

$ ls -l test/test_large_ldata
-rw-r--r-- 1 root root 1560 Dec 30 22:11 test/test_large_ldata
$ examples/coap-client -t 50 -m post -f test/test_large_ldata coap://127.0.0.1/test -v8 -L3
````
Which returns
````
v:1 t:CON c:POST i:4f7c {01000000000003} [ Uri-Path:test, Content-Format:application/json, Block1:0/M/1024, Size1:1560 ] ::
v:1 t:ACK c:2.31 i:4f7c {01000000000003} [ Block1:0/M/1024 ]
...
v:1 t:CON c:POST i:4f7d {02000000000003} [ Uri-Path:test, Content-Format:application/json, Block1:1/_/1024, Size1:1560 ] ::
v:1 t:ACK c:2.01 i:4f7d {02000000000003} [ Location-Path:test ]
````

**Comment by rbeere** [comment]
@mrdeep1 Thanks for the response. As I tried around a bit more I found out that the setup of the base PDU of all later block request is done in coap_add_data_large_request.

The problem was that I added the options including format and uri (coap_add_optlist_pdu) after this call. That's why they are included in the first block which is directly sent from the call to coap_send(). ....but later on they are missing in the PDUs.

So I guess this can be closed again. ....maybe a hint in the docs would be good that the sequence of the method calls is important.

BR
René

**Comment by mrdeep1** [comment]
> The problem was that I added the options including format and uri (coap_add_optlist_pdu) after
> this call. That's why they are included in the first block which is directly sent from the call to
> coap_send(). ....but later on they are missing in the PDUs.

I was surprised that libcoap actually allowed you to add an option (with `coap_add_option()`) following adding the data, but see that this is possible when doing a quick code inspection.

[coap_pdu_setup(3)](https://libcoap.net/doc/reference/develop/man_coap_pdu_setup.html) does refer the order of building up the PDU in the Description

> The CoAP PDU is of the form
> 
> --header--|--optional token--|--optional options--|--optional payload--
> 
> The terminology used is taken mainly from https://tools.ietf.org/html/rfc7252#section-1.2
> 
> The PDU must be built in the correct order, from left to right. In particular, the options need
>  to be added in the correct numerical option order as they are stored in the PDU using relative
>  numeric offsets from the previous option number.

and then under Payload Data

> The coap_add_data() function adds in the specified payload data of length length to the
> PDU pdu. Adding the payload data must be done after any token or options are added.

I will look at not allowing `coap_add_option()` after `coap_add_data_large_request()` before calling `coap_send()` so that others do not fall into the trap you found.

**Comment by rbeere** [comment]
Thanks for the explanation ... I will close the issue.
