### ISSUE TITLE
Behavior of coap_encode_var_safe8 is different than described in docs

### ISSUE THREAD

**Issue by panekk** [obgm/libcoap#815]
Hello.

The docs for `coap_encode_var_safe8` say that this function returns 0 of error. Usually it's true, however, things are becoming complicated when I'm trying to encode 0. I'd expect in that case the function returns 1, but it actually returns 0, so nothing is encoded even though it's possible to encode 0 on a single byte. This behavior is useful for encoding options (it's also used in libcoap), so probably changing it isn't the best solution, but I think it should at least be documented, because one may want to use it in other contexts to convert from host byte order to network byte order.

**Comment by mrdeep1** [comment]
As ever a corner case - oops.  As it happens, if there is an error, an `assert() `is thrown (if asserting enabled, which it is by default).
As per [3.2. Option Value Formats](https://datatracker.ietf.org/doc/html/rfc7252#section-3.2), we have

>                                         For example, the number 0 is
>              represented with an empty option value (a zero-length
>              sequence of bytes)

so `coap_encode_var_safe8()` correctly does not encode anything and returns 0 as the length (minimizing the bytes that go onto the wire).  This length is then usually used in building an option, so a pseudo length value of 1 will confuse things. `coap_decode_var_bytes8()` correctly returns 0 for an empty option value.

I am loath to change an API as it could potentially break existing applications.  If you have a need to convert host/network byte order for a 64 bit integer (or perhaps larger), then it would be best to write your own function (or use another library's function) to do this.

**Comment by mrdeep1** [comment]
I have raised PR #816 to clarify the documentation.

**Comment by panekk** [comment]
Thank you, I think it's enough to have this behavior documented instead of changing the behavior.
