### ISSUE TITLE
Different resources in a Proxy CoAP-to-CoAP scenario

### ISSUE THREAD

**Issue by jperezdi** [obgm/libcoap#817]
**Describe the solution you'd like**

I am testing a scenario where the communication is client(CoAP)->(CoAP)Proxy(CoAP)->(CoAP)Server and I get the connection from client to server. The problem I have is that the server that has the -P parameter 'Local IP', Server Name. The server detects that it is the endpoint, but when selecting the resource, it does not select the resource that arrives in the Proxy-Uri, but select the resource ''. I share the command lines of the three components:
 
Sever: IP: \*.\*.\*.39
﻿coap-server -v 9 -P coap://\*.\*.\*.39,\*::\*:\*:\*:e84f
 
Proxy: IP: \*.\*.\*.80
coap-server -P coap://\*.\*.\*.39,badname -v 9
 
Client:
coap-client -P coap://\*.\*.\*.80 -T cafe -m get coap://[\*::\*:\*:\*.e84f]/posrequest

The log of the server is this:
v:1 t:CON c:GET i:ec02 {63616666} [ Hop-Limit:15, Proxy-Uri:coap://[\*::\*:\*:\*:e84f]/posrequest ]
Feb 06 13:17:05.038 DEBG call custom handler for resource ''
Feb 06 13:17:05.038 DEBG \*  [::ffff:\*.\*.\*.39]:5683 <-> [::ffff:\*.\*.\*.80]:51926 (if2) UDP : sent 150 bytes
v:1 t:ACK c:2.05 i:ec02 {63616666} [ Content-Format:text/plain, Max-Age:196607 ] :: 'This is a test server made with libcoap (see https://libcoap.net)\x0ACopyright (C) 2010--2021 Olaf Bergmann <bergmann@tzi.org> and others\x0A\x0A'

**Describe alternatives you've considered**

The need is given by having different resources on the coap server when there is a CoAP-to-CoAP proxy between the client and the server and not only the root resource.

Greetings and thanks in advance.

**Comment by mrdeep1** [comment]
@jperezdi Thank you for raising this issue.  I can confirm that the wrong resource is getting requested on Server.  I will look at getting a fix out for this.

However, if you define your Proxy to connect directly to Server (rather than Proxy treating Server as another proxy in the chain) all should work for you.  e.g.
````
Sever: IP: *::*:*:*.e84f
﻿coap-server -v 9
 
Proxy: IP: *.*.*.80
coap-server -P ,badname -v 9
 
Client:
coap-client -P coap://*.*.*.80 -T cafe -m get coap://[*::*:*:*.e84f]/posrequest
````

**Comment by mrdeep1** [comment]
See PR #818 for a fix.
