### ISSUE TITLE
Include directory in pkgconfig is likely to cause conflicts

### ISSUE THREAD

**Issue by jcmichelou** [obgm/libcoap#82]
Currently in libcoap-1.pc.in, Cflags is set to -I${includedir}/coap.
This has the consequence that if a project uses pkgconfig to build with libcoap, all coap headers files are in the include path, some of which have very generic names (address.h, resource.h, bits.h, uri.h, net.h, and so on ...) that have a high probability to conflict with system libs or the project's own include files.
There are a few possible fixes, including the most two most simple:
1) Change Cflags to -I${includedir}. In that case, applications using libcoap shall include <coap/coap.h> instead of <coap.h>. Very simple, but will break existing applications using libcoap with pkgconfig.
2) Rename all header files with a coap_ prefix (requires changes in the library itself as well)
I think the first one is more elegant in the long term.
Of course there are other solutions. Some projects use scripts to generate a unique header file by concatenation. Another alternative is to create a subdir under ${includedir}/coap.

**Comment by tijuca** [comment]
Good catch, I agree on that.
The current behaviour of the pkg-config file wasn't intended this way, it's simply not tested enough for correctness. We need to change libcoap-1.pc like you suggested in the first point. Maybe we should also create a 4.1.3 release then to catch the issue right now and not with a release of 4.2.0.

**Comment by obgm** [comment]
+1

The current path setting was an intermediary step but it seems that we forgot to finish that once the pkgconfig mechanism has worked.

**Comment by tijuca** [comment]
@obgm 
Would you take care on this? It's a tiny chance and really needed.

**Comment by obgm** [comment]
Okay, will do.

**Comment by obgm** [comment]
This is now fixed in commit 6d7ba61.
