### ISSUE TITLE
Management of options from the proxy server

### ISSUE THREAD

**Issue by jperezdi** [obgm/libcoap#825]
**Is your feature request related to a problem? Please describe.**

Management of options from the proxy server

**Describe the solution you'd like**

I am testing the coap-to-coap proxy functionality and I have encountered the following behaviour: When I send a message to coap with option 9 (being this one critical and safe-to-forward), the proxy is returning 'Bad Option'.  

**Describe alternatives you've considered**
As I read in the RFC (7252) of CoAP it appears the following: Safe-to-Forward Option. An option that is intended to be safe for forwarding by a proxy that does not understand it.  Forwarding the message even without understanding the option is acceptable. 
Is the behaviour that has been defined for the proxy the correct one, or is it a behaviour that has not been set for the proxy?

Thanks in advance.

**Comment by mrdeep1** [comment]
@jperezdi Thanks for raising this.  As it happens PR #764 is waiting to be merged into the develop branch and handles the Oscore option (9).

The checking for critical options that are safe to forward if the incoming CoAP request is destined for the proxy logic to be forwarded is missing.

The logic is currently only checking for known options that are critical (or have been defined by the recieving server logic using the `coap_register_option()` function) to block or allow the critical option.

The current logic can be re-worked for special casing incoming proxy type CoAP requests, but the proxy logic only kicks in after the CoAP options are checked for the critical options.  This needs to be properly thought through.

**Comment by jperezdi** [comment]
Hello,

After various tests, the problem persists. This condition is never fulfilled: 
if (COAP_PDU_IS_REQUEST(pdu) && ctx->proxy_uri_resource &&
              (opt_iter.number & 0x02) == 0 &&
              (coap_check_option(pdu, COAP_OPTION_PROXY_URI, &t_iter) ||
               coap_check_option(pdu, COAP_OPTION_PROXY_SCHEME, &t_iter))) {
            pdu->crit_opt = 1;
}

Thanks in advance.

**Comment by mrdeep1** [comment]
Interesting.  Are you trying to do this as a reverse proxy (in other words the received PDU does not include either of the COAP_OPTION_PROXY_URI or COAP_OPTION_PROXY_SCHEME options)?

It would be good to see a copy of an example packet that fails - as reported when logging at the level of LOG_DEBUG (standard coap-server option -v7) and information surrounding that packet.

It may be an issue with the returning packet from the upstream server.  I will look at that once I can see the packet that is causing the issue.

**Comment by mrdeep1** [comment]
I have reworked/updated #826.  Please let us know if this now works for you, otherwise please provide us with some debug logs.

My test scenarios are based on (Oscore from PR #764)
Oscore core client -- proxy server -- Oscore core server
varying the proxy parameter on the proxy server to try to berak different things.

**Comment by mrdeep1** [comment]
Thanks.

the updated code in #826, it should recognize the the new client session opened up from the proxy to the server is a ongoing proxy connection and hence handle the critical option in the response before passing it on to client. 

I assume you are using the version of coap-server as a part of #826.

In my testing, the #826 based proxy was running on a different host  to #764 client and server using the Oscore enabling -E option.

**Comment by mrdeep1** [comment]
With my coap-server built with #826, I get (192.168.0.88 is CoAP proxy, [::ffff:192.168.0.88]:5683 is client<->proxy and 192.168.0.88:44483 is proxy<->server)
[proxy.txt](https://github.com/obgm/libcoap/files/8096171/proxy.txt)

In particular, I would be expecting `process upstream incoming 2.04 response:`, 
````
Feb 18 09:59:22.318 DEBG *  192.168.0.88:44483 <-> 192.168.0.189:5683 UDP : received 34 bytes
v:1 t:ACK c:2.04 i:c9cf {01000000000002} [ 9:\x01\x0B ] :: binary data length 19
<<c86801ed1ac3db69d90c4dd71a9c463f647984>>
<<. h . . . . . i . . M . . . F ? d y . >>
Feb 18 09:59:22.322 DEBG ** 192.168.0.88:44483 <-> 192.168.0.189:5683 UDP : mid=0xc9cf: removed 1
Feb 18 09:59:22.333 DEBG ** process upstream incoming 2.04 response:
Feb 18 09:59:22.344 DEBG *  [::ffff:192.168.0.88]:5683 <-> [::ffff:192.168.0.189]:45270 (if2) UDP : sent 34 bytes
v:1 t:CON c:2.04 i:78f5 {01000000000002} [ 9:\x01\x0B ] :: binary data length 19
<<c86801ed1ac3db69d90c4dd71a9c463f647984>>
<<. h . . . . . i . . M . . . F ? d y . >>
````
but you are seeing in the same place `unknown critical option 9`, the check for which is before `process upstream incoming 2.04 response:` is reported.

````
diff --git a/src/net.c b/src/net.c
index a7179f5..fdeee39 100644
--- a/src/net.c
+++ b/src/net.c
...
@@ -706,6 +707,21 @@ coap_option_check_critical(coap_context_t *ctx,
         break;
       default:
         if (coap_option_filter_get(&ctx->known_options, opt_iter.number) <= 0) {
+#if COAP_SERVER_SUPPORT
+          if ((opt_iter.number & 0x02) == 0) {
+            coap_opt_iterator_t t_iter;
+
+            /* Safe to forward  - check if proxy pdu */
+            if (session->proxy_session)
+              break;
+            if (COAP_PDU_IS_REQUEST(pdu) && ctx->proxy_uri_resource &&
+                (coap_check_option(pdu, COAP_OPTION_PROXY_URI, &t_iter) ||
+                 coap_check_option(pdu, COAP_OPTION_PROXY_SCHEME, &t_iter))) {
+              pdu->crit_opt = 1;
+              break;
+            }
+          }
+#endif /* COAP_SERVER_SUPPORT */
````
I would be expecting `session->proxy_session` to have been set, thus allowing in option 9, which is done in
````
diff --git a/src/coap_session.c b/src/coap_session.c
index 230dc8b..536e294 100644
--- a/src/coap_session.c
+++ b/src/coap_session.c
@@ -860,6 +860,8 @@ coap_session_create_client(
   if (local_if)
     session->sock.flags |= COAP_SOCKET_BOUND;
   SESSIONS_ADD(ctx->sessions, session);
+  if (ctx->proxy_uri_resource)
+    session->proxy_session = 1;
   return session;

 error:
````

Are you using 2 different coap_context_t*  in the proxy - 1 for incoming connections, the other for outgoing onward connections?

**Comment by jperezdi** [comment]
Hello,
 
After several tests I have managed to get it working. I had to make changes in the net.c file. The problem is because the server response does not meet the added condition and therefore does not activate pdu->crit_opt = 1. 
 
The modification that I have made is this, but I understand that it is not valid, since it would only serve for the deployment of the server as a proxy and not as a server itself:
 
﻿#if COAP_SERVER_SUPPORT
          coap_opt_iterator_t t_iter;
 
          /* Acting as proxy, critical and safe to forward ? */
          if (COAP_PDU_IS_REQUEST(pdu) && ctx->proxy_uri_resource &&
              (opt_iter.number & 0x02) == 0 &&
              (coap_check_option(pdu, COAP_OPTION_PROXY_URI, &t_iter) ||
               coap_check_option(pdu, COAP_OPTION_PROXY_SCHEME, &t_iter))) {
            pdu->crit_opt = 1;
            break;
          }
          pdu->crit_opt = 1;
          break;
#endif /* COAP_SERVER_SUPPORT */
 
I haven't changed anything else in the proxy code.
 
Thank you in advance.

**Comment by jperezdi** [comment]
Hello,

Sorry, but I didn't see that more files have been updated. After downloading all the files and compiling them, the solution works perfectly.

Thanks in advance.

**Comment by mrdeep1** [comment]
Excellent - thanks fo the feedback.  Good to have got it sorted.
