### ISSUE TITLE
Separate response handling

### ISSUE THREAD

**Issue by codable** [obgm/libcoap#83]
Request and response matching should use token instead of message id. However, the request is removed from sendqueue once an ACK of the same message id is received. This causes the real response is handled without the matching request.

**Comment by obgm** [comment]
Yes, this was deliberately designed this way.

Keeping the initial request until the response is received needs to be done on the application layer.
A similar issue related to observe has been discussed on the mailing list some time ago [1]. Resolving the observe issue may produce a resolution to your problem with separate responses as wel.

[1] https://sourceforge.net/p/libcoap/mailman/message/35547934/

**Comment by obgm** [comment]
Closing off as this issue has been fixed in PR #552
