### ISSUE TITLE
POST method in coap-server

### ISSUE THREAD

**Issue by eliot4321** [obgm/libcoap#834]
Hi,

There is no implementation for CoAP POST method I tried to use the COAP_REQUEST_POST but it uses the put method instead, any idea?

**Comment by mrdeep1** [comment]
If you run the examples coap-server with the `-d` options (e.g. `-d 5`), and then do a POST to a non-existant URI, coap-server will handle this POST request and create URI which can be used for subsequent GET/PUT requests.

It would help if you can demonstrate your issue using the examples coap-server / coap-client

**Comment by eliot4321** [comment]
Hi @mrdeep1 ,

Thanks for your response, the plan is to send data from a file so the method needs to be implemented with specific requirements.

**Comment by mrdeep1** [comment]
I assume you are using the latest code from the develop branch.
````
Window 1
$ examples/coap-server -d5
Window 2
$ cat /tmp/data
This is some data
$ examples/coap-client -m post -f /tmp/data coap://127.0.0.1/test
$ examples/coap-client -m get coap://127.0.0.1/test
This is some data
$
````

**Comment by eliot4321** [comment]
Still the same error

**Comment by mrdeep1** [comment]
Run the examples in the 2 windows with the -v7 option and report the results so we can properly debug what is going on.

**Comment by eliot4321** [comment]
here you go:
coap-server:
Feb 28 23:18:10.061 DEBG created UDP  endpoint [::]:5683
Feb 28 23:18:10.062 DEBG created TCP  endpoint [::]:5683
Feb 28 23:18:12.597 DEBG ***[::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:54427 (if1) UDP : new incoming session
Feb 28 23:18:12.597 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:54427 (if1) UDP : received 10 bytes
milliseconds arrived: 1646083092596
v:1 t:CON c:GET i:c6fe {01} [ Uri-Path:test ]
Feb 28 23:18:12.597 DEBG request for unknown resource 'test', return 4.04
Feb 28 23:18:12.597 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:54427 (if1) UDP : sent 15 bytes
milliseconds arrived: 1646083092596
v:1 t:ACK c:4.04 i:c6fe {01} [ ] :: 'Not Found'

coap-client:
v:1 t:CON c:POST i:b838 {01} [ Uri-Path:test ]
Feb 28 23:19:18.528 DEBG ** 127.0.0.1:49425 <-> 127.0.0.1:5683 UDP : mid=0xb838: added to retransmit queue (2750ms)
Feb 28 23:19:18.528 DEBG timeout is set to 90 seconds
Feb 28 23:19:18.528 DEBG *  127.0.0.1:49425 <-> 127.0.0.1:5683 UDP : received 15 bytes

v:1 t:ACK c:4.04 i:b838 {01} [ ] :: 'Not Found'
Feb 28 23:19:18.528 DEBG ** 127.0.0.1:49425 <-> 127.0.0.1:5683 UDP : mid=0xb838: removed
Feb 28 23:19:18.528 DEBG ** process incoming 4.04 response:
4.04 Not Found
Feb 28 23:19:18.529 DEBG ***127.0.0.1:49425 <-> 127.0.0.1:5683 UDP : session closed

**Comment by mrdeep1** [comment]
The request you report in the coap-server entry `v:1 t:CON c:GET i:c6fe {01} [ Uri-Path:test ]` (note in particular `i:c6fe`) is not the same as you have for the coap-client `v :1 t:CON c:POST i:b838 {01} [ Uri-Path:test ]` (a different mid `i:b838`), so nothing can be learnt from this.

It does not appear that you are running the coap-server with the `-d 5` option, or else you are running an old version of code (not the latest develop branch).

What does
````
examples/coap-server -? 2>&1 | head -5
````
report ?  Or
````
git describe --tags
````
report ?

**Comment by eliot4321** [comment]
IT appears I have copied an old report sorry, please find below the new one among the other requests:
coap-server:
Mar 01 00:14:36.661 DEBG created UDP  endpoint [::]:5683
Mar 01 00:14:36.661 DEBG created TCP  endpoint [::]:5683
Mar 01 00:14:39.425 DEBG ***[::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:37706 (if1) UDP : new incoming session
Mar 01 00:14:39.425 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:37706 (if1) UDP : received 10 bytes

v:1 t:CON c:POST i:1068 {01} [ Uri-Path:test ]
Mar 01 00:14:39.425 DEBG request for unknown resource 'test', return 4.04
Mar 01 00:14:39.425 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:37706 (if1) UDP : sent 15 bytes

v:1 t:ACK c:4.04 i:1068 {01} [ ] :: 'Not Found'

coap-client:
ar 01 00:14:39.424 DEBG sending CoAP request:

Mar 01 00:14:39.425 DEBG *  127.0.0.1:37706 <-> 127.0.0.1:5683 UDP : sent 10 bytes

v:1 t:CON c:POST i:1068 {01} [ Uri-Path:test ]
Mar 01 00:14:39.425 DEBG ** 127.0.0.1:37706 <-> 127.0.0.1:5683 UDP : mid=0x1068: added to retransmit queue (2906ms)
Mar 01 00:14:39.425 DEBG timeout is set to 90 seconds
Mar 01 00:14:39.425 DEBG *  127.0.0.1:37706 <-> 127.0.0.1:5683 UDP : received 15 bytes

v:1 t:ACK c:4.04 i:1068 {01} [ ] :: 'Not Found'
Mar 01 00:14:39.425 DEBG ** 127.0.0.1:37706 <-> 127.0.0.1:5683 UDP : mid=0x1068: removed
Mar 01 00:14:39.425 DEBG ** process incoming 4.04 response:
4.04 Not Found
Mar 01 00:14:39.427 DEBG ***127.0.0.1:37706 <-> 127.0.0.1:5683 UDP : session closed

coap-server -? 2>&1 | head -5:
coap-server: invalid option -- '?'
coap-server v4.3.0 -- a small CoAP implementation
(c) 2010,2011,2015-2021 Olaf Bergmann <bergmann@tzi.org> and others

libcoap 4.3.0

**Comment by mrdeep1** [comment]
Please use the latest version of the develop branch code and try again.  The coap-server help message is from an older code version.

**Comment by eliot4321** [comment]
Thanks, I will try with the new branch, I assume the new code has supported the POST method if I want to transfer specific data from a file,  of course, it needs to be implemented?

**Comment by mrdeep1** [comment]
POST is supported in the latest code version in the example coap-server when using the -d option.  Libcoap library has supported it for a very long time using the API calls

**Comment by eliot4321** [comment]
@mrdeep1, I was busy with other things, I'm working now on this, the plan is to use the POST method to transfer large data from a file, I will let you know if I have any issues.  Thanks!

**Comment by eliot4321** [comment]
HI @mrdeep1 ,

I have created a resource named "file_data" using POST method with specific code for it but it's not organized by server when I'm calling it 
THis is log:
v:1 t:CON c:POST i:0000 {01000000000002} [ Uri-Path:file_data ]
Mar 02 11:46:47.143 DEBG call custom handler for resource '- Unknown -'
v:1 t:ACK c:2.01 i:0000 {01000000000002} [ Location-Path:file_data ]
Mar 02 11:46:47.143 INFO *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:43351 TLS : SSL3 alert read:warning:close notify
Mar 02 11:46:47.143 DEBG ***[::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:43351 TLS : session disconnected (reason 3)
Mar 02 11:46:47.143 INFO *  [::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:43351 TLS : SSL3 alert write:warning:close notify
Mar 02 11:46:47.143 DEBG ***EVENT: 0x0000
Mar 02 11:46:47.143 DEBG ***EVENT: 0x1002
Mar 02 11:46:47.143 DEBG ***EVENT: 0x2002
Mar 02 11:46:47.143 DEBG ***[::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:43351 TLS : session disconnected (reason 1)
Mar 02 11:46:47.143 DEBG ***[::ffff:127.0.0.1]:5684 <-> [::ffff:127.0.0.1]:43351 TLS : session 0x558a159a8310: closed

**Comment by mrdeep1** [comment]
As I read this debug log, the server received the POST, responded with the 2.01 (Created) and then recieved a SSL alert close notify from the client - i.e. the client closed down the connection.

From the server's perspective, all is OK.  You need to check into what the client log says - did it recieve the 2.01 etc.

**Comment by eliot4321** [comment]
this the client side,  but no response has been received:
v:1 t:CON c:CSM i:0000 {} [ Max-Message-Size:8388864, Block-wise-Transfer: ]
Mar 02 11:46:47.142 DEBG ***127.0.0.1:43351 <-> 127.0.0.1:5684 TLS : session connected
Mar 02 11:46:47.143 DEBG ***EVENT: 0x2001
Mar 02 11:46:47.143 DEBG ** 127.0.0.1:43351 <-> 127.0.0.1:5684 TLS : mid=0xe859: transmitted after delay
v:1 t:CON c:POST i:e859 {01000000000002} [ Uri-Path:file_data ]
Mar 02 11:46:47.143 DEBG *  127.0.0.1:43351 <-> 127.0.0.1:5684 TLS : received 19 bytes
v:1 t:CON c:2.01 i:0000 {01000000000002} [ Location-Path:file_data ]
Mar 02 11:46:47.143 DEBG ** 127.0.0.1:43351 <-> 127.0.0.1:5684 TLS : lg_crcv 0x55db74ef8c40 released
Mar 02 11:46:47.143 DEBG ** process incoming 2.01 response:
Mar 02 11:46:47.145 INFO *  127.0.0.1:43351 <-> 127.0.0.1:5684 TLS : SSL3 alert write:warning:close notify
Mar 02 11:46:47.145 INFO *  127.0.0.1:43351 <-> 127.0.0.1:5684 TLS : SSL3 alert read:warning:close notify
Mar 02 11:46:47.145 DEBG ***EVENT: 0x0000

**Comment by mrdeep1** [comment]
The client has recieved the 2.01(Created) response, as in
````
Mar 02 11:46:47.143 DEBG * 127.0.0.1:43351 <-> 127.0.0.1:5684 TLS : received 19 bytes
v:1 t:CON c:2.01 i:0000 {01000000000002} [ Location-Path:file_data ]
Mar 02 11:46:47.143 DEBG ** 127.0.0.1:43351 <-> 127.0.0.1:5684 TLS : lg_crcv 0x55db74ef8c40 released
Mar 02 11:46:47.143 DEBG ** process incoming 2.01 response:
Mar 02 11:46:47.145 INFO * 127.0.0.1:43351 <-> 127.0.0.1:5684 TLS : SSL3 alert write warning close notify
````
Were you expecting some data in the response?  If so, that that would be down to the application server to be doing that, which the examples coap-server is not set up to do.
If you were to follow up this POST request with another execution of the examples coap-client doing a GET /file_data, you will then get the data back from the server you sent in in the POST as per my previous comment :-
````
Window 1
$ examples/coap-server -d5
Window 2
$ cat /tmp/data
This is some data
$ examples/coap-client -m post -f /tmp/data coap://127.0.0.1/test
$ examples/coap-client -m get coap://127.0.0.1/test
This is some data
$
````

**Comment by eliot4321** [comment]
I made a quick sketch to give you an idea of what I'm planning to have
![Screenshot 2022-03-02 at 14 29 16](https://user-images.githubusercontent.com/61513352/156361942-20a42698-9022-4b11-9644-df5c75dfe3a5.png)
.

**Comment by mrdeep1** [comment]
Then the request handler in the server needs logic that parses the payload and then generates the appropriate response which is sent back using [coap_add_data_large_response().](https://libcoap.net/doc/reference/develop/man_coap_block.html)  As well as the examples code, there is sample code in the man pages - see [Manual Pages](https://libcoap.net/doc/reference/develop/manpage.html) for other information.

**Comment by eliot4321** [comment]
Actually, I'm working on the logic when I'm trying to debug it seems that the resources are not calling even the method I made to handle the request I tried to show in log some message but nothing, I'm still worried about the logs of the CoAP server showing this line:
Mar 02 11:46:47.143 DEBG call custom handler for resource '- Unknown -'

**Comment by mrdeep1** [comment]
In examples/coap-server.c, we have
````
  if (support_dynamic > 0) {
    /* Create a resource to handle PUTs to unknown URIs */
    r = coap_resource_unknown_init(hnd_put_post_unknown);
    /* Add in handling POST as well */
    coap_register_handler(r, COAP_REQUEST_POST, hnd_put_post_unknown);
    coap_add_resource(ctx, r);
  }

````
which would be handling your POST to a "unknown" resource that is not yet defined for the coap-server.  Hence:-
````
Mar 02 11:46:47.143 DEBG call custom handler for resource '- Unknown -'
````
The function [hnd_put_post_unknown()](https://libcoap.net/doc/reference/develop/man_coap_resource.html) will get called in the coap-server, which then creates a new resource for the provided uri-path.  Any subsequent POST  against this now defined resource will go to the request handler hnd_put_post(), and you will then see a message of the form:-
````
Mar 02 11:46:47.143 DEBG call custom handler for resource 'file_data'
````

**Comment by eliot4321** [comment]
But I have created a resource to handle my post request, please see below:
  r = coap_resource_init(coap_make_str_const("file_data"), resource_flags);
  coap_register_request_handler(r, COAP_REQUEST_POST, hnd_post_file_data);
  
  coap_resource_set_get_observable(r, 1);

  coap_add_attr(r, coap_make_str_const("ct"), coap_make_str_const("0"), 0);
  coap_add_attr(r, coap_make_str_const("title"), coap_make_str_const("\"File data\""), 0);
  coap_add_resource(ctx, r);

Why then it's handled as unknown?

**Comment by mrdeep1** [comment]
Your code looks fine (`coap_resource_set_get_observable(r, 1); `is for GET/FETCH, but that should not matter).

I have to assume that you are running with the latest built version of coap-server.  THe only other thing is  - have you only set up 1 `ctx`, or did you build another one and so attach your resource to an alternate `ctx`?

**Comment by eliot4321** [comment]
Yes I'm running the latest one as you recommended yesterday, for the second part of the question I didn't understand it very well, could you please elaborate ?

**Comment by mrdeep1** [comment]
`coap_new_context()` (called by` get_context()` in coap-server.c) should only be called once in your server code.  If you call it twice, but using the returned `ctx ` from the first call for setting up and adding in the resource from coap_resource_unknown_init() and then use the returned `ctx `from the second call to coap_get_context() for adding in your "file_data" resource will cause things to not work.

What does the following return when your server is running?
````
examples/coap-client coap://127.0.0.1/.well-known/core
````
(does it include </file_data> ?)

**Comment by eliot4321** [comment]
Please see below:
``Mar 02 16:52:53.502 DEBG (D)TLS not enabled as neither -k or -c options specified
Mar 02 16:52:53.503 DEBG created UDP  endpoint [::]:5683
Mar 02 16:52:53.503 DEBG created TCP  endpoint [::]:5683
Mar 02 16:52:55.283 DEBG ***[::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:50242 (if1) UDP : session 0x55e1bb6a9540: new incoming session
Mar 02 16:52:55.283 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:50242 (if1) UDP : received 22 bytes
v:1 t:CON c:GET i:f6a8 {01} [ Uri-Path:.well-known, Uri-Path:core ]
Mar 02 16:52:55.283 INFO create default response for .well-known/core
Mar 02 16:52:55.283 DEBG get_wkc_len: coap_print_wellknown() returned 151
Mar 02 16:52:55.283 DEBG *  [::ffff:127.0.0.1]:5683 <-> [::ffff:127.0.0.1]:50242 (if1) UDP : sent 162 bytes
v:1 t:ACK c:2.05 i:f6a8 {01} [ Content-Format:application/link-format, Size2:151 ] :: '</>;title="General Info";ct=0,</time>;if="clock";rt="ticks";title="Internal Clock";ct=0;obs,</async>;ct=0,</example_data>;title="Example Data";ct=0;obs'

I have checked the coap_new_context(); is called only once.

**Comment by mrdeep1** [comment]
OK.  I think you have a reporting cut and paste issue (with the pseudo html tags), namely
````
v:1 t:ACK c:2.05 i:f6a8 {01} [ Content-Format:application/link-format, Size2:151 ] :: '</>;title="General Info";ct=0,;if="clock";rt="ticks";title="Internal Clock";ct=0;obs,;ct=0,</example_data>;title="Example Data";ct=0;obs'

is not the same as what I get (some missing </.....> but have the same size of output (151 bytes)

v:1 t:ACK c:2.05 i:1d2d {01} [ Content-Format:application/link-format, Size2:151 ] :: '</>;title="General Info";ct=0,</time>;if="clock";rt="ticks";title="Internal Clock";ct=0;obs,</async>;ct=0,</example_data>;title="Example Data";ct=0;obs'
````
but there is no reference to </file_data> hence why you are seeing " -Unknown -".

This leads me to thinking that your code below is never called, or there is an error of some sort that is not immediately obvious.
````
  r = coap_resource_init(coap_make_str_const("file_data"), resource_flags);
  coap_register_request_handler(r, COAP_REQUEST_POST, hnd_post_file_data);
  
  coap_resource_set_get_observable(r, 1);

  coap_add_attr(r, coap_make_str_const("ct"), coap_make_str_const("0"), 0);
  coap_add_attr(r, coap_make_str_const("title"), coap_make_str_const("\"File data\""), 0);
  coap_add_resource(ctx, r);
````

**Comment by eliot4321** [comment]
I'm a bit confused why I shoudl see file_data URI if I'm requesting another resource, anyway even I'm calling the file data resource the related logic it's not executed,  with the old version it is with GET method.

**Comment by mrdeep1** [comment]
For libcoap, `.well-known/core` returns all the resources (apart from "- Unknown -" for `coap_resource_unknown_init()` or "- Proxy URI -" for `coap_resource_proxy_uri_init()`) that are registered by the coap-server.

As `</file_data>` is not getting returned, this resource is not getting added in by your coap-server.

>  with the old version it is with GET method

I am not sure what you are saying here - did you register the request call-back handler for GET for the resource you set up for "file_data" as well?

**Comment by eliot4321** [comment]
I meant the one I was using before before you recommended to use the new version to have the POST method.
I'm pretty sure I have followed the steps to file_data as a resource so I cannot see why it's not added to the server.
I assume the code  have shared before is correct to create a new resource and add it to the server.

**Comment by mrdeep1** [comment]
OK.

Yes, your code sample looks OK, but it is either not being executed during coap-server startup or there is a bug in it that I cannot see.  This code should not be in a call-back (i.e. request handler), but in main() or one of the subroutines called by main().

Either debug your code using gdb, or put in a statement such as `coap_log(LOG_DEBUG, "Setting up resource for file_data\n")`; where you have put the code sample you gave me.  Is it getting executed?

I assume that you are not using LwIP or Contiki environments here (i.e you are building in a Linux or Windows environment).

**Comment by eliot4321** [comment]
I have the code inside the init-resources(); method.
It's not executed, logs doesn't show the message.

**Comment by mrdeep1** [comment]
As `.well-known/core` showed all the other resources created by `init_resources()`, then you do not appear to be running the executable that you just built.

However, there may be some other code that you are running in coap-server that is corrupting your executable code (which may explain why some of your `.well-known/core` output was missing).

Are valgrind errors produced then you run at the command prompt?
````
valgrind examples/coap-server -v7
````

**Comment by eliot4321** [comment]
no errors from valgrind, it's really weird as I cannot see why the resource is not added.

**Comment by mrdeep1** [comment]
It has to be that you are running a different executable from the one you built.  You do not for example have `/usr/bin/coap-server` and `/usr/local/bin/coap-server` ?

What is the qualifying path that you are using to run coap-server ?

Did you forget to do a `make install` ?

What does `which coap-server` report?

**Comment by eliot4321** [comment]
You are right, I found out yesterday I was running just make! Thanks, @mrdeep1 for your help much appreciated!
