### ISSUE TITLE
Both coap server and client not working with PSK mode

### ISSUE THREAD

**Issue by pioneerAlone** [obgm/libcoap#843]
I want just do some tests with PSK mode， I enable openssl，However, I did not see the expected results.

Let me know where I might have made a mistake, basically I have two doubts,
#1 How to use -u -k option for PSK mode
#2 How to set the port for DTLS, I set 5683, but the client cannot access 5684

// the commands for coap server
# coap-server-openssl -A ::1 -k 12345678 -h 123 -p 5683 -v 5

//the command for coap client
coap-client-openssl -m POST -e Hello,%20COAP! coaps://10.66.98.156:5684 -u 123 -k 123456789

**Comment by mrdeep1** [comment]
The value of the -k option (the pre-shared key) on both the client and server MUST be identical - in the examples you give, they are different 

On the server, you do not normally need to specify the -h or -p options.  With the -p option, this defines the base, non encrypted port, and the DTLS port is one greater.

The / path request you are trying to use works for GET but does not support POST.

**Comment by pioneerAlone** [comment]
Thanks for your help.

Now , I've able to connect server with DTLS on local server.

Next step, I hope that my device connect to coap server through proxy server, I see that -p option should be available, but there is some confusion about the Settings. What should "name" be set to

//the below is my setting
# coap-server -A ::1 -k 123456789 -v 5 -u 123 -P scheme://121.62.17.70[:45202]
Apr 29 10:15:08.574 WARN Zero or more proxy host names not defined
error specifying proxy address or host names

Thank you in advance!

**Comment by mrdeep1** [comment]
As per [coap-server(5)](https://libcoap.net/doc/reference/develop/man_coap-server.html)

> -P scheme://address[:port],[name1[,name2[,name3..]]]
>
> Scheme, address, optional port of how to connect to the next proxy server and zero or more names
>  (comma separated) that this proxy server is known by. The , (comma) is required. If there is no name1
>  or if the hostname of the incoming proxy request matches one of these names, then this server is considered
>  to be the final endpoint. If scheme://address[:port] is not defined before the leading , (comma) of the 
>  first name, then the ongoing connection will be a direct connection. Scheme is one of coap, coaps, coap+tcp
>  and coaps+tcp.

So, you need to define what the local address is of the proxy-server, which can be a null entry, so that hte logic can detect whether the proxy-server is the end of the proxy forwarding path to prevent a forwarding loop.  The `[` and matching `]` notation is defining the optional parameters that you can specify (but you do not include the `[` `]` when specifying the parameter, and so in your case, I suspection that you do not want to define name1, name2, name3 etc., but you do need at lease one `,` (comma).  Also note that `[:45202]` should be `:45202`

**Comment by pioneerAlone** [comment]
Thanks,

I've modify the command of server side. as follow:
#coap-server -A ::1 -k 123456789 -v 5 -u 123 -P coaps://121.62.17.70:45202,

But, I am not sure how to do setting on the client-side.
#coap-client -m get coaps://121.62.17.70:45202/ -k 123456789 -u 123

Could you help further check. The purpose is to access proxy server:121.62.17.70 and forward to local server:127.0.0.1:5684

**Comment by mrdeep1** [comment]
Connection 1
Client  --  Proxy Server
Connection 2
Proxy Server -- Actual server

So, you have 3 executables running - client, proxy server, actual server

With your coap-client invocation line, I would expect proxy server to be listening on (unencrypted) port 45201 and with your definition, the actual server to be listening on (unencrypted) port 5683.

So, actual server would be run as :-
(Listening on port 5683 and 5684 (encrypted) on loopback address)
$coap-server -A ::1 -k123456789 -v5

proxy server would be run as :-
(Listening on port 45201and 45202(encrypted) on any address, proxy forwarding to 127.0.0.1 on the same application server)
$coap-server -k 123456789 -u 123 -p 45201 -P coaps://127.0.0.1,
