### ISSUE TITLE
Multicast request leisure delay implementation

### ISSUE THREAD

**Issue by midcontinentcontrols** [obgm/libcoap#854]
## Environment

- libcoap version (run ``git describe --tags`` to find it):
    // v4.3.0, also tested with develop (patched with [#851](https://github.com/obgm/libcoap/pull/851))
- Build System:  CMake
- Operating System:  Linux
- Operating System Version: 5.11.0-49-generic
- Hosted Environment: None

## Problem Description

Greetings, I have an issue with libcoap's implementation of delaying multicast requests' responses (per [RFC7252 - Section 8.2](https://datatracker.ietf.org/doc/html/rfc7252#section-8.2)). The delay is sequenced to occur prior to forwarding the request to the application layer (handle_request in net.c). This results in a random delay up to COAP_DEFAULT_LEISURE (5 seconds) before the contents of the message can be processed by the application - which does delay the response, but also introduces a large random latency from the perspective of the application layer at the server. The application layer may decide to not even send a response in this scenario. It is important that server applications receive multicast requests without undue delay to keep network state as synchronized as possible.

### Expected Behavior

Application layer should receive multicast requests immediately, and be able to register async to satisfy leisure requirements if they need to send a response.

### Actual Behavior

Libcoap internally registers async for multicast requests, forwarding to application layer only after leisure time has elapsed.

### Steps to reproduce

Building libcoap - using autoconf instead of CMake to simplify this example due to [#851](https://github.com/obgm/libcoap/pull/851), because the request must be recognized as multicast for this behavior to occur. The results are the same when the aforementioned PR's changes are applied to develop/4.3.0 and built with CMake.

```bash
cd /tmp
git clone https://github.com/obgm/libcoap.git
cd libcoap

./autogen.sh
./configure --enable-async --disable-doxygen --disable-manpages --disable-dtls
make

./examples/coap-server -g ff05::1 -v 9
```

Client request
```bash
./examples/coap-client -m get coap://[ff05::1]/ -N -v 9
```

## Debug Logs

Server
```
May 26 12:06:00.370 DEBG created UDP  endpoint [::]:5683
May 26 12:06:00.370 DEBG created TCP  endpoint [::]:5683
May 26 12:06:00.370 DEBG added mcast group [ff05::1]:5683
May 26 12:06:02.531 DEBG ***[ff05::1]:5683 <-> [fd5e:9a9e:c5bd:10:324a:fbcf:6d18:389e]:59745 (if3) UDP : session 0x56296b2c9f70: new incoming session
May 26 12:06:02.531 DEBG ***EVENT: 0x4001
May 26 12:06:02.531 DEBG *  [ff05::1]:5683 <-> [fd5e:9a9e:c5bd:10:324a:fbcf:6d18:389e]:59745 (if3) UDP : received 11 bytes
v:1 t:NON c:GET i:bf31 {01000000000002} [ ]
May 26 12:06:02.531 DEBG    [ff05::1]:5683 <-> [fd5e:9a9e:c5bd:10:324a:fbcf:6d18:389e]:59745 (if3) UDP : Async request delayed for 4.179 secs
May 26 12:06:06.710 DEBG call custom handler for resource ''
May 26 12:06:06.710 DEBG *  [ff05::1]:5683 <-> [fd5e:9a9e:c5bd:10:324a:fbcf:6d18:389e]:59745 (if3) UDP : sent 153 bytes
v:1 t:NON c:2.05 i:bf31 {01000000000002} [ Max-Age:196607 ] :: 'This is a test server made with libcoap (see https://libcoap.net)\x0ACopyright (C) 2010--2021 Olaf Bergmann <bergmann@tzi.org> and others\x0A\x0A'
```

Note message received at 12:06:02.531, but not forwarded to application layer until 12:06:06.710.

Client
```
May 26 12:06:02.531 DEBG ***[::]:59745 <-> [ff05::1]:5683 UDP : session 0x5599c85da440: created outgoing session
May 26 12:06:02.531 DEBG sending CoAP request:
May 26 12:06:02.531 DEBG PDU presented by app
v:1 t:NON c:GET i:bf31 {01} [ ]
May 26 12:06:02.531 DEBG ** [::]:59745 <-> [ff05::1]:5683 UDP : lg_crcv 0x5599c85db130 initialized - stateless token xxxx000000000002
May 26 12:06:02.531 DEBG *  [::]:59745 <-> [ff05::1]:5683 UDP : sent 11 bytes
v:1 t:NON c:GET i:bf31 {01000000000002} [ ]
May 26 12:06:02.531 DEBG timeout is set to 5 seconds
May 26 12:06:06.710 DEBG *  [::]:59745 <-> [fd5e:9a9e:c5bd:10:324a:fbcf:6d18:389e]:5683 UDP : received 153 bytes
v:1 t:NON c:2.05 i:bf31 {01000000000002} [ Max-Age:196607 ] :: 'This is a test server made with libcoap (see https://libcoap.net)\x0ACopyright (C) 2010--2021 Olaf Bergmann <bergmann@tzi.org> and others\x0A\x0A'
May 26 12:06:06.710 DEBG ** [::]:59745 <-> [fd5e:9a9e:c5bd:10:324a:fbcf:6d18:389e]:5683 UDP : lg_crcv 0x5599c85db130 released
May 26 12:06:06.710 DEBG ** process incoming 2.05 response:
This is a test server made with libcoap (see https://libcoap.net)
Copyright (C) 2010--2021 Olaf Bergmann <bergmann@tzi.org> and others

May 26 12:06:07.531 INFO timeout
May 26 12:06:07.532 DEBG ***[::]:59745 <-> [fd5e:9a9e:c5bd:10:324a:fbcf:6d18:389e]:5683 UDP : session 0x5599c85da440: closed
```

## Other items if possible

Simple test setup runs client and server on the same machine.

Due to being early in our product development, I am not sure at this point if disabling async alltogether is an acceptable solution as the number of nodes in the system grows. It may be acceptable, as a good portion of our multicast requests do not elicit a response at this time, however that could change.

Cheers, and thank you for this excellent tool. Let me know if there is anything I can try in order to assist in resolving this issue.

**Comment by mrdeep1** [comment]
I had not thought of this scenario requirement.

The delay code was put into libcoap in the first instance so that the application layer had no need to worry about putting in an multicast async response delay in all the different request handlers, so the server was always RFC7252 8.2 compliant. This was done when the async code was cleaned up and simplified.  

If you want to give this async response delay (or drop) responsibility to the server, it is easy to add in a patch where this is configurable to indicate it will be done by the server application (default is to continue doing it in libcoap).  This configuration would need to be done at the coap_context_t level, not the coap_session_t level.  It is then the responsibility of the server application to be multicast delay compliant in all circumstances by using the async logic.

Would this work for you?

**Comment by midcontinentcontrols** [comment]
That sounds great to me! That ought to offer all the flexibility I need. 

Our use case seems to be dippinginto [RFC 7390](https://datatracker.ietf.org/doc/html/rfc7390#section-2.8), which is not explicitly listed as supported by libcoap, however much of it seems to be application layer oriented. Either way some of our requests are intended as notifications, which can drive state updates visible to the user, but do not require sending a CoAP response.

Thanks once again for the quick response!

**Comment by mrdeep1** [comment]
Just pushed #855 which should address your issue.  [ietf-core-groupcomm](https://datatracker.ietf.org/doc/html/draft-ietf-core-groupcomm-bis-06.txt) is expected to replace RFC 7390 and will be a Standards track rather than experimental.

Please let us know if the PR works for you.

**Comment by midcontinentcontrols** [comment]
I have set up a test of [#855](https://github.com/obgm/libcoap/pull/855) in my application and it appears to be working well! Thanks for the link to the standards track, I'll dive into that. 

Thanks again for the super quick responses, I appreciate your work! I'm going to go ahead and close this issue since the PR solves it for me.
