### ISSUE TITLE
Using both server & client on the same port

### ISSUE THREAD

**Issue by remenyo** [obgm/libcoap#882]
### Not-so-short TLDR:
- I need to reach a local device behind a NAT + Firewall configuration.
- I want to faciliate bi-directional unsolicited communication between exactly two ends.
- I'm open for any method to use server and client capabilities on the same port, to trick firewalls and keep NAT table entries alive. Maybe my proposed solution down below is not the best way to pass through a firewall with libcoap. 

---

My idea is to send out messages from the same port where I listen to new ones creating the NAT+Firewall tunnel from client side, and use that tunnel backwards. This would look like a "reply" for the Firewall, but in reality the traffic would be simple POST request / ACKs from both directions.
I have not found a way to set the port from the libcoap API side, I am not even sure it exists.

I think I need this method to allow the foreign service to send unsolicited messages (like a client) through the NAT + Firewall configuration to my server, altough you may know a better way to faciliate bi-directional unsolicited communication.

I have read several questions here about almost the same topic, but I don't think I have found an exact one like this hence the new issue.

In #772 and #707 mrdeep1 *(don't want to mention him, probably reads this anyways)* talked about the Observer methods in CoAP, but that would mean the foreign server configuration has to be changed to subscribe to the client(s) right?

I have read about keepalive in the documentation, but that needs a session first to keep alive, (and does not solve the original NAT problem if I understood it.)

#### Additional information:
- The topology is (the usual?) one to many: I have one foreign server, with a static public IPv4 address and many clients which could be anywhere, in the worst and most usual case behind a Firewall and NAT device like a home router.
- I can change the clients code more easily than the server's, but it is possible.

Thank you for reading through.

**Comment by remenyo** [comment]
Thank you for your help. Indeed, there is a way to set the local interface, thus the port.

I searched in session setter functions, not the session creation itself. I have not read the manpage of coap-client as well which I totally should have.

It seems to work, so im closing this _quessue_, but I'm not sure how it works.
I can set up a server listening on the same port on which I can send requests and recieve responses.
The response handler and the endpoints are listening on the same port, and libcoap is smart enough to decide which handlers get the message?

<details>
<summary>Sample of how I set the port:</summary>
<br>
In the coap-client, as mrdeep1 said, I could set the port with -p, and the address with -a (It does not seem that -p can work without the address parameter, but you can set it to 0.0.0.0)

In code, `coap_new_client_session` has a local_if parameter:

```C
// small, and a bit modified sample from coap-client
// I'm not sure if all lines are needed.
coap_address_t bind_addr;
coap_address_init(&bind_addr);
bind_addr.size = dst_addr->size;
bind_addr.addr.sa.sa_family = dst_addr->addr.sa.sa_family;
bind_addr.addr.sin.sin_port = ntohs(atoi("5555"));
session = coap_new_client_session(ctx, &bind_addr, dst_addr, uri.scheme == COAP_URI_SCHEME_COAP_TCP ? COAP_PROTO_TCP : COAP_PROTO_UDP);
```
</details>

**Comment by mrdeep1** [comment]
I will look at the -p issue when -a is not specified separately.  Thanks for finding this.

Multiple applications can reuse the same port for accepting / sending data from, but with some caveats as to which application receives the packet when it is being received on that port.  The reason why it is working is that when the client sets up its local source address/port and makes a "connection" to the same port on the same host (no initial matching 5-tuple as "connection" has not completed) the server application gets the packet, and then any returning packets matching the 5 tuple of the connection will get sent to the client application.  If there are no 5-tuple "connection" matches, then the packet gets sent to the listening server's port.
