### ISSUE TITLE
gettimeofday() path calculates time wrong

### ISSUE THREAD

**Issue by franc0is** [obgm/libcoap#9]
`tmp = tv.tv_usec * Q(FRAC, (COAP_TICKS_PER_SECOND/1000000.0));`
should be
`tmp = SHR_FP(tv.tv_usec * Q(FRAC, (COAP_TICKS_PER_SECOND/1000000.0)), FRAC);`

The code was fixed for linux but not for platforms that do not have `clock_get_time`

A commit to fix it is at https://github.com/franc0is/libcoap/commit/bde305210e9003117b51f243014626e057a05212

**Comment by obgm** [comment]
Thanks, I have cherry-picked from there.
