### ISSUE TITLE
Value of observe option repeated in the first 2 responses to a GET

### ISSUE THREAD

**Issue by jcmichelou** [obgm/libcoap#90]
If a client does a GET with an Observe option set to zero, the server must acknowledge the subscription for notifications by including an Observe option in the response (according to section 3.1 of RFC7641).
If ctx->observe is used as the value of the Observe option like it is in the server example then later on, when the resource becomes dirty, the client may receive a new GET response with an Observe option set to that same sequence number, but with the new content. This is because observe is incremented after the notification is sent, not before, so if no other notification is dispatched between the two events observe will have the same value. I suppose moving the incrementation of observe at the top of coap_notify_observer would fix this.

**Comment by mrdeep1** [comment]
This is no longer an issue with the current code and can be closed off.

**Comment by obgm** [comment]
Closing.
