### ISSUE TITLE
Block3 and block4 option

### ISSUE THREAD

**Issue by jqiaobln** [obgm/libcoap#907]
**Is your feature request related to a problem? Please describe.**

Block1 and 2 option needs ACK for every block, which slows transmission

**Describe the solution you'd like**

As described here, http://www.watersprings.org/pub/id/draft-bosh-core-new-block-00.html, new block3&4 options are proposed, which will significantly improve the transfer speed.

**Comment by mrdeep1** [comment]
This is now RFC9177, coded as #611, and will be apart of release 4.3.2.
