### ISSUE TITLE
Observe option may exceed allowed size instead of wrapping

### ISSUE THREAD

**Issue by jcmichelou** [obgm/libcoap#91]
I have noticed that the “observe” variable in coap_context_t in used as a value for the Observe option in notification to clients. The maximum size of that option is 3 bytes, and RFC7641 section 4.4 is quite clear that the value is limited to 2^24-1 and should wrap. The way it is incremented currently, it could end up being greater or equal than 2^24, which is probably a bug.

**Comment by obgm** [comment]
Closing as this has been fixed in PR #114
