### ISSUE TITLE
Value of observe option is global for all resources

### ISSUE THREAD

**Issue by jcmichelou** [obgm/libcoap#92]
Currently the value used for observe option in GET responses is a global variable common to all resources. This means it may increases more quickly than expected if you have many resources. Why not maintain an “observe” value per resource as suggested as a valid implementation in RFC ?
Rather than the public API being a modification of the internal state (dirty flag) in coap_resource_t, wouldn’t a coap_resource_set_dirty() function make sense ? It would be able to set the dirty flag without exposing it publicly, increment a per-resource observe sequence number which scales better in case the number of resources is large, and open the way to maintaining a linked list of dirty resources instead of having to scan through all the resources, including non-observable and non-observed ones in coap_check_notify().

**Comment by obgm** [comment]
Closing as this has been fixed in PR #114
