### ISSUE TITLE
Concurrent block-wise transmit and receive interrupts each other

### ISSUE THREAD

**Issue by jqiaobln** [obgm/libcoap#921]
## Environment

- libcoap version (run ``git describe --tags`` to find it):

    v4.3.0-rc3-41-g25fe796 merged with f4507e6e9adb943aae5e9c43e662a928d370ee6d
- Build System:             [CMake]
- Operating System:         [Other ]
- Operating System Version: [ ]
- Hosted Environment:       [None]

## Problem Description

Have 1 large transmit and 1 large receive going at the same time. I observed erroneous behaviors and subsequent transmission/receiving failures:
1.  ACK of the receive is passed to transmit, which made the transmit lg_xmit to be released prematurely. 
2.  Data payload missing for large transmit after an ACK of the receive is passed to the transmit mistakenly.

### Expected Behavior

Large transmit and receive should work concurrently.

### Actual Behavior

The ACK of 1 request (GET in my case) is passed to the transmit which caused erroneous behaviors.

### Steps to reproduce

1. Set up a large transmit and a large receive which runs at the same time

### Code to reproduce this issue

N/A

### Logs for case #1

PDU presented by app
v:1 t:CON c:POST i:4c8a {cd1f00d0} [ Uri-Host:host, Uri-Port:5784, Content-Format:application/octet-stream ] :: binary data length 1488

**  <->  UDP : lg_xmit 200a1db0 initialized
**  <->  UDP : lg_crcv 200a1570 initialized
*   <->  UDP : sent 1121 bytes
v:1 t:CON c:POST i:4c8a {0100000001} [ Uri-Host:host, Uri-Port:5784, Content-Format:application/octet-stream, Block1:0/M/1024, Size1:1488 ] :: binary data length 1024

*   <->  UDP : received 12 bytes
v:1 t:ACK c:2.31 i:4c8a {0100000001} [ Block1:0/M/1024 ]
**  <->  UDP : mid=0x4c8a: removed
found Block option, block size is 1024, block nr. 0
*   <->  UDP : sent 561 bytes
v:1 t:CON c:POST i:4c8b {02cd1f00d0} [ Uri-Host:host, Uri-Port:5784, Content-Format:application/octet-stream, Block1:1/_/1024, Size1:1488 ] :: binary data length 464

*   <->  UDP : sent 129 bytes
v:1 t:CON c:GET i:4c8c {632200d0} [ Uri-Host:host, Uri-Port:5784, Uri-Path:manifest, Content-Format:application/octet-stream, Block2:0/_/1024 ]

*   <->  UDP : received 210 bytes
v:1 t:ACK c:2.05 i:4c8c {632200d0} [ Content-Format:application/octet-stream, Size1:196 ] :: binary data length 196
**(This is the ACK for GET request 4c8c)**

**  <->  UDP : mid=0x4c8c: removed
PDU given to app
v:1 t:ACK c:2.05 i:4c8c {cd1f00d0} [ Content-Format:application/octet-stream, Size1:196 ] :: binary data length 196
**(The ACK is passed to the lg_xmit where it got the original token of the transmit)**

**  <->  UDP : lg_xmit 200a1db0 released

*   <->  UDP : received 34 bytes
v:1 t:ACK c:2.01 i:4c8b {02cd1f00d0} [ Content-Format:text/plain, Block1:1/_/1024 ] :: 'Successfully written'
**  <->  UDP : mid=0x4c8b: removed

### Logs for case #2

PDU presented by app
v:1 t:CON c:POST i:4c9d {19ee2500} [ Uri-Host:host, Uri-Port:5784, Content-Format:application/octet-stream ] :: binary data length 1488

**  <->  UDP : lg_xmit 200a1258 initialized
**  <->  UDP : lg_crcv 200a0808 initialized
*   <->  UDP : sent 1121 bytes

v:1 t:CON c:POST i:4c9d {0148fe04d4} [ Uri-Host:host, Uri-Port:5784, Content-Format:application/octet-stream, Block1:0/M/1024, Size1:1488 ] :: binary data length 1024

**  <->  UDP : lg_crcv 200a2c20 released

*   <->  UDP : received 12 bytes
v:1 t:ACK c:2.31 i:4c9d {0148fe04d4} [ Block1:0/M/1024 ]
**  <->  UDP : mid=0x4c9d: removed
found Block option, block size is 1024, block nr. 0
*   <->  UDP : sent 561 bytes
v:1 t:CON c:POST i:4c9e {0219ee2500} [ Uri-Host:host, Uri-Port:5784, Content-Format:application/octet-stream, Block1:1/_/1024, Size1:1488 ] :: binary data length 464

*   <->  UDP : sent 122 bytes
v:1 t:CON c:GET i:4c9f {70f02500} [ Uri-Host:host, Uri-Port:5784, Content-Format:application/octet-stream, Block2:0/_/1024 ]

v:1 t:ACK c:2.05 i:4c9f {70f02500} [ Content-Format:application/octet-stream, Block2:0/M/1024, Size2:4096, Size1:4096 ] :: binary data length 1024

**  <->  UDP : mid=0x4c9f: removed
PDU given to app
v:1 t:ACK c:2.05 i:4c9f {19ee2500} [ Content-Format:application/octet-stream, Block2:0/M/1024, Size2:4096, Size1:4096 ] :: binary data length 1024
**(The ACK of GET request 4c9f is passed to lg_xmit mistakenly)**

**  <->  UDP : lg_xmit 200a1258 released
found Block option, block size is 1024, block nr. 0
*   <->  UDP : sent 94 bytes
v:1 t:CON c:POST i:4ca0 {70f02501} [ Uri-Host:host, Uri-Port:5784, Content-Format:application/octet-stream, Block2:1/_/1024, Size1:1488 ]
**(Binary payload is empty)**

*   <->  UDP : received 34 bytes
v:1 t:ACK c:2.01 i:4c9e {0219ee2500} [ Content-Format:text/plain, Block1:1/_/1024 ] :: 'Successfully written'
**  <->  UDP : mid=0x4c9e: removed

*   <->  UDP : received 53 bytes
v:1 t:ACK c:4.00 i:4ca0 {70f02501} [ Content-Format:text/plain ] :: 'Binary payload for message missing or empty'
**  <->  UDP : mid=0x4ca0: removed

**Comment by mrdeep1** [comment]
Can you please confirm the issue still exists with the latest develop (i.e. 4.3.1rc2 +) code as there has been considerable work in the code in this particular area (specifically better token matching and use of RFC9175).

**Comment by jqiaobln** [comment]
I confirm that after upgrading to 4.3.1rc2 the issue has been fixed.
