### ISSUE TITLE
Should coap_pdu_init be called for each new message sent?

### ISSUE THREAD

**Issue by srikumaresan** [obgm/libcoap#923]

**Comment by srikumaresan** [comment]
coap_pdu_init allocates memory using malloc, which might be undesirable in some applications at runtime. So I am wondering if it needs to be called for every message

**Comment by mrdeep1** [comment]
Yes.

Once a PDU has been transmitted, or there is a transmit failure, the PDU and any other memory associated with it gets freed off.

Therefore re-using the created PDU will cause malloc double free errors and is certainly not recommended!

**Comment by srikumaresan** [comment]
I see, thank you! @mrdeep1
