### ISSUE TITLE
RST message after message with invalid code

### ISSUE THREAD

**Issue by elesrs** [obgm/libcoap#927]
After client received a message of unknown type, RST message is automatically sent back to the server.
```
Sep 15 12:07:52.908 DEBG dropped message with invalid code (1.04)
Sep 15 12:07:52.908 DEBG *  127.0.0.1:39906 <-> 127.0.0.1:5684 UDP : sent 4 bytes
v:1 t:RST c:0.00 i:71f7 {} [ ]
```
Is there a way to check for this type of event/thing happening? (none of registered handlers was called)

**Comment by mrdeep1** [comment]
@elesrs Interesting question.  I guess that the code could be changed to call a defined event handler whenever there is a syntax error in a received CoAP packet.  However, this event handler could get very busy if rogue devices out there decide to flood your CoAP application (in particular if it is a CoAP server).

The code is doing the correct thing as per [RFC7252 4.2](https://datatracker.ietf.org/doc/html/rfc7252#section-4.2)

> A recipient
> MUST either (a) acknowledge a Confirmable message with an
> Acknowledgement message or (b) reject the message if the recipient
> lacks context to process the message properly, including situations
> where the message is Empty, uses a code with a reserved class (1, 6,
> or 7), or has a message format error.

I can see some potential merit in the application being informed of a badly formatted packet, but what would the application do with that knowledge?

**Comment by elesrs** [comment]
@mrdeep1 I agree that the behavior is in line with the standard.

In my case the source of the RST message is the client which is not informed about this event so it waits for the timeout which takes a while. I would like it to fail faster and inform the application as soon as possible.

**Comment by mrdeep1** [comment]
I will look at creating a nack event - COAP_NACK_BAD_RESPONSE, which will only fire if a CON (as opposed to a NON) request has been sent.

**Comment by mrdeep1** [comment]
@elesrs Please check out PR #929 and confirm back that this fixes your situation.

**Comment by elesrs** [comment]
The fix works like a charm. Thank you very much!
