### ISSUE TITLE
Debug messages using coap_set_log_handler 

### ISSUE THREAD

**Issue by fbucafusco** [obgm/libcoap#928]
## Environment

- libcoap version : The one coming precompiled in https://github.com/platformio/platform-espressif32/releases/tag/v4.4.0

- Build System:       Platformio
- Operating System:       Windows
- Operating System Version:10
- Hosted Environment:      ESP-IDF + Arduino framework

## Problem Description

The firmware I am maintaining is using Arduino framework for ESP32 and it is very dependent to the default Serial Port for debugging messages (Serial object). We also have another serial port on the system which is called Serial2. 

Recently I received a hardware version which have routed both serial ports crossed, so I need to switch between the UART used for Serial and Serial2. I've managed to do that but I 've found out that some other libraries have hardcoded dependencies (and the libraries are downloaded automatically by platformio, so in theory I cannot change them). Anyway, I also managed to solve that. 

In regard libcoap something similar is happening. I used the function `coap_set_log_handler ` to redirect all the log messages to my new UART but still, the library is sending some messages to the one I defined and some others to the default one. So I am getting debug messages from both UARTs. 

I checked coap_debug.c  and the function `coap_show_pdu` fill a super long buffer called  `outbuf` which then is sent using `COAP_DO_SHOW_OUTPUT_LINE`.

While writing this, I realized that `COAP_DO_SHOW_OUTPUT_LINE `also is a conditional inserted code depending on a global variable `use_fprintf ` which uses fprintf (which was the function that redirected the bytes to the default UART instead of the one I needed). 

### Expected Behavior

The callback settled by `coap_set_log_handler `should be the only interface for allow sending debug messages.

**Comment by mrdeep1** [comment]
@fbucafusco Thanks for raising this.  It was a requirement that `coap_show_pdu()` could either output using `fprintf()` or `coap_log()` (which will invoke the callback set by `coap_set_log_handler()`).  See [coap_show_pdu()](https://libcoap.net/doc/reference/develop/man_coap_show_pdu.html).

Please see [coap_set_show_pdu_output(3)](https://libcoap.net/doc/reference/develop/man_coap_set_show_pdu_output.html) on how to change the function used for output.

**Comment by fbucafusco** [comment]
Hi! THanks for the response. 

In the end I figure out that I needed to call 
`    coap_set_log_handler( coap_log_handler );`
`    coap_set_show_pdu_output( false );        `

I raised this because from my point of view is like very confusing having that behavior.
Let's say `log_handler` is NULL, then `coap_log_impl` will print all the log messages using fprintf like functions (and will fulfill the requirement). In that case it is logic that the `COAP_DO_SHOW_OUTPUT_LINE` uses fprintf. But then , as soon the user needs to redirect the output to some other place usign `coap_set_log_handler`, I think all the library should send all messages over the user handler.  From my point of view having to configure two things is not the best. Just my opinion. 

BTW Was a requirement from whom ?

**Comment by fbucafusco** [comment]
BTW I could fix that and create a PR if you think it worth the effort.

**Comment by mrdeep1** [comment]
> BTW Was a requirement from whom ?

This all came about in #219.  I agree that if `coap_set_log_handler() `has been set, then it makes sense all logging traffic should go via the logging handler which was not properly thought through at the time.  However, we also need to maintain backwards compatibility (old app source compiled using new library source, or the dynamically loaded library is just updated) so that there are no surprises for the user.  So, I am not sure about this as a PR.

The current documentation (Doxygen and man pages) does clearly show that the output method is dependent on the setting of `coap_set_show_pdu_output()`.

**Comment by fbucafusco** [comment]
Ok. Should I close this ?

**Comment by mrdeep1** [comment]
Unfortunately, I think yes.
