### ISSUE TITLE
Memory leak occurs in function setup_pki_ssl line 1452-1459 of coap_openssl.c file

### ISSUE THREAD

**Issue by Lee-nju** [obgm/libcoap#940]
## Environment

- libcoap version:         `v4.3.0`
- Build System:             `Make`
- Operating System:         `Linux`
- Operating System Version: `EulerOS release 2.0 (SP10)`
- Hosted Environment:       `EulerOS release 2.0 (SP10)`

## Problem Description
When multiple CA certificates are used, X509_free(x) is required to release memory for each CA certificate.

### Expected Behavior
No memory leakage occurs.

### Actual Behavior
Memory leakage occurs.

### Error Code
```c
st = SSL_CTX_get_cert_store(ctx);
for (;;) {
  if (PEM_read_bio_X509(in, &x, NULL, NULL) == NULL)
    break;
  add_ca_to_cert_store(st, x);
}
BIO_free(in);
X509_free(x);
```

### Experted Code
```c
st = SSL_CTX_get_cert_store(ctx);
for (;;) {
  if (PEM_read_bio_X509(in, &x, NULL, NULL) == NULL)
    break;
  add_ca_to_cert_store(st, x);
  X509_free(x);
  x = NULL;
}
BIO_free(in);
X509_free(x);
```

**Comment by mrdeep1** [comment]
@Lee-nju Thanks for raising this.  I will work on getting a fix out which will be slightly different to your suggestion, but following the same principles.

**Comment by mrdeep1** [comment]
@Lee-nju Can you please confirm that #942 fixes your issue.
