### ISSUE TITLE
Logged error information is not cleared

### ISSUE THREAD

**Issue by Lee-nju** [obgm/libcoap#941]
## Environment

- libcoap version:         `v4.3.0`
- Build System:             `Make`
- Operating System:         `Linux`
- Operating System Version: `EulerOS release 2.0 (SP10)`
- Hosted Environment:       `EulerOS release 2.0 (SP10)`

## Problem Description
The previously logged error information is not cleared when the CA certificate is added.

### Error Code
```c
st = SSL_CTX_get_cert_store(ctx);
for (;;) {
  if (PEM_read_bio_X509(in, &x, NULL, NULL) == NULL)
    break;
  add_ca_to_cert_store(st, x);
}
BIO_free(in);
X509_free(x);
```

### Experted Code
```c
int ca_count = 0;
st = SSL_CTX_get_cert_store(ctx);
for (;;) {
  if (PEM_read_bio_X509(in, &x, NULL, NULL) == NULL)
    break;
  add_ca_to_cert_store(st, x);
  ca_count++;
}
BIO_free(in);
X509_free(x);
/* If the CA certificate is successfully added, clear the recorded error information. */
if (ca_count > 0) {
  ERR_clear_error();
}
```

**Comment by mrdeep1** [comment]
@Lee-nju I am not sure why you are seeing an error here that needs to be cleared.  `add_ca_to_cert_store()` clears out all the outstanding errors at entry, and then if there is an issue adding the certificate to the store then all the errors are logged and cleared out before `add_ca_to_cert_store()` returns.

If `PEM_read_bio_X509()` generates an error, this could be on the first iteration and so `ERR_clear_error()` does not get called anyway.

Is this the proper fix to what you are seeing ?
````
diff --git a/src/coap_openssl.c b/src/coap_openssl.c
index c92ba16..84b2fa9 100644
--- a/src/coap_openssl.c
+++ b/src/coap_openssl.c
@@ -1473,6 +1474,7 @@ setup_pki_ssl(SSL *ssl,
       }
       st = SSL_CTX_get_cert_store(ctx);
       for (;;) {
+        x = NULL;
         if (PEM_read_bio_X509(in, &x, NULL, NULL) == NULL)
             break;
         add_ca_to_cert_store(st, x);
````

**Comment by mrdeep1** [comment]
@Lee-nju Can you please confirm that #942 fixes your issue.

**Comment by Lee-nju** [comment]
Thank you, no problem after testing.
