### ISSUE TITLE
coap_can_exit function is not checking for lg_crcv and lg_srcv

### ISSUE THREAD

**Issue by jqiaobln** [obgm/libcoap#947]
## Environment

- libcoap version (run ``git describe --tags`` to find it):
  4.3.1rc2

- Build System:            CMake
- Operating System:        Other
- Operating System Version: [ ]
- Hosted Environment:       Other

## Problem Description

coap_can_exit(coap_context_t *context) function is not checking for lg_crcv and lg_srcv

### Expected Behavior

The function should check for lg_crcv and lg_srcv for pending large receives.

### Actual Behavior

Function returns 1 when lg_crcv is still receiving.

### Steps to reproduce

N/A

### Code to reproduce this issue

N/A

## Debug Logs

N/A

**Comment by mrdeep1** [comment]
@jqiaobln Thank you for raising this issue.  Unfortunately is in not a simple case of just adding in a `session->lg_crcv` check as I have found that `session->lg_crcv `does not always timeout in a timely manner.

I am working on a fix (need to do some regression testing) and am introducing a new function `coap_io_pending()` (returns 1 when i/o is pending) leaving `coap_can_exit()` alone continuing to have the same transmit only characteristics checks.

**Comment by mrdeep1** [comment]
@jqiaobln Please see and test fix in PR #948.

**Comment by mrdeep1** [comment]
@jqiaobln Can this issue now be closed off?
