### ISSUE TITLE
Add support for unix sockets for reverse proxies

### ISSUE THREAD

**Issue by WndDezorian** [obgm/libcoap#958]
**Is your feature request related to a problem? Please describe.**

Complex IOT systems may run multiple processes with different characteristics, perhaps running some processes on demand, knowing others might hang unexpectedly while processing, while still others might be real-time processes.  I want to use a reverse proxy to distribute COAP communications to these processes.  In this circumstance, it would be nice to use Unix sockets rather than IP sockets for the reverse proxy, due to their lower overhead and higher security (not visible to the outside world, regardless of firewall)

**Describe the solution you'd like**

I would like to have a compile-time flag to enable Unix sockets as part of the coap_address_t union.

**Describe alternatives you've considered**

The alternative is to continue using UDP sockets for the reverse proxy.  This incurs higher overhead and is not as secure, especially if DTLS handshakes are handled at the reverse-proxy and not necessarily forwarded on to the children.

**Additional context**

I don't think unix sockets should be built-in by default; sockaddr_un is much larger than the current sockaddr_* in coap_address_t, and I know the project needs to support extremely small and lightweight platforms.

That said, I don't see that much would need to change beyond expanding the union.  Socket constructor calls use the sockaddr family instead of hardcoded AF_INET (except for multicast, which obviously wouldn't apply to a unix socket), and beyond that the system should be transparent.

I'm not sure what the preferred implementation would be, though.  One option would be having a compile-time definition expanding the union, something like this:

```
 /** multi-purpose address abstraction */
typedef struct coap_address_t {
  socklen_t size;           /**< size of addr */
  union {
    struct sockaddr         sa;
    struct sockaddr_in      sin;
    struct sockaddr_in6     sin6;
#ifdef COAP_UNIX_SOCK_SUPPORT
    struct sockaddr_un      un;
#endif
  } addr;
} coap_address_t;
```

But the library seems to use compile-time checks for internal code and only use runtime checks in the public API.  At least, all the *COAP_FEATURE* predefines seem to be hidden and unusable in the publicly installed headers.

If I'm correct and the team doesn't want to have compile-time checks in the headers, another approach would be to leave coap_address_t alone, create a separate coap_unix_address_t large enough to hold unix addresses, and create a coap_address_storage_t for internal storage?  coap_address_storage_t 's size would be set at compile time, and runtime users could query if unix sockets are supported before using a coap_unix_address_t in place of a coap_address_t.

**Comment by mrdeep1** [comment]
I concur with you that unix sockets are only likely to be used in a reverse proxy situation (for CoAP).  However, the final server needs to know how to listen on a named unix socket so things like `coap_new_endpoint()` need to know how to process unix sockets.

The reverse proxy logic (as for any reverse proxy) just needs to follow a set of rules as to which internal server to connect to (and how).

It is unfortunate that `coap_address_t` was not added to the opaque set of structures when that major API change work was done.  This means  that functions such as `coap_session_get_addr_remote()` return a potentially differing structure based on library compile time options affecting the size of `coap_address_t`.

A compromise here may be to create an equivalent local struct for sockaddr_un that has a size that is the same as sockaddr_in6 so that the overall size of coap_address_t is the same for AF_UNIX, but the filename is considerably shorter to not break the public API. 
````
#define COAP_UNIX_PATH_MAX   (sizeof (struct sockaddr_ip6) - 2)

struct coap_sockaddr_un {
        sa_family_t sun_family; /* AF_UNIX */
        char sun_path[COAP_UNIX_PATH_MAX];   /* pathname max 26 with NUL byte */
};
````
with coap_address_t updated as per
````
 /** multi-purpose address abstraction */
typedef struct coap_address_t {
  socklen_t size;           /**< size of addr */
  union {
    struct sockaddr         sa;
    struct sockaddr_in      sin;
    struct sockaddr_in6     sin6;
    struct coap_sockaddr_un      un; /* CoAP shortened special */
  } addr;
} coap_address_t;
````
as 25 bytes is a reasonable max length for a unix domain socket.

**Comment by mrdeep1** [comment]
@WndDezorian See a fix in #997 to support Unix Domain Sockets.  There is a limit of the path name to be 26 characters long so that the API is not broken.

**Comment by WndDezorian** [comment]
Thanks!  I'm very excited to try this out!

**Comment by mrdeep1** [comment]
@WndDezorian It would be good to get feedback on the implementation.  I have just pushed to #997 a client setup example in coap_endpoint_client(3) and a server setup example in coap_endpoint_server(3) man pages which may help you.

**Comment by mrdeep1** [comment]
See https://mailarchive.ietf.org/arch/msg/core/FKvB8zOrw-FbqR7ZiOjulj8BNOk for further discussions

**Comment by mrdeep1** [comment]
@WndDezorian Have you had a chance to check this out yet?

**Comment by WndDezorian** [comment]
Sorry, travel pulled me away for a bit.  I'll try this out today.

**Comment by WndDezorian** [comment]
Things are looking good to me!  I've successfully compiled, tested using the provided utilities, and then pulled the updated code into my own project.  There I was able to shift communications from UDP to unix sockets with only minor code changes, and demonstrated that everything is still functioning.

A few minor nits that might need to be fixed-

- The server cleans up the unix socket when it is closed, but I didn't see similar behavior for the clients.  Sockets were left orphaned in /tmp, both by the example and by my own code.
- I didn't see any `#include <sys/un.h>`, so I'm assuming there's no need for a CMAKE option to disable this feature?
- I don't believe the change to coap_uri_scheme is backwards compatible.  If backwards compatibility is needed, could you instead add a new "coap_uri_info" structure with the additional information alongside the existing name list?
- If coaps+unix(s) requires DTLS support, you might want to add that to man/coap-client.txt.in (lines 44-45)
- The details on coap_new_client_session in man/coap_endpoint_client.txt.in (lines 134-141) removed a part noting that if port is set to 0, the default coap port is used.  You may wish to restore that line.
- I'm not sure why the "CoAP client DTLS PSK" example was removed from man/coap_endpoint_server.txt.in.  Was that an error?
- The naming convention coap(s) + unix(s) may be confusing, as the first optional 's' refers to encryption, while the second optional 's' refers to stream vs datagram.  I'm not sure of a better naming convention, but others might be confused as well.
  - Following onto that, is there a reason to implement streaming unix instead of only datagrams?  Unix datagrams are reliable, so unless there's a throughput advantage for block transfers I'm not sure you need to add the additional two protocols.  Of course, the code changes are so minor I don't think carrying unix streams costs you much.

Thank you for implementing this!  This will help my projects tremendously!

**Comment by mrdeep1** [comment]
Thanks for doing the testing, confirming that  things are working  and coming back with a load of good comments / questions.

In answer to your 7 points
1. /tmp socket file cleanups
Yes, this is a bug - code now fixed.

2. #include <sys/un.h>
This is not required as using it would change the size of the `coap_address_t`.  This PR uses `coap_sockaddr_un `instead which has a smaller `sun_path[]` than `sockaddr_un `so `coap_address_t `size does not change when adding in `coap_sockaddr_un `to the union.

3. coap_uri_scheme{}
This was introduced in PR #764 which was only merged last week.  So, yes, it is not backward compatible, only true for a week and is not a change from latest release 4.3.1.  I copied some of the #764 code in this area when I created #997.

4. unix + (D)TLS
Good point - corrected.

5. coap_endpoint_client.txt.in
Agreed as per the other `coap_new_client_session_*()`.

6. Client example in coap_endpoint_server.txt.in
As this man page is for the server endpoint, I did not think the the client example was relevant (I suspect this came about when I split a man page into the client and server respective parts and the client was not removed).  If there is a good reason to keep it there, please let me know.

7. Naming conventions
I really struggled with how to do the naming.

As it happens, `coap+unix://%2Fsome%2Fdgram_file/a/path` and `coap://%2Fsome%2Fdgram_file/a/path` give the same unix domain usage result (as does `coaps+unixs://%2Fsome%2Fstream_file/a/path` and `coaps+tcp://%2Fsome%2Fstream_file/a/path`) as the leading `%2F` in the host portion of the URI is not an IPv6 address (`[`) or IPv4 address (is digit).  The %2F (hex for `/`) is needed so the parser knows when the host ends and the path starts in the URI.

I'm inclined to drop all the coap(s)+unix(s) scheme variants as they are not really needed for the URI. This then removes a lot of the complexities out of the different man mages.  Thoughts?

I'm also inclined to change the coap-server's` -U strm` to `-U stream` for better consistency.

**Comment by WndDezorian** [comment]
Will do.  Looking at it now.

**Comment by WndDezorian** [comment]
@mrdeep1 The updates work for me, both in your demo code and in my own project.  The only nit I could find was the help message for coap-server's -U option was not indented correctly.

Thanks again for getting this change for us!

**Comment by mrdeep1** [comment]
Thanks for doing this.  Will fix nit and get it merged later.

**Comment by mrdeep1** [comment]
No merged.  Thank you.
