### ISSUE TITLE
enabling debug in libcoap

### ISSUE THREAD

**Issue by hareshel** [obgm/libcoap#97]
how to enable all the debug in libcoap. Tried with -V option but never seen any messages.

**Comment by obgm** [comment]
with `-v9`, you get a lot of debug output for both, client and server.
Of course, when writing your own applications, you will have to set the log level by yourself using `coap_set_log_level()`.

**Comment by hareshel** [comment]
Thanks for the info.

I am trying to send GET messages using coap-client like
./coap-client -m get COAP://[FF03::FD]/.well-known/core?rt=urn:zcl:c:6 -v9

which URI is smart bulb and my device has Thread/6LoWPAN stack with
interface wpan0.

I have enabled debug statement in my wpan tunnel driver. But when I execute
the above command I dont see any debug messages sent through this tunnel
driver.

how to specify the interface for coap-client? like wpan0 to use. basically
I need to send CoAP over wpan0.

help will be useful.

**Comment by obgm** [comment]
Try moving the -v option in front of the URI.
The interface can be specified with `-A`. 

You may consider consulting the manual page for coap-client or just invoke `coap-client` without any options to get a brief summary of supported command line options.
