### ISSUE TITLE
Compilation options for iOS support

### ISSUE THREAD

**Issue by ticatagdev** [obgm/libcoap#98]
Can you please detail the steps to compile the DTLS branch for iOS ?

**Comment by obgm** [comment]
I have no idea.
You could try asking on the mailing list.

**Comment by tijuca** [comment]
macOS is basically a Unix derivate so the build should be very similar to a build under current Linux platforms. Unfortunately your question is a bit a meta question, there are plenty howto available for using and building autools based projects in a macOS environments. So if you run into trouble then probably simply post the issue than. We happily add missing flags or instruction if we know what to add.

**Comment by obgm** [comment]
On MacOS, libcoap should build out of the box. iOS, however, is not on the list of supported platforms and I do not know of any ports. @stuffrabbit has done two nice CoAP implementations in Objective-C and Swift, respectively:
https://github.com/stuffrabbit/iCoAP
https://github.com/stuffrabbit/SwiftCoAP

**Comment by ticatagdev** [comment]
Unfortunately none of those 2 libraries are supporting DTLS. DTLS is require to support iKEA tradfrit lights :(
I really need a solution

**Comment by Thomas-Vos** [comment]
Hey @ticatagdev, did you figure out how to compile this library for iOS?
