### ISSUE TITLE
Implement amplification attacks that targets CoAP

### ISSUE THREAD

**Issue by salmeghlef** [obgm/libcoap#995]
**Is your feature request related to a problem? Yes, amplification attacks against CoAP should be implemented for further research to protect CoAP

I'm always frustrated when using CoAP in the production due to security issues.

**Describe the solution you'd like**
Implementing amplification attacks that target CoAP may help to find coherent solutions 

Implement the amplification attacks that are described in this link https://datatracker.ietf.org/doc/html/draft-mattsson-t2trg-amplification-attacks may help to find a defense mechanism to face these attacks:
1- Amplification using single response
2- Amplification using observe
3- Amplification using multicast
4- Amplification using MITM
 
**Describe alternatives you've considered**
None
None
Please give as many details as you can. Include suggestions for useful APIs or interfaces if relevant.
None
**Additional context**
None
The details are in this link https://datatracker.ietf.org/doc/html/draft-mattsson-t2trg-amplification-attacks

**Comment by mrdeep1** [comment]
As mentioned on the mailing list 2 weeks ago the latest version of this document can be found here [CoAP Amplification Attacks](https://datatracker.ietf.org/doc/html/draft-mattsson-t2trg-amplification-attacks). It is much better and safer to refer to documents this way than attach a PDF which most security professionals are very reluctant to open in case it contains a virus etc.

I see that you have also raised this question at the home for [coap-actuators](https://github.com/EricssonResearch/coap-actuators) as https://github.com/EricssonResearch/coap-actuators/issues/17 where some suggestions have been made as to how you can create these amplification attacks for testing.

**Comment by mrdeep1** [comment]
There is a full set of libcoap documentation at [libcoap documentaion](https://libcoap.net/doc/reference/develop).

**Comment by salmeghlef** [comment]
Thanks a lot for your quick response and your concern. From my side, I need to understand the 2000 lines of code for CoAP client in order to do the trivial changes. As the developers here understand the code, they need to do some trivial changes to the CoAP client code to simulate the required attacks. Hope someone has some time to modify the CoAP client code to fit for simple attack, observe, multicast and MITM elaborated in this document https://datatracker.ietf.org/doc/html/draft-mattsson-t2trg-amplification-attacks. 

Thanks for your understanding and cooperation always

**Comment by salmeghlef** [comment]
> @salmeghlef I hear you about understanding the 2000 lines of code for the example client. This is why [libcoap-minimal](https://github.com/obgm/libcoap-minimal) was created where there is less than 100 lines to understand for the client code.
> 
> I personally do not have the time to update the client examples as you wish. This (and libcoap-minimal) is an open source project and so anyone who wants to contribute can.

Cool. Hope you can assure that libcoap project support the amplification attacks. In case of no, I might need to go for other implementation of the CoAP. Thank you

**Comment by mrdeep1** [comment]
After a quick read of the RFC, I cannot see why libcoap cannot generate the packets to emulate the different types of attack.  The modification of the packets for the MITM attacks is more down to modifying UDP packet headers which has nothing to do with any CoAP Library.

**Comment by salmeghlef** [comment]
Thanks Jon. I think for the first attack (simple amplification), the payload comes from the CoAP server with a huge message. In this case, we might need to implement a tiny script to do a loop on sending large responses to the CoAP client unless an action taken to stop the loop.

**Comment by mrdeep1** [comment]
@salmeghlef Can this issue now be closed off?

**Comment by mrdeep1** [comment]
Closing as per comment in #1003.
